/**
 * Dopamine pattern templates per genre (Phase 28 TIER 2 — extracted).
 * Used by Architect to design per-chapter dopamine peaks.
 */

import type { DopamineType } from '../types';

export interface DopaminePattern {
  type: DopamineType;
  name: string;
  description: string;
  frequency: 'every_chapter' | 'every_3_chapters' | 'every_arc' | 'arc_end';
  intensity: 'medium' | 'high' | 'very_high' | 'extreme';
  setup: string;
  payoff: string;
}

export const DOPAMINE_PATTERNS: Record<DopamineType, DopaminePattern> = {
  face_slap: {
    type: 'face_slap',
    name: 'Tát mặt',
    description: 'Đối thủ kinh ngạc/thán phục/câm lặng trước thành tựu hoặc thực lực của MC',
    frequency: 'every_chapter',
    intensity: 'high',
    setup: 'OPTION A (PROACTIVE — ưu tiên): MC chủ động hành động (kinh doanh, thi triển tài năng, đạt thành tựu) → đối thủ quan sát từ ngoài. OPTION B: Villain coi thường/xúc phạm MC trước.',
    payoff: 'OPTION A (PROACTIVE — ưu tiên): Kết quả MC vượt xa kỳ vọng → đối thủ kinh ngạc thán phục, không thể phản kháng. OPTION B: MC đánh bại villain ngoạn mục.',
  },
  power_reveal: {
    type: 'power_reveal',
    name: 'Lộ sức mạnh',
    description: 'MC tiết lộ thực lực khiến mọi người sốc',
    frequency: 'every_3_chapters',
    intensity: 'very_high',
    setup: 'Mọi người đánh giá thấp MC',
    payoff: 'MC thể hiện sức mạnh vượt xa dự đoán',
  },
  treasure_gain: {
    type: 'treasure_gain',
    name: 'Nhặt kho báu',
    description: 'MC có được vật phẩm quý hiếm',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'Phát hiện địa điểm/cơ hội bí mật',
    payoff: 'Thu hoạch tài nguyên quý giá',
  },
  breakthrough: {
    type: 'breakthrough',
    name: 'Đột phá',
    description: 'MC lên cảnh giới mới',
    frequency: 'every_arc',
    intensity: 'very_high',
    setup: 'Tích lũy đủ, gặp khó khăn kích thích',
    payoff: 'Đột phá thành công, sức mạnh tăng vọt',
  },
  revenge: {
    type: 'revenge',
    name: 'Trả thù',
    description: 'MC đánh bại kẻ thù cũ',
    frequency: 'arc_end',
    intensity: 'extreme',
    setup: 'Nhớ lại mối hận cũ',
    payoff: 'Đánh bại kẻ thù thỏa mãn',
  },
  recognition: {
    type: 'recognition',
    name: 'Được công nhận',
    description: 'Người khác nhận ra giá trị của MC',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'MC bị hiểu lầm hoặc bỏ qua',
    payoff: 'Người quan trọng công nhận tài năng',
  },
  beauty_encounter: {
    type: 'beauty_encounter',
    name: 'Gặp mỹ nhân',
    description: 'MC gặp và gây ấn tượng với nữ nhân vật',
    frequency: 'every_arc',
    intensity: 'medium',
    setup: 'Hoàn cảnh bất ngờ gặp gỡ',
    payoff: 'Tạo ấn tượng tốt, hint romance',
  },
  secret_identity: {
    type: 'secret_identity',
    name: 'Thân phận bí ẩn',
    description: 'Lộ ra MC có background khủng',
    frequency: 'arc_end',
    intensity: 'extreme',
    setup: 'Manh mối về quá khứ MC',
    payoff: 'Tiết lộ thân phận choáng váng',
  },
  business_success: {
    type: 'business_success',
    name: 'Thành công kinh doanh',
    description: 'Chốt deal lớn, kiếm lợi nhuận bùng nổ',
    frequency: 'every_3_chapters',
    intensity: 'high',
    setup: 'Bị ép giá / gặp rào cản kinh doanh / đối thủ chèn ép, HOẶC nhìn ra cơ hội thị trường mới (không cần adversity)',
    payoff: 'Lật ngược thế cờ HOẶC chốt deal mượt mà, kiếm tiền sốc, thị trường kinh ngạc',
  },
  harvest: {
    type: 'harvest',
    name: 'Thu hoạch thành quả',
    description: 'Đạt được thành quả sau thời gian dài chăm sóc',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'Chăm sóc vất vả / nguy cơ thất thu, HOẶC chăm sóc đến mùa thu hoạch một cách yên bình',
    payoff: 'Thu hoạch đột biến, sản phẩm chất lượng cao hiếm có',
  },
  flex_wealth: {
    type: 'flex_wealth',
    name: 'Thể hiện tài phú/IQ',
    description: 'Giải quyết vấn đề bằng tiền hoặc trí tuệ áp đảo',
    frequency: 'every_chapter',
    intensity: 'high',
    setup: 'Bị coi thường / bị dồn vào góc, HOẶC chủ động dùng tài lực giải quyết (không cần ai khinh trước)',
    payoff: 'Dùng tiền hoặc IQ đập nát âm mưu HOẶC giải quyết mượt mà, đối phương câm nín hoặc kinh ngạc',
  },
  comfort: {
    type: 'comfort',
    name: 'Ấm áp/Chữa lành',
    description: 'Khoảnh khắc bình yên, thấu hiểu, đồ ăn ngon',
    frequency: 'every_chapter',
    intensity: 'medium',
    setup: 'Mệt mỏi/áp lực/vết thương cũ, HOẶC đơn thuần là khoảnh khắc ấm áp đời thường (không cần đau khổ trước)',
    payoff: 'Được quan tâm, ăn ngon, cảm thấy bình yên và thấu hiểu',
  },
  comedy_misunderstanding: {
    type: 'comedy_misunderstanding',
    name: 'Hiểu lầm hài hước',
    description: 'Hiểu lầm tạo ra tình huống dở khóc dở cười',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'Thông tin không đồng nhất, suy diễn sai lệch',
    payoff: 'Phát hiện sự thật đầy bất ngờ và hài hước',
  },
  steal_luck: {
    type: 'steal_luck',
    name: 'Cướp đoạt Khí vận',
    description: 'Phản phái MC cướp đoạt cơ duyên, bảo vật hoặc hồng nhan của Thiên Mệnh Chi Tử',
    frequency: 'every_3_chapters',
    intensity: 'high',
    setup: 'Thiên Mệnh Chi Tử chuẩn bị lấy được bảo vật/tình cảm',
    payoff: 'MC xen ngang cướp đoạt mượt mà, Thiên Mệnh Chi Tử tức hộc máu nhưng không làm gì được',
  },
  simulate_success: {
    type: 'simulate_success',
    name: 'Mô phỏng thành công',
    description: 'MC dùng hệ thống mô phỏng tìm ra đường sống trong chỗ chết',
    frequency: 'every_3_chapters',
    intensity: 'extreme',
    setup: 'Tình huống bế tắc, 99.9% là chết',
    payoff: 'MC dùng kết quả mô phỏng lật kèo hoàn hảo, bàng quan kinh hãi vì sự "tiên tri" của MC',
  },
  tears_of_regret: {
    type: 'tears_of_regret',
    name: 'Nước mắt hối hận',
    description: 'Sự thật về sự hy sinh thầm lặng của MC được phơi bày',
    frequency: 'arc_end',
    intensity: 'extreme',
    setup: 'MC bị hiểu lầm là kẻ ác, bị mọi người xỉ vả và phản bội',
    payoff: 'Ký ức/sự thật bộc quang, những kẻ từng phản bội ôm đầu khóc lóc hối hận tột cùng',
  },
  flex_power_casual: {
    type: 'flex_power_casual',
    name: 'Tiện tay nghiền nát',
    description: 'MC quá mạnh, tiện tay làm một việc nhỏ cũng gây chấn động',
    frequency: 'every_3_chapters',
    intensity: 'high',
    setup: 'Kẻ thù tự cao tự đại đem theo tuyệt chiêu mạnh nhất',
    payoff: 'MC chỉ hắt xì hoặc phẩy tay cũng khiến kẻ thù tan thành tro bụi, quần chúng hóa đá',
  },
  civilization_harvest: {
    type: 'civilization_harvest',
    name: 'Thu hoạch văn minh',
    description: 'Quan sát và thu hoạch thành quả từ nền văn minh do MC tạo ra',
    frequency: 'every_3_chapters',
    intensity: 'extreme',
    setup: 'MC gieo mầm sự sống, tua nhanh thời gian hàng vạn năm',
    payoff: 'Nền văn minh phát triển rực rỡ, hiến tế sức mạnh/tín ngưỡng cho MC, hoặc MC lấy trộm kỹ thuật của họ',
  },
  player_exploitation: {
    type: 'player_exploitation',
    name: 'Bóc lột người chơi',
    description: 'Bóc lột công sức của Đệ tứ thiên tai (game thủ)',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'Game thủ liều mạng đánh boss, nộp tiền nạp thẻ, cày cuốc ngày đêm',
    payoff: 'MC ngồi mát ăn bát vàng, thu hoạch toàn bộ lợi ích, game thủ vẫn khen "game quá hay"',
  },
  two_world_shock: {
    type: 'two_world_shock',
    name: 'Hai thế giới kinh hãi',
    description: 'Đem đồ hiện đại sang dị giới hoặc ngược lại gây sốc',
    frequency: 'every_chapter',
    intensity: 'high',
    setup: 'Dị giới đang thiếu thốn tài nguyên, khinh thường MC',
    payoff: 'MC móc ra bật lửa, mì gói hoặc súng AK khiến cao thủ dị giới quỳ rạp, đổi lấy kho báu vạn năm',
  },
  master_flex: {
    type: 'master_flex',
    name: 'Sư tôn vô địch',
    description: 'MC yếu nhưng dựa vào đồ đệ não bổ và buff hệ thống để dọa người',
    frequency: 'every_3_chapters',
    intensity: 'extreme',
    setup: 'Đồ đệ gặp nguy hiểm sinh tử, đối mặt đại năng cao hơn nhiều cảnh giới',
    payoff: 'MC xuất hiện với phong thái đạo mạo, dùng đạo cụ/hệ thống một chiêu dọa sợ hoặc miểu sát đại năng',
  },
  book_manifestation: {
    type: 'book_manifestation',
    name: 'Sách hiện thực',
    description: 'Độc giả lĩnh ngộ từ sách hoặc triệu hoán nhân vật trong sách',
    frequency: 'arc_end',
    intensity: 'extreme',
    setup: 'Mọi người khinh thường truyện của MC, hoặc MC gặp nguy hiểm không có người bảo vệ',
    payoff: 'Độc giả đột phá nhờ đọc sách quỳ lạy MC, hoặc MC triệu hoán Tôn Ngộ Không ra đập tan kẻ thù',
  },
  monster_evolution: {
    type: 'monster_evolution',
    name: 'Tiến hóa quái vật',
    description: 'Ăn nuốt hoặc hấp thụ gene để tiến hóa hình thái mới',
    frequency: 'every_3_chapters',
    intensity: 'high',
    setup: 'MC (dạng quái vật) gặp kẻ thù mạnh hơn, đánh bại và nuốt chửng',
    payoff: 'Hệ thống báo tiến hóa, mọc thêm cánh/chuyển dạng, chỉ số tăng vọt, đè bẹp kẻ thù tiếp theo',
  },
  // ── Anti-self-torture patterns: dopamine without requiring adversity setup ──
  smooth_opportunity: {
    type: 'smooth_opportunity',
    name: 'Chộp cơ hội',
    description: 'MC quan sát thấy cơ hội rồi hành động nhanh gọn, không cần ai chèn ép trước',
    frequency: 'every_chapter',
    intensity: 'medium',
    setup: 'MC quan sát thấy cơ hội (thị trường ngách, tài nguyên ẩn, quan hệ tốt, manh mối nhỏ)',
    payoff: 'MC chộp lấy nhanh gọn, kết quả vượt mong đợi — KHÔNG cần kẻ thù hay rào cản trước',
  },
  casual_competence: {
    type: 'casual_competence',
    name: 'Tự tin giải quyết',
    description: 'MC giải quyết vấn đề tự nhiên với kinh nghiệm/tài nguyên có sẵn',
    frequency: 'every_chapter',
    intensity: 'medium',
    setup: 'Vấn đề/yêu cầu xuất hiện, người thường thấy khó',
    payoff: 'MC giải quyết tự nhiên với kinh nghiệm/tài nguyên có sẵn, bystander kinh ngạc nhẹ — KHÔNG cần đau khổ trước',
  },
  peaceful_growth: {
    type: 'peaceful_growth',
    name: 'Phát triển yên bình',
    description: 'MC tiến bộ trong khoảng thời gian yên bình giữa các sự kiện lớn',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'Khoảng thời gian yên bình giữa các sự kiện lớn',
    payoff: 'MC tiến bộ qua training/quan hệ/khám phá nhỏ — không cần kẻ thù tạo áp lực',
  },
  // ── "Ngón tay vàng" patterns: MC win without combat (modern 2024-2026 standard) ──
  knowledge_leverage: {
    type: 'knowledge_leverage',
    name: 'Dùng Kiến Thức Thắng',
    description: 'MC leverage chuyên môn / kiến thức tương lai / training quá khứ để giải vấn đề',
    frequency: 'every_chapter',
    intensity: 'high',
    setup: 'Vấn đề xuất hiện, người khác bối rối / không biết hướng giải quyết',
    payoff: 'MC dùng kiến thức/chuyên môn (kỹ thuật, y học, kinh doanh, lịch sử) đưa giải pháp elegant — bystander kinh ngạc, đối thủ câm lặng. KHÔNG combat.',
  },
  network_payoff: {
    type: 'network_payoff',
    name: 'Quan Hệ Giải Quyết',
    description: 'MC dùng network/connection + đàm phán → win không cần đối đầu',
    frequency: 'every_3_chapters',
    intensity: 'medium',
    setup: 'Vấn đề thông thường cần "force" hoặc thời gian dài',
    payoff: 'MC gọi 1 cuộc điện thoại / nhờ 1 mối quan hệ / đàm phán mượt mà → vấn đề tan biến. Đối thủ ngạc nhiên vì MC có connection họ không ngờ.',
  },
  business_pivot: {
    type: 'business_pivot',
    name: 'Xoay Chiều Kinh Doanh',
    description: 'MC đọc thị trường, pivot strategy → grow mà không cần đối đầu trực tiếp',
    frequency: 'every_3_chapters',
    intensity: 'high',
    setup: 'Market signal (đối thủ ra mắt, customer feedback, trend mới)',
    payoff: 'MC adapt strategy mượt — beat competition bằng innovation/product/positioning, KHÔNG bằng confrontation hay thị phần war.',
  },
  quiet_competence: {
    type: 'quiet_competence',
    name: 'Lặng Lẽ Chuyên Nghiệp',
    description: 'MC làm việc lặng lẽ, không khoe — kết quả vượt expect khiến người xung quanh nhận ra',
    frequency: 'every_chapter',
    intensity: 'medium',
    setup: 'MC giao việc thông thường, không ai để ý',
    payoff: 'Kết quả của MC vượt xa standard — sếp/đồng nghiệp/khách hàng dần nhận ra MC thực lực. Recognition tự nhiên không cần MC self-promotion.',
  },
  insider_advantage: {
    type: 'insider_advantage',
    name: 'Lợi Thế Kẻ Biết Trước',
    description: 'MC dùng ký ức tương lai / kiến thức nội bộ → chộp deal trước khi người khác nhận ra',
    frequency: 'every_3_chapters',
    intensity: 'high',
    setup: 'Cơ hội/nguy cơ chỉ MC biết trước (dựa rebirth memory, insider info, expert knowledge)',
    payoff: 'MC ra quyết định trước — đầu tư đúng, tránh bẫy, ký deal đúng thời điểm. Sau đó người khác mới nhận ra MC "biết trước" như thế nào.',
  },
};
