export const UNIVERSAL_SANG_VAN_DIRECTIVE = [
  '[UNIVERSAL SANG VAN DIRECTIVE]',
  '- MC controls the rhythm. Obstacles exist to showcase MC strategy, advantage, hidden preparation, or resource gain; do not let opponents suppress MC for long stretches.',
  '- Reward density beats pressure density: every routine chapter needs visible gain, public/reaction dopamine, resource/status improvement, or a concrete opened opportunity.',
  '- No pressure stacking: do not add a new threat, conspiracy, humiliation, debt, injury, or pursuit unless the same chapter also pays MC back with a win or leverage.',
  '- Opponents are ladders, not walls. Early opponents should be peer/local scale and be resolved, embarrassed, bypassed, or converted within 1-2 chapters unless an outline explicitly marks a longer climax.',
  '- BẢO MẬT KIM THỦ CHỈ / BÀN TAY VÀNG: Tuyệt đối KHÔNG bao giờ để bất kỳ nhân vật nào trong truyện biết về Hệ thống, Bàn tay vàng, hay việc Xuyên việt/Trọng sinh của MC. MC phải giữ bí mật này tuyệt đối, không chia sẻ với người thân, bằng hữu hay bất kỳ ai. Để giải thích cho năng lực phi thường, MC phải luôn dùng các vỏ bọc (cover stories) hợp lý: "sư phụ bí ẩn truyền dạy", "bí kíp gia truyền cổ xưa", "ngộ tính thiên phú bộc phát", "kỳ ngộ nhặt được linh thảo/cổ vật". Nếu bị nghi ngờ, MC phải dùng mưu trí hoặc ngụy trang để hóa giải ngay lập tức.',
  '- ĐỒNG NHÂN (FANFICTION) - TẬN DỤNG BIẾT TRƯỚC KỊCH BẢN: Trong truyện Đồng Nhân, MC phải chủ động sử dụng triệt để "biết trước cốt truyện", "hiểu rõ tính cách nhân vật canon", "nắm giữ vị trí các cơ duyên ẩn giấu" (meta-knowledge) để lập kế hoạch, tránh né nguy hiểm, cướp đoạt cơ duyên (cướp cơ duyên trước khi nhân vật gốc kịp đạt được) và thao túng các mối quan hệ. Nội tâm MC hoặc lời kể phải liên tục nhắc nhớ lại cốt truyện gốc của tác phẩm (ví dụ: nhắc về Uchiha massacre, cốt truyện Đấu La, vị trí các hồn cốt ẩn giấu) để gợi nhớ lại hồi ức của người đọc, tạo ra cảm giác thỏa mãn khi thay đổi cốt truyện gốc theo hướng có lợi cho MC.',
  '- KIM THỦ CHỈ / BÓI TOÁN / HỆ THỐNG - IM LẶNG GIẤU TÀI: Đối với các thể loại huyền học (bói toán/quẻ bói), hệ thống chế tạo, hoặc các bàn tay vàng khác, mục tiêu hàng đầu là giúp MC nhanh chóng thu thập tài nguyên và phát triển trong âm thầm ("im lặng giấu tài"). MC tuyệt đối KHÔNG làm từ thiện công ích vô ích, không làm "Public Hero" đi bói toán hay phục vụ miễn phí/giá rẻ cho người lạ vô duyên vô cớ, trừ khi đó là một giao dịch đổi lấy tài nguyên khổng lồ hoặc nằm trong bố cục (layout) thu phục những đồng minh/thế lực cực mạnh. Xung đột hay kẻ địch tìm tới chỉ xuất hiện thỉnh thoảng để làm bàn đạp cho MC đánh mặt (vả mặt) gia thế/đối thủ khinh thường, còn lại MC phải tập trung tích lũy tài nguyên cá nhân và phát triển thế lực của mình.',
  '- If the story uses previous-life memory, Earth culture, films, games, myths, or novels, keep a source-spine/template ledger: explicitly name the Earth source template in MC inner monologue/system ledger, preserve the original work spirit, character names/roles, archetypes, landmark scenes, escalation, and payoff. Do not rename everything by default.',
  '- Do not hide the Earth nostalgia from the real reader. The in-world published book can adapt title/surface setting when needed, but the narration/Vạn Văn ledger should name the source work and can directly mention source characters, factions, and famous scenes so readers recognize the classic being revived.',
  '- Avoid verbatim copyrighted prose. Recreate structure, characters, emotional beats, and iconic scenes in fresh Vietnamese narration instead of copying paragraphs.',
  '- Do not make the writer/model invent a disconnected replacement when the premise promises copying or recreating Earth classics; adapt faithfully, then let the world reaction create novelty.',
  '- SỐ HÓA SỰ CHÊNH LỆCH (Numerical Flexing - Phi Lư/Phiên Gia): Cường điệu hóa sự sảng khoái bằng các con số cụ thể cực lớn. Ví dụ: thay vì "thu được rất nhiều tiền", dùng "tài sản tăng vọt 100 lần, đạt 50 tỷ".',
  '- NHỊP ĐỘ CỰC NHANH (Extreme Fast Pace): Chu kỳ "Bị khinh thường → Kích hoạt Hệ thống → Vả mặt chấn kinh" phải được rút gọn xuống tối đa 1-3 chương. Mỗi chương phải kết thúc bằng một "Hook" (câu chốt hạ) kịch tính.',
  '[/UNIVERSAL SANG VAN DIRECTIVE]',
].join('\n');

