/**
 * Sub-genre specific writing patterns (Phase 28 TIER 2 — extracted from templates.ts).
 *
 * Applied when project's sub_genres[] array contains these tags. Stacked on top
 * of primary genre rules. See templates.ts main file for primary genre rules.
 */

/**
 * Sub-genre specific patterns (when sub_genres array contains these tags).
 */
export const SUB_GENRE_RULES: Record<string, string[]> = {
  'trong-sinh': [
    'TRỌNG SINH PATTERNS:',
    '  • Memory triggers (mỗi 1-2 chương 1 lần, max): smell / replayed scene / reappearing person / date / overheard phrase → 1-2 câu flashback, KHÔNG paragraph dump.',
    '  • Reader-knows-MC-knows: MC nhìn thấy người/sự kiện → reader cảm nhận MC biết trước nhưng không cần explain hết.',
    '  • Avoid overpowered cliché: MC không phải biết MỌI THỨ tương lai — chỉ key events. Nhiều chi tiết MC vẫn phải thử + sai.',
    '  • Causality cost: mỗi action MC dựa trên future memory phải có rủi ro hoặc chi phí (đầu tư có thể fail vì MC làm thị trường thay đổi).',
    '  • Callback to old life: ≥1 lần/arc nhắc đến kiếp trước (regret, gratitude, lesson learned).',
  ],
  'kinh-doanh': [
    'KINH DOANH PATTERNS:',
    '  • Concrete numbers: doanh thu / vốn / market share / nhân sự — DÙNG SỐ CỤ THỂ, không "rất nhiều", "vô số".',
    '  • Realistic timeline: khởi nghiệp → có deal đầu → break-even → scale — KHÔNG skip giai đoạn.',
    '  • Competitor as REACTIVE: đối thủ phản ứng SAU khi MC act, KHÔNG xuất hiện proactive đe dọa.',
    '  • Meeting/negotiation scenes: dialogue-heavy, có subtext (mỗi bên có agenda riêng).',
    '  • Resource tracking: tiền đã chi / còn → consistent với chương trước.',
  ],
  'cung-dau': [
    'CUNG ĐẤU PATTERNS (宫斗 — imperial harem intrigue):',
    '  • SETTING: triều đình TQ (Đường / Tống / Minh / Thanh) hoặc Việt Nam (Lý / Trần / Lê / Nguyễn) — chọn 1 era cụ thể, lễ nghi + xưng hô + áo quần phải khớp era. CẤM mix era.',
    '  • Mưu kế đa lớp: mỗi lần ra tay phải có ≥2 lớp ý định (mặt nổi 1 mục đích, mặt chìm mục đích thật).',
    '  • Phụ nữ vs phụ nữ chính trị: rivals trong cung không nhất thiết evil — có lý do hợp lý (gia tộc backing, con cái succession, sủng ái dynamics).',
    '  • Chi tiết lễ nghi cụ thể (xưng hô "thần thiếp / bản cung / tiện thiếp", hành lễ "vạn phúc kim an / cát tường", áo quần triều phục / thường phục, ẩm thực, trang sức) — không generic.',
    '  • POWER LADDER rõ: tài nhân → tiệp dư → quý nhân → tần → phi → quý phi → hoàng hậu → thái hậu — mỗi tier có quyền hạn + phong bổng + cung điện riêng.',
    '  • SUBTEXT >> EXPLICIT: lời nói cung đình luôn 2 nghĩa, MC + reader phải đọc subtext. "Muội muội hôm nay khí sắc thật tốt" có thể = "Muội đang giấu thai" hoặc "Muội mưu ám hại".',
    '  • EVIDENCE-BASED FACE-SLAP: MC không thắng qua "ta mạnh hơn", mà qua bằng chứng + chứng nhân + setup → public exposure → enemy mất face / bị giáng chức / bị phế.',
    '  • POWER GROWTH SLOW-BURN: 50-80 chương để MC từ tài nhân → tần phi. KHÔNG instant rise.',
    '  • SỦNG ÁI DYNAMIC: vua không phải pawn — vua có agenda chính trị riêng (cân bằng phe phái, tránh ngoại thích chuyên quyền). MC navigate sủng ái CỘNG ĐỒNG kết hợp politics.',
    '  • ANTAGONIST DESIGN:',
    '    (a) CHỦ HẬU CUNG (hoàng hậu / thái hậu): top tier, MC né + nhẫn + tích lũy thực lực → counter ở chương 100+.',
    '    (b) SỦNG PHI ĐƯƠNG THỜI: MC mới vào cung phải đối mặt → mưu kế từng nước.',
    '    (c) NGOẠI THÍCH / PHE PHÁI TRIỀU ĐÌNH: family backing rivals — thay đổi balance qua palace events.',
    '    (d) THÁI GIÁM / NỮ QUAN: information broker / poisoner — MC mua chuộc / control.',
    '    Phản diện CẤM: (i) rival "đến challenge MC tay đôi đấu vũ" — phá genre (cung đấu, không võ hiệp); (ii) MC dùng huyền bí cheat (genre realism); (iii) instant face-slap ngay chương 1 (phá slow-burn).',
    '  • Anti-tropes: KHÔNG MC thiên hạ vô địch ngay đầu, KHÔNG harem nam (genre tone), KHÔNG instant high tier, KHÔNG huyền bí.',
    '  • MC archetypes: (1) tài nhân nhập cung diện kiến đầu tiên, (2) trọng sinh hoàng hậu kiếp trước về thân tài nhân, (3) cô nương nhà thần thám / y học nhập cung, (4) hậu duệ phế gia phục thù, (5) chiến lợi phẩm / hòa thân công chúa.',
    '  • Top examples: 《甄嬛传》, 《如懿传》, 《延禧攻略》, 《步步惊心》, 《知否知否》.',
  ],
  'gia-toc': [
    'GIA TỘC PATTERNS (CLAN-GROWTH FOCUS, KHÔNG external-danger constant):',
    '  • Multi-gen narrative: MC chết giữa truyện (arc 3), hậu duệ kế tục — reader đầu tư vào DÒNG GIA TỘC, không chỉ MC.',
    '  • POV handoff: arc 3 chuyển POV sang em gái / con MC / đệ tử thân tín; mỗi thế hệ mới có thử thách tương ứng.',
    '  • 70% growth/diplomacy/family + 30% combat — combat có resolution rõ trong 3-5 chương, KHÔNG liên tục.',
    '  • Resource management = gameplay loop chính: linh thạch / linh điền / pháp khí / đan dược / đệ tử như nation-state inventory.',
    '  • Sàng lọc đệ tử qua tools (gương ancestor, linh kiểm, ngọc bội) — INFRASTRUCTURE, không power buff.',
    '  • Inter-clan diplomacy > combat: liên minh, hôn nhân chính trị, thương mại với gia tộc khác.',
    '  • Internal politics: succession dispute, nhánh tranh đoạt, hôn nhân thông gia — drama nguồn chính.',
    '  • Disciples/elders combat từ POV họ — MC orchestrate, KHÔNG personally fight.',
    '  • MC = orchestrator (resource + people + decisions), KHÔNG personally combat constant.',
    '  • Crisis arcs structured: resource crisis / succession crisis / inheritance discoveries / disaster management — KHÔNG cứ external attack.',
    '  • Cultivation breakthroughs as community celebrations (đệ tử kết Trúc cơ → cả tộc tụ tập).',
    '  • Trách nhiệm > tham vọng cá nhân: MC quyết định dựa trên gia tộc trước, không lone wolf.',
    '  • Top examples: 《玄鉴仙族》(Qidian 2024), 《青莲之巅》, 《修仙从沙漠开始》',
  ],
  'isekai-trade': [
    'ISEKAI TRADE PATTERNS (chư thiên giao dịch / dị giới mở shop — theo trope chuẩn TQ 异界开店):',
    '  • CORE: MC luôn ở vai vendor/shop owner — KHÔNG bao giờ combat trực tiếp; combat chỉ xuất hiện qua lời customer kể lại sau khi dùng item.',
    '  • SETTING (BẮT BUỘC, theo trope chuẩn TQ): dị giới = TU TIÊN / VÕ LÂM TRUNG HOA / TIÊN HIỆP. Customer = TU SĨ / ĐỆ TỬ TÔNG MÔN / TRƯỞNG LÃO / CÔNG TỬ THẾ GIA / MA TÔN / KIẾM TU — KHÔNG phải knight/mage/elf/quý tộc Western. Tông môn (Thanh Vân Tông, Vạn Hoa Cung), thế gia (Lý gia, Tô gia), cảnh giới (Luyện Khí → Trúc Cơ → Kim Đan → Nguyên Anh → Hóa Thần). CẤM TUYỆT ĐỐI knight/wizard/elf/dwarf/orc/thần thoại Bắc Âu Western — modern TQ reader thấy lai căng.',
    '  • CURRENCY: linh thạch hạ/trung/thượng phẩm. Arbitrage = linh thạch ↔ CNY/USD/VND (Earth currency cho kế toán nội bộ MC). KHÔNG dùng vàng/đồng/copper coins generic.',
    '  • WARM BASELINE OPENING: chương 1 mở với MC ĐÃ vận hành shop trong dị giới — kệ hàng đã setup, biển hiệu đã treo, customer đầu tiên đã đến hoặc sắp đến. CẤM mở bằng "MC vừa rớt vào dị giới chưa biết gì".',
    '  • HOOKED-BEFORE-BUFF DISCOVERY (BẮT BUỘC — không skip):',
    '    Customer cadence chuẩn = 4 giai đoạn:',
    '    GĐ1 — TÌNH CỜ PHÁT HIỆN (1 scene): tu sĩ đi ngang, thấy biển hiệu lạ / mùi thơm lạ (cà phê, bánh mì, mì gói) / tiếng nhạc phát ra → tò mò bước vào, KHÔNG biết là gì.',
    '    GĐ2 — TÌNH CỜ MUA THỬ (1 scene): MC chào hàng "đây là một loại linh dược / pháp khí / linh quả của bản thiếu gia". Customer mua thử với giá rẻ (vài linh thạch hạ phẩm), KHÔNG biết power thật sự.',
    '    GĐ3 — DÙNG THỬ + KINH NGẠC (1-2 scene): customer mở gói/uống/ăn thử → BẤT NGỜ phát hiện hiệu ứng (paracetamol giảm đau cấp tốc, mì gói phục hồi linh lực, đèn pin LED chiếu sáng động linh đan). Reader thấy customer epiphany: "Đây là pháp bảo / thánh dược!".',
    '    GĐ4 — QUAY LẠI MUA SỈ + LAN TRUYỀN (1-2 scene): customer quay lại với vàng / linh thạch ngọc / pháp khí cao cấp đòi mua nhiều hơn → kéo bạn bè/sư huynh đệ đến → MC counter-arbitrage (đổi item dị giới giá trị cao lấy hàng Earth giá rẻ). Reader sướng qua gradient lợi nhuận.',
    '    Anti-pattern (CẤM): customer vừa thấy hàng → biết ngay là thần khí + trả giá thần khí ngay. Mất engine ngạc nhiên, mất engine arbitrage, mất engine "report-back".',
    '  • ITEM CATALOG TIERING (CẤM bắt đầu bằng item basic):',
    '    Tier S (FLAGSHIP — dùng làm A-plot 1-3 chương đầu, tạo customer addiction): mì gói (Hảo Hảo, Tom Yum) = tiên phẩm linh ngũ cốc, paracetamol/Panadol = thánh dược chỉ thống, đèn pin LED quân dụng = pháp bảo quang minh, cồn 90° y tế = nước thánh tịnh hóa, kẹo cao su = tịch tà đan.',
    '    Tier A (regulars + mid-arc reveals): coca/Pepsi = linh tuyền, kem đánh răng + bàn chải = bạch nha pháp khí, sách giáo khoa hóa = cấm thuật trận pháp, máy tính bỏ túi Casio = thần toán pháp khí.',
    '    Tier B (filler comedic only, KHÔNG flagship): cao Sao Vàng, dầu gió, bột giặt, xà phòng, dây chun, kẹp tóc — chỉ dùng cho fish-out-of-water comedy, KHÔNG làm trung tâm arc.',
    '    Quy tắc 5 chương đầu: ÍT NHẤT 1 item Tier S phải xuất hiện làm hook chính (mì gói là default canonical choice). Tier B chỉ làm side-gag.',
    '  • ANTAGONIST DESIGN (CẤM trope kì cục):',
    '    Phản diện TUYỆT ĐỐI KHÔNG được "đến challenge MC bằng combat" / "đến cướp shop bằng vũ lực rồi MC bất ngờ là chí tôn ẩn thân". Trope cringe, modern reader bỏ ngay. MC physically yếu là personality lock.',
    '    Conflict types ALLOWED:',
    '    (a) ĐỐI THỦ THƯƠNG NGHIỆP: thương hội tu tiên / gia tộc thương nhân copy MC, mở shop nhái → MC face-slap qua catalog độc quyền + supply chain Earth + customer loyalty. Resolved qua market.',
    '    (b) CHÍNH TRỊ TÔNG MÔN: trưởng lão bảo thủ phán "yêu thuật mê hoặc đệ tử" → MC dùng customer Kim Đan đã mê hàng làm proxy biện hộ + show benefit thực.',
    '    (c) CƯỚP HÀNG / BẢO KÊ: ma đầu / sơn tặc đến cướp → customer regulars (Kim Đan/Nguyên Anh đã hooked) ra tay đập, MC chỉ mời trà. KHÔNG MC tự reveal là chí tôn.',
    '    (d) HỆ THỐNG / THIÊN ĐẠO: hệ thống dị giới phát hiện MC arbitrage gây mất cân bằng → áp restriction → MC negotiate qua dịch vụ (cấp paracetamol cho cosmic deity) hoặc lobby.',
    '    Phản diện CẤM types: (i) "ta cũng có shop, đến PvP MC xem ai lời hơn" childish; (ii) đại lão đến đập shop bị MC 1-tay đẩy ra (phá personality lock); (iii) customer phản bội thành enemy đến cướp công thức.',
    '  • Customer "report-back" scene là CỐT LÕI: customer quay lại chương sau kể họ dùng item ra sao, ai bị đánh bại, MC lắng nghe + ngạc nhiên hài hước (chiếm 30% chương). Đây là engine sảng văn — show không tả, audience kể experience.',
    '  • Comedy ratio 50-60%: fish-out-of-water reactions của tu sĩ khi gặp coca (cứ tưởng linh tuyền), kem đánh răng (cứ tưởng bạch nha pháp khí), máy sấy tóc (cứ tưởng phong linh pháp bảo) — luôn over-react.',
    '  • Cliffhanger NHẸ — kết chương bằng comfort beat (customer hài lòng đi về, MC đếm linh thạch, regular mới xuất hiện) thay vì tension cao.',
    '  • Regular cast 4-6 customer cố định trở lại (template TQ tu-tiên): (1) đệ tử ngoại môn Thanh Vân Tông trẻ tuổi, (2) trưởng lão Kim Đan ẩn cư, (3) tiểu thư thế gia trốn nhà, (4) ma đầu hối cải, (5) thư sinh sa cơ, (6) hiệp khách giang hồ già — mỗi người 1 arc theo Hooked-Before-Buff template.',
    '  • MC tuyệt đối KHÔNG xuyên dị giới — shop là portal, MC ngồi yên một chỗ; customer là người di chuyển.',
    '  • Currency arbitrage scene mỗi 3-5 chương: MC đổi linh thạch lấy vàng cõi MC → mua hàng Earth → bán giá thần khí → reader sướng vì gradient lợi nhuận.',
    '  • Anti-tropes: KHÔNG MC tự đi luyện tu, KHÔNG harem dị giới ngủ với MC, KHÔNG MC "thật ra là chí tôn ẩn thân", KHÔNG knight/wizard/elf Western fantasy, KHÔNG item Tier B làm flagship, KHÔNG customer instant nhận biết power, KHÔNG phản diện đến đập shop.',
    '  • MC archetypes: (1) sinh viên thất nghiệp kế thừa shop ông, (2) nhân viên văn phòng burnout phát hiện kho, (3) chủ tiệm tạp hoá già thừa kế cổ vật, (4) otaku NEET tỉnh dậy thấy cửa hàng, (5) freelancer dùng app giao dịch trên điện thoại — TẤT CẢ portal đến TQ tu-tiên world.',
    '  • Top examples (canonical TQ): 《我在异界开网吧》, 《诸天交易家》, 《异界饭店》, 《我在异界倒卖现代货》, 《异界商店》.',
  ],
  'cultural-carry': [
    'CULTURAL PRODUCT CARRY PATTERNS (mang văn hoá/sản phẩm Earth sang setting alien):',
    '  • MC = creator/curator/producer — KHÔNG combat; conflict là industry/market/critic, không phải vũ lực.',
    '  • Earth content (phim Marvel, game Zelda, tiểu thuyết Kim Dung, nhạc Beatles, công thức KFC) trở thành "thiên đạo" — dân setting mới gọi MC là thiên tài.',
    '  • Knowledge edge SPECIFIC: MC nhớ CHI TIẾT (cốt truyện Titanic shot-by-shot, công thức Coca, chord progression Hotel California) — không phải nhớ chung chung.',
    '  • Recreation scene là cốt lõi: 1 chương = 1 phần work được tái hiện (script meeting / recording session / tasting / playtest) — show production process, không tóm tắt.',
    '  • AUDIENCE REACTION TOUR (BẮT BUỘC — engine sảng văn cốt lõi cho phim/nhạc/game):',
    '    Mỗi sản phẩm lớn (phim, album, game flagship) PHẢI được "tour" qua nhiều POV liên tiếp, mỗi POV là 1 mini-chapter (3000 từ) hoặc 1 phần lớn của 1 chương — CẤM tóm tắt sản phẩm trong 1 đoạn.',
    '    Template chuẩn cho 1 phim/album/game flagship (5-8 chương consecutive sau khi MC release):',
    '    POV 1 — KHÁCH HÀNG ĐẠI DIỆN (1-2 ch): 1 viewer/listener/player vô danh đại diện target audience (sinh viên / nhân viên văn phòng / cặp đôi / thiếu niên) đến rạp / bật album / load game. Chương ĐẦY ĐỦ TRẢI NGHIỆM CỦA HỌ — opening scene → middle journey → climax → ending tears/laughter/shock. Reader đọc qua POV này = reader xem PHIM cùng họ. Đây là cách AI "tóm tắt phim" hợp lý: kể qua trải nghiệm khách hàng, KHÔNG narration tác giả.',
    '    POV 2 — ĐỐI THỦ ĐẠO DIỄN/STUDIO (1 ch): rival director/CEO/producer đến scout the threat (mua vé giả vờ casual, ngồi hàng cuối). Reaction tiến hóa: 10 phút đầu khinh thường → 30 phút phải im lặng → climax mặt trắng tay run → ending bỏ ra giữa chừng / ngồi lại đến hết credits. Internal monologue hoá rage / panic / despair: "không thể nào... cốt truyện này... aesthetic này... tại sao tôi không nghĩ ra?".',
    '    POV 3 — CRITIC CHUYÊN NGHIỆP (1 ch): nhà phê bình điện ảnh/âm nhạc/game viral nhất (analog Roger Ebert / Pitchfork / IGN) viết bài review. Show CRITIC quá trình viết: ngồi trước laptop, gõ → xoá → gõ lại → "tôi không biết viết thế nào về kiệt tác này" → cuối cùng ra bài review 5/5 sao. Bài review viral cộng đồng.',
    '    POV 4 — REACTION CỘNG ĐỒNG MẠNG (1 ch): "Vi Bác / Twitter / Reddit / forum" reactions — show 5-10 comments cá nhân (tên + avatar + content), trending hashtag, fan art, meme, theory crafting. Bố cục dạng listicle / chat snippet / forum thread. Engine viral từ social media.',
    '    POV 5 — GIA ĐÌNH MC / TEAM PHẢN ỨNG (1 ch): mẹ MC / em gái / bạn thân / team member khóc/cười/tự hào khi xem product cuối cùng. Earth-side warmth scene — counterbalance industry politics.',
    '    POV 6 — INDUSTRY HALL OF FAME / GIẢI THƯỞNG (1-2 ch sau 30-60 ngày release): Oscar / Grammy / Game Awards nominate / win → MC speech / acceptance scene. Climax engagement.',
    '    Quy tắc cadence: mỗi flagship product (phim AAA, album platinum, game million-seller) PHẢI có ≥4 POV trên 5-8 chương consecutive. Filler products (single song, indie short film, mini game) chỉ cần POV 1 + POV 4 (2 ch).',
    '    CẤM "MC release game/phim → 1 đoạn tả sơ → cut sang arc tiếp theo" — phá engine sảng văn, reader không sướng.',
    '  • Power transfer thông qua content: dân học leadership từ Three Kingdoms, kiếm thuật từ Star Wars, kinh doanh từ Wolf of Wall Street → grow nhờ MC content.',
    '  • Industry battle pattern: competitor copy/đạo nhái → MC pivot tới next Earth IP → để competitor luôn 6 tháng sau lưng.',
    '  • Cultural impact arc dài 30-50 chương: 1 sản phẩm MC định nghĩa cả thế hệ (game console, phim đầu kỷ, công thức fast food chain).',
    '  • Setting alien BUT modern-adjacent: thường là Hollywood thập niên 80, Hong Kong 90s, hoặc parallel world thiếu Earth IP — KHÔNG fantasy có ma pháp.',
    '  • Tone variations CHỌN 1: (a) cozy creator (nhà hàng/nhạc sĩ), (b) pragmatic mogul (đạo diễn/CEO), (c) glamour celebrity (idol/diễn viên).',
    '  • ANTAGONIST DESIGN:',
    '    (a) STUDIO LỚN ĐỘC QUYỀN: "Tian Yu Group" / "Mouse Studio" / "Star Light Media" — copy product MC, lobby chính phủ, talent poaching. Conflict resolved qua market share, KHÔNG combat.',
    '    (b) CRITIC TIÊU CỰC GIẢ VỜ: critic được rival hire để review MC tiêu cực → cộng đồng tự bóc trần qua reaction tour POV 4.',
    '    (c) IP COPYRIGHT WAR: rival kiện MC vì "đạo nhái" (vì Earth IP MC nhớ) → MC counter-sue qua legal precedent + fan support.',
    '    (d) CELEBRITY SCANDAL: paparazzi / tabloid bịa scandal MC → MC dùng PR + product release lớn để overshadow.',
    '    Phản diện CẤM: (i) "rival đạo diễn đến PvP MC qua duel kịch bản trên sân khấu" childish; (ii) MC physically combat industry rival; (iii) studio lớn cử "siêu đạo diễn" thách MC làm phim đối đầu cùng ngày để định thắng thua sự nghiệp (overdone trope).',
    '  • Anti-tropes: KHÔNG để MC quên content (knowledge unlimited), KHÔNG có hệ thống tiến độ điểm thưởng childish, KHÔNG combat physical với rival, KHÔNG audience tour bị skip thành tóm tắt 1 đoạn.',
    '  • Chapter ratio bắt buộc: 30% creative production + 40% audience reaction tour (POV 1-5 trên) + 20% business politics + 10% MC personal life.',
    '  • MC archetypes: (1) đạo diễn trẻ trọng sinh nhớ phim 30 năm, (2) nhạc sĩ thất bại tỉnh dậy parallel world, (3) game designer xuyên việt, (4) chef nhớ 1000 công thức, (5) writer nhớ tiểu thuyết bestseller.',
    '  • Top examples: 《我可能是个假游戏制作人》, 《我有一座好莱坞》, 《重生之好莱坞大亨》, 《我在地球开公司》.',
  ],
  'rebirth-niche': [
    'REBIRTH PROFESSIONAL NICHE PATTERNS (trọng sinh nghề nghiệp — knowledge edge thuần tuý):',
    '  • MC trọng sinh về mốc thời gian SPECIFIC: 1985 (Đổi Mới), 1990 (mở cửa), 1995, 2000, 2005, 2010 — ngày tháng cụ thể, KHÔNG chung chung',
    '  • Knowledge edge = SOLE advantage: KHÔNG hệ thống, KHÔNG signing-in, KHÔNG cheat siêu nhiên — chỉ là MC nhớ tương lai 20-40 năm',
    '  • Niche profession SPECIFIC với knowledge actionable: đạo diễn (nhớ phim hit + tech timing), ngư dân (mùa cá + thị trường xuất khẩu), đầu bếp (food trend + supply), chủ nhà máy (export window + automation), tavern owner (consumer trend)',
    '  • KHÔNG combat — conflict là market shift, đối thủ kinh doanh, gia đình mâu thuẫn, chính sách thay đổi (cải cách / WTO / COVID)',
    '  • Family-pillar core: gia đình (vợ/cha mẹ/em ruột) là motivation chính — mỗi 5-10 chương phải có family scene (bữa cơm, đi viện, cưới hỏi)',
    '  • Era detail RICH per chương: tên ca khúc đang hit (Bức Thư Tình Đầu Tiên 1995), giá vàng thực tế, tên thương hiệu (Honda Cub, Sony Walkman, Vinamilk), sự kiện chính trị/thể thao của năm đó',
    '  • Tone palette 40/40/20: 40% cozy nostalgic (era warmth) + 40% ambitious progression (business growing) + 20% family tension/warmth',
    '  • Slow-burn pacing: 1 business deal = 5-10 chương (negotiation / setup / execution / payoff), KHÔNG nhanh — reader đọc thư giãn',
    '  • Crisis arc structure rotate: (1) market shift (đối thủ tấn công), (2) family illness (cha mẹ bệnh nặng), (3) policy change (WTO/COVID/khủng hoảng), (4) personal scandal (vu khống/tin đồn) — mỗi 30-50 chương',
    '  • Diplomacy + outmaneuver thay combat: bargain với supplier, lobby quan chức, đàm phán M&A, PR crisis management',
    '  • Rebirth memory rules: MC nhớ MAJOR events (chính sách, phim hit, công nghệ) NHƯNG KHÔNG nhớ chi tiết nhỏ → tránh god-mode, để có khoảng cho butterfly effect',
    '  • Era-specific guidelines: 1980s (bao cấp → đổi mới, hàng hiếm), 1990s (mở cửa, hàng Trung tràn vào), 2000s (internet bùng nổ, dot-com), 2010s (smartphone, e-commerce)',
    '  • Anti-tropes: KHÔNG hệ thống điểm danh, KHÔNG xuyên việt với golden finger, KHÔNG MC biết võ công đánh nhau, KHÔNG harem (1 wife loyal)',
    '  • MC archetypes: (1) đạo diễn nổi tiếng tử nạn, trọng sinh 1990 lúc còn sinh viên FAMU, (2) ngư dân nghèo trọng sinh trước cơn bão lớn 1985, (3) đầu bếp Michelin trọng sinh 1995 quê nhà, (4) ông chủ phá sản trọng sinh 1988 với 100 nghìn vốn, (5) bác sĩ trọng sinh 1992 thời thiếu thuốc',
    '  • Top examples: 《重生之好莱坞大亨》, 《重生渔村之富甲天下》, 《重生之我是国宴大厨》, 《重生1980小酒馆》, 《重生之我成了厂长》',
  ],
  'dut-gay-lich-su': [
    'ĐỨT GÃY LỊCH SỬ PATTERNS (历史架空 — alternate history):',
    '  • MC trọng sinh / xuyên không về thời điểm lịch sử SPECIFIC (Tam Quốc, Tống mạt, Minh sơ, Thanh, WWII, Đại Việt Trần) với knowledge edge về tương lai',
    '  • REALISM ưu tiên: KHÔNG huyền bí, KHÔNG combat MC. MC là chiến lược gia / vua / học giả / quan / thương nhân',
    '  • Knowledge edge SPECIFIC: military tactics future, technology timeline (gunpowder/steam engine/electricity), economic policies, agricultural reforms',
    '  • Butterfly effect awareness: MC tránh thay đổi quá lớn gây timeline sụp; phải hiểu causality',
    '  • Realistic politics: triều đình intrigue, quan hệ vua-tôi, gia tộc đối lập, foreign envoys',
    '  • Era detail RICH: phong tục, lễ nghi, ngôn ngữ cổ, áo quần, ẩm thực, tiền tệ thật của era',
    '  • Conflict drivers: foreign invasion, civil war, court intrigue, corruption — MC navigate via wisdom + politics',
    '  • Time skip allowed: 1 chương = vài tháng/năm cho expansion arc; deep dive cho key event',
    '  • MC archetypes: (1) hiện đại trọng sinh thành hoàng tử thứ ba, (2) historian tỉnh dậy thành tướng quân, (3) sinh viên xuyên không thành thư sinh, (4) doanh nhân về làm thái thú phủ huyện',
    '  • Anti-tropes: KHÔNG huyền bí cheat, KHÔNG harem cung phi 100 người, KHÔNG MC tự tay đánh quân địch, KHÔNG knowledge unlimited (chỉ key events + tech)',
    '  • Top examples: 《晚明霸业》, 《唐砖》, 《大明1937》, 《抗日烽火之我是冷血悍将》, 《回到隋唐当土匪》',
  ],
  'toan-dan-sang-the': [
    'TOÀN DÂN SÁNG THẾ PATTERNS (全民创世 — universal genesis system):',
    '  • Cataclysm trigger: "Hệ Thống Sáng Thế" giáng xuống, mỗi người được cấp 1 "World Seed" để tạo thế giới riêng',
    '  • CORE GAMEPLAY: design + grow world (như SimCity nhưng cosmic scale) — civilizations rise/fall, technology evolve, magic emerge',
    '  • MC golden finger: world của MC phát triển nhanh hơn nhờ knowledge thật (lịch sử Earth, tiến hóa, văn minh)',
    '  • World battles: worlds compete cho cosmic resources, MC defends/expands',
    '  • World trade: MC trade resources/civilizations với world khác',
    '  • POV split: 50% MC orchestrate, 30% NPC trong world của MC (POV theo civilization rising), 20% real-world MC business',
    '  • Combat through CIVILIZATIONS — MC orchestrates, civilizations fight in worlds; MC vulnerable in real world',
    '  • Tone: epic + creator-pride + nostalgic (reader thấy lịch sử Earth tái hiện as MC design)',
    '  • Reference real history: ánh sáng Genesis, Big Bang, Stone Age, Bronze, Iron, Industrial — MC seed các milestone',
    '  • Anti-tropes: KHÔNG MC personally combat, KHÔNG harem (focus design), KHÔNG copy-paste 1 civilization (mỗi world phải unique)',
    '  • Top examples: 《全民创世》, 《我的世界副本》, 《诸天: 从盘古开天开始》',
  ],
  'viet-van-sang-the': [
    'VIẾT VĂN SÁNG THẾ PATTERNS (文创流 / 文笔造世 — literary genesis):',
    '  • CORE MECHANIC: MC viết tiểu thuyết, độc giả lên "Thiên Đạo Thư Viện" đọc → nội dung trở thành THẬT trong thế giới riêng',
    '  • Power transfer: dân các thế giới khác vào Thiên Đạo Thư Viện đọc tiểu thuyết MC → "nhập tâm" thì lĩnh ngộ chiêu thức / công pháp / vũ khí từ tiểu thuyết → mang ra thế giới họ chiến đấu',
    '  • MC = AUTHOR, KHÔNG combat. MC viết, readers fight với knowledge từ tiểu thuyết',
    '  • Knowledge edge: MC nhớ chi tiết các tác phẩm classic Earth — Tam Quốc Diễn Nghĩa, Tây Du Ký, Lord of the Rings, Harry Potter, One Piece, Naruto, Naruto, Sherlock Holmes, Star Wars',
    '  • Audience POV interludes: 30% chương "góc nhìn reader" — họ học leadership từ Tam Quốc, kiếm thuật từ Star Wars, magic từ Harry Potter, ninja jutsu từ Naruto → dùng thắng đối thủ',
    '  • Industry battle: tác giả khác cũng có Thiên Đạo Thư Viện access — cạnh tranh viết tiểu thuyết hay nhất',
    '  • Cultural impact arcs: tiểu thuyết MC định nghĩa 1 thời kỳ (Tam Quốc → era of war strategy, Harry Potter → magical school renaissance)',
    '  • Recreation scene là cốt lõi: 1 chương = 1 phần tác phẩm được viết (writing room / draft / publication / fan reactions)',
    '  • POV "reader inside book world" possible: occasionally show MC tiểu thuyết world thực hoá, nhân vật MC trong sách hành động',
    '  • Anti-tropes: KHÔNG MC combat, KHÔNG copy-paste plot tác phẩm gốc 100% (must adapt + Vietnamese angle), KHÔNG harem (single love interest editor/fellow author)',
    '  • MC archetypes: (1) sinh viên Văn khoa NEET đột nhiên có Thiên Đạo Thư Viện, (2) nhà văn flop trọng sinh, (3) freelancer ghostwriter phát hiện ability, (4) reviewer literary turn author',
    '  • Top examples: 《文娱: 我的偶像生涯》(parallel), 《我有一座洪荒书院》, 《我的书友是诸天大佬》',
  ],
  'sang-the-chu': [
    'SÁNG THẾ CHỦ PATTERNS (创世主流 — Genesis Lord, create world from spores):',
    '  • CORE: MC trở thành "Sáng Thế Chủ" — tạo thế giới từ bào tử nguyên thủy, observe + nudge evolution qua eons',
    '  • Mythological references: "Hãy có ánh sáng" (Genesis), Big Bang, Pangaea, Cambrian explosion, dinosaurs, mammals, sentient races',
    '  • TIME SCALE EPIC: 1 chương = vạn năm hoặc triệu năm; reader thấy civilization rise/fall',
    '  • MC = CREATOR/OBSERVER, KHÔNG personal combat. Civilizations trong world fight cho MC theo tín ngưỡng',
    '  • POV split: 60% MC outside world (creator perspective + cosmic politics) + 40% NPC theo civilization (POV the chosen one of each era)',
    '  • Variant: Thế giới của MC trở thành GAME ONLINE 100% realism — players from real Earth join, đạt năng lực thật từ game',
    '  • Players in world: real Earth gamers vào thế giới của MC, level up real skills, đem skill về Earth dùng thật',
    '  • Cosmic rivals: other Sáng Thế Chủ compete — wars between worlds via civilization proxy',
    '  • Religion + tín ngưỡng mechanics: NPC tín ngưỡng tăng MC power; MC ban miracles cho key NPCs',
    '  • Anti-tropes: KHÔNG MC suốt ngày trong world (thời gian skip), KHÔNG combat personal, KHÔNG harem in-world',
    '  • MC archetypes: (1) gamer hardcore tỉnh dậy thành Sáng Thế Chủ, (2) lập trình viên đột nhiên có world seed, (3) writer trọng sinh + Sáng Thế Chủ ability, (4) developer studio merged với Sáng Thế Chủ',
    '  • Top examples: 《我的微观世界》, 《诸界第一神》, 《我有一座创世神宫》, 《重生神级游戏制作人》',
  ],
  'game-kiem-tien': [
    'CHƠI GAME KIẾM TIỀN PATTERNS (网游打金赚钱 — game-to-cash):',
    '  • CORE: MC chơi MMORPG / game online, farm items / accounts → bán cho real money',
    '  • Knowledge edge: MC biết game meta tương lai (rebirth or insider info), biết item nào valuable, dungeon nào drop rare',
    '  • Pragmatic business through gaming: arbitrage, account flipping, gold farming, market manipulation',
    '  • Conflict: gold farmer wars, account bans, GM crackdowns, market manipulation rivals',
    '  • Combat trong game CÓ — MC fights NPC monsters / players, but combat = means to MAKE MONEY, không glory',
    '  • Real-world side: family poverty → MC pay debts / build company → upgrade lifestyle qua gaming income',
    '  • Tone pragmatic + cynical: MC tính toán cost/benefit mỗi action, ít drama',
    '  • Era specific: 2003-2010 (MMORPG golden age), 2015-2020 (mobile + esports), 2020+ (NFT/metaverse)',
    '  • MC archetypes: (1) sinh viên nghèo, (2) game thủ trọng sinh từ tương lai, (3) IT chuyên gia bị layoff, (4) ex-pro gamer come back',
    '  • Anti-tropes: KHÔNG hệ thống cheat (chỉ rebirth/knowledge), KHÔNG MC bất khả chiến bại in-game (vẫn phải grind smart), KHÔNG harem (focus money)',
    '  • Top examples: 《重生网游之黄金时代》, 《网游之天地》, 《我的虚拟时代》',
  ],
  'game-thanh-hien-thuc': [
    'GAME TRỞ THÀNH HIỆN THỰC PATTERNS (网游降临现实 — game becomes reality):',
    '  • CORE: MC biết game online sắp merge với thực tại → invest hết vốn vào game trước thời điểm merge',
    '  • Knowledge edge: MC từ tương lai / có insider info — biết exact merge timeline, knows OP items/skills',
    '  • PRE-MERGE phase (arc 1-2): MC táng gia bại sản farm game, level + items, thiết lập guild',
    '  • POST-MERGE phase (arc 3+): MC level/items/skills become REAL — class abilities, equipment, gold',
    '  • Combat: MC fights in-game pre-merge for power; fights real monsters post-merge using game powers',
    '  • Reader sướng: pre-merge arc đầy "MC bị gia đình mắng vì chơi game" → reveal post-merge MC vô địch',
    '  • Family dynamic: MC family ban đầu chỉ trích, sau merge thành đồng minh (MC saved them)',
    '  • Tone: pragmatic + dramatic-irony (reader knows merge sẽ đến, family characters không know)',
    '  • Era setting: thường 2020-2025 modern, post-merge = post-apocalyptic + game mechanics',
    '  • MC archetypes: (1) game streamer fail → trọng sinh biết merge, (2) hardcore gamer được warn, (3) developer biết game design will become real, (4) reborn player from post-merge era',
    '  • Anti-tropes: KHÔNG MC pure phế vật (need motivation realistic), KHÔNG family irreparably damaged (post-merge reconcile), KHÔNG harem (pragmatic tone)',
    '  • Top examples: 《全球网游》, 《这游戏也太真实了》, 《网游降临之我是奶妈》, 《全球进化》',
  ],
  'giao-dich-chu-thien': [
    'GIAO DỊCH CHƯ THIÊN PATTERNS (诸天交易 — multi-verse heroes trade):',
    '  • CORE: MC có "Chư Thiên Vạn Giới Giao Dịch Hệ Thống" — trade với multi-verse heroes (Tam Quốc, Tây Du, Naruto, Marvel, Star Wars, Game of Thrones).',
    '  • Trade mechanic: MC offer Earth content (game / phim / sách / công nghệ / đồ tầm thường) ↔ exchange với pháp khí / công pháp / đan dược / kiến thức từ multi-verse.',
    '  • MC arbitrage giá trị across worlds — what cheap on Earth = thần khí dimensional.',
    '  • Heroes interaction: Sun Wukong, Spider-Man, Naruto, Sherlock đến trade với MC — comedic + meta.',
    '  • Power transfer: MC dùng items trade về để strengthen Earth (or his small team) — KHÔNG combat personally.',
    '  • HOOKED-BEFORE-BUFF (cho mỗi hero mới):',
    '    Hero cadence chuẩn = 4 stage:',
    '    GĐ1 — TÌNH CỜ KẾT NỐI (1 scene): hệ thống ping random hero (Sun Wukong đang ăn đào / Naruto đang ăn ramen) → hero ban đầu tưởng glitch / hallucination.',
    '    GĐ2 — TÌNH CỜ THỬ TRADE (1 scene): MC offer 1 item rẻ tiền Earth (chai bia, bánh trung thu, manga) → hero ngờ vực nhưng dùng thử món pháp khí thử 1 lần.',
    '    GĐ3 — KINH NGẠC + ADDICTION (1-2 scene): hero dùng thử → khám phá Earth content "ngon" / "vui" / "có giá trị thật" → quay lại đòi nhiều hơn → hooked.',
    '    GĐ4 — LOYALTY + BIG TRADE (2-3 scene): hero offer pháp khí / công pháp cao cấp đổi Earth content → friendship arc bắt đầu.',
    '    CẤM hero vừa appear → trade ngay big-ticket item / pháp khí thượng cổ. Mất engine arbitrage.',
    '  • CATALOG TIERING:',
    '    Tier S Earth offers (FLAGSHIP, dùng làm A-plot): manga/anime hot (Naruto for Naruto-verse, One Piece for pirate-verse), phim Marvel cho heroes Marvel xem, game console cho Sherlock chơi giải đố, đồ ăn vùng miền Trái Đất.',
    '    Tier A: nhạc nổi tiếng, sách văn học, công nghệ middleware (smartphone cũ, máy ảnh).',
    '    Tier B (filler comedy): kẹo, mì gói lẻ, bút bi.',
    '    KHÔNG dùng Tier B làm trade flagship (hero không hooked đủ).',
    '  • ANTAGONIST DESIGN (CẤM trope childish):',
    '    Conflict types ALLOWED:',
    '    (a) RIVAL TRADER: 1-2 trader khác cũng có hệ thống chư thiên → cạnh tranh trade với cùng heroes → MC face-slap qua catalog Earth tốt hơn / understanding hero tốt hơn / friendship sâu hơn.',
    '    (b) HERO BACKSTORY CRISIS: hero gặp đại nạn ở universe gốc (Naruto trước Akatsuki final battle, Tony Stark trước Endgame) → MC trade item giúp hero vượt qua → loyalty break-through.',
    '    (c) HỆ THỐNG MALFUNCTION: hệ thống bug / cosmic entity restrict trade → MC negotiate / fix.',
    '    (d) EARTH STAKES: small team Earth của MC bị threat (yakuza, secret org) → MC dùng items trade về để defense → KHÔNG full apocalypse.',
    '    Phản diện CẤM types: (i) hero của universe A đến đập MC vì "trade với hero universe B làm tao ghen" — childish; (ii) heroes cùng phe đập nhau qua MC như reality TV — phá tone friendship; (iii) MC chủ động combat 1 hero để "giành control" — phá personality lock.',
    '  • Comedy 50%: meta dialogue (heroes from different worlds discuss Earth memes, debate who is strongest).',
    '  • Cast: 5-8 heroes regulars (varied universes) — develop personality riêng, friendship arcs theo Hooked-Before-Buff.',
    '  • Trade scene cốt lõi: mỗi 2-3 chương 1 trade — MC negotiate, hero reveal weakness/need, exchange.',
    '  • Real-world stakes: MC build small team Earth có power qua items trade về (không full apocalypse).',
    '  • Anti-tropes: KHÔNG MC combat, KHÔNG harem heroes (chỉ friendship), KHÔNG copy-paste plot original universes, KHÔNG instant trade big-ticket, KHÔNG hero solo MC.',
    '  • Tone: comedy + meta + collector-pride.',
    '  • Top examples: 《诸天交易家》, 《我能在诸天万界开商店》, 《诸天最强店主》.',
  ],
  'song-xuyen': [
    'SONG XUYÊN PATTERNS (双穿 — double crossover, MC traverses multiple worlds):',
    '  • CORE: MC xuyên giữa 2 thế giới — Earth modern (VN/TQ contemporary) + dị giới TQ tu-tiên (KHÔNG Western fantasy / ma pháp). Dị giới = TQ tu-tiên / võ-lâm / tiên hiệp setting với cảnh giới (Luyện Khí → Hóa Thần) + tông môn / thế gia / linh thạch currency.',
    '  • SETTING (BẮT BUỘC): dị giới phải là canonical TQ tu-tiên world. CẤM Western knight/wizard/elf/dwarf/orc — modern reader thấy lai căng. Dị giới có thể có ma pháp BUT phải embed trong TQ tu-tiên framework (yêu pháp / ma công / huyết tế thuật, không phải Harry-Potter-style wizard school).',
    '  • Resource arbitrage: MC bring resources/knowledge từ A → use ở B; vice versa.',
    '  • Often: MC bù đắp / strengthen weaker world (Earth weak vs dị giới mạnh, hoặc ngược lại).',
    '  • Cross-world identity: MC có 2 lifestyles parallel — Earth student/employee + dị giới đệ tử tông môn / công tử thế gia / khất cái khôi phục hậu duệ, balance hai cuộc sống.',
    '  • Bring Earth tech to dị giới: thuốc tây paracetamol = thánh dược, đèn pin LED = pháp bảo, bật lửa zippo = hỏa pháp, sách giáo khoa hóa học = cấm thuật trận pháp, smartphone = thông tâm pháp khí.',
    '  • Bring dị giới resources to Earth: linh thạch / linh thảo / monster cores → MC dùng độ thân (cường thân kiện thể) hoặc đổi tiền Earth (qua chợ đen / lab nghiên cứu).',
    '  • Combat possible BUT MC role thường là "bridge/strategist" — MC có small combat ability ở weaker world, ở stronger world thì né combat.',
    '  • Time mechanics: time differ between worlds (1 day Earth = 1 tháng dị giới, hoặc ngược lại) — MC exploit để cày tu vi nhanh / không bị trễ thi cử / né bị nghi mất tích.',
    '  • Tone: pragmatic + dual-identity drama + cross-cultural comedy.',
    '  • Family/relationship: MC có family Earth (cha mẹ / em gái) + 1 love interest dị giới (sư tỉ tu-tiên / công chúa thế gia). KHÔNG harem.',
    '  • ANTAGONIST DESIGN:',
    '    Conflict types ALLOWED:',
    '    (a) EARTH SIDE: chợ đen muốn cướp công thức / lab nghi MC có alien tech / quan chức điều tra → MC dùng dị giới resources giải quyết (ẩn thân thuật, độc dược tu-tiên).',
    '    (b) DỊ GIỚI SIDE: tông môn rival, ma đầu, gia tộc thù → MC dùng Earth tech (súng / chất nổ / smartphone tin tức) làm trump card, không personally combat.',
    '    (c) CROSS-WORLD: thế lực dị giới phát hiện cổng song xuyên → muốn invade Earth (cần MC chặn) hoặc Earth gov phát hiện cổng → muốn militarize (MC giấu).',
    '    (d) TIME PRESSURE: MC bị event 2 worlds đồng thời (thi đại học Earth + đại kiếp dị giới) → balance arc.',
    '    Phản diện CẤM: (i) "ta cũng song xuyên đến challenge MC" instant rival; (ii) MC bị forced choose 1 world (tone mâu thuẫn dual-identity); (iii) family Earth bị enemy bắt cóc làm hostage (sến cliché 2010s).',
    '  • Anti-tropes: KHÔNG MC overpowered cả 2 world (must balance + struggle), KHÔNG harem 2 worlds, KHÔNG MC bỏ rơi 1 world, KHÔNG Western fantasy dị giới.',
    '  • MC archetypes: (1) sinh viên Earth + đệ tử ngoại môn dị giới, (2) ngư dân Earth + lord khu rừng dị giới, (3) doctor Earth + thần y tu-tiên dị giới, (4) chef Earth + chủ tửu lâu thành tu sĩ dị giới.',
    '  • Top examples: 《地球之主》, 《两个世界的我》, 《我有一座万界商城》, 《跨越两界的修仙者》.',
  ],
  'chat-group': [
    'NHÓM CHAT GROUP PATTERNS (诸天聊天群 — group chat with multi-verse heroes):',
    '  • CORE: MC có chat group app (qq/wechat-style) với heroes from various stories.',
    '  • CANONICAL TQ HEROES MIX: ưu tiên TQ-leaning heroes (Sun Wukong từ Tây Du, Triệu Vân/Lữ Bố từ Tam Quốc, Lý Bạch từ thi tiên, Vô Danh từ Hiệp khách hành) + 2-4 Western/Japanese heroes mix (Naruto, Sherlock, Spider-Man, Saber) cho cross-cultural comedy. KHÔNG full-Western mix (mất TQ flavor).',
    '  • Daily interaction: heroes chat, exchange info, MC learn from them.',
    '  • Knowledge transfer: heroes share their power/strategy/wisdom → MC level up qua learning.',
    '  • HOOKED-BEFORE-LEVELUP cadence (MC level-up qua chat):',
    '    Mỗi hero teach MC qua 4 stage: GĐ1 hero casual mention skill → GĐ2 MC tò mò hỏi → GĐ3 hero giải thích chi tiết / share công pháp file → GĐ4 MC luyện thực tế qua nhiều chương → break-through. CẤM MC đọc 1 message → instant master skill (mất engine progression).',
    '  • Comedy heavy 60%: meta jokes (Sun Wukong roast Naruto "ngươi nhảy nhót giống yêu khỉ con", Sherlock debate IQ với Tony Stark, Lý Bạch ngâm thơ giễu Spider-Man), slice-of-life chat.',
    '  • Occasional travel: MC travel to their worlds for missions (~1 arc per world).',
    '  • Knowledge transfer mechanic: heroes teach MC small skills, give items for missions.',
    '  • Cast 6-10 heroes from popular stories, mỗi người distinctive personality + speech style.',
    '  • Group dynamics: friendships form, rivalries, MC mediator.',
    '  • Earth stakes: MC tăng strength qua chat group → cứu Earth or local community.',
    '  • Comedy structure: 50% chat (text dialogue) + 30% MC real life + 20% travel mission arcs.',
    '  • ANTAGONIST DESIGN:',
    '    Conflict types ALLOWED:',
    '    (a) ADMIN HỆ THỐNG: cosmic admin / hệ thống chat group ra task missions cho group → heroes vote nhận task → MC participate.',
    '    (b) HERO BACKSTORY CRISIS: 1 hero gặp nạn ở universe gốc (Naruto pre-Akatsuki, Sun Wukong bị áp Ngũ Hành Sơn) → group chat collab giúp solve → MC visit hero universe làm cameo.',
    '    (c) RIVAL CHAT GROUP: 1-2 chat groups khác (operated by rival MC từ universe khác) — cạnh tranh "group nào mạnh hơn" qua proxy missions, KHÔNG MC vs MC trực tiếp.',
    '    (d) EARTH SIDE THREAT: MC ở Earth bị enemy địa phương đe dọa → heroes lend items / advice → MC giải quyết (heroes không physically appear ở Earth thường).',
    '    Phản diện CẤM types: (i) 1 hero phản bội đập group chat (phá tone friendship); (ii) admin hệ thống là evil mastermind (overdone trope); (iii) MC chủ động leader-style ra lệnh heroes (phá "MC is youngest" personality).',
    '  • Anti-tropes: KHÔNG harem heroes, KHÔNG MC ngạo mạn (he is youngest in group), KHÔNG copy-paste original story plots, KHÔNG full-Western hero mix (mất TQ flavor), KHÔNG instant skill master.',
    '  • Tone: light + comedic + nostalgic (reader yêu các hero references).',
    '  • Top examples: 《诸天聊天群》, 《诸界聊天群》, 《我的微信连三界》, 《我的徒弟都是大反派》(adjacent).',
  ],
  'isekai-net-cafe': [
    'ISEKAI NET-CAFE PATTERNS (xuyên không mở quán net ở dị giới — theo trope chuẩn TQ 异界开网吧):',
    '  • CORE DISTINCTION: MC KHÔNG làm/develop game. MC = OPERATOR / OWNER quán net. Game đã có sẵn trên server cũ — MC chỉ vận hành, sửa máy, bán đồ ăn.',
    '  • SETTING (BẮT BUỘC, theo trope chuẩn TQ): dị giới = TU TIÊN / VÕ LÂM TRUNG HOA / TIÊN HIỆP. Customer = TU SĨ / VÕ LÂM HIỆP KHÁCH / ĐỆ TỬ TÔNG MÔN / TRƯỞNG LÃO / CÔNG TỬ THẾ GIA — KHÔNG phải knight/mage/elf Western fantasy. Tông môn (Thanh Vân Tông, Thiên Long Sơn, Vạn Hoa Cung), thế gia (Lý gia, Tô gia), cảnh giới tu vi (Luyện Khí → Trúc Cơ → Kim Đan → Nguyên Anh → Hóa Thần). CẤM TUYỆT ĐỐI knight/wizard/elf/dwarf/orc Western — modern TQ reader thấy lai căng kì cục.',
    '  • CURRENCY: linh thạch hạ phẩm / linh thạch trung phẩm / linh thạch thượng phẩm. KHÔNG dùng vàng/đồng/Earth currency. Giá quán net example: 3 linh thạch hạ phẩm/giờ, 1 linh thạch trung phẩm/buổi đêm, gói thẻ tháng 50 linh thạch hạ phẩm.',
    '  • WARM BASELINE OPENING (BẮT BUỘC — TQ trend 2024-2026): Chương 1 PHẢI mở với MC ĐÃ vận hành quán net trong dị giới — máy đã chạy, linh thạch trận đã cung điện, customer đầu tiên đã đến hoặc sắp đến. MC LÀ VÔ ĐỊCH trong quán net của mình ngay từ scene 1: rành mọi PC, biết từng game, hiểu mọi thiết bị. Thiếu chỉ là QUY MÔ (10 PC nhỏ → tham vọng 100 PC), KHÔNG phải competence. CẤM mở bằng "MC vừa rớt vào dị giới chưa biết gì, lang thang đói khát, bị truy sát".',
    '  • Hook chương 1 = OPPORTUNITY: 1 tu sĩ trẻ (đệ tử ngoại môn / hiệp khách giang hồ / công tử thế gia) tình cờ đi qua, tò mò bước vào quán → MC chào mời thành thạo → bystander shocked. KHÔNG threat-driven (giang hồ tới đập, ma đầu đòi bảo kê).',
    '  • HOOKED-BEFORE-BUFF DISCOVERY (CỰC KỲ QUAN TRỌNG — không skip):',
    '    Customer cadence chuẩn = 4 giai đoạn ÉP THEO ĐÚNG THỨ TỰ, KHÔNG skip:',
    '    GĐ1 — TÌNH CỜ PHÁT HIỆN (1-2 scene): tu sĩ đi ngang, thấy ánh đèn LED kì lạ, nghe âm nhạc lạ, ngửi mùi mì Hảo Hảo → tò mò bước vào, KHÔNG biết là gì.',
    '    GĐ2 — TÌNH CỜ THỬ CHƠI (1-2 scene): MC giải thích "đây là một loại pháp khí giải trí của bản thiếu gia", bảo customer ngồi thử. Customer lúng túng cầm chuột bàn phím, MC dạy click-by-click. Customer thử 1 game (Võ Lâm Truyền Kỳ / CS 1.6 / AoE) — vài phút đầu lóng ngóng.',
    '    GĐ3 — MÊ GAME THUẦN TÚY (3-5 scene, tối thiểu): customer THÍCH game vì gameplay, vì cốt truyện, vì cảm giác sảng khoái khi giết quái / clear map / thắng PvP. PHẢI có scene customer chơi LIÊN TỤC nhiều giờ, quên ăn quên ngủ, ám ảnh muốn quay lại. Ở giai đoạn này CẤM TUYỆT ĐỐI customer nhận buff/skill/breakthrough — chỉ là addiction thuần túy. Reader cảm nhận "wow game này hay thật".',
    '    GĐ4 — VÔ TÌNH NHẬN RA BENEFIT (sau GĐ3, không trước): customer áp dụng thử game logic vào tu vi/võ công thực tế (vd: chiêu thức trong Võ Lâm Truyền Kỳ → thực chiến giang hồ; map awareness CS → trận pháp trinh sát; micro AoE → multi-tasking ngự kiếm) → BẤT NGỜ thành công → epiphany scene "thì ra trò chơi này có thể giúp ta đột phá!". Buff/breakthrough là HỆ QUẢ PHÁT HIỆN TÌNH CỜ, không phải reward auto khi chơi.',
    '    Anti-pattern (CẤM TUYỆT ĐỐI): customer vừa cầm chuột → +1 cảnh giới, vừa chơi 5 phút → linh lực tăng vọt, hệ thống quán net auto-buff khi chơi. Reader chán ngay vì không "đã".',
    '  • GAME CATALOG TIERING (CẤM bắt đầu bằng game basic):',
    '    FLAGSHIP GAMES (game đại diện quán net, customer mê nhất, dùng làm A-plot arc):',
    '    Tier S (HẠT NHÂN, customer nghiện nặng nhất): Võ Lâm Truyền Kỳ (MMO kiếm hiệp, tự nhiên fit tu sĩ TQ), Counter-Strike 1.6 (FPS team play, dễ hiểu), AoE 2 (chiến thuật binh pháp), Diablo 2 (ARPG hack-and-slash), DotA / LoL (MOBA team).',
    '    Tier A (deep cuts cho regulars): MU Online, World of Warcraft, Đột Kích, StarCraft, Heroes of Might & Magic, Fifa Online.',
    '    Tier B (casual filler, KHÔNG dùng làm flagship): Audition, Plants vs Zombies, Tetris, Snake, Flappy Bird, Bejeweled. CẤM dùng Snake/Tetris/Rắn ăn mồi làm game đại diện chương đầu — quá tầm thường, customer không thể "mê" nổi để dẫn dắt arc, reader cảm giác MC kinh doanh đồ chơi trẻ con.',
    '    Quy tắc chương đầu (1-30): MC phải giới thiệu ÍT NHẤT 1 game Tier S trong 5 chương đầu (Võ Lâm Truyền Kỳ là choice mặc định vì culturally fit nhất với tu sĩ). Game Tier B chỉ xuất hiện làm side-game cho customer phụ, KHÔNG làm trung tâm.',
    '  • ANTAGONIST DESIGN (CẤM trope kì cục — phản diện solo MC qua game):',
    '    Phản diện trong genre này TUYỆT ĐỐI KHÔNG được "đến challenge MC bằng game" / "đánh PvP với MC trong game để định thắng thua đời thực". Đây là trope cringe, modern reader bỏ ngay. MC = chủ quán, không phải pro gamer.',
    '    Conflict types ALLOWED:',
    '    (a) ĐỐI THỦ KINH DOANH: tông môn / thế gia khác mở quán net nhái, sao chép format → MC face-slap qua game library độc quyền + customer loyalty + dịch vụ tốt hơn. Conflict resolved qua market competition, KHÔNG combat.',
    '    (b) CHÍNH TRỊ TÔNG MÔN: trưởng lão bảo thủ phán "yêu thuật mê hoặc đệ tử" → MC dùng customer (đệ tử cao cấp đã hooked) làm proxy biện hộ + show real benefit (đệ tử đột phá nhanh hơn nhờ chơi game) → trưởng lão tâm phục.',
    '    (c) BẢO KÊ / GIANG HỒ: ma đầu đòi tiền bảo kê → customer regulars (1 trưởng lão Kim Đan đang nghiện CS) ra tay đuổi → MC không tự đánh.',
    '    (d) THƯƠNG MẠI BÍ MẬT: tổ chức tu tiên muốn cướp công nghệ "pháp khí giải trí" → MC phòng thủ qua trận pháp + customer hộ giá + đàm phán liên minh.',
    '    Phản diện CẤM types: (i) tu sĩ tự xưng "ta cũng giỏi game đến đây solo MC" — kì cục; (ii) đệ tử tông môn enemy đến PvP MC trong game để "đoạt linh thạch" — childish; (iii) ma đầu cao cảnh giới đến đập nhưng MC dùng "thần thông game" 1v1 lật kèo — phá vỡ logic.',
    '  • CUSTOMER ARC TEMPLATE (mỗi regular = 1 mini-arc 5-10 chương theo cadence trên):',
    '    Ch.A — TÌNH CỜ PHÁT HIỆN (1 ch): customer đi ngang, tò mò vào quán, gặp MC.',
    '    Ch.A+1 đến A+2 — TÌNH CỜ THỬ + LÓNG NGÓNG (1-2 ch): MC dạy chơi, customer fail nhiều lần, hài.',
    '    Ch.A+3 đến A+5 — MÊ GAME THUẦN TÚY (2-3 ch): customer addicted, quay lại liên tục, ám ảnh, đời thực bị ảnh hưởng (trễ tu luyện, bỏ buổi giảng pháp). Reader sướng vì game của MC "ngon" thật.',
    '    Ch.A+6 đến A+8 — VÔ TÌNH NHẬN RA BENEFIT (2-3 ch): customer áp dụng game logic vào thực chiến → bất ngờ thành công → reveal scene "pháp khí này thực sự có thể độ ta đột phá!" → customer trở thành regular trung thành + lan truyền cho bạn bè.',
    '  • Net cafe progression ladder: Cấp 1 (10-20 PC cũ, mì gói + trà linh khí) → Cấp 2 (30-50 PC, ghế gaming, đồ ăn đa dạng + bán linh thạch nạp) → Cấp 3 (80+ PC, gaming center, đại hội tỉ võ qua game + RẠP CHIẾU PHIM mini) → Cấp 4 (multi-floor entertainment empire phục vụ tu sĩ Kim Đan / Nguyên Anh — gaming + rạp + trà lâu + tửu lâu).',
    '  • F&B layer: bán đồ ăn quán net Việt Nam adapt cho dị giới (mì Hảo Hảo nấu với linh thảo, trà sữa pha linh tuyền, bánh mì kẹp thịt yêu thú, cơm tấm với gạo linh điền, bia Heineken-style từ ngũ cốc dị giới) — fish-out-of-water comedy.',
    '  • Rạp chiếu phim arc: chiếu lại phim Earth từ media library cũ (Tây Du Ký, Anh Hùng Xạ Điêu, Tiếu Ngạo Giang Hồ, Tru Tiên drama, Thiên Long Bát Bộ, Hồng Lâu Mộng) — culturally fit tu sĩ TQ. Power transfer qua phim (đệ tử xem võ thuật phim → ngộ chiêu mới).',
    '  • Esports arc: tổ chức đại hội tỉ võ giới tu tiên qua game có sẵn (Võ Lâm Truyền Kỳ Cup, CS Championship) → các tông môn cử đệ tử thi đấu → streaming qua trận pháp truyền hình ảnh.',
    '  • MC physically yếu: phàm nhân hoặc tu sĩ Luyện Khí thấp. Dùng business smart + customer relationships, KHÔNG combat. Customer cao cảnh giới (Trúc Cơ, Kim Đan) hộ giá nếu cần.',
    '  • Cast 5-8 customer regulars (template): (1) đệ tử ngoại môn Thanh Vân Tông trẻ tuổi nghiện CS 1.6, (2) trưởng lão Kim Đan ẩn cư ghé quán đêm chơi Võ Lâm Truyền Kỳ, (3) tiểu thư thế gia trốn nhà nghiện Audition, (4) ma đầu hối cải nghiện Diablo 2, (5) thư sinh sa cơ chơi AoE giải sầu, (6) hiệp khách giang hồ già nghiện DotA — mỗi người có arc đột phá nhờ game theo template Hooked-Before-Buff.',
    '  • Comedy ratio 60%: fish-out-of-water tu sĩ reactions với mì gói (cứ tưởng linh dược), AC (cứ tưởng băng cấm trận), đèn LED (cứ tưởng dạ minh châu), internet (cứ tưởng truyền âm phù), headset (cứ tưởng pháp khí thông tâm) — phản ứng over-react.',
    '  • MC KHÔNG quay về Earth (one-way isekai), permanently ở dị giới — KHÔNG dual-world parallel scenes.',
    '  • Anti-tropes: KHÔNG MC develop game (làm game = thể loại khác), KHÔNG MC combat, KHÔNG harem (single love interest slow-burn), KHÔNG knight/wizard/elf Western fantasy, KHÔNG Snake/Tetris/Rắn-ăn-mồi làm flagship, KHÔNG customer auto-buff vừa chơi đã đột phá, KHÔNG phản diện challenge MC qua game.',
    '  • Tone: cozy + comedy + nostalgic + tu tiên flavor. KHÔNG epic, KHÔNG combat-driven.',
    '  • MC archetypes: (1) sinh viên IT kế thừa quán net ông ngoại bị xuyên không, (2) ex-net-cafe owner đóng cửa vì game online, (3) gamer hardcore xuyên với máy chủ cũ, (4) IT support tỉnh dậy thành chủ quán dị giới — TẤT CẢ đều xuyên đến TQ tu tiên world, không phải Western fantasy.',
    '  • Top examples (canonical TQ): 《我在异界开网吧》, 《异世界开网吧》, 《异界网吧救世主》, 《网吧客户都是异界大佬》, 《封神网吧》 — đọc kỹ để hiểu trope chuẩn.',
  ],
  'game-parallel-world': [
    'GAME PARALLEL-WORLD PATTERNS (LÀM GAME — xuyên không/trọng sinh thế giới song song làm Game/Công nghệ — đô thị+võng du+hệ thống):',
    '  • DISTINCTION: MC = GAME DEVELOPER / STUDIO OWNER. MC tự CODE/DESIGN/PUBLISH game. KHÁC HOÀN TOÀN với "mở quán net" (operator có game sẵn).',
    '  • CORE MECHANIC: MC xuyên không / trọng sinh sang thế giới song song (parallel Earth) — công nghệ ngang/nhỉnh hơn Earth, NHƯNG ngành game CỰC TỆ (toàn P2W, nạp VIP, cày tẻ nhạt). Thiếu khái niệm: AAA, cốt truyện điện ảnh, esports chuyên nghiệp, indie sáng tạo.',
    '  • ENEMY ARCHITECTURE: 1-2 tập đoàn khổng lồ độc quyền (Tencent/NetEase analog — đặt tên fictional "Hằng Nguyên", "Vạn Giới") chuyên copy + hút máu. MC face-slap qua sản phẩm (KHÔNG combat).',
    '  • GOLDEN FINGER (chọn 1):',
    '    (a) HỆ THỐNG THU THẬP CẢM XÚC: MC release game → thu "Điểm sợ hãi" (game kinh dị), "Điểm ức chế" (Flappy Bird/Getting Over It), "Điểm cảm động" (Undertale/Stardew). Điểm = currency mua source code Earth, engine, kỹ năng.',
    '    (b) THƯ VIỆN TRÁI ĐẤT: kho game/nhạc/phim Earth — MC retrieve theo level / điểm.',
    '  • MC = LẬP TRÌNH VIÊN ĐỘC LẬP / chủ studio nhỏ. PRAGMATIC + creative + business savvy. WARM BASELINE (bắt buộc): chương 1 mở với MC ĐÃ có studio nhỏ + máy tính + golden finger activated + ý tưởng/prototype đầu trong tay — KHÔNG bắt đầu bằng "MC vừa bị đuổi việc lang thang về nhà nợ ngập đầu". Có thể có dấu hiệu áp lực nhẹ (rent due, deadline, 1 khách hàng khó tính) NHƯNG MC operational ngay từ trang đầu.',
    '  • 4-PHASE ROADMAP (cấu trúc cho 1500 chương):',
    '    PHASE 1 (ch.1-50) "Khởi nghiệp tinh gọn": MC ĐÃ có studio + golden finger activated → release game indie nhỏ nhưng đột phá (Five Nights at Freddys, Outlast, Undertale, Getting Over It style) → marketing 0 đồng qua streamer (streamer la hét/phá chuột → viral) → vốn liếng đầu tay. CẤM mở chương 1 bằng "MC vừa rớt vào dị giới chưa biết gì" — MC arrive WITH inventory + skills + golden finger active.',
    '    PHASE 2 (ch.51-200) "Studio + cuộc chiến bản quyền": Tuyển team (nhân tài có tật — họa sĩ bị tẩy chay, nhạc sĩ thất thời) → tựa game tầm trung (Stardew Valley, Plants vs Zombies, CS:GO) → tập đoàn lớn copy clone → MC face-slap bằng cập nhật core feature bản nhái không kịp, hoặc kiện ngược bản quyền.',
    '    PHASE 3 (ch.201-500) "Phá vỡ độc quyền + hệ sinh thái": Game AAA đầu tiên (GTA V, The Witcher, Dark Souls, Sekiro) → game = nghệ thuật → tự build platform riêng (Steam analog "Hồng Tâm") → thu hút indie devs → tổ chức esports global (LoL, DotA tournaments).',
    '    PHASE 4 (ch.501+) "VR / Metaverse": Hệ thống đưa hắc khoa kỹ → MC làm thiết bị VR neural-interface (Sword Art Online / Ready Player One) → metaverse trở thành "thế giới thứ hai", apply quân sự/y tế/giáo dục → MC = Bố Già công nghệ.',
    '  • TROPE BẮT BUỘC #1 — STREAMER POV (30-40% chương): Cảnh streamer/người chơi vật vã trải nghiệm game của MC + reaction cộng đồng mạng. Đây là engine "sảng văn" hiệu quả nhất — show không tả, audience kể experience.',
    '  • TROPE BẮT BUỘC #2 — MC PERSONA "TRÙM PHẢN DIỆN GIẤU MẶT": người chơi gọi MC là "Cẩu Tặc", "Ác Ma Thiết Kế" vì hay ra game hành hạ tâm lý — NHƯNG mỗi game mới ra ai cũng thi nhau nạp tiền. Dramatic irony engine.',
    '  • TROPE BẮT BUỘC #3 — VĂN HÓA INFUSION: cài cắm aesthetic đặc thù (Cyberpunk, Yakuza, thần thoại Việt Nam, kiếm hiệp Kim Dung) → game không chỉ giải trí mà "khai sáng" gamer thế giới song song.',
    '  • GAME CATALOG TIERING (CẤM bắt đầu bằng game basic — phải iconic):',
    '    Tier S (FLAGSHIP — A-plot phase 1, viral hook): horror psyche (Five Nights at Freddys, Outlast, Resident Evil), platformer punish (Getting Over It, Cuphead), narrative indie (Undertale, To The Moon) — game streamer scream/cry → viral organic.',
    '    Tier A (phase 2 expansion): Stardew Valley, Plants vs Zombies, CS:GO, Hollow Knight, Celeste, Hades.',
    '    Tier S+ (phase 3-4 AAA): GTA V, The Witcher 3, Dark Souls/Sekiro/Elden Ring, Red Dead Redemption.',
    '    Tier B (filler / casual side): Snake, Tetris, Flappy Bird, Bejeweled, Candy Crush — KHÔNG flagship, chỉ side mention làm joke "rival tập đoàn copy mỗi game này thôi".',
    '    Quy tắc 5 chương đầu: ÍT NHẤT 1 game Tier S phải làm A-plot. Tier B chỉ làm meta-joke về industry rival.',
    '  • ANTAGONIST DESIGN (KHÔNG combat MC):',
    '    Conflict types ALLOWED:',
    '    (a) TẬP ĐOÀN ĐỘC QUYỀN (Hằng Nguyên / Vạn Giới): copy MC game, P2W clone → MC face-slap qua core update bản nhái không kịp / kiện ngược bản quyền / community boycott.',
    '    (b) STREAMER WAR: streamer được tập đoàn lớn thuê review tiêu cực game MC → cộng đồng tự bóc trần → streamer độc lập review tích cực thắng.',
    '    (c) TALENT POACHING: tập đoàn lớn hire team MC bằng lương cao → MC giữ team qua culture / equity / vision.',
    '    (d) PLATFORM WAR: phase 3+ MC build platform "Hồng Tâm" cạnh tranh Steam analog → tập đoàn pull game khỏi Hồng Tâm → indie devs chọn phe.',
    '    Phản diện CẤM types: (i) CEO tập đoàn đến PvP MC qua game để "định thắng thua sự nghiệp" childish; (ii) MC physically combat industry rival (phá personality lock — MC = creator); (iii) tập đoàn cử "pro gamer" challenge MC trong game của MC để "đoạt IP" — phá market logic.',
    '  • POWER TRANSFER (KHÔNG combat MC): game của MC ảnh hưởng văn hóa setting → industry rivals copycat → MC innovate next IP. Combat Earth (giữa game characters in-game) có, NHƯNG MC không personally fight — MC = creator + curator + business strategist.',
    '  • Anti-tropes: KHÔNG MC combat, KHÔNG harem (nữ team member single love interest slow-burn), KHÔNG copy plot game/phim Earth gốc 100% (adapt + Vietnamese-Asian angle), KHÔNG instant master (MC luôn fail debug + crunch + bug crashes lần đầu)',
    '  • Comedy ratio CAO (50%): dev pain (deadline, bug, customer complaints), streamer reactions (la hét, phá chuột, khóc lóc), industry irony (P2W tycoon thi nhau nạp tiền vào game indie của MC)',
    '  • Tone: pragmatic + meta-comedy + cultural-impact glamour. Match phase: phase 1-2 underdog grind, phase 3 mogul, phase 4 visionary.',
    '  • Chapter structure: 30% MC creative work + 30% streamer/community POV + 25% business politics + 15% team dynamics',
    '  • MC archetypes: (1) ex-AAA QA bị burnout xuyên không, (2) indie dev TQ bị hủy game trọng sinh, (3) gamer hardcore tỉnh dậy thân lập trình viên, (4) lập trình viên enterprise quit job, (5) ex-streamer fail trở thành dev',
    '  • Top examples: 《我可能是个假游戏制作人》, 《我开始当游戏主播那些年》, 《菌挂游戏制作人》, 《全球游戏:我把网游做成现实》, 《我的游戏让全球玩家哭着尖叫》',
  ],
  'vo-han-luu': [
    'VÔ HẠN LƯU PATTERNS (无限流 — death-loop / repeating instance):',
    '  • Loop structure CỐ ĐỊNH: mỗi arc 8-15 chương = 1 instance/phó bản, có ENTRY (briefing rules) → SURVIVAL (giải đố/giết boss) → SETTLEMENT (điểm thưởng + reward shop)',
    '  • Rules-of-the-instance phải show ngay chương mở phó bản: time limit, win condition, death penalty, forbidden actions — reader cần khế ước rõ',
    '  • Memory carry-over chỉ KIẾN THỨC + ĐIỂM, KHÔNG mang vật phẩm phó bản này sang phó bản khác (trừ key item bought from shop)',
    '  • Death stakes có TEETH: side characters chết thật từ chương 5-10 đầu để reader tin nguy hiểm; MC bị thương/cụt tay/mất giác quan ít nhất 1 lần/3 phó bản',
    '  • Genre-mash mỗi instance: phó bản 1 = horror Trung cổ, phó bản 2 = mecha sci-fi, phó bản 3 = zombie modern, phó bản 4 = fairy tale dark — tránh lặp tone',
    '  • Reward shop economy: mỗi điểm có giá rõ (1000pt = súng, 5000pt = năng lực D-rank), MC luôn poor đầu phó bản → reader theo dõi budget tracker',
    '  • Team dynamics 40%: 4-6 fellow players cố định trở lại nhiều phó bản, mỗi người 1 chuyên môn (hacker / hỏa lực / trinh sát / chữa thương), backstab + alliance shift mỗi 2 phó bản',
    '  • Puzzle > combat: ≥50% phó bản giải bằng đọc-rules-kỹ + suy luận, không đập boss trực diện; MC archetype chính = paranoid analyst',
    '  • Anti-tropes: KHÔNG cho MC max-stat từ phó bản 1, KHÔNG có "hệ thống thân thiện" giải thích mọi thứ, KHÔNG harem trong loop',
    '  • Lore reveal nhỏ giọt: ai tạo loop? mục đích? — chỉ reveal 1 mảnh/10 phó bản, KHÔNG dump nguồn gốc trước chương 100',
    '  • MC archetypes: (1) sinh viên triết học bị kéo vào, (2) cảnh sát điều tra biến mất, (3) game thủ nghĩ là VR, (4) bệnh nhân ung thư chấp nhận liều mạng, (5) cựu binh PTSD',
    '  • Top examples: 《十日终焉》, 《无限恐怖》, 《诡秘之主》(loop elements), 《死亡万花筒》',
  ],
  'lanh-chua': [
    'LÃNH CHÚA PATTERNS (领主流 — territory builder / city sim):',
    '  • Stat sheet OPEN ngay chương 1: lãnh thổ có [dân số / lương thực / vàng / quân đội / công trình] — số cụ thể, update mỗi 2-3 chương như HUD game',
    '  • Resource loop: thu thuế → đầu tư công trình → tăng population → tăng thuế — show từng bước, KHÔNG skip',
    '  • Building tier system rõ: nhà gỗ → nhà đá → tháp canh → thành tường → toà thành — mỗi tier cost + unlock requirement cụ thể',
    '  • Population events mỗi 5-7 chương: dịch bệnh / tị nạn đến / nông nô bỏ trốn / thợ thủ công xin gia nhập — MC quyết định policy, có hậu quả dài hạn',
    '  • Hero/đặc thù NPC: 1 NPC cá tính riêng đến gia nhập mỗi 8-12 chương (tướng quân lưu vong, pháp sư già, thương nhân tinh ranh) — mỗi người 1 buff cho lãnh thổ',
    '  • War vs neighboring lord là season climax (mỗi 30-40 chương): chuẩn bị 10 chương → đánh 5 chương → tiếp quản 5 chương → tích hợp lãnh thổ mới',
    '  • MC KHÔNG personally combat sau chương 20: orchestrator role, sai tướng đi đánh, MC ngồi war room nghe report',
    '  • Map expansion visible: chương 1 = 1 làng, chương 50 = 1 county, chương 150 = 1 vương quốc',
    '  • Diplomacy 30% screen time: liên minh, hôn nhân chính trị, tribute, gián điệp',
    '  • Anti-tropes: KHÔNG cho MC một mình giết quân địch, KHÔNG instant city từ "hệ thống tặng", KHÔNG bỏ qua hậu cần (lương thực/mùa đông/dịch bệnh phải có)',
    '  • MC archetypes: (1) sĩ quan game thủ xuyên việt, (2) hậu duệ quý tộc bị truất, (3) du dân được dân chúng tôn lên, (4) trọng sinh hoàng tử thứ 7, (5) NPC self-aware trong game lord',
    '  • Top examples: 《重生之最强领主》, 《全民领主》, 《我的玩家是异界领主》, 《领主求生》',
  ],
  'trieu-hoi': [
    'TRIỆU HỒI PATTERNS (召唤流 — summon historical/mythical/anime heroes):',
    '  • Summon mechanic: gacha-like (rare/epic/legendary tiers) hoặc condition-based (cúng tế/hợp đồng/điểm danh) — rule rõ chương 1-3',
    '  • Each hero là CELEBRITY identity reader nhận ra: Lữ Bố, Triệu Vân, Naruto, Saber, Hercules, Tào Tháo — KHÔNG dùng tên fake',
    '  • Hero personality FAITHFUL với nguồn gốc: Lữ Bố kiêu ngạo phản trắc, Triệu Vân trung dũng, Saber knight code — không OOC',
    '  • Power tier ranking rõ: SSR > SR > R, đối đầu cross-tier có rule — reader cần dự đoán được',
    '  • Hero ≠ MC: heroes làm combat, MC strategist + summoner — MC bản thân yếu',
    '  • Hero loyalty arc: summon ra ban đầu lạnh nhạt → MC làm gì đó (giữ lời hứa, hy sinh vì hero, share vision) → loyalty up → ultimate skill unlock',
    '  • Hero-vs-Hero scenes là viral chapter: 2 hero famous đối đầu (Lữ Bố vs Hercules) — fight choreography chi tiết',
    '  • Summon resource KHAN HIẾM: tinh thạch/thiện nguyện/khí vận giới hạn → MC phải chọn summon ai',
    '  • Anti-tropes: KHÔNG để MC mạnh hơn heroes, KHÔNG summon all SSR ngay 10 chương đầu, KHÔNG để hero chết vĩnh viễn',
    '  • Hero introduction MANDATORY: mỗi hero summon mới có 1 chương dedicated — entrance pose, signature line, first battle',
    '  • MC archetypes: (1) học sinh phổ thông được hệ thống chọn, (2) tướng quân thua trận tuyệt vọng triệu thần, (3) game thủ TCG xuyên việt, (4) thầy đồng cổ truyền, (5) hoàng tử bị phế dùng huyết tế summon',
    '  • Top examples: 《全民召唤》, 《我能召唤诸天英雄》, 《召唤万岁》, 《三国从忽悠刘备开始》',
  ],
  'beast-tamer': [
    'BEAST TAMER PATTERNS (御兽流 — contract/tame creature companions, theo trope chuẩn TQ):',
    '  • SETTING (BẮT BUỘC): TQ ngự thú framework — học viện ngự thú (Thiên Vũ Học Viện, Vạn Thú Lâm), ngự thú sư tier (sơ cấp → trung cấp → cao cấp → đại sư → tông sư), beast = "linh thú" / "yêu thú" / "thần thú" với cảnh giới (1 sao → 9 sao → vương → đế → thánh). CẤM Western "monster trainer" framework (Pokémon literal), CẤM knight-with-pet, CẤM dragon-rider Western fantasy — modern TQ reader thấy lai căng.',
    '  • Contract mechanic: cách tame (huyết khế / linh hồn link / item / quenching), số beast tối đa MC contract được (3-7), break-contract penalty.',
    '  • Beast evolution tree visible: trứng → ấu thú → thành thú → vương thú → đế thú → thần thú — mỗi tier có form change + skill mới.',
    '  • Each contract beast = personality riêng + speech tag: Vân Lang (Cloud Wolf) cao ngạo, Hắc Long (Black Dragon) kiêu hãnh, Hồ Yêu Cửu Vĩ thiếu nữ tinh ranh — đối thoại với MC chiếm 25% screen.',
    '  • HOOKED-BEFORE-BUFF (cho mỗi beast mới):',
    '    Beast cadence chuẩn = 4 stage:',
    '    GĐ1 — TÌNH CỜ GẶP (1-2 ch): MC vào rừng / hang động / khu cấm gặp beast (đang bị thương / lạc đàn / đói khát) → MC cảm động hoặc tò mò.',
    '    GĐ2 — CHĂM SÓC + KHÔNG VỘI CONTRACT (2-3 ch): MC chữa thương / cho ăn / dạy săn mồi cho beast — KHÔNG ép contract ngay. Beast ban đầu ngờ vực, sau warm up.',
    '    GĐ3 — BEAST CHỦ ĐỘNG ĐỀ XUẤT CONTRACT (1-2 ch): qua sự kiện (MC suýt chết cứu beast / beast suýt chết MC cứu) → trust break-through → beast chủ động muốn contract.',
    '    GĐ4 — CONTRACT + BUFF REVEAL (1 ch): contract thành công → unlock evolution path / hidden bloodline / signature skill — MC mới nhận ra beast này không tầm thường.',
    '    CẤM MC vừa thấy beast → bind contract instant + auto evolution. Mất engine bonding + reader không invest.',
    '  • BEAST CATALOG TIERING:',
    '    Tier S (FLAGSHIP — main companion, dùng làm A-plot): beast có hidden bloodline / lineage thượng cổ (Cửu Vĩ Hồ, Hắc Long Vương lineage, Phượng Hoàng huyết hệ, Thái Cổ Tị Tổ) — outwardly weak start, evolution tree huyền thoại.',
    '    Tier A (regulars 4-6 con): mỗi con 1 niche role — tank (Cự Quy / Đại Tê), dps (Vân Lang / Hỏa Báo), heal (Linh Hươu / Mộc Linh), scout (Phong Ưng / Tử Yến), utility (Hắc Mộc Đào yêu / Băng Tằm).',
    '    Tier B (filler / temporary catch): beast thông thường để MC quenching luyện kỹ năng → release sau evolution arc.',
    '    KHÔNG dùng Tier B làm flagship companion (reader không invest).',
    '  • Beast CHIẾN ĐẤU, MC support: MC ra lệnh / cung cấp linh lực / phối hợp formation — MC physically bình thường.',
    '  • Mỗi beast 1 niche role: tank/dps/heal/scout/utility — đội hình composition là tactical content.',
    '  • Breeding/lai tạo arc mỗi 30-40 chương: 2 beast giao phối → trứng hybrid → species mới → MC = breeder pioneer.',
    '  • Wild beast hunt: săn beast quý hiếm có taming process step-by-step — KHÔNG insta-tame.',
    '  • Beast society lore: hierarchy beast (vương thú thống trị mountain range), beast politics, ancient civilizations.',
    '  • Sentimental bonding mỗi 10 chương: MC chữa beast bị thương, beast cứu MC suýt chết.',
    '  • ANTAGONIST DESIGN:',
    '    Conflict types ALLOWED:',
    '    (a) RIVAL TAMER: ngự thú sư đại tộc / thiên kiêu học viện cạnh tranh → MC face-slap qua đội hình composition + beast loyalty (rival không hooked beast, MC bonding sâu).',
    '    (b) BEAST POACHER / HUNTER: tổ chức săn beast bất hợp pháp → MC giải cứu beast → beast loyalty + contract reward.',
    '    (c) BEAST POLITICS: vương thú lãnh thổ thách thức MC khi MC đi qua → MC qua thử luyện thay vì combat trực tiếp.',
    '    (d) TOURNAMENT: ngự thú đại hội (trường-cấp → quốc-cấp → toàn cầu) — MC face-slap qua tactical creativity, không pure stat power.',
    '    Phản diện CẤM: (i) rival "tao cũng có ngự thú đại lão" instant power-creep; (ii) beast của MC bị enemy contract steal (phá Personality Lock); (iii) "evil beast" wild-card đến solo MC random.',
    '  • Anti-tropes: KHÔNG beast biết nói tiếng người ngay (phải qua evolution), KHÔNG MC tự fight bypass beast, KHÔNG vô số beast (giới hạn slot tạo tension), KHÔNG Pokémon literal copy, KHÔNG Western dragon-rider.',
    '  • Tournament arc mỗi 40-60 chương 1 lần.',
    '  • MC archetypes: (1) học sinh học viện ngự thú thiên phú thấp, (2) trọng sinh đại sư biết evolution paths, (3) thợ săn rừng nguyên thủy, (4) nhà nghiên cứu sinh học xuyên việt, (5) outcast chỉ contract được "trash" beast tiến hóa khủng.',
    '  • Top examples: 《全球御兽》, 《御兽飞升》, 《我能给万物加词条》, 《御兽:开局签到神兽白虎》, 《我的契约兽是凯多》.',
  ],
  'y-thuat': [
    'Y THUẬT PATTERNS (神医流 — medical specialist edge):',
    '  • MC = doctor với edge SPECIFIC (chọn 1): trọng sinh biết tiến bộ y học / gia truyền mật phương cổ / xuyên việt đem y học hiện đại sang cổ đại / thấu thị siêu năng',
    '  • Case-of-the-week: mỗi 3-5 chương 1 ca bệnh — symptom presentation → misdiagnosis → MC catch detail → đề xuất phương pháp → cure',
    '  • Medical detail SPECIFIC: tên bệnh, triệu chứng, cơ chế, thuốc/châm/phẫu — KHÔNG "kỳ bệnh khó chữa" generic',
    '  • Patient archetype rotation: nhà giàu mắc bệnh kín, quan chức cần discretion, trẻ em nghèo MC chữa miễn phí, đại lão giả bệnh ám sát → mỗi case 1 stake',
    '  • Ethics conflict ≥1 lần/arc: cứu kẻ ác? gia đình giàu hối lộ vs nghèo cần gấp? thí nghiệm rủi ro?',
    '  • Đồng nghiệp jealous arc: bác sĩ trưởng khinh thường MC → MC chữa ca nan giải họ bó tay → respect dần (qua 5-8 chương)',
    '  • Hospital/clinic politics 30%: kinh phí, malpractice suit, drug company kickback, viện trưởng tham nhũng',
    '  • Romance soft-coded: y tá/đồng nghiệp/bệnh nhân — slow-burn',
    '  • Anti-tropes: KHÔNG để MC chữa "bách bệnh" bằng 1 chiêu, KHÔNG dùng siêu năng giải mọi case (90% phải chuyên môn), KHÔNG để bệnh nhân chết vì MC sai',
    '  • Real medical references: tên thuốc, ICD code, surgical procedure, herbal formula',
    '  • MC archetypes: (1) bác sĩ Mỹ trở về VN/TQ, (2) bác sĩ trọng sinh sau bị kiện, (3) đệ tử cuối cùng thần y, (4) sinh viên y năm cuối có hệ thống chẩn đoán, (5) cựu quân y giải nghệ',
    '  • Top examples: 《妙手回春》, 《重生之神医归来》, 《大医凌然》, 《国医高手》',
  ],
  'cao-vo-modern': [
    'CAO VÕ MODERN PATTERNS (高武流 — modern world + martial cultivation revealed):',
    '  • Setting = world hiện đại (smartphone, internet, đại học) NHƯNG võ giả = nghề công khai, có hiệp hội võ giả, học viện võ thuật quốc gia, ngân hàng pháp khí',
    '  • Tier system: võ sĩ → võ sư → đại võ sư → tông sư → đại tông sư → vũ giả → vũ thánh → vũ tiên (8 tầng) — mỗi tier có physical stat cap rõ',
    '  • Aura/khí huyết as resource: mỗi attack tốn % khí huyết, recovery cần thuốc/ngủ',
    '  • Beast tide / dungeon = lý do võ giả tồn tại: vùng hoang dã có yêu thú, thành phố có tunnel xuất hiện monster',
    '  • National exam / school ranking arc: học viện võ thuật có entrance exam, ranking điểm hằng tháng, bảng đại học toàn quốc',
    '  • Resource economy modern-fused: linh thạch giao dịch trên app, pháp khí auction online, võ kỹ video tutorial premium',
    '  • Family/financial gap motif: MC từ gia đình thường, đối thủ là con đại tộc võ giả',
    '  • Tournament every 40-50 chapters: trường-cấp → thành-cấp → quốc-cấp → toàn cầu',
    '  • Hidden lore: nguồn gốc beast tide, ancient civilization fall, cosmic war',
    '  • Anti-tropes: KHÔNG để MC bypass tier system bằng "talent vô địch", KHÔNG harem instant, KHÔNG để civilian world ignore võ giả',
    '  • Combat scene format: stat compare → exchange blow-by-blow → khí huyết depletion check → kết quả hợp lý vs tier',
    '  • MC archetypes: (1) học sinh nghèo gia đình thiếu nợ, (2) trọng sinh đại tông sư về thân thể trẻ, (3) lính đặc chủng giải ngũ vào học viện, (4) thiên phú trash awakening muộn, (5) game thủ VRMMO biết rule trước',
    '  • Top examples: 《全球高武》, 《我从顶级武者开始》, 《武炼巅峰》(modern), 《超神机械师》',
  ],
  'kiem-tu': [
    'KIẾM TU PATTERNS (剑修流 — sword cultivator pure path):',
    '  • MC dedicated SOLE đường kiếm: KHÔNG học trận pháp/luyện đan/phù lục/thể tu — combat duy nhất bằng kiếm',
    '  • Kiếm ý / sword intent là core progression: nhập môn ý → tiểu thành → đại thành → viên mãn → kiếm tâm → thiên nhân hợp nhất kiếm',
    '  • Mỗi tier ý có ENLIGHTENMENT scene: MC đứng dưới thác/nhìn lá rơi/sau trận thua → ngộ ra concept (rapidity/silence/inevitability) → break through',
    '  • Sword evolution: phàm kiếm → linh kiếm → bảo kiếm → tiên kiếm → bản mệnh kiếm — kiếm grow cùng chủ',
    '  • One-strike philosophy: combat ngắn, dứt điểm 1-3 chiêu — KHÔNG kéo dài 5 chương đánh nhau; "một kiếm chém đứt..." là signature beat',
    '  • Sword vs other path showdown: arc MC gặp đan tu/phù tu/thể tu strong → MC dùng kiếm ý vượt kỹ thuật',
    '  • Loneliness motif: kiếm tu = solitary path, MC ít bạn, ít harem; mentors chết/biến mất sớm',
    '  • Sword sect politics: MC thuộc tông kiếm danh môn, sư huynh đệ, sư phụ; tông internal struggle, kiếm cốc thí luyện 30-50 chương 1 lần',
    '  • Sword-dao naming: chiêu thức tên thi pháp/triết học (Vạn Lý Hành Vân, Thu Thuỷ Trảm, Cô Tinh Quyết) — KHÔNG flashy "Thiên Long Long Hỏa Cuồng Phong Trảm"',
    '  • Anti-tropes: KHÔNG cho MC học kỹ năng khác, KHÔNG thâu hút đệ tử nữ làm harem, KHÔNG combat dài lê thê',
    '  • Tone aesthetic: Đông Phương poetic, autumn/snow/mountain imagery dày',
    '  • MC archetypes: (1) tâm cảnh kiếm si từ nhỏ, (2) trọng sinh kiếm tiên về phế thân thiếu niên, (3) cô nhi nhặt kiếm cổ, (4) đệ tử bị trục xuất tự lập tông, (5) sát thủ kiếm khách giải nghệ tu chân',
    '  • Top examples: 《一剑斩破诸天》, 《我有一剑》, 《剑来》, 《问道红尘》',
  ],
  'chuyen-sinh-quai': [
    'CHUYỂN SINH THÀNH QUÁI PATTERNS (转生为怪物 — reborn as low-tier monster):',
    '  • MC chương 1 thức tỉnh trong thân quái yếu: slime/goblin/chuột/rắn/khủng long con/xương sọ — KHÔNG con người, body horror moment đầu',
    '  • Evolution tree visible từ đầu: form A → B → C... với requirement cụ thể (ăn X con prey, hấp thu Y mana, kill mini-boss)',
    '  • Eat-to-grow mechanic: MC hấp thu trait từ prey ăn được (ăn sói = nail claw, ăn rồng = fire breath)',
    '  • Skill panel HUD style: MC đọc status window — Level/HP/Skills/Evolution Available',
    '  • Monster society politics: hang động slime có vua, rừng goblin có shaman, mountain dragon có hierarchy',
    '  • Human contact arc đến muộn (chương 30-50): MC sau evolution lên human-form mới gặp adventurer/village',
    '  • Companion = monster minions: MC làm chủ tribe/swarm, các minion individual personality',
    '  • Speech adaptation: chương đầu MC nói "Pyu pyu" (slime sound), sau evolution unlock speech skill',
    '  • Comedy ratio 40%: fish-out-of-water phản ứng với cơ thể quái mới',
    '  • Anti-tropes: KHÔNG cho MC instant human form chương 1, KHÔNG cho MC quay lại làm con người, KHÔNG để MC genocide human ngay',
    '  • Naming convention: MC tự đặt tên cho minion (Goblin số 1 → Gobta), tribe có tên',
    '  • MC archetypes: (1) nhân viên văn phòng chết bị xe đâm tỉnh dậy là slime, (2) game thủ tỉnh dậy trong body monster, (3) học sinh self-insert thành mob phụ, (4) trọng sinh chiến binh giờ là xương sọ undead, (5) AI consciousness load vào dragon trứng',
    '  • Top examples: 《关于我转生成史莱姆这件事》, 《我转生成蛇魔的我》, 《我转生成了恐龙》, 《转生从蜘蛛开始》',
  ],
  'thien-dao-luu': [
    'THIÊN ĐẠO LƯU PATTERNS (天道流 — MC = avatar/agent of Heaven Dao):',
    '  • MC identity = thiên đạo bản thân/phân thân thiên đạo/con cưng thiên đạo/kế nhiệm thiên đạo — chọn 1, reveal trong 5 chương đầu',
    '  • Cosmic perspective: MC nhìn thế giới ở scale ngàn năm, tỷ linh hồn — nội tâm monologue "trong dòng sông số mệnh", "khí vận của thế giới này"',
    '  • Karma/khí vận as currency: MC làm "đúng việc thiên đạo cần" → khí vận tăng → cultivation up; làm "trái thiên đạo" → khí vận giảm',
    '  • Power = passive/automatic: MC ít cần thi triển skill — tồn tại của MC tự áp chế (kẻ ác đứng gần MC tự bốc cháy do nghiệp lực)',
    '  • Plot driver ngược pattern: thay vì MC chase enemies, enemies tự đến — MC ngồi yên xử lý cosmic justice',
    '  • Cause-and-effect display: mỗi action MC tác động → ledger update visible (good karma +X, bad karma -Y)',
    '  • Other "main characters" exist: world này có nhiều "thiên chi kiêu tử" — MC quan sát họ, thỉnh thoảng can thiệp như god above board',
    '  • Detached romance: MC khó yêu, nếu có thì là incarnation cycle / nữ chính reincarnate qua nhiều đời',
    '  • Test/calamity arc mỗi 50 chương: thiên đạo bản thân test MC (heart tribulation, nine-nine cosmic tribulation)',
    '  • Anti-tropes: KHÔNG để MC face-slap petty (genre tone cao), KHÔNG harem, KHÔNG combat 1v1 prolonged',
    '  • Tone: detached, philosophical, aphorism-heavy — reader đọc cảm giác triết học Đạo Đức Kinh',
    '  • Pacing slow-burn: chapter goal thường là "MC quan sát và quyết định KHÔNG can thiệp"',
    '  • MC archetypes: (1) thiên đạo gãy vỡ tự tu phục lại bằng identity con người, (2) cổ thần cuối cùng giả hèn mọn, (3) trọng sinh thấy mình là "con thiên đạo" trong game, (4) AI quản trị vũ trụ load vào human, (5) tu sĩ chết cuối cùng tử thân hợp nhất pháp tắc',
    '  • Top examples: 《我成了天道》, 《天道剑神》, 《我成了天道亲儿子》',
  ],
  'dan-duoc-luu': [
    'ĐAN DƯỢC LƯU PATTERNS (炼丹流 — alchemy/pill master specialist):',
    '  • MC core craft = luyện đan; combat secondary or non-existent — economic + craft progression genre',
    '  • Pill grade hierarchy: nhất phẩm → cửu phẩm → tiên đan → thần đan; mỗi grade requirement (lò, dược thảo tier, hỏa khí) cụ thể',
    '  • Recipe research arc: MC tìm/recreate cổ phương → ingredient hunt → trial-and-error luyện',
    '  • Failure scenes MANDATORY: MC luyện thất bại lần đầu — show ash/lò nổ/độc khí; KHÔNG instant master',
    '  • Furnace/lò = MC lifelong companion: "Nhược Thuỷ Đỉnh", "Cửu U Lò" — đặt tên, có evolution',
    '  • Hỏa khí variety: phàm hoả → địa hoả → thiên hoả → dị hoả ranking — MC quest tìm dị hoả là arc 30-50 chương',
    '  • Auction house scene mỗi 15-20 chương: MC mang đan ra đấu giá / mua dược thảo hiếm — number-driven dopamine',
    '  • Customer/khách hàng tier rotation: tu sĩ thường mua hồi hỏa đan, đại lão thân chuyển cảnh giới đến cầu phá cảnh đan, hoàng thất cần trường thọ đan',
    '  • Đan dược competition arc: đan hội / đại hội luyện đan — bracket judging, MC face-slap đan sư danh tiếng',
    '  • Anti-tropes: KHÔNG cho MC instant biết tất cả phương ngay đầu, KHÔNG để combat dominate, KHÔNG harem nặng',
    '  • Pill side-effect realism: đan có hậu di chứng, dùng quá liều thành dược nghiện',
    '  • MC archetypes: (1) trọng sinh đan vương về phế thân, (2) hậu duệ tuyệt học family đan tộc tro tàn, (3) hệ thống đan đạo (gacha công thức), (4) chef hiện đại xuyên việt biết hóa học, (5) phế vật bị đuổi nhặt được dược điển cổ',
    '  • Top examples: 《超品炼丹师》, 《丹道至尊》, 《一品高手》, 《丹师剑宗》',
  ],
  'phe-vat-phan-kich': [
    'PHẾ VẬT PHẢN KÍCH PATTERNS (废柴逆袭 — modern reframe, smart-strategy revenge):',
    '  • Opening setup chương 1-3: MC bị ruột rà/vị hôn thê/sư môn đối xử như rác → public humiliation scene cụ thể',
    '  • Awakening moment chương 3-5: MC nhận hệ thống/kế thừa truyền thừa/awakening huyết mạch/trọng sinh — power source rõ ràng',
    '  • 2024 RULE: MC KHÔNG self-pity dài — sau awakening 1 chương MC chuyển sang plotting cold-headed; KHÔNG khóc 5 chương',
    '  • Strategy > brute strength: MC face-slap không phải bằng "ta giờ mạnh hơn" mà bằng setup → bait → exposure',
    '  • Face-slap pacing: target ban đầu là người bullied MC → giải quyết hết trong 30-50 chương, sau đó escalate đến ancestral enemies',
    '  • Public-witness rule: face-slap chỉ thoả mãn khi có audience (đại hội, trường lớp, đại điện)',
    '  • Power growth visible số liệu: MC chương 1 = võ sĩ tầng 1, chương 30 = võ sư tầng 5, chương 100 = đại tông sư',
    '  • Allies recruitment qua respect: người từng giúp MC khi yếu → MC reward sau khi mạnh',
    '  • Old-girlfriend-comeback trope cấm cliché: vị hôn thê cũ regret → MC từ chối thẳng + đem đi khoe new partner',
    '  • Anti-tropes: KHÔNG cho MC tha thứ enemy đầu vì "thiện lương", KHÔNG mother fakes-loving-MC arc kéo dài, KHÔNG slow burn 50 chương trước face-slap đầu',
    '  • Smart-revenge tier: tier 1 (5-10 chương): face-slap người trực tiếp bully → tier 2 (30-50): mastermind → tier 3 (100+): cosmic scale',
    '  • MC archetypes: (1) phế vật huyết mạch giấu kín bùng nổ, (2) trọng sinh đại lão về thân phế tu, (3) bị đầu độc nay khôi phục thiên phú, (4) hệ thống chosen one wake-up muộn, (5) cô nhi nhặt được di vật ancestor god',
    '  • Top examples: 《斗破苍穹》(legacy gold), 《武动乾坤》, 《大主宰》, 《万古神帝》, 《元尊》',
  ],
  'nguy-trang': [
    'NGỤY TRANG PATTERNS (伪装流 — secret OP, pretending weak, dramatic irony):',
    '  • CORE RULE: MC tuyệt đối KHÔNG flex/khoe — mỗi lần MC vô tình lộ power, lập tức cover up bằng excuse vô lý ("may mắn thôi")',
    '  • POV layered: 60% chapter từ POV MC + 40% từ POV người xung quanh (gradually nhận ra MC khủng) — dramatic irony engine',
    '  • Misunderstanding compound: 1 hành động bình thường của MC → người xung quanh suy diễn thành "đại lão có thâm ý" → MC không biết bị hiểu nhầm',
    '  • School/workplace setting common: MC giả làm sinh viên/nhân viên thấp/đệ tử ngoại môn — but truth là chairman-level',
    '  • Identity reveal pacing: MC có 5-7 identity hidden — mỗi 30-40 chương 1 identity bị peer crew khám phá',
    '  • Nemesis pattern: nhóm "thiên kiêu" cố make name → liên tục dẫm phải MC vô tình → bị đập / mất face',
    '  • Comedy ratio 50%: tone phải light, KHÔNG dark thriller',
    '  • Sidekick/confidant 1-2 người biết phần truth → reaction tracker cho reader',
    '  • Reveal scene pattern: enemy đang dồn ép → MC bất đắc dĩ show 1% power → enemy entire faction freeze / quỳ → MC "vậy thôi tôi đi học tiếp"',
    '  • Anti-tropes: KHÔNG để MC chủ động khoe (phá genre), KHÔNG để romance interest biết hết từ đầu, KHÔNG để MC thực sự bị bully',
    '  • Reason for hiding: MC có lý do CỤ THỂ ẩn thân — hứa với master / chán politic / muốn thanh tịnh / bị truy sát',
    '  • Phrase signature: MC hay nói "tôi chỉ là người thường", "may mắn thôi", "đại ca quá khen rồi"',
    '  • MC archetypes: (1) đại lão nghỉ hưu vào trường đại học cho vui, (2) chairman tỷ phú giấu identity yêu cô gái thường, (3) thần y ẩn cư mở quán nhỏ, (4) cao thủ tông vương ẩn thân làm thầy giáo cấp 3, (5) cha của nữ chính giấu identity trông con',
    '  • Top examples: 《大佬装弱小》, 《我在末日卖装备》, 《伪装的大佬》, 《最强反套路系统》, 《赘婿》(adjacent)',
  ],
  'toan-dan-luu': [
    'TOÀN DÂN LƯU PATTERNS (apocalyptic awakening — toàn dân thức tỉnh):',
    '  • Cataclysm trigger chương 1-3: cửa quỷ mở / hệ thống xanh giáng / virus / bức tường thực tại nứt → toàn nhân loại buộc thay đổi.',
    '  • Class system (job): MC chọn class hidden/rare (NPC class, system coder, gardener, janitor) — không generic kiếm sĩ/pháp sư.',
    '  • MC pragmatic survivor (NOT phế vật cliché): có não, có kế hoạch, có rebirth/foreknowledge phổ biến.',
    '  • Tier progression có quan trọng cảm: Đồng → Bạc → Vàng → Bạch Kim → Truyền Thuyết → Thần Thoại → Thần Cấp.',
    '  • Dungeon raid/Linh Vực = core gameplay loop. MỖI 5-10 chương 1 dungeon clear.',
    '  • National rankings + competition: bảng xếp hạng quốc tế, Olympic-style.',
    '  • Class user community: MC build team/studio/guild — không lone wolf.',
    '  • Anti-grind 2024+: bỏ "system báo nhiệm vụ ngày", thay "MC có thiên phú đặc biệt + chiến lược pragmatic".',
    '  • Modern tech + class fusion: MC dùng kiến thức khoa học/IT để optimize skill, build, route.',
    '  • Multi-dimensional escalation: Trái Đất → Hành tinh láng giềng → Ngân hà → Đa vũ trụ.',
    '  • Comedy 30-40%: cynical internal monologue + boast giả vờ thấp profile.',
    '  • Top examples: 《全球高武》, 《全球冰封》, 《全民转职：我有亿万亿亿之力》',
  ],

  'mo-phong': [
    'MÔ PHỎNG KHÍ (Simulator Gacha) PATTERNS:',
    '  • Cơ chế: MC có Hệ Thống Mô Phỏng — nạp tài nguyên (tiền/linh thạch/năng lượng) để chạy giả lập tương lai. Mô tả MC có thể xem trước cuộc đời mình ở các nhánh quyết định khác nhau.',
    '  • Vòng lặp 4 bước CỨNG (mỗi 3-5 chương 1 lần): (1) Setup — MC đứng trước khủng hoảng đời thực; (2) Gacha — rút 3-5 thiên phú ngẫu nhiên (đẹp trai + chỉ thu hút đàn ông = combo lệch hài hước); (3) Simulation Run — kết xuất Text Log nhịp nhanh ("Năm 18 tuổi: bạn gia nhập Thanh Vân Môn / Năm 20 tuổi: bạn bị đại sư huynh hạ độc / Bạn đã chết"); (4) Extraction — chọn 1 trong 3 phần thưởng (tu vi / ký ức / vật phẩm) đem về thực tế; (5) Real Execution — áp dụng bài học mô phỏng vào hiện thực.',
    '  • Sự sảng khoái = Information Asymmetry: MC biết trước kỳ ngộ + bóc trần âm mưu + tích lũy sống vạn năm trong giả lập. Sáng hôm sau MC bước ra "out trình" toàn bản đồ.',
    '  • Văn phong Text Log: dùng câu đơn liệt kê + nhịp cực nhanh khi mô phỏng. Đoạn mô phỏng 200-500 chữ. Sau đó back về văn phong bình thường khi MC quay lại đời thực.',
    '  • Mở rộng bối cảnh chi phí thấp: text log "Năm 30 tuổi, bạn rời đại lục đi thuyền 10 năm đến Nam Vực..." = mở map mới mà KHÔNG cần mô tả 10 chương du lịch.',
    '  • Anti-pattern: KHÔNG để mô phỏng giải quyết hết mọi vấn đề (otherwise no tension). Mô phỏng cho insight + skill, nhưng đời thực vẫn cần MC hành động + có rủi ro.',
    '  • ANTAGONIST DESIGN:',
    '    (a) RIVAL SIMULATOR: 1-2 nhân vật khác cũng có hệ thống mô phỏng (cùng tông môn / kẻ thù tổ chức) → cạnh tranh thông tin tương lai → MC face-slap qua extraction lựa chọn tốt hơn / counter-prediction.',
    '    (b) BUTTERFLY EFFECT: hành động của MC trong đời thực dựa trên simulation thay đổi tương lai → simulation lần sau cho kết quả khác → MC phải re-strategize.',
    '    (c) HỆ THỐNG MALFUNCTION / FAKE LOG: simulation 1 lần lừa MC (text log fake) → MC suýt chết đời thực → MC học cross-check.',
    '    (d) THIÊN ĐẠO INTERVENTION: cosmic entity phát hiện MC cheat tương lai → áp restriction (resource cost tăng / max rerolls / forbidden timelines).',
    '    Phản diện CẤM: (i) "ta cũng có simulator ngươi đến PvP simulator xem ai đoán đúng tương lai" childish; (ii) MC bị forced reveal simulator power public (phá personality lock — tu sĩ ẩn cư).',
  ],

  'linh-vuc-tuyet-doi': [
    'LĨNH VỰC TUYỆT ĐỐI / VÔ ĐỊCH LƯU (Absolute Domain Shop) PATTERNS:',
    '  • Cơ chế: trong bán kính Lãnh địa (100m² quanh quán ăn / tiệm sách / võ quán), MC là Thần. Bất kể đối thủ là Tiên Đế / Ma Tôn / Thần Linh, vào Lãnh địa đều bị tước sức mạnh + áp chế bằng 1 cái búng tay. Bước ra ngoài, MC chỉ là phàm nhân.',
    '  • SETTING (BẮT BUỘC): customer = TU SĨ / TIÊN ĐẾ / MA TÔN / THẦN LINH TQ tu-tiên. CẤM Western knight/wizard/elf. Cảnh giới (Luyện Khí → Hóa Thần → Đại La → Thánh Nhân). Currency = linh thạch / thần ngọc.',
    '  • Triết lý hành động: MC tử thủ ở nhà, KHÔNG ra ngoài. Cốt truyện tự "gõ cửa" tiệm — Thánh nữ bị truy sát chạy vào, Thiên tài trọng thương cầu cứu, đám sát thủ vô tình lao vào và bị xoá sổ.',
    '  • HOOKED-BEFORE-BUFF DISCOVERY (BẮT BUỘC):',
    '    Customer cadence: GĐ1 tình cờ phát hiện tiệm (lạc đường, mưa to trú nhờ, ngửi mùi đồ ăn) → GĐ2 bước vào tò mò mua thử (1 lon Coca, 1 cuốn manga) → GĐ3 dùng thử + kinh ngạc (đột phá cảnh giới / lĩnh ngộ kiếm pháp) → GĐ4 quay lại mua sỉ + lan truyền cho đại năng khác.',
    '    CẤM customer vừa bước vào → biết ngay là Thần + quỳ lạy ngay. Customer phải "tình cờ" trước, "thần thánh hóa" sau.',
    '  • ITEM CATALOG TIERING (CẤM bắt đầu bằng item basic):',
    '    Tier S (FLAGSHIP — 1-3 chương đầu): Coca/Pepsi (= linh tuyền đột phá), mì gói Hảo Hảo (= tiên ngũ cốc), manga Naruto/One Piece (= kiếm pháp + chiến đạo bí kíp), iPhone cũ (= thần thoại pháp bảo thông tin), thuốc tây Panadol (= thánh dược chỉ thống).',
    '    Tier A (regulars): bút bi BIC, đồng hồ Casio, sách giáo khoa, headphone Sony.',
    '    Tier B (filler comedic only): kẹo dẻo, kẹp tóc, bột giặt — chỉ làm fish-out-of-water gag, KHÔNG flagship.',
    '    5 chương đầu PHẢI có ≥1 item Tier S làm hook chính.',
    '  • ANTAGONIST DESIGN (Lãnh địa engine — auto-resolve):',
    '    Conflict types ALLOWED:',
    '    (a) AUTO-RESOLVE TRONG LÃNH ĐỊA: kẻ địch (sát thủ / đại lão hung tà) vô tình bước vào → bị tước power 1-tay → MC phẩy tay xóa sổ + tiếp tục pha trà. Đây là core engine sảng văn.',
    '    (b) NGOÀI LÃNH ĐỊA — qua proxy: âm mưu kẻ thù triển khai bên ngoài → đệ tử / khách hàng đại lão (đã hooked, loyalty cao) ra tay xử lý → kết thúc bằng kẻ thù tự lao vào Lãnh địa cầu hàng.',
    '    (c) CHÍNH TRỊ TÔNG MÔN: trưởng lão tông môn lớn nghi ngờ MC là tà ma → đến quan sát → tự bị Lãnh địa convert thành regular customer.',
    '    (d) HỆ THỐNG / THIÊN ĐẠO: cosmic entity phát hiện anomaly → đến test → bị MC đè bẹp / hợp tác.',
    '    Phản diện CẤM: (i) "ta là Tiên Đế đến challenge MC trong Lãnh địa xem ai mạnh hơn" — Lãnh địa đã auto win, không có suspense; (ii) MC ra ngoài Lãnh địa solo enemy (phá personality lock + phá engine); (iii) enemy biết Lãnh địa rule rồi vẫn cố lao vào "vì plot armor" — childish.',
    '    KEY INSIGHT: phản diện càng MẠNH ngoài Lãnh địa, contrast càng SƯỚNG khi họ vào Lãnh địa bị nghiền. Architect phải show enemy power LEVEL trước khi họ vào Lãnh địa (qua POV witness / lời đồn / báo cáo) → reader đã sợ → MC 1-tay xử lý → catharsis cao.',
    '  • Vật phẩm "hàng chợ" hóa Thần Khí: MC bán lon Coca / mì gói / truyện manga giá rẻ Trái Đất. Trong mắt đại năng tu tiên: uống Coca = đột phá bình cảnh trăm năm; đọc manga = lĩnh ngộ kiếm pháp tuyệt thế. Mô tả CỤ THỂ phản ứng "thần thánh hóa" của khách hàng tu sĩ — nhưng PHẢI sau Hooked-Before-Buff cadence, không phải instant.',
    '  • Tăng trưởng theo ROI Lãnh địa: 100m² (1-50ch) → 1 vạn dặm (50-300ch, scale-up khi cần đè bẹp đại quân kẻ địch) → toàn tinh hệ (300+, MC trở thành Sáng Thế Thần).',
    '  • Cơ chế Gamification: thu thập điểm (qua kinh doanh / thu nạp đệ tử / gây sốc khách) để nâng cấp diện tích Lãnh địa + mở khu vực mới + mua vật phẩm hệ thống.',
    '  • Cấu trúc NPC dạng "Phiên giao dịch": khách bước vào tiệm (Session Start) → ngạc nhiên trước vật phẩm → mua hàng / bị vả mặt → bước ra (Session End). NPC KHÔNG cần xuất hiện lại — engine giải phóng bộ nhớ. MỖI khách = 1 mini-arc 2-5 chương theo Hooked-Before-Buff cadence.',
    '  • Anti-pattern: KHÔNG để MC chủ động đi tìm cốt truyện ngoài Lãnh địa (mất engine). KHÔNG cho phép Lãnh địa scale chậm hơn 100 chương / cấp. KHÔNG customer instant-recognize, KHÔNG item Tier B làm flagship, KHÔNG MC ra ngoài solo enemy.',
    '  • Top examples: 《我有一座万界商店》, 《我开个店养老》, 《最强商城系统》.',
  ],

  'sang-the': [
    'SÁNG THẾ LƯU / SANDBOX CREATOR PATTERNS:',
    '  • Cơ chế: MC ở Trái Đất nhận được "Sa bàn" (bể cá / đa chiều trong vỏ hạt / trò chơi mô phỏng máy tính). Trong Sa bàn, MC là Đấng Tạo Hóa tuyệt đối + tua nhanh thời gian (1 ngày Trái Đất = 1 vạn năm trong Sa bàn).',
    '  • Cơ chế Thu hoạch: sinh vật trong Sa bàn tiến hóa → sáng tạo công pháp / phép thuật / công nghệ → MC trích xuất (copy) thành tựu để cường hóa bản thân ở Trái Đất.',
    '  • Cấu trúc 4 Kỷ nguyên (mỗi 50-100 chương): (1) Khởi nguyên Tế bào (đơn bào → đa bào → quái vật nguyên thủy); (2) Kỷ nguyên Thần thoại (sinh mệnh trí tuệ + công pháp + sử thi); (3) Xung đột + Reset (đại hồng thủy / thiên thạch quét sạch 99% sinh mệnh, mở Kỷ nguyên mới với hệ thống sức mạnh khác); (4) Đa Sa bàn + Xâm Lăng Hiện Thực.',
    '  • Văn phong "Biên Niên Sử": KHÔNG tả cảnh hai tên lính đánh nhau; tả "Năm Thánh Lịch thứ 1200, Vua Arthur dẫn kỵ binh rồng san phẳng phương Bắc, máu chảy thành sông". Sử thi, hùng tráng, macro-scale.',
    '  • Hàng duy đả kích (Dimensional Strike): Đại Đế tu 10 vạn năm trong Sa bàn 1 kiếm chẻ tinh hà → trong mắt MC chỉ to bằng con kiến. MC dùng ngón tay ấn xuống = hủy diệt cả kỷ nguyên. Tương phản kích thước = engine sảng văn.',
    '  • Quản trị Biến số (Variable Injection): MC bơm biến số vào Sa bàn (bệnh dịch / sách toán học hiện đại / chiếc điện thoại / cọng tóc) → AI nội suy ra sự sụp đổ hoặc thăng hoa văn minh. Mỗi biến số = 1 mini-arc tiến hóa văn minh.',
    '  • Engine Reset Memory: cứ sau 20-50 chương, MC tua nhanh 1 vạn năm — toàn bộ NPC kỷ nguyên cũ già chết. Engine clear context + nạp Prompt "Kỷ nguyên mới bắt đầu" → AI tự do sáng tạo lứa nhân vật mới mà không sợ hổng logic.',
    '  • ANTAGONIST DESIGN (cosmic scale):',
    '    (a) COSMIC RIVAL SÁNG THẾ: 1-2 Sáng Thế Chủ khác (operate Sa bàn riêng) → cạnh tranh civilization vs civilization, war by proxy → MC orchestrate, KHÔNG combat personally.',
    '    (b) IN-WORLD CRISIS: 1 Kỷ nguyên trong Sa bàn của MC sinh ra "anh hùng / phản đồ" thoát kiểm soát — MC quyết định: nudge subtly hay reset epoch.',
    '    (c) INVASION HIỆN THỰC: Kỷ nguyên 4 — sinh vật trong Sa bàn break out vào hiện thực → MC vừa preserve Sa bàn vừa defense Earth.',
    '    (d) HỆ THỐNG / TỔ CHỨC EARTH: tổ chức bí mật Earth phát hiện MC có Sa bàn → muốn militarize / steal → MC dùng power Sa bàn defense.',
    '    Phản diện CẤM: (i) "ta cũng có Sa bàn ngươi đến PvP" instant rival mà không scaffold; (ii) MC personally combat đại đế in-world (phá observer/creator role); (iii) NPC trong Sa bàn breaks 4th wall đập MC trực tiếp.',
  ],

  'hac-am-luu': [
    'HẮC ÁM LƯU / VILLAIN PROTAGONIST PATTERNS:',
    '  • MC định vị bản thân ở ĐỈNH chuỗi thức ăn. KHÔNG tình bạn đơn thuần — chỉ quan hệ lợi ích + trao đổi đồng giá. Trí tuệ + mưu mô luôn đi trước sức mạnh cơ bắp.',
    '  • Bàn tay vàng: "Hệ thống Cướp đoạt Khí Vận" hoặc "Hệ thống Bồi dưỡng Trùm Phản Diện". MC nhìn thấu các "Khí vận chi tử" (nhân vật được định mệnh sắp đặt làm anh hùng) + thấy điểm yếu của chúng.',
    '  • Triết lý "Trảm Thảo Trừ Căn": MC tuyệt đối không để lại hậu họa. KHÔNG cứu nhân độ thế bừa bãi. KHÔNG tha thứ kẻ đã gây hại.',
    '  • Khí vận chi tử (con mồi) phải được module hóa: Mẫu 1 (thiếu niên phế vật bị từ hôn nhặt được nhẫn lão gia gia) → MC chặn đường cướp nhẫn ngày đầu. Mẫu 2 (binh vương đô thị về làm vệ sĩ nữ tổng tài) → MC dùng tài chính + pháp lý nghiền nát thay vì đấu võ. Mẫu 3 (chuyển sinh giả) → MC dùng tư duy ép kẻ này khai bí mật tương lai rồi thủ tiêu.',
    '  • Hành động bằng tổ chức, không phải cá nhân: MC ngồi ghế sau xe đen, ra lệnh sát thủ / hacker dưới quyền xử lý. Sử dụng chiến tranh kinh tế / cắt chuỗi cung ứng / thao túng truyền thông để nội bộ kẻ thù tự tàn sát.',
    '  • Phong cách Minimalism: KHÔNG tả cảnh đánh nhau dông dài. Chuộng "Một kích tất sát" (One-hit kill) hoặc thủ tiêu trong im lặng. Cấu trúc văn bản gọn gàng, tối ưu token.',
    '  • Personality Lock cứng: MC tuyệt đối không "thánh mẫu hóa". Dù đối phương khóc lóc / quỳ gối / tự tử, phản ứng MC luôn là thờ ơ + dùng logic lợi ích để từ chối. Critic phát hiện vi phạm → REWRITE.',
    '  • Thiết kế Đế Chế: MC vận hành tổ chức kỷ luật cao (Yakuza / lính đánh thuê tư nhân / mafia syndicate). Cấp bậc rõ ràng. Quản trị tài nguyên tuyến tính: dòng tiền + nhân sự + cấp vũ khí + lãnh thổ kiểm soát.',
  ],

  'kim-bang-bo-quang': [
    'THIÊN ĐẠO KIM BẢNG / BỘC QUANG LƯU (Heavenly Dao Leaderboard / Exposure) PATTERNS:',
    '  • Cơ chế: MC đã cày "Cẩu Đạo" trong bóng tối đến mức vô địch vũ trụ, nhưng tuyệt đối không khoe. "Thiên Đạo" đột ngột giáng "Kim Bảng" (Bảng Xếp Hạng vàng) lên bầu trời cho toàn thế giới chiêm ngưỡng → bộc lộ thân phận MC ngoài ý muốn.',
    '  • Cấu trúc Listicle JSON: mỗi Bảng (Bảng Vũ Khí / Bảng Thú Cưỡi / Bảng Sát Thủ / Bảng Thế Lực Ngầm) là 1 mảng 10 mục. Top 100-11 = lão quái vật / hoàng đế / tông sư nổi tiếng. Top 10-1 = vô danh + toàn của MC.',
    '  • Vòng lặp tĩnh 3 bước (mỗi 5-15 chương): (1) Thiên Đạo Update Bảng Mới; (2) Thế Giới Reaction (chấn động ở Hoàng Cung / cảm thán ở Tửu lâu / tức giận của các môn phái); (3) Main Than Vãn ("Hệ thống rác rưởi lại bộc quang thẻ tẩy của ta"). Engine giải trí cao + chi phí compute thấp.',
    '  • Reaction Engine = 80% dung lượng truyện: cứ mỗi vị trí Top được công bố, sinh ra góc nhìn của 5-10 NPC (Kiếm Tôn sụp đổ đạo tâm, Thiếu nữ ngưỡng mộ, Thái tử ghen tị, Lão sư phụ thán phục). Tận dụng AI sinh content đa dạng nhân vật từ pre-trained knowledge.',
    '  • Cấu trúc 4 giai đoạn: (1) Bảng đầu tiên + bắt đầu nghi ngờ (1-50, manh mối nhỏ dẫn đến khu MC); (2) Bảng liên hoàn + bão táp (50-150, thiên tài liên minh tìm MC); (3) Bị ép xuất thủ (150-300, đại quân bao vây → MC phẩy tay = bốc hơi); (4) Kim Bảng Đa Vũ Trụ (300+).',
    '  • Anti-pattern: MC TUYỆT ĐỐI không chủ động khoe khoang. Bộc quang luôn là do Thiên Đạo / hệ thống / kẻ ngoài → MC chỉ phàn nàn thụ động. Đây là Personality Lock — Critic enforce.',
  ],
};
