/**
 * Rewrite 10 most recent novels with new full-evidence pipeline (Phase 22).
 *
 * Steps:
 * 1. Identify 10 newest active/paused novels
 * 2. Set status='paused' to halt cron
 * 3. Wipe all chapter content + memory tables
 * 4. Reset current_chapter=0
 * 5. Re-set status='active' so cron picks them up and writes from ch.1 (cron will
 *    auto-generate arc plans on first chapter)
 *
 * Outline regeneration: skipped — keeps existing master_outline + story_outline (already
 * regenerated by Phase 19D / Phase 20A spawn for these novels). Pipeline reads outlines
 * during writing.
 *
 * Usage: ./node_modules/.bin/tsx scripts/rewrite-recent-10.ts [--dry-run] [--limit=N]
 */

import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';

try {
  const envText = readFileSync('.env.local', 'utf-8');
  for (const line of envText.split('\n')) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/);
    if (m && !process.env[m[1]]) {
      let val = m[2].trim();
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1);
      }
      process.env[m[1]] = val;
    }
  }
} catch { /* ignore */ }

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE env vars');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, { auth: { persistSession: false } });

const args = process.argv.slice(2);
const DRY_RUN = args.includes('--dry-run');
const LIMIT = (() => {
  const arg = args.find(a => a.startsWith('--limit='));
  return arg ? parseInt(arg.split('=')[1], 10) : 10;
})();

const MEMORY_TABLES = [
  'chapter_summaries',
  'story_synopsis',
  'arc_plans',
  'character_states',
  'story_memory_chunks',
  'plot_threads',
  'world_rules_index',
  'beat_usage',
  'volume_summaries',
  'foreshadowing_plans',
  'character_arcs',
  'character_signature_traits',
  'pacing_blueprints',
  'voice_fingerprints',
  'mc_power_states',
  'world_locations',
  'location_bibles',
  'character_knowledge',
  'character_relationships',
  'character_bibles',
  'location_timeline',
  'quality_metrics',
  'project_daily_quotas',  // 2026-04-30 fix: cron skips novels with completed quotas
];

(async () => {
  console.log(`📚 Rewrite ${LIMIT} most recent novels (DRY_RUN=${DRY_RUN})\n`);

  // 1. Identify targets
  const { data: targets, error: selErr } = await supabase
    .from('ai_story_projects')
    .select('id,novel_id,genre,status,total_planned_chapters,current_chapter,created_at,novels!ai_story_projects_novel_id_fkey(title)')
    .in('status', ['active', 'paused'])
    .order('created_at', { ascending: false })
    .limit(LIMIT);

  if (selErr) { console.error('Select failed:', selErr.message); process.exit(1); }
  if (!targets || targets.length === 0) { console.error('No targets'); process.exit(1); }

  console.log('Targets:');
  for (let i = 0; i < targets.length; i++) {
    const p = targets[i] as unknown as { id: string; novel_id: string; genre: string; status: string; current_chapter: number; total_planned_chapters: number; novels: { title: string } | null };
    console.log(`  ${i + 1}. ${p.novels?.title?.slice(0, 50) || '?'} [${p.genre}] (${p.current_chapter}/${p.total_planned_chapters}) — id=${p.id}`);
  }
  console.log();

  if (DRY_RUN) {
    console.log('🛑 DRY_RUN — exiting without modifications.');
    process.exit(0);
  }

  const projectIds = targets.map((t: { id: string }) => t.id);
  const novelIds = targets.map((t: { novel_id: string }) => t.novel_id);

  // 2. Set status='paused' to halt cron
  console.log('⏸  Pausing cron...');
  const { error: pauseErr } = await supabase
    .from('ai_story_projects')
    .update({ status: 'paused' })
    .in('id', projectIds);
  if (pauseErr) { console.error('Pause failed:', pauseErr.message); process.exit(1); }
  console.log('   ✓ All paused.\n');

  // 3. Wipe memory tables
  console.log('🗑  Wiping memory tables...');
  for (const tbl of MEMORY_TABLES) {
    const { error, count } = await supabase
      .from(tbl)
      .delete({ count: 'exact' })
      .in('project_id', projectIds);
    if (error) console.warn(`   ✗ ${tbl}:`, error.message);
    else console.log(`   ✓ ${tbl}: ${count ?? 0} rows`);
  }
  console.log();

  // 4. Wipe chapters
  console.log('🗑  Wiping chapters...');
  const { error: chErr, count: chCount } = await supabase
    .from('chapters')
    .delete({ count: 'exact' })
    .in('novel_id', novelIds);
  if (chErr) console.warn('   ✗', chErr.message);
  else console.log(`   ✓ chapters: ${chCount ?? 0} rows\n`);

  // 5. Reset state: wipe outlines, set total=1000, current=0. KEEP status='paused' until
  //    outlines regenerated (else cron picks up and writes with null outlines = degraded).
  console.log('🔄 Resetting state (total=1000, wipe outlines, current=0, still paused)...');
  const { error: resetErr } = await supabase
    .from('ai_story_projects')
    .update({
      total_planned_chapters: 1000,
      master_outline: null,
      story_outline: null,
      story_bible: null,
      current_chapter: 0,
      updated_at: new Date().toISOString(),
    })
    .in('id', projectIds);
  if (resetErr) { console.error('Reset failed:', resetErr.message); process.exit(1); }
  console.log('   ✓ State reset. Outlines NULL, total=1000.\n');

  // 6. Regenerate master_outline + story_outline at 1000-chapter target via existing script
  console.log('📝 Regenerating master_outline + story_outline at 1000 chương...');
  const { execSync } = require('child_process');
  process.env.TARGET_PROJECTS = projectIds.join(',');
  try {
    execSync(
      `${process.cwd()}/node_modules/.bin/tsx scripts/generate-outlines-for-novels.ts`,
      { stdio: 'inherit', env: process.env },
    );
    console.log('   ✓ Outlines regenerated.\n');
  } catch (e) {
    console.error('Outline regen failed:', e instanceof Error ? e.message : String(e));
    console.error('Novels remain paused. Inspect logs and rerun outline gen manually.');
    process.exit(1);
  }

  // 7. Activate (only after outlines confirmed)
  console.log('🚀 Activating projects...');
  const { error: activateErr } = await supabase
    .from('ai_story_projects')
    .update({ status: 'active', updated_at: new Date().toISOString() })
    .in('id', projectIds);
  if (activateErr) { console.error('Activate failed:', activateErr.message); process.exit(1); }
  console.log('   ✓ All active.\n');

  // 6. Verification queries
  console.log('🔍 Verifying...');
  const { data: verifyChapters } = await supabase
    .from('chapters')
    .select('novel_id', { count: 'exact', head: true })
    .in('novel_id', novelIds);
  const { count: chapterCount } = (verifyChapters as unknown as { count: number }) || { count: 0 };

  const { data: verifyState } = await supabase
    .from('ai_story_projects')
    .select('id,status,current_chapter,total_planned_chapters,master_outline,story_outline')
    .in('id', projectIds);

  const allActive = verifyState?.every(s => s.status === 'active' && s.current_chapter === 0);
  const allTarget1000 = verifyState?.every(s => s.total_planned_chapters === 1000);
  const allOutlinesNull = verifyState?.every(s => !s.master_outline && !s.story_outline);

  console.log(`   chapters remaining: ${chapterCount ?? '?'}`);
  console.log(`   all active + ch=0: ${allActive ? '✓' : '✗'}`);
  console.log(`   all total=1000: ${allTarget1000 ? '✓' : '✗'}`);
  console.log(`   all outlines wiped (will regen): ${allOutlinesNull ? '✓' : '✗'}`);

  console.log('\n✅ Done. Cron will pick up and start writing from ch.1 within 5 minutes.');
  console.log('   First write triggers master_outline + story_outline regen (DeepSeek Pro tier).');
  console.log('   Monitor: SELECT id, current_chapter, master_outline IS NOT NULL AS has_outline FROM ai_story_projects WHERE id IN (...);');
})();
