import { FlagshipCatalogueV1Schema, type FlagshipStoryPackageV1 } from './catalogue';

type PackageInput = Omit<FlagshipStoryPackageV1, 'schemaVersion' | 'coverArt' | 'status' | 'storySpecStatus' | 'writerIsolation'> & {
  artScene: string;
  artStyle: string;
  artComposition: string;
  artMood: string;
  artPalette: string;
};

function storyPackage(input: PackageInput): FlagshipStoryPackageV1 {
  const { artScene, artStyle, artComposition, artMood, artPalette, ...story } = input;
  return {
    schemaVersion: 1,
    ...story,
    coverArt: {
      assetPath: `/covers/flagship-first-30/${input.slotId.toLowerCase()}.webp`,
      sourceAssetPath: `/covers/flagship-first-30/source/${input.slotId.toLowerCase()}.webp`,
      alt: `Bìa truyện ${input.title}: ${input.tagline}`,
      imagePrompt: `Use case: illustration-story
Asset type: art-only background for a 3:4 Vietnamese serialized-fiction cover
Primary request: ${artScene}
Story-specific medium: ${artStyle}
Shared art direction: restrained editorial book illustration, matte painted surfaces, deliberate large color shapes, subtle natural paper texture, human proportions, tactile real-world materials, confident selective detail. It should feel commissioned by an experienced human illustrator, not like generic AI fantasy art.
Composition/framing: ${artComposition}; strict 3:4 portrait composition; one clear focal subject and one story-defining object or environment; asymmetrical visual hierarchy; keep the top 30 percent calm and low-detail for later typography; keep critical faces and objects inside the central 70 percent so a mechanical 3:4 crop is safe.
Lighting/mood: ${artMood}
Color palette: ${artPalette}
Text: no text, no letters, no typography, no watermark; typography will be added later by the cover renderer.
Hard exclusions: no sparkles, no glowing dust, no floating particles, no bokeh, no lens flare, no volumetric light shafts, no neon rim light, no magical UI panels, no collage or character montage, no glossy 3D-render finish, no plastic skin, no exaggerated anime face, no decorative clutter, no shower of embers, no random symbols.
Originality: original characters and world only; do not imitate an existing book cover or living artist.`,
      renderSpec: {
        width: 1086,
        height: 1448,
        title: input.title,
        watermark: 'truyencity.com',
      },
    },
    status: 'concept_package_ready',
    storySpecStatus: 'not_materialized',
    writerIsolation: true,
  };
}

const packages: FlagshipStoryPackageV1[] = [
  storyPackage({
    slotId: 'HX-01',
    title: 'Đi Kiểm Định Dị Tượng, Tôi Phát Hiện Thành Phố Này Có Luật Giết Người',
    tagline: 'Mỗi dị tượng đều có quy luật; cái giá nằm ở việc ai dám kiểm chứng trước.',
    logline: 'Một nhân viên kiểm định hiện trường phát hiện những tai nạn vô lý trong thành phố đều để lại cùng một loại vật chứng, nhưng mỗi lần anh chứng minh được một quy tắc, thành phố lại sinh ra ngoại lệ nguy hiểm hơn.',
    catalogueDescription: 'Huyền huyễn điều tra thiên về trí mưu và khoái cảm giải mã. Main không biết sẵn đáp án, phải quan sát, thử sai và dùng vật chứng để giành quyền diễn giải từ một cơ quan vốn sống nhờ giữ bí mật. Mỗi thắng lợi đem lại uy tín lẫn một cách mới để thế giới phản công.',
    protagonistSeed: 'Lâm Khải, nhân viên kiểm định bị xem là quá cẩn thận, giỏi thấy sai lệch nhỏ nhưng sợ đưa người khác vào thí nghiệm nguy hiểm.',
    settingSeed: 'Thành phố Vọng Hải hư cấu, nơi dị tượng được quản lý như sự cố công cộng và mỗi khu phố có lịch sử quy tắc khác nhau.',
    openingHook: 'Trong một toa tàu ngừng giữa đường hầm, Khải nhận ra hành khách biến mất không theo vị trí mà theo thứ tự họ nói dối, buộc anh tự nói ra bí mật đầu tiên để cứu người.',
    serialPromise: 'Mỗi vụ việc mở một quy tắc, một thiết chế hưởng lợi và một thay đổi đời sống; hiểu biết cũ liên tục mất giá khi các quy tắc chồng lên nhau.',
    visualFingerprint: 'red-thread-evidence-map-inside-flooded-metro',
    artScene: 'A sharp-eyed Vietnamese male investigator in a rain-dark underground train, holding a small evidence bag while red rule-lines appear across fogged windows and missing passenger silhouettes dissolve into reflections',
    artStyle: 'cinematic dark fantasy illustration with grounded urban textures and precise mystery details',
    artComposition: 'investigator in the lower center, converging train lines and luminous evidence marks framing his face',
    artMood: 'cold emergency lighting, controlled dread, intelligent rather than grotesque',
    artPalette: 'charcoal black, wet steel blue, restrained crimson evidence glow',
  }),
  storyPackage({
    slotId: 'HX-02',
    title: 'Võ Sư Hạng Bét Trực Đêm: Nhìn Sai Số, Cứu Cả Khu Phố',
    tagline: 'Giấy phép cho anh quyền ra tay; mỗi cú đấm buộc anh chịu trách nhiệm lâu hơn.',
    logline: 'Một võ sư hạng thấp làm đội bảo hộ đêm dùng khả năng đọc sai số vận động để cứu các khu phố, từ đó từng bước giành chứng chỉ, quyền điều động và niềm tin của đội ngũ.',
    catalogueDescription: 'Cao võ đô thị nhưng sức mạnh nằm trong nghề nghiệp, giấy phép và phối hợp. Công cụ của main chỉ đo phản hồi luyện tập, không tặng kỹ năng. Anh thắng sớm nhờ chuẩn bị đúng, rồi phải gánh hậu quả công khai của từng quyết định bảo hộ.',
    protagonistSeed: 'Phan Duy, võ sư từng bỏ dở kỳ thi cấp phép, ít nói, đọc trận tốt nhưng có thói quen tự nhận mọi rủi ro.',
    settingSeed: 'Thành phố Lam Cảng, nơi khu dân cư thuê các đội võ sư được cấp phép để xử lý sinh vật năng lượng và sự cố công nghiệp.',
    openingHook: 'Trong ca trực bị coi là việc vặt, Duy phát hiện nhịp rung cầu vượt lệch với báo cáo và tự đổi đội hình trước khi một đoàn xe buýt lao vào vùng sụp.',
    serialPromise: 'Mỗi nhiệm vụ đổi loại địa hình, quyền hạn và đồng đội; tiến bộ thể lực luôn đi cùng trách nhiệm pháp lý và xã hội nhìn thấy được.',
    visualFingerprint: 'night-shift-martial-guardian-under-neon-viaduct',
    artScene: 'A Vietnamese urban martial guardian in practical licensed protective gear beneath a cracked neon viaduct, bracing one hand against vibrating concrete while a night bus and teammates wait behind him',
    artStyle: 'modern martial-arts concept art with believable municipal rescue design',
    artComposition: 'low-angle full figure, diagonal bridge fracture, team silhouettes establishing responsibility rather than lone hero worship',
    artMood: 'urgent but capable, rain-lit night shift energy',
    artPalette: 'deep navy, sodium orange, electric cyan safety markers',
  }),
  storyPackage({
    slotId: 'HX-03',
    title: 'Xuyên Đến Vùng Biên Nuôi Linh Thú, Tôi Dựng Lại Gia Nghiệp',
    tagline: 'Nuôi được một sinh vật mạnh không khó bằng khiến cả đàn tin mình.',
    logline: 'Một kỹ thuật viên chăn nuôi xuyên tới vùng biên có linh thú, dùng quan sát tập tính và chăm sóc dài hạn để cứu trại thú của gia đình khỏi bệnh, nợ và tranh chấp đất.',
    catalogueDescription: 'Ngự thú theo hướng gia đình và tài sản sống. Kiến thức sinh học chỉ giúp main đặt giả thuyết; mỗi giống loài có phản ứng riêng, cần thời gian và nguồn thức ăn thật. Payoff đến từ đàn thú khỏe lên, mái nhà ổn hơn và cộng đồng học cách cùng bảo vệ nguồn sống.',
    protagonistSeed: 'Trần Túc, kỹ thuật viên kiên nhẫn nhưng quen coi dữ liệu đáng tin hơn cảm xúc, phải học cách xin sự hợp tác của cả người lẫn thú.',
    settingSeed: 'Thung lũng Bạch Sam hư cấu với các trang trại nhỏ, đồng cỏ cộng đồng và những loài linh thú gắn với mùa.',
    openingHook: 'Túc tỉnh dậy đúng ngày con thú giống cuối cùng bỏ ăn; thay vì dùng thuốc quý, anh tháo chuồng và đi theo dấu chân nó tới nguồn nước đã bị đổi dòng.',
    serialPromise: 'Các vòng nuôi dưỡng đổi từ bệnh, sinh sản, cộng sinh tới đất đai; mỗi tiến bộ của đàn thú tạo nghĩa vụ mới với gia đình và làng xóm.',
    visualFingerprint: 'warm-backyard-beast-ranch-with-biological-notes',
    artScene: 'A young Vietnamese male beast caretaker kneeling in a rustic backyard ranch, gently touching the forehead of a luminous antlered calf while several distinct spirit animals watch from handmade enclosures and family lights glow behind',
    artStyle: 'warm painterly fantasy with tactile rural detail and expressive animals',
    artComposition: 'intimate foreground bond, layered ranch depth, home visible as the emotional anchor',
    artMood: 'hopeful, nurturing, quietly magical',
    artPalette: 'moss green, warm amber, soft turquoise bioluminescence',
  }),
  storyPackage({
    slotId: 'HX-04',
    title: 'Bảo Tôi Xây Thành Trên Tro Trắng, Tôi Lại Bắt Đầu Bằng Lịch Thay Đá',
    tagline: 'Muốn thành không chết khát, trước hết phải biết viên đá nào sẽ mục vào ngày nào.',
    logline: 'Ở thung lũng Tro Trắng, Khang phát hiện rễ rêu làm đá dẫn nước mục sau ba tháng và biến lịch thay đá, phân loại vật liệu cùng bảo trì thành nền móng của một thành phố.',
    catalogueDescription: 'Huyền huyễn xây dựng văn minh bắt đầu từ một vòng đời vật liệu cụ thể. Đá giữ nước, rêu tạo lương thực nhưng đồng thời ăn mòn đá; mỗi thay đổi lịch bảo trì làm dịch chuyển khẩu phần nước, sinh kế thợ rêu và quyền lực của xưởng nung.',
    protagonistSeed: 'Khang, thợ bảo trì lạnh lùng có thể đo độ mủn của đá bằng xúc giác, giỏi hệ thống nhưng thường xem nhẹ lòng tự ái và lợi ích ngắn hạn của người khác.',
    settingSeed: 'Thung lũng Tro Trắng sống nhờ mạng kênh lót đá mang dấu tay, ruộng rêu và khẩu phần nước; một viên đá mục sai ngày có thể kéo cả tuyến kênh sụp xuống tro.',
    openingHook: 'Khang chặn dòng trái lệnh để cứu tuyến kênh số bốn, rồi nhận ra muốn không bị cắt nước lần nữa anh phải đánh dấu tuổi thọ từng viên đá và ép cả thung lũng theo lịch mới.',
    serialPromise: 'Từ một tuyến kênh tới cả mạng cấp nước, mỗi lần mở rộng làm bài toán thay đá, rêu, nhân lực và quyền phân phối phức tạp hơn; thành lớn lên bằng hệ thống có nguồn và cái giá nhìn thấy được.',
    visualFingerprint: 'white-ash-city-rising-around-water-channel',
    artScene: 'A determined Vietnamese male organizer standing above a white volcanic ash valley where refugees build a curved water channel, kilns and first homes, with a nascent city glowing through drifting ash',
    artStyle: 'epic civilization-building fantasy illustration grounded in labor and engineering',
    artComposition: 'wide vertical vista, protagonist small but central, water channel leading the eye toward the growing settlement',
    artMood: 'constructive, windswept, earned hope after disaster',
    artPalette: 'chalk white, volcanic gray, copper fire, clear water blue',
  }),
  storyPackage({
    slotId: 'HX-05',
    title: 'Trọng Sinh Về Xưởng Luyện Khí, Tôi Dùng Phế Liệu Dựng Cơ Nghiệp',
    tagline: 'Nhớ được nguyên lý không có nghĩa là làm đúng ngay lần đầu.',
    logline: 'Trọng sinh về lúc còn là thợ phụ, một luyện khí sư dùng ký ức về sai lầm cũ để biến phế liệu thành công cụ hữu ích, nhưng phải tự dựng lại công thức, uy tín và mạng cung ứng.',
    catalogueDescription: 'Khoái cảm chế tạo đi cùng kinh tế tài nguyên. Mỗi món đồ bắt đầu từ nhu cầu thật, vật liệu có sai số và phép thử có thể hỏng. Main không nhặt báu vật liên tục; anh xây tay nghề, dụng cụ xưởng và quan hệ với thợ lẫn khách hàng.',
    protagonistSeed: 'Vũ Kha, thợ phụ trọng sinh mang mặc cảm về một tai nạn xưởng cũ, giỏi nguyên lý nhưng thiếu kiên nhẫn với người học chậm.',
    settingSeed: 'Khu thợ Bảy Lò của đô thành huyền huyễn, nơi nguyên liệu qua nhiều tầng độc quyền và sản phẩm phải chịu kiểm định công khai.',
    openingHook: 'Ngày đầu trở lại, Kha mua một thùng phế liệu không phải vì có bảo vật mà vì nhận ra ba loại hợp kim hỏng có thể ghép thành dụng cụ cứu ca làm đêm.',
    serialPromise: 'Mỗi vòng chế tạo đổi nhu cầu, vật liệu và khách hàng; lợi thế ký ức giảm dần khi tiêu chuẩn tăng và người khác học theo.',
    visualFingerprint: 'alley-forge-scrap-metal-transforming-into-tool',
    artScene: 'A young Vietnamese male artificer in a cramped alley forge, arranging discarded enchanted metal fragments into a precise new tool while imperfect sparks reveal hidden material layers and skeptical workers watch',
    artStyle: 'high-detail craft fantasy with practical workshop realism',
    artComposition: 'three-quarter workbench view, hands and materials prominent, narrow alley rising behind like a vertical furnace canyon',
    artMood: 'inventive, industrious, satisfying rather than bombastic',
    artPalette: 'burnished brass, soot black, ember orange, jade-green material glow',
  }),
  storyPackage({
    slotId: 'HX-06',
    title: 'Tận Thế Mất Điện: Khôi Phục Máy Bơm, Dựng Lại Từng Khu Phố',
    tagline: 'Sống sót không chỉ là giết quái; đó là làm cho đèn sáng lại vào tối mai.',
    logline: 'Sau một biến cố năng lượng, một kỹ thuật viên bảo trì dùng năng lực hấp thụ duy nhất một dạng phóng xạ để dựng nơi trú ẩn, khôi phục hạ tầng và kết nối các cộng đồng có chiến lược sinh tồn khác nhau.',
    catalogueDescription: 'Mạt thế khoái hoạt theo hướng chủ động xây lại đời sống. Main có lợi thế sớm nhưng phải đo năng lượng, tiêu hao vật tư và dựa vào đội ngũ. Thành quả là ánh sáng, nước sạch, khu ở và người có thể quay lại làm việc.',
    protagonistSeed: 'Ngô Phúc, kỹ thuật viên điện lực hay pha trò khi căng thẳng, biết sửa máy nhưng không quen lãnh đạo người khác.',
    settingSeed: 'Thành phố đa tầng sau cơn bão năng lượng, mỗi quận còn một loại hạ tầng và cộng đồng bảo vệ nguồn lực riêng.',
    openingHook: 'Đêm đầu mất điện, Phúc bỏ qua kho lương gần nhất để khởi động máy bơm tầng hầm trước khi nước nhiễm độc tràn vào khu trú ẩn.',
    serialPromise: 'Mỗi vùng an toàn mới mở một chuỗi cung ứng, cộng đồng và bí mật môi trường; tiến bộ luôn hiện qua hạ tầng có thể sử dụng.',
    visualFingerprint: 'blackout-city-first-lamp-relit-by-maintenance-worker',
    artScene: 'A Vietnamese male maintenance engineer standing on a dark apartment rooftop as he relights the first amber utility lamp, cables and improvised batteries connecting to small pockets of survivors across a powerless futuristic city',
    artStyle: 'hopeful post-apocalyptic science-fantasy concept art with believable infrastructure',
    artComposition: 'vertical skyline swallowed by darkness, one lamp and the engineer forming the bright focal point',
    artMood: 'resilient, communal, tense but not despairing',
    artPalette: 'midnight blue, concrete gray, warm amber, faint radioactive violet',
  }),
  storyPackage({
    slotId: 'HX-07',
    title: 'Bảo Tôi Làm Phản Diện, Tôi Bán Gia Sản Tự Mua Đường Sống',
    tagline: 'Kịch bản cho hắn một cái chết; hắn trả giá để mua từng ngày tự do.',
    logline: 'Biết mình chỉ là phản diện sẽ chết ở hồi đầu, một thiếu chủ không đi cướp cơ duyên của nhân vật chính mà bán tài sản phe cũ, lập giao ước mới và chịu butterfly effect để giành quyền tự quyết.',
    catalogueDescription: 'Phá mệnh theo hướng giao dịch và kiến thiết phe mới. Main chỉ nhớ các điểm chết lớn; sau lựa chọn đầu tiên, kịch bản mất độ tin cậy. Đối thủ không ngu và nhân vật nguyên tác có mục tiêu độc lập.',
    protagonistSeed: 'Tạ Minh, thiếu chủ mang tiếng tàn nhẫn vì luôn làm đúng vai gia tộc giao, nay lần đầu phải tự chọn điều mình muốn bảo vệ.',
    settingSeed: 'Thế giới huyền huyễn nơi các đại tộc ký giao ước bằng tài nguyên và lời thề có hiệu lực vật chất.',
    openingHook: 'Thay vì dự tiệc nơi mình sẽ đắc tội thiên mệnh chi tử, Minh đem bán chiếc ấn thiếu chủ và dùng tiền chuộc những người sẽ chết cùng mình.',
    serialPromise: 'Mỗi mốc thoát kịch bản làm thông tin cũ mất giá, buộc main xây tài sản, quan hệ và uy tín không dựa vào vai phản diện.',
    visualFingerprint: 'villain-breaking-seal-and-buying-freedom-contracts',
    artScene: 'An elegant Vietnamese-inspired fantasy young lord breaking a black clan seal over a table of glowing contracts and redeemed debt tokens, while the grand banquet meant to doom him burns out of focus behind',
    artStyle: 'stylized eastern fantasy drama with sharp contractual symbolism and restrained luxury',
    artComposition: 'hands breaking the seal in foreground, calm face above, doomed scripted path receding behind',
    artMood: 'defiant, clever, liberating rather than vengeful',
    artPalette: 'ink black, ivory, muted gold, decisive vermilion',
  }),
  storyPackage({
    slotId: 'TH-01',
    title: 'Trọng Sinh Về Gia Tộc Tu Tiên, Tôi Gieo Tiếng Vọng Cho Mười Năm Sau',
    tagline: 'Một câu nói hôm nay có thể hóa thành tài nguyên hoặc tai kiếp khi nó dội lại.',
    logline: 'Lâm Viễn trọng sinh về ngày gia tộc bán linh điền Vọng Âm, nơi mọi lời nói và cảm xúc sẽ kết tinh thành hậu quả vật lý sau một, mười hoặc trăm năm.',
    catalogueDescription: 'Tiên hiệp gia tộc phi cổ điển với tài nguyên có độ trễ. Main biết các chu kỳ tiếng vọng nhưng không thể nhớ chính xác mọi biến số; muốn cứu người nhà, anh phải quản lời nói, Âm Thạch, nước ngầm và cả những cảm xúc không chịu nằm yên trong im lặng.',
    protagonistSeed: 'Lâm Viễn, người sống sót từ kiếp trước, quyết liệt và sẵn sàng tự trả giá trước nhưng lầm tưởng kiểm soát tuyệt đối có thể dập tắt mọi oán hận trong gia tộc.',
    settingSeed: 'Lâm thị trấn giữ thung lũng Vọng Âm, nơi linh điền ghi nhớ âm thanh, người chết để lại tiếng vọng và từng nhánh họ phải gánh hậu quả do tổ tiên gieo xuống.',
    openingHook: 'Viễn xé khế ước bán đất và dựng trận cách âm ngay trước tiếng vọng mười năm dội về, nhưng mệnh lệnh cấm khẩu cứu gia tộc cũng lập tức biến anh thành kẻ độc đoán.',
    serialPromise: 'Các chu kỳ một năm, mười năm và trăm năm chồng lên nhau; mỗi lời nói, vụ mùa và minh ước hôm nay tạo món nợ hoặc phần thưởng cho một thế hệ khác.',
    visualFingerprint: 'multi-generation-family-tree-beneath-spirit-pine',
    artScene: 'A Vietnamese-inspired cultivation family gathered beneath an ancient green pine whose glowing roots weave through fields, ancestral tablets and the silhouettes of future generations, with a young reborn cultivator holding an unfinished family ledger',
    artStyle: 'elegant multigenerational xianxia illustration with human warmth and landscape depth',
    artComposition: 'towering pine as vertical spine, present family below and faint future figures among branches',
    artMood: 'patient, protective, quietly epic',
    artPalette: 'pine green, weathered earth, moon silver, warm ancestral gold',
  }),
  storyPackage({
    slotId: 'TH-02',
    title: 'Bảo Tôi Dạy Đám Đệ Tử Bị Loại, Họ Lại Dựng Lại Tiên Môn',
    tagline: 'Thu đồ dễ, dạy họ thành người không giống mình mới khó.',
    logline: 'Một tu sĩ giỏi nhìn tiềm năng nhận quản một tiên môn sắp giải tán, dùng cách dạy riêng cho từng học trò để dựng lại xưởng nghề và danh dự môn phái.',
    catalogueDescription: 'Tiên hiệp sư đồ pha vận hành tổ chức. Main không nhìn được thiên mệnh; học trò có ý chí và mục tiêu riêng. Payoff đến từ lúc người học tự vượt nút thắt, còn xung đột nảy sinh khi họ trưởng thành theo hướng thầy không kiểm soát.',
    protagonistSeed: 'Đặng Mặc, tu sĩ từng là thợ sửa pháp khí, không giỏi diễn thuyết nhưng nhìn ra người khác học tốt nhất bằng cách nào.',
    settingSeed: 'Tiên môn Hạ Vân chỉ còn một xưởng hỏng, bảy học trò trái tính và khoản nợ danh dự với các môn phái nghề nghiệp.',
    openingHook: 'Trong ngày tuyển sinh cuối cùng, Mặc loại người có thiên phú cao nhất và nhận ba thí sinh bị chê vì anh phát hiện họ cùng sửa được một lỗi mà trưởng lão không thấy.',
    serialPromise: 'Mỗi học trò mở một nghề, quan hệ và bài toán dạy khác; thành công của họ tăng uy tín môn phái đồng thời tạo quyền tự quyết mới.',
    visualFingerprint: 'workshop-sect-teacher-with-diverse-apprentices',
    artScene: 'A practical Vietnamese-inspired cultivation teacher in a half-ruined mountain workshop, guiding three very different apprentices as they repair a large cracked spiritual mechanism together',
    artStyle: 'bright character-driven xianxia workshop illustration with handcrafted magical machinery',
    artComposition: 'teacher slightly behind the apprentices, repaired mechanism forming a circular frame around the team',
    artMood: 'energetic, warm, humorous and aspirational',
    artPalette: 'sky blue, workshop wood, brass, fresh green spiritual sparks',
  }),
  storyPackage({
    slotId: 'TH-03',
    title: 'Xuyên Đến Tiên Môn, Tôi Biến Tu Tiên Thành Một Môn Khoa Học',
    tagline: 'Linh khí không đọc sách giáo khoa, và thí nghiệm sai vẫn phải có người trả giá.',
    logline: 'Một nghiên cứu viên xuyên tới tiên môn dùng phương pháp giả thuyết và đo lường để tìm hiểu linh khí, nhưng phát hiện quy luật nơi đây phản ứng với người quan sát và lợi ích học thuật.',
    catalogueDescription: 'Tu tiên nghiên cứu, nơi tri thức tạo cả sức mạnh lẫn xung đột thể chế. Main chỉ giỏi đặt câu hỏi; cần thiết bị, vật liệu, cộng sự và quyền công bố. Mỗi phát hiện mở một ứng dụng cùng một nguy cơ đạo đức.',
    protagonistSeed: 'Mai Kính, nghiên cứu viên cứng đầu, quen tin số đo hơn địa vị nhưng phải học rằng dữ liệu linh khí cũng mang dấu vết người đo.',
    settingSeed: 'Học cung Thiên Đo trên đỉnh mây, chia quyền tiếp cận theo trường phái và kiểm soát các vùng linh khí bất ổn.',
    openingHook: 'Trong buổi kiểm tra nhập môn, Kính không giải bài mà chứng minh dụng cụ chuẩn của học cung cho kết quả khác nhau khi đổi người cầm, khiến cả phòng thi phải đóng cửa.',
    serialPromise: 'Ba mươi chương liên tục đổi giả thuyết, sai số và người chịu tác động; tiến bộ hiện qua thiết bị, dữ liệu và quyền học thuật.',
    visualFingerprint: 'cloud-top-laboratory-observation-changing-spirit-light',
    artScene: 'A Vietnamese male researcher in simple cultivation robes inside a cloud-top laboratory, comparing crystal instruments as streams of spiritual light visibly bend differently around each observer',
    artStyle: 'intellectual xianxia science-fantasy illustration with elegant apparatus and atmospheric clouds',
    artComposition: 'central experiment table, curved light paths leading upward into the title area, collaborators in distinct positions',
    artMood: 'curious, revelatory, precise with a hint of danger',
    artPalette: 'cloud white, cobalt ink, translucent violet, fine gold measurement lines',
  }),
  storyPackage({
    slotId: 'TH-04',
    title: 'Tu Tiên Mô Phỏng: Mỗi Kiếp Tôi Chỉ Được Mang Về Một Thứ',
    tagline: 'Sống lại vô số lần, nhưng mỗi lần anh chỉ cứu được một ký ức.',
    logline: 'Một đệ tử được mô phỏng những vòng đời khác nhau trong tiên môn, song mỗi lần thất bại chỉ có thể giữ lại một kỹ năng hoặc mảnh thông tin và mọi can thiệp đều làm lịch sử biến dạng.',
    catalogueDescription: 'Vòng lặp tu tiên không farm vô hạn. Mỗi đời là một chiến lược có mục tiêu và mất mát, còn hiện thực chỉ nhận một kết quả hữu hạn. Càng biết nhiều, main càng phải chọn điều gì đáng mang về.',
    protagonistSeed: 'Chu Tinh, đệ tử sợ quên những người mình từng gặp trong mô phỏng, luôn ghi tên họ dù biết chỉ mình còn nhớ.',
    settingSeed: 'Tiên môn dùng một cổ kính cho đệ tử sống thử các nhánh lịch sử, nhưng chiếc kính lấy ký ức làm phí và không reset hoàn hảo.',
    openingHook: 'Sau vòng đời đầu tiên kéo dài bốn mươi năm, Tinh tỉnh lại ở tuổi mười bảy và bỏ lại tuyệt kỹ mạnh nhất để giữ tên của người sẽ cứu cả môn phái.',
    serialPromise: 'Mỗi vòng đổi mục tiêu, quan hệ và lịch sử; quyết định giữ một thứ luôn đóng vĩnh viễn nhiều con đường khác.',
    visualFingerprint: 'many-lifetimes-in-shattered-mirror-one-memory-kept',
    artScene: 'A young Vietnamese-inspired cultivator reaching through a shattered ancient mirror containing many different lifetimes, choosing one small glowing handwritten name while powerful techniques fade away in other fragments',
    artStyle: 'poetic surreal xianxia illustration with clear emotional storytelling',
    artComposition: 'central hand and memory token, mirror fragments spiraling vertically through alternate lives',
    artMood: 'bittersweet, strategic, intimate despite cosmic scale',
    artPalette: 'midnight indigo, mirror silver, pale memory gold, fading rose',
  }),
  storyPackage({
    slotId: 'TH-05',
    title: 'Y Tu Mở Quán Dưới Tiên Sơn, Chữa Một Người Để Cứu Cả Làng',
    tagline: 'Chữa một người là trả lại cho cả làng một phần sức sống.',
    logline: 'Một y tu có khả năng cảm nhận sinh cơ mở quán ở vùng nghèo, chữa bệnh bằng dược liệu hữu hạn và gây dựng dược điền để cộng đồng tự sống được sau khi anh rời đi.',
    catalogueDescription: 'Tiên hiệp chữa lành nhưng không cứu miễn phí. Chẩn đoán của main có phạm vi hẹp và tiêu hao sức lực; bệnh nhân có quyền từ chối. Mỗi ca chữa trị phục hồi một con người, một nghề và một mắt xích sinh kế.',
    protagonistSeed: 'Hoàng Yên, y tu từng thất bại vì chỉ nhìn bệnh không nhìn người, nay đặt nguyên tắc không chữa nếu bệnh nhân chưa hiểu cái giá.',
    settingSeed: 'Làng Dược Khê dưới chân tiên sơn, thiếu người lao động, đất thuốc bỏ hoang và bị thương lái ép giá theo mùa.',
    openingHook: 'Bệnh nhân đầu tiên không phải người sắp chết mà là bà chủ cối xay mất cảm giác ở tay; chữa bà đồng nghĩa cả làng có bột trước mùa mưa.',
    serialPromise: 'Ca bệnh, dược điền và sinh kế nối nhau; uy tín tăng kéo theo chuẩn mực, dịch bệnh và lựa chọn phân phối dược liệu khó hơn.',
    visualFingerprint: 'mountain-foot-clinic-herb-garden-restoring-village',
    artScene: 'A calm Vietnamese male healer at a small mountain-foot clinic, checking the hand of an elderly miller while terraced medicinal gardens and villagers returning to work glow in the background',
    artStyle: 'luminous healing xianxia illustration with botanical accuracy and lived-in village detail',
    artComposition: 'intimate treatment foreground, herb terraces rising vertically toward the mountain',
    artMood: 'restorative, humane, quietly competent',
    artPalette: 'herbal green, warm wood, mist white, gentle life-energy gold',
  }),
  storyPackage({
    slotId: 'DT-01',
    title: 'Trọng Sinh Về Làng Biển, Tôi Biến Cá Rẻ Thành Cơ Nghiệp Cả Nhà',
    tagline: 'Anh nhớ mùa biển đổi, nhưng mẻ cá đầu tiên vẫn phải tự tay kéo lên.',
    logline: 'Trọng sinh về làng biển cuối thập niên 1980, một người đàn ông dùng kinh nghiệm mùa cá, bảo quản và thị trường để cứu gia đình khỏi nợ rồi dựng sinh kế bền vững cho cả nhóm thuyền.',
    catalogueDescription: 'Niên đại làng biển khoái hoạt, main chủ động từ chương đầu và có thành quả vật chất trước chương ba. Ký ức chỉ cho xu hướng, không cho tọa độ hay giá chính xác; mỗi đồng tiền phải đi qua lao động, hao hụt và đầu ra thật.',
    protagonistSeed: 'Nguyễn Hải Sơn, người từng bỏ quê đi làm thuê, trở lại tuổi hai mươi tám với mong muốn duy nhất là để cha mẹ không phải bán chiếc thuyền cuối cùng.',
    settingSeed: 'Làng biển Vạn Gió hư cấu cuối thập niên 1980, với bến cá nhỏ, xưởng đá cây và chợ huyện cách một chuyến xe đêm.',
    openingHook: 'Sơn thức dậy trong ngày cả làng bỏ một luồng cá nhỏ vì giá rẻ; anh không lao ra khơi xa mà gom người làm mẻ cá khô thử ngay trước cơn mưa trái mùa.',
    serialPromise: 'Đánh bắt, chế biến và phân phối thay nhau tạo payoff; lợi thế ký ức giảm khi thị trường học theo và nguồn lợi biển cần được bảo vệ.',
    visualFingerprint: 'late-eighties-vietnamese-fishing-village-first-full-net',
    artScene: 'A late-1980s Vietnamese coastal fisherman hauling a shining but believable net beside his father on a weathered wooden boat, while a humble village pier, ice shed and family home wait in sunrise mist',
    artStyle: 'cinematic historical coastal illustration with authentic working textures and restrained nostalgia',
    artComposition: 'dynamic net in foreground, father and son forming the human center, village layered upward behind',
    artMood: 'fresh-start optimism, salt-air realism, earned abundance',
    artPalette: 'sea teal, sunrise peach, weathered wood brown, silver fish highlights',
  }),
  storyPackage({
    slotId: 'DT-02',
    title: 'Trọng Sinh Về Bản Núi, Một Tay Dẫn Cả Bản Làm Giàu Từ Lộc Rừng',
    tagline: 'Biết lấy gì từ rừng chưa đủ; phải biết để lại gì cho mùa sau.',
    logline: 'Trọng sinh về bản núi nghèo, một người thợ rừng dùng kinh nghiệm mùa vụ và sơ chế lâm sản để nuôi gia đình, nhưng mỗi lần kiếm nhanh đều đặt nguồn sống năm sau trước lựa chọn khó.',
    catalogueDescription: 'Niên đại miền núi thiên về sinh kế và đời sống ấm. Main biết kỹ thuật chứ không biết kho báu hay vị trí con mồi. Payoff là dụng cụ tốt hơn, bếp đủ ăn và nguồn hàng tái sinh, không phải săn giết vô hạn.',
    protagonistSeed: 'Bùi Văn Lộc, người từng mất em trai trong một chuyến khai thác liều lĩnh, trở về quyết làm giàu mà không trả giá bằng mạng người hay cánh rừng.',
    settingSeed: 'Bản Khe Mây hư cấu với rừng tre, dược liệu theo mùa, đường chợ khó đi và quyền khai thác dựa trên thỏa thuận cộng đồng.',
    openingHook: 'Lộc ngăn nhóm thanh niên đuổi theo đàn thú và dẫn họ tới một vùng măng trái vụ; muốn bán được, anh phải tự chế lò sấy trước khi đường núi bị mưa cắt.',
    serialPromise: 'Mỗi mùa đổi sản vật, cách sơ chế và quyền khai thác; tiến bộ vật chất luôn gắn với việc giữ nguồn hàng sống qua năm sau.',
    visualFingerprint: 'mountain-forager-carrying-renewable-harvest-through-mist',
    artScene: 'A Vietnamese mountain forager carrying baskets of carefully harvested bamboo shoots and medicinal leaves through misty terraced forest, with a small handmade drying kiln and waiting family visible below',
    artStyle: 'naturalistic historical rural illustration with rich forest ecology and human warmth',
    artComposition: 'ascending forest path, protagonist mid-step, renewable harvest and village linked in one vertical flow',
    artMood: 'resourceful, peaceful, quietly prosperous',
    artPalette: 'deep forest green, mist gray, bamboo gold, earthen red',
  }),
  storyPackage({
    slotId: 'DT-03',
    title: 'Trọng Sinh Năm 1989: Dùng Tiền Cưới Mua Máy Phế Liệu Mở Xưởng',
    tagline: 'Anh nhớ thị trường sẽ cần gì; chiếc máy cũ vẫn bắt anh làm lại từ đầu.',
    logline: 'Trọng sinh về năm 1989, một kỹ thuật viên chọn sản phẩm gia dụng nhỏ đang thiếu, sửa máy, làm mẫu và dựng mạng đại lý mà không sở hữu bản vẽ tương lai hay vốn vô hạn.',
    catalogueDescription: 'Niên đại công nghiệp lấy logic kỹ thuật, vốn lưu động, đội ngũ và phân phối làm causal engine. Main thắng nhờ chọn đúng nhu cầu và thử nhỏ, nhưng sai số sản xuất cùng công nợ có thể giết xưởng dù hàng bán được.',
    protagonistSeed: 'Trương Hữu Thành, kỹ thuật viên từng chứng kiến xưởng gia đình phá sản, nhớ nguyên lý và nhu cầu nhưng không nhớ thông số hoàn chỉnh.',
    settingSeed: 'Thị xã Tân Phú hư cấu năm 1989, nơi xưởng cơ khí tập thể tan rã, máy cũ được bán lại và mạng đại lý tư nhân vừa hình thành.',
    openingHook: 'Thành dùng toàn bộ tiền cưới để mua chiếc máy ép bị coi là phế liệu, rồi phải làm ra một lô mẫu bán được trong bảy ngày trước khi gia đình buộc anh trả lại.',
    serialPromise: 'Từ mẫu thử tới quy trình, máy móc và hợp đồng phân phối; ký ức tương lai giảm giá trị khi đối thủ học và tiêu chuẩn thị trường tăng.',
    visualFingerprint: '1989-small-workshop-first-machine-and-product-sample',
    artScene: 'A late-1980s Vietnamese mechanic in a cramped small workshop restarting a worn metal press as the first clean household product sample emerges, with coworkers and handwritten orders surrounding the machine',
    artStyle: 'cinematic industrial historical illustration with authentic machinery and hopeful entrepreneurial energy',
    artComposition: 'machine and glowing sample as foreground focal point, protagonist and team forming a compact triangle',
    artMood: 'determined, tactile, optimistic under financial pressure',
    artPalette: 'machine green, steel gray, tungsten amber, faded paper cream',
  }),
  storyPackage({
    slotId: 'DT-04',
    title: 'Về Quê Chăm Mẹ, Tôi Mở Bếp Theo Mùa Nuôi Cả Nhà',
    tagline: 'Một bữa ngon không đổi đời ngay, nhưng bốn mùa có thể dựng lại một mái nhà.',
    logline: 'Một người đàn ông về quê chăm mẹ mở bếp theo mùa, biến nông sản đúng vụ thành món ăn có khách và từng bước sửa lại nhà, vườn cùng quan hệ làng xóm.',
    catalogueDescription: 'Hưu nhàn nhưng không đứng yên. Mỗi mùa có nguyên liệu, sức lao động và nhu cầu khách khác nhau; món ăn là payoff cảm xúc đồng thời tạo tiền, dụng cụ và sinh hoạt cộng đồng mới.',
    protagonistSeed: 'Lê Nam, đầu bếp kiệt sức sau nhiều năm ở thành phố, tay nghề vững nhưng phải học lại nhịp sống và lòng tự trọng của mẹ.',
    settingSeed: 'Làng Bình An hư cấu với vườn cây, chợ phiên và căn bếp cũ nhìn ra cánh đồng thay màu bốn mùa.',
    openingHook: 'Ngày về quê, Nam không mở quán mà nấu hết mẻ cà chua sắp hỏng của mẹ thành sốt đóng chai, đem đổi lấy mái ngói trước cơn mưa.',
    serialPromise: 'Mùa vụ, món ăn, khách quen và không gian nhà cùng tiến triển; đời sống ấm áp luôn để lại thay đổi vật chất hoặc quan hệ.',
    visualFingerprint: 'four-seasons-home-kitchen-around-one-table',
    artScene: 'A Vietnamese male cook in an open rural home kitchen, one abundant wooden table transitioning subtly through spring herbs, summer fruit, autumn harvest and winter steam, with his elderly mother smiling nearby',
    artStyle: 'cozy painterly food illustration with realistic Vietnamese rural textures',
    artComposition: 'table as strong foreground anchor, seasonal landscape rising in four gentle bands behind',
    artMood: 'restorative, appetizing, unhurried but purposeful',
    artPalette: 'leaf green, tomato red, rice gold, winter steam blue',
  }),
  storyPackage({
    slotId: 'DT-05',
    title: 'Cổng Song Xuyên Chỉ Mở Khi Mưa, Tôi Mang Máy Lọc Nước Đổi Hàng',
    tagline: 'Hai thế giới không thiếu đồ; chúng thiếu người hiểu thứ gì thật sự có giá trị.',
    logline: 'Một chủ kho nhỏ phát hiện cánh cổng chỉ mở trong mưa và vận chuyển được khối lượng hữu hạn, từ đó xây tuyến giao dịch giữa thành phố hiện đại với một thế giới khan nước nhưng thừa vật liệu lạ.',
    catalogueDescription: 'Song xuyên kinh doanh với logistics, nguồn hàng và phản ứng thị trường thật. Không gian không vô hạn, hàng không tự sinh và đối tác hai bên có mục tiêu riêng. Tiến bộ đi từ món hàng sang hạn mức, kho vận và tín nhiệm.',
    protagonistSeed: 'Đinh Quân, chủ kho đang nợ, giỏi ghép nhu cầu với hàng hóa nhưng có thói quen giấu nguồn để giữ quyền kiểm soát.',
    settingSeed: 'Một bên là thành phố Việt hư cấu có mạng bán buôn; bên kia là đô thị đá sống nhờ hệ thống thu nước và những hợp đồng khắc trên vật liệu.',
    openingHook: 'Trong cơn mưa đầu mùa, Quân đưa nhầm một thùng ống lọc nước qua cổng và phát hiện nó có giá hơn vàng, nhưng chỉ còn mười bảy phút để tìm cách đổi hàng có thể mang về hợp pháp.',
    serialPromise: 'Mỗi giao dịch làm giá, luật và quyền lực hai bên đổi; cổng hữu hạn buộc main chọn quan hệ dài hạn thay vì vét báu vật.',
    visualFingerprint: 'rain-gate-warehouse-two-worlds-limited-cargo',
    artScene: 'A Vietnamese warehouse owner pushing a single carefully weighed cargo trolley through a rain-made portal, modern stacked goods on one side and a water-scarce stone city with luminous trade tokens on the other',
    artStyle: 'cinematic dual-world commercial fantasy with grounded logistics and original architecture',
    artComposition: 'portal dividing the vertical cover, trolley crossing the threshold, both markets visibly reacting',
    artMood: 'opportunistic, adventurous, clever rather than extravagant',
    artPalette: 'rain blue, warehouse amber, sandstone, luminous aqua trade marks',
  }),
  storyPackage({
    slotId: 'DT-06',
    title: 'Xuyên Đến Giới Giải Trí, Tôi Không Chép Nhạc Vẫn Thành Nhà Sản Xuất',
    tagline: 'Anh mang theo cách làm nghề, không mang theo một kho kiệt tác để chép lại.',
    logline: 'Xuyên tới một nền giải trí khác, một nhà sản xuất thất bại dùng phương pháp thử khán giả và phối hợp đội ngũ để tạo từng sản phẩm mới, thay vì sao chép tác phẩm từ thế giới cũ.',
    catalogueDescription: 'Truyện giải trí thiên về quá trình sáng tạo và phản hồi phân hóa. Main có thẩm mỹ lẫn kinh nghiệm nhưng không nhớ nguyên văn bài hát, phim hay thuật toán. Mỗi dự án nâng kỹ năng, khán giả và quyền sản xuất cùng trách nhiệm.',
    protagonistSeed: 'Đào Khánh, nhà sản xuất từng đốt cháy đội ngũ vì ám ảnh thành công, nay phải làm lại với một ca sĩ có giọng tốt nhưng không muốn thành ngôi sao.',
    settingSeed: 'Đô thị giải trí hư cấu nơi nền tảng phát hành minh bạch dữ liệu thử nghiệm nhưng quyền tác giả được chia rất chặt.',
    openingHook: 'Khánh được giao cứu một buổi diễn thất bại trong hai ngày; anh không viết hit mà cắt sân khấu xuống còn một căn phòng và để khán giả quyết định phần cuối.',
    serialPromise: 'Từng sản phẩm đổi định dạng, công chúng và quan hệ sáng tạo; thành công không đồng thanh và luôn mở dự án khó hơn.',
    visualFingerprint: 'empty-recording-studio-first-authentic-performance',
    artScene: 'A Vietnamese male music producer in a nearly empty recording studio, adjusting analog controls as one singer performs behind glass and small audience-response lights split into different colors rather than unanimous applause',
    artStyle: 'contemporary entertainment-drama illustration with cinematic studio realism',
    artComposition: 'producer foreground profile, singer framed through studio glass, layered reflections suggesting creative choices',
    artMood: 'creative, intimate, second-chance energy',
    artPalette: 'deep burgundy, studio black, warm tungsten, cool signal blue',
  }),
  storyPackage({
    slotId: 'DT-07',
    title: 'Trọng Sinh Khi Con Gái Còn Nhỏ, Lần Này Tôi Nhất Định Về Nhà Sớm',
    tagline: 'Anh nhớ những tiếc nuối lớn, nhưng phải học lại con mình từ đầu.',
    logline: 'Trọng sinh về lúc con gái còn nhỏ, một người cha chọn rời cuộc đua nghề nghiệp cũ để chăm con, dựng lại nếp nhà và gây dựng một công việc cho phép mình có mặt đúng lúc.',
    catalogueDescription: 'Nãi ba nam tần nhưng cả trẻ và người thân đều có nhu cầu, ranh giới riêng. Main không biết trước mọi bệnh hay cảm xúc. Payoff đến từ hành động chăm sóc cụ thể, lòng tin được xây lại và năng lực nghề nghiệp phù hợp đời sống mới.',
    protagonistSeed: 'Phạm Minh, người cha từng thành công quá muộn, vụng lời nhưng nhớ rõ những ngày mình đã vắng mặt và quyết không dùng quà cáp thay cho hiện diện.',
    settingSeed: 'Khu tập thể ven đô hư cấu, nơi Minh vừa chăm con vừa nhận sửa đồ gia dụng để kiếm tiền tại nhà.',
    openingHook: 'Ngày đầu trở lại, Minh bỏ cuộc họp quyết định thăng chức để đến buổi biểu diễn của con, rồi phát hiện chính chiếc máy âm thanh hỏng cho anh cơ hội kiếm đơn hàng đầu tiên.',
    serialPromise: 'Mỗi vòng chăm sóc gắn với một bước nghề nghiệp và nếp nhà; tiến bộ đo bằng lòng tin của con, thời gian thật và căn nhà tốt lên.',
    visualFingerprint: 'father-repair-bench-child-waiting-under-warm-clock',
    artScene: 'A Vietnamese father repairing a small cassette player at a home workbench while his young daughter waits beside a handmade school-stage prop, a wall clock showing he arrived early and evening light filling the modest room',
    artStyle: 'warm cinematic family illustration with authentic late-urban domestic detail',
    artComposition: 'father and child at eye level, repair tools forming a gentle frame, clock visible but not dominant',
    artMood: 'tender, capable, healing without sentimentality',
    artPalette: 'warm cream, faded green, copper light, soft red school fabric',
  }),
  storyPackage({
    slotId: 'DT-08',
    title: 'Tiếp Quản Kho Hàng Nhà Mình, Tôi Dùng Một Tuyến Xe Cứu Cả Phố Cũ',
    tagline: 'Cứu một cửa hàng không khó bằng khiến những người giữ nó chịu chia quyền.',
    logline: 'Một chuyên gia vận hành trở về phố cũ tiếp quản kho hàng gia đình, dùng dữ liệu, thử nghiệm nhỏ và thương lượng để cứu mạng lưới tiểu thương khỏi đứt dòng tiền.',
    catalogueDescription: 'Đô thị nghề nghiệp thực tế, nơi khách hàng, hợp đồng, hàng hóa và quyền truy cập đều có chủ. Main không biết ý định đối tác hay kết quả thị trường; mỗi thắng lợi tạo thêm nghĩa vụ kinh tế và buộc anh học cách tin đội ngũ.',
    protagonistSeed: 'Nguyễn An Bình, chủ kho đời thứ hai giỏi đọc dòng tiền nhưng luôn giữ số liệu vì sợ mất tài sản cuối cùng của gia đình.',
    settingSeed: 'Phố buôn hư cấu với kho lạnh nhỏ, nhóm tiểu thương lâu năm và mạng giao hàng đang bị thay đổi bởi quy mô mới.',
    openingHook: 'Bình phát hiện kho không mất tiền vì trộm mà vì lịch xe khiến hàng chết chậm; anh cược khoản cọc cuối cùng vào một tuyến giao thử có thể chứng minh điều đó trong đêm.',
    serialPromise: 'Mỗi nút thắt vận hành đổi quyền, dữ liệu và quan hệ; tiến bộ hiện qua dòng tiền, tài sản và quyền quyết định được chia đúng.',
    visualFingerprint: 'old-street-ledger-cold-warehouse-delivery-route',
    artScene: 'A Vietnamese small-warehouse operator studying an open debt ledger beside stacked cold crates, while an old commercial street and a single delivery route glow through the rolling door at dawn',
    artStyle: 'grounded contemporary business-drama illustration with tactile logistics detail',
    artComposition: 'ledger and hand in foreground, protagonist centered, route line leading into the old street',
    artMood: 'focused, streetwise, hopeful under real financial pressure',
    artPalette: 'cool warehouse blue, ledger cream, dawn orange, muted shop-sign red',
  }),
  storyPackage({
    slotId: 'DT-09',
    title: 'Bảo Tôi Làm Phản Diện Cướp Dự Án, Tôi Lại Nghỉ Việc Tự Khởi Nghiệp',
    tagline: 'Biết mình sẽ bị hạ bệ, anh quyết không diễn tiếp cảnh mà người khác đã viết.',
    logline: 'Một giám đốc trẻ nhận ra đời mình đang đi đúng kịch bản phản diện, chủ động rời tập đoàn gia đình và gây dựng nghề nghiệp hợp pháp trước khi thông tin cũ mất hết giá trị.',
    catalogueDescription: 'Phá kịch bản đô thị không dựa vào bí mật tác giả để vả mặt. Sau mỗi can thiệp, người khác phản ứng độc lập và tuyến sự kiện đổi thật. Main phải xây tài sản, nghề và quan hệ mới thay vì chỉ né tai họa cũ.',
    protagonistSeed: 'Võ Khải, người thừa kế bị dạy rằng kiểm soát là yêu thương, biết các mốc sụp đổ lớn nhưng không hiểu động cơ thật của những người quanh mình.',
    settingSeed: 'Đô thị thương mại hư cấu nơi các gia đình lớn sở hữu chuỗi dịch vụ nhưng mọi giao dịch rời hệ thống đều để lại bằng chứng.',
    openingHook: 'Ngay trước cuộc họp nơi anh sẽ cướp dự án của “nam chính”, Khải nộp đơn nghỉ việc và dùng tiền cá nhân mua lại đội bảo trì nhỏ sắp bị giải tán.',
    serialPromise: 'Mỗi bước thoát vai làm kịch bản cũ mất giá; tự do tăng cùng trách nhiệm với đội ngũ và những người bị lựa chọn mới tác động.',
    visualFingerprint: 'corporate-villain-walking-away-with-resignation-and-tool-team',
    artScene: 'A composed Vietnamese young executive leaving a glass corporate tower with a signed resignation folder, walking toward a small practical maintenance team and service van as scripted character silhouettes fracture behind him',
    artStyle: 'stylized contemporary drama illustration with subtle meta-narrative visual motifs',
    artComposition: 'vertical split between tower and street-level team, protagonist crossing the boundary',
    artMood: 'liberating, intelligent, quietly rebellious',
    artPalette: 'corporate graphite, glass cyan, street amber, clean white paper',
  }),
  storyPackage({
    slotId: 'DT-10',
    title: 'Bảo Tôi Lập Bang Đánh Boss, Tôi Lại Mở Dịch Vụ Cho Cả Máy Chủ',
    tagline: 'Họ không mạnh nhất máy chủ; họ khiến cả máy chủ cần đến mình.',
    logline: 'Một người chơi dùng dữ liệu giao dịch đã xảy ra để tổ chức bang hội dịch vụ, tạo thị trường và ảnh hưởng cộng đồng mà không săn drop hiếm hay độc quyền chiến lực.',
    catalogueDescription: 'Võng du kinh tế cộng đồng. Bảng dữ liệu không dự báo giá hoặc hành động người chơi; nhà phát hành, bang hội khác và khách hàng đều phản ứng theo lợi ích. Payoff đến từ đội nhóm, niềm tin và quyền thị trường.',
    protagonistSeed: 'Đỗ Vinh, cựu đội trưởng raid mệt mỏi vì tranh hạng, giỏi tổ chức người khác nhưng phải học cách không biến đồng đội thành nhân lực miễn phí.',
    settingSeed: 'Game thực tế ảo hư cấu có kinh tế vật phẩm khan hiếm, nghề dịch vụ và luật can thiệp thị trường minh bạch.',
    openingHook: 'Trong ngày mở máy chủ, Vinh bỏ qua cuộc đua boss đầu tiên để lập trạm sửa trang bị miễn phí có giới hạn, thu về thứ quý hơn vàng: dữ liệu nhu cầu thật.',
    serialPromise: 'Dịch vụ, đội ngũ và thị trường thay nhau tiến triển; mỗi thành công khiến người chơi lẫn nhà phát hành học và phản ứng.',
    visualFingerprint: 'noncombat-guild-market-hub-in-virtual-city',
    artScene: 'A Vietnamese male guild organizer standing at a bustling virtual repair-and-trade hub, diverse players exchanging crafted services and trust tokens while a distant boss battle is deliberately ignored',
    artStyle: 'polished game-world illustration focused on community economy rather than combat spectacle',
    artComposition: 'market hub rising vertically with protagonist at the coordination table, boss silhouette small in distant background',
    artMood: 'clever, social, energetic and satisfying',
    artPalette: 'digital teal, market gold, violet interface light, dark stone',
  }),
  storyPackage({
    slotId: 'DT-11',
    title: 'Giám Bảo Gốm Cổ: Tôi Chạm Một Lần, Biết Nó Được Nung Bằng Lửa Gì',
    tagline: 'Men có thể làm cũ, chứng thư có thể mua; cấu trúc của lửa thì không biết nói dối.',
    logline: 'Kỹ sư vật liệu Hoàng có thể cảm nhận độ kết tinh trong cốt gốm, dùng mảnh vỡ tiêu bản và bằng chứng lò nung để đối chất với thị trường đồ cổ sống bằng uy tín.',
    catalogueDescription: 'Giám bảo nghề nghiệp với năng lực xúc giác hữu hạn, không phải mắt thần biết giá. Hoàng phải tìm tiêu bản, kiểm lịch sử phục chế và bỏ tiền thật cho mỗi kết luận; sự thật vật liệu chỉ có giá trị khi anh biến nó thành bằng chứng người mua hiểu và chấp nhận.',
    protagonistSeed: 'Hoàng, kỹ sư vật liệu điềm tĩnh, tôn trọng vẻ đẹp bất toàn của lửa củi nhưng quá tin rằng bằng chứng khoa học một mình có thể thắng mọi quan hệ lợi ích.',
    settingSeed: 'Phố đồ cổ và bãi phế liệu ven sông của một thành phố Việt hư cấu, nơi lò ga hiện đại làm hàng giả hoàn hảo còn uy tín cá nhân quyết định ai được quyền kết luận.',
    openingHook: 'Hoàng từ chối ký cho chiếc bình giả dù mất tiền công, rồi cược hai trăm triệu và mang năm triệu cuối cùng đi tìm một mảnh gốm vỡ đủ sức chứng minh dấu lửa thật.',
    serialPromise: 'Mỗi vụ giám định đòi một tiêu bản, kỹ thuật nung và mạng lợi ích khác; thư viện mảnh vỡ, vốn lưu động cùng uy tín của Hoàng tăng hoặc mất bằng bằng chứng cụ thể.',
    visualFingerprint: 'cracked-ceramic-restoration-hidden-glaze-layer',
    artScene: 'A Vietnamese male antique restorer under a focused workshop lamp, carefully revealing a hidden glaze layer beneath dust on a cracked ceramic vessel, with provenance papers and a riverside old-goods market beyond',
    artStyle: 'refined mystery-drama illustration with material-rich restoration detail',
    artComposition: 'macro ceramic surface foreground, restorer face and evidence papers forming a vertical discovery path',
    artMood: 'quietly thrilling, cultured, evidence-driven',
    artPalette: 'celadon green, dust brown, lamp gold, river blue-gray',
  }),
  storyPackage({
    slotId: 'DT-12',
    title: 'Từ Ghế Dự Bị Đến Suất Đá Chính: Đọc Nhịp Trận Đấu Để Đổi Đời',
    tagline: 'Đọc được trận đấu chỉ cho anh một cơ hội; đôi chân phải tự chạy đến phút cuối.',
    logline: 'Một tiền vệ hạng dưới có khả năng đọc nhịp trận đấu gây dựng sự nghiệp dài bằng luyện tập, chiến thuật và niềm tin đồng đội, thay vì liên tục phá kỷ lục cá nhân.',
    catalogueDescription: 'Thể thao đường dài với tiến bộ nhìn thấy qua bài tập, vai trò và cách đội vận hành. Main không được hệ thống tăng chỉ số; chấn thương, lịch thi đấu và cạnh tranh vị trí đều có hậu quả kéo dài.',
    protagonistSeed: 'Nguyễn Tấn, tiền vệ thông minh nhưng thể lực trung bình, quen sửa lỗi người khác và phải học cách để đồng đội tự quyết trong sân.',
    settingSeed: 'Giải bóng đá chuyên nghiệp hư cấu với câu lạc bộ tỉnh nhỏ, học viện trẻ và lịch thi đấu khắc nghiệt.',
    openingHook: 'Bị đẩy lên ghế dự bị trong trận khai mùa, Tấn nhận ra đối thủ hụt nhịp sau phút sáu mươi và xin vào sân với một phương án chỉ có tác dụng nếu cả đội tin anh.',
    serialPromise: 'Từng cửa sổ trận đấu đổi điểm yếu, bài tập và vai trò; thành công của main được đo bằng đội mạnh lên và cơ thể còn đi được đường dài.',
    visualFingerprint: 'second-half-midfielder-reading-field-lines-under-rain',
    artScene: 'A Vietnamese male midfielder stepping onto a rain-soaked pitch at the start of the second half, seeing subtle tactical passing lanes while tired teammates turn toward him with cautious trust',
    artStyle: 'dynamic sports-drama illustration with realistic athletic motion and stadium atmosphere',
    artComposition: 'player entering from lower frame, luminous tactical lanes leading upward across the pitch',
    artMood: 'focused comeback energy, collective rather than superstar triumph',
    artPalette: 'wet grass green, stadium white, deep blue, restrained tactical gold',
  }),
  storyPackage({
    slotId: 'DT-13',
    title: 'Bác Sĩ Cấp Cứu Không Hệ Thống: Chỉ Dựa Chẩn Đoán Vẫn Cứu Được Người',
    tagline: 'Bác sĩ giỏi không biết hết; anh biết lúc nào phải hỏi thêm một người.',
    logline: 'Một bác sĩ cấp cứu giỏi đọc dấu hiệu nhưng không có năng lực siêu nhiên, giải các ca bệnh bằng loại trừ giả thuyết, phối hợp và tôn trọng quyền quyết định của bệnh nhân.',
    catalogueDescription: 'Y nghiệp có domain truth và giới hạn thẩm quyền. Ca bệnh tạo căng thẳng từ thông tin thiếu, thời gian và nguồn lực, không cần đồng nghiệp ngu để bị vả mặt. Payoff gồm kết quả điều trị, lòng tin và năng lực đội ngũ.',
    protagonistSeed: 'Bác sĩ Lê Minh Khoa, bình tĩnh khi cấp cứu nhưng hay tự gánh quyết định, phải học rằng hội chẩn đúng lúc cũng là một loại năng lực.',
    settingSeed: 'Bệnh viện đa khoa hư cấu phục vụ cả thành phố và vùng ven, với quy trình, nguồn lực và đội ngũ có giới hạn thật.',
    openingHook: 'Trong ca trực đầu, Khoa từ chối chẩn đoán hiếm được mọi người mong đợi và quay lại hỏi một câu đơn giản về bữa ăn, mở ra hướng xử lý kịp thời nhưng cần bệnh nhân đồng ý.',
    serialPromise: 'Ca bệnh thay đổi chuyên khoa, thông tin và quan hệ; sau ba mươi chương, cả khoa phải làm việc tốt hơn chứ không chỉ danh tiếng main tăng.',
    visualFingerprint: 'night-emergency-team-around-patient-no-miracle-light',
    artScene: 'A Vietnamese emergency doctor at night studying a patient chart while a nurse, imaging technician and consulting physician form an active coordinated team around the patient, no supernatural effects',
    artStyle: 'grounded cinematic medical-drama illustration with accurate professional body language',
    artComposition: 'doctor slightly off-center, team actions creating a clear diagnostic flow upward',
    artMood: 'urgent, humane, competent and calm',
    artPalette: 'hospital teal, clean white, night navy, warm skin tones',
  }),
  storyPackage({
    slotId: 'DT-14',
    title: 'Xuyên Đến Dị Giới, Tôi Dùng Kỹ Thuật Cấp Nước Xây Lại Cả Thành Phố',
    tagline: 'Anh không mang theo máy móc hiện đại; chỉ mang theo cách tìm đúng nút thắt.',
    logline: 'Một kỹ sư xuyên tới thế giới mới phải dùng vật liệu địa phương để sửa nước, đường và năng lượng, trong khi mỗi công trình làm thay đổi nhóm hưởng lợi lẫn người phải trả chi phí.',
    catalogueDescription: 'Kỹ nghệ thế giới mới nhưng không phát minh thần tốc. Main nhớ nguyên lý, thiếu bản vẽ và tiêu chuẩn; mọi giải pháp phải đo, thử, bảo trì. Payoff cộng đồng hiện qua nước sạch, đường đi và công xưởng vận hành được.',
    protagonistSeed: 'Kỹ sư Trần Dương, giỏi tìm nút thắt hệ thống nhưng từng bỏ qua người dùng cuối, nay phải thương lượng với những cộng đồng không tin công trình của người lạ.',
    settingSeed: 'Thành phố bậc thang hư cấu xây quanh vực khô, dùng máy nước cổ và vật liệu có tính chất khác Trái Đất.',
    openingHook: 'Dương được yêu cầu sửa cỗ máy nước trung tâm nhưng phát hiện nó hoạt động đúng; vấn đề nằm ở cách ba khu dân cư khóa van để tự bảo vệ mình.',
    serialPromise: 'Mỗi hạ tầng đổi vật liệu, người hưởng lợi và chi phí bảo trì; tiến bộ kỹ thuật luôn tạo bài toán phân phối mới.',
    visualFingerprint: 'engineer-restoring-water-through-terraced-fantasy-city',
    artScene: 'A Vietnamese male engineer opening a massive ancient valve as clean water begins flowing through a dry terraced fantasy city, with local workers testing handmade pipes and different districts watching from above',
    artStyle: 'epic engineering fantasy illustration grounded in hydraulics, labor and original materials',
    artComposition: 'water channel as luminous vertical line, engineer and workers at the valve, city terraces towering behind',
    artMood: 'transformative, practical, collectively hopeful',
    artPalette: 'sandstone, oxidized copper, brilliant water blue, sunlit cream',
  }),
  storyPackage({
    slotId: 'DT-15',
    title: 'Đội Xe Sắp Giải Tán: Từ Chuyến Hàng Đầu Tiên Đến Nghiệp Vận Tải Đường Dài',
    tagline: 'Giao đúng hẹn là lời hứa; giữ được người đi cùng mới là sự nghiệp.',
    logline: 'Một điều phối viên dựng đội vận tải nhỏ bằng dữ liệu tuyến, bảo quản và lòng tin tài xế, xử lý những biến cố không thể biết trước trên các chuyến đường dài.',
    catalogueDescription: 'Logistics hiện thực, mỗi đơn hàng có nguồn, lịch, chi phí nhiên liệu và bằng chứng giao. Main không biết trước tai nạn hay khách hàng; anh thắng nhờ ghép đúng xe, người và tuyến rồi tái đầu tư có kiểm soát.',
    protagonistSeed: 'Lương Quốc, điều phối viên từng mất đội vì ép lịch, nay quyết xây doanh nghiệp nơi tài xế có quyền từ chối tuyến không an toàn.',
    settingSeed: 'Mạng đường Việt hư cấu nối cao nguyên, đồng bằng và cảng, với thời tiết cùng nhu cầu bảo quản khác nhau.',
    openingHook: 'Đơn hàng đầu tiên có thể cứu đội xe lại không vừa bất kỳ thùng nào; Quốc phải chia chuyến và thuyết phục hai khách đối nghịch cùng chia một tuyến.',
    serialPromise: 'Tuyến đường, hàng hóa, thời tiết và đội ngũ liên tục đổi; tiến bộ hiện qua xe, dữ liệu và hợp đồng dài hạn có thể mất.',
    visualFingerprint: 'night-truck-convoy-route-map-and-signed-delivery',
    artScene: 'A Vietnamese transport coordinator beside a modest long-haul truck at a rain-swept mountain junction, holding a signed delivery receipt while route lights connect coast, highland and city in the distance',
    artStyle: 'cinematic road-and-logistics illustration with authentic vehicles and working-class dignity',
    artComposition: 'truck and coordinator low in frame, winding road and route lights climbing vertically',
    artMood: 'dependable, adventurous, grounded in responsibility',
    artPalette: 'asphalt blue, truck red, rain silver, warm cabin amber',
  }),
  storyPackage({
    slotId: 'DT-16',
    title: 'Về Phố Nhỏ Mở Quán, Tôi Dùng Món Theo Mùa Nuôi Khách Quen',
    tagline: 'Khách quen không đến vì món đắt nhất; họ đến vì quán nhớ mình cần gì.',
    logline: 'Một đầu bếp mở quán nhỏ theo mùa, dùng nguyên liệu địa phương và sự quan sát để nuôi khách quen, cải thiện không gian quán và dựng một cộng đồng không ồn ào.',
    catalogueDescription: 'Cozy nam tần có progression rõ. Mỗi món phục vụ một nhu cầu thật, bị giới hạn bởi mùa, giá và sức lao động. Đời sống chữa lành nhưng quán, nghề và quan hệ vẫn thay đổi sau từng cửa sổ chương.',
    protagonistSeed: 'Tô Lâm, đầu bếp rời nhà hàng lớn sau chấn thương cổ tay, giỏi nhớ khẩu vị nhưng không quen để khách bước vào đời riêng của mình.',
    settingSeed: 'Quán ăn trong con ngõ ven sông hư cấu, có bếp mở, sân nhỏ và nguồn nguyên liệu thay đổi theo mùa nước.',
    openingHook: 'Ngày khai quán không có khách, Lâm dùng phần nguyên liệu sắp hỏng nấu một nồi cháo cho nhóm công nhân mắc mưa, vô tình tạo những khách quen đầu tiên.',
    serialPromise: 'Món ăn, khách quen và không gian quán cùng mở rộng; mỗi comfort payoff phải để lại tiền, kỹ năng hoặc quan hệ mới.',
    visualFingerprint: 'seasonal-alley-restaurant-rainy-first-guests',
    artScene: 'A Vietnamese male cook serving steaming bowls in a tiny riverside alley restaurant during rain, the first group of tired workers warming up as seasonal ingredients and a modest open kitchen frame the scene',
    artStyle: 'rich cozy food illustration with cinematic rain and realistic Vietnamese neighborhood detail',
    artComposition: 'steaming bowls foreground, cook and guests in a warm interior, rainy alley rising behind',
    artMood: 'welcoming, restorative, quietly progressive',
    artPalette: 'broth gold, rain blue, wood brown, herb green',
  }),
  storyPackage({
    slotId: 'DT-17',
    title: 'Cổng Song Xuyên Mỗi Ngày Chỉ Chở Một Tấn, Tôi Mang Nước Cứu Làng Hạn Hán',
    tagline: 'Cổng chỉ chở được một tấn; cứu ai trước trở thành quyết định không thể trốn.',
    logline: 'Một nhân viên cứu trợ phát hiện cổng tới vùng cổ đại đang hạn hán, nhưng hạn mức vận chuyển buộc anh thiết kế từng gói nước, lương thực và thuốc có nguồn rồi tổ chức phân phối cùng người bản địa.',
    catalogueDescription: 'Song xuyên cứu trợ không biến hiện đại thành kho vô hạn. Mọi hàng phải mua, cân và theo dõi; can thiệp làm giá cả, quyền phân phối và nhu cầu hai bên đổi. Payoff là cộng đồng phục hồi năng lực tự sống.',
    protagonistSeed: 'Nguyễn Tâm, nhân viên logistics cứu trợ từng ám ảnh vì không thể cứu tất cả, nay phải công khai tiêu chí phân phối để giữ tín nhiệm hai thế giới.',
    settingSeed: 'Một bên là kho cứu trợ tư nhân ở thành phố Việt hư cấu; bên kia là vùng cổ đại khô hạn chia thành nhiều cộng đồng giữ nguồn nước.',
    openingHook: 'Cổng mở lần đầu đúng lúc một làng thiếu nước, nhưng Tâm chỉ chuyển được một tấn và từ chối chở toàn nước đóng chai để dành chỗ cho dụng cụ lọc có tác dụng lâu hơn.',
    serialPromise: 'Mỗi chuyến đổi nhu cầu cấp bách, hậu cần và quyền phân phối; giới hạn cổng giữ lựa chọn khó trong khi đời sống vẫn khá lên rõ.',
    visualFingerprint: 'one-ton-relief-gate-water-filters-and-community',
    artScene: 'A Vietnamese relief logistics worker weighing a carefully balanced one-ton pallet of water filters, medicine and grain before a portal opening onto a drought-stricken ancient valley where local organizers wait with distribution maps',
    artStyle: 'humanitarian dual-world illustration with practical logistics and respectful historical fantasy design',
    artComposition: 'cargo scale centered at the threshold, both coordination teams mirrored across the portal',
    artMood: 'urgent, compassionate, responsible rather than savior-like',
    artPalette: 'warehouse gray, relief blue, dry ochre, clean water turquoise',
  }),
  storyPackage({
    slotId: 'DT-18',
    title: 'Xuyên Nhanh Làm Nghề: Mỗi Thế Giới Tôi Chỉ Được Giữ Một Kỹ Năng',
    tagline: 'Anh không mang phần thưởng về; anh mang một kỹ năng và hậu quả của việc đã thay đổi nơi ấy.',
    logline: 'Một người đàn ông đi qua các thế giới nhiệm vụ nghề nghiệp, mỗi lần phải hiểu cơ chế địa phương, tạo thay đổi bền rồi chỉ được giữ lại một bài học hoặc kỹ năng.',
    catalogueDescription: 'Khoái xuyên nam tần không farm điểm hệ thống. Mỗi thế giới là bài toán nghề và tổ chức khác, người bản địa có mục tiêu riêng và nơi cũ không reset sạch. Tiến bộ dài hạn là khả năng ra quyết định cùng bản sắc được giữ lại.',
    protagonistSeed: 'Lê Bách, người từng đổi quá nhiều việc và không biết mình giỏi gì, bắt đầu giữ một cuốn sổ chỉ ghi những điều người khác đã dạy mình.',
    settingSeed: 'Trạm chuyển tiếp tối giản nối các thế giới nghề nghiệp hư cấu, nơi quyền chọn nhiệm vụ phải được mua bằng ký ức đã giữ.',
    openingHook: 'Nhiệm vụ đầu giao Bách cứu một xưởng gốm trong bảy ngày; khi thành công, anh bỏ kỹ thuật tạo men để mang về cách người thợ cả phân công nhóm.',
    serialPromise: 'Mỗi thế giới đổi hoàn toàn nghề, luật và cộng đồng; chỉ một kỹ năng được giữ khiến lựa chọn rời đi luôn có cái giá cảm xúc và chiến lược.',
    visualFingerprint: 'traveler-crossing-worlds-carrying-one-tool-per-life',
    artScene: 'A Vietnamese male traveler stepping through layered doorways into distinct professional worlds—a pottery workshop, storm observatory and bridge site—carrying only one simple learned tool and a worn notebook',
    artStyle: 'imaginative serialized-adventure illustration with clear world transitions and grounded professions',
    artComposition: 'traveler centered, vertical sequence of doorways and professions rising behind, one tool clearly visible',
    artMood: 'curious, uplifting, reflective with forward momentum',
    artPalette: 'neutral traveler earth tones, each doorway accented with a distinct restrained color',
  }),
];

export const FLAGSHIP_FIRST_30_CATALOGUE_V1 = FlagshipCatalogueV1Schema.parse({
  schemaVersion: 1,
  catalogueId: 'flagship-first-30-catalogue',
  generatedAt: '2026-07-13T11:00:00.000Z',
  packages,
});
