import { MarketResearchRegistryV1Schema, PortfolioManifestV1Schema, buildDistinctnessFingerprint, type PortfolioSlotV1 } from './portfolio';

type SlotInput = Omit<PortfolioSlotV1, 'researchQuestions' | 'antiPatterns' | 'distinctnessFingerprint' | 'status'>;

function preparedSlot(input: SlotInput): PortfolioSlotV1 {
  const slot = {
    ...input,
    researchQuestions: [
      `Cơ chế ${input.workingLabel} vận hành bằng nguồn lực, giới hạn và bằng chứng nào để không trở thành lời giải tùy tiện?`,
      `Các tài sản ${input.progressionCurrencies.join(', ')} được tạo, tiêu và mất ra sao để độc giả nhìn thấy tiến bộ thật?`,
      `Nguồn xung đột ${input.conflictSource} phản ứng thế nào sau mỗi thắng lợi để vòng thưởng không lặp lại?`,
    ],
    antiPatterns: [
      `Không để lợi thế ${input.advantageFamily} cung cấp đáp án, tài nguyên hoặc chiến thắng không có chi phí.`,
      `Không lặp cùng một màn khoe năng lực rồi đổi tên đối thủ, địa điểm hoặc loại phần thưởng.`,
      `Không dùng nhân vật phụ ngu đi, đứng nhìn hoặc chỉ kinh ngạc để chứng minh nhân vật chính mạnh.`,
    ],
    distinctnessFingerprint: '',
    status: 'prepared' as const,
  };
  slot.distinctnessFingerprint = buildDistinctnessFingerprint(slot);
  return slot;
}

const slots: PortfolioSlotV1[] = [
  preparedSlot({ slotId: 'HX-01', workingLabel: 'Huyền huyễn quy tắc và dị tượng', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_rules', experienceMode: 'Nhân vật đọc hiểu quy tắc nguy hiểm rồi thắng bằng suy luận, chuẩn bị và lựa chọn có giá.', advantageFamily: 'native', advantageBoundary: 'Năng lực quan sát tốt nhưng không biết sẵn đáp án; quy tắc mới phải được kiểm chứng bằng rủi ro thật.', rewardLoop: 'Phát hiện dấu hiệu, thử quy tắc, trả giá để xác nhận, khai thác kẽ hở rồi đổi vị thế trong cộng đồng.', progressionCurrencies: ['hiểu biết quy tắc', 'vật chứng', 'uy tín điều tra'], conflictSource: 'Các quy tắc chồng lấn, tổ chức độc quyền diễn giải và người khác có cách sinh tồn hợp lý riêng.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'HX-02', workingLabel: 'Đô thị cao võ nghề nghiệp', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_high_martial', experienceMode: 'Sức mạnh gắn với nghề, giấy phép, đội nhóm và hậu quả công khai trong một thành phố hiện đại hư cấu.', advantageFamily: 'bounded_system', advantageBoundary: 'Hệ thống chỉ đo phản hồi huấn luyện và gợi ý sai số, không tặng kỹ năng hoặc tài nguyên.', rewardLoop: 'Chẩn đoán điểm yếu, luyện đúng mục tiêu, hoàn thành nhiệm vụ nghề nghiệp, nhận quyền hạn rồi gánh trách nhiệm lớn hơn.', progressionCurrencies: ['thể năng', 'chứng chỉ nghề', 'quyền điều động'], conflictSource: 'Cơ quan nghề nghiệp, hợp đồng bảo hộ và cạnh tranh tài nguyên huấn luyện có quy trình thực tế.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid', 'market_urban_professional'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'HX-03', workingLabel: 'Ngự thú tiến hóa và gia đình', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_beast_family', experienceMode: 'Nuôi dưỡng sinh vật, chăm gia đình và xây tài sản sống thay vì chỉ bắt thú mạnh hơn.', advantageFamily: 'transmigration', advantageBoundary: 'Kiến thức sinh học chỉ là giả thuyết; từng giống loài phản ứng khác và cần thời gian chăm sóc.', rewardLoop: 'Quan sát tập tính, thử chế độ nuôi, mở năng lực cộng sinh, dùng thành quả giúp gia đình rồi nhận trách nhiệm đàn thú.', progressionCurrencies: ['độ tin cậy của thú', 'nguồn thức ăn', 'đất chăn nuôi'], conflictSource: 'Chu kỳ sinh trưởng, bệnh tật, quyền sử dụng đất và lợi ích giữa người nuôi với cộng đồng.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'HX-04', workingLabel: 'Văn minh và lãnh địa', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_civilization', experienceMode: 'Sảng cảm đến từ biến đất nghèo thành nơi đáng sống bằng tổ chức, sản xuất và niềm tin có nguồn.', advantageFamily: 'native', advantageBoundary: 'Nhân vật giỏi tổ chức nhưng thiếu dân, vật tư và tính chính danh; không có bảng xây dựng tự sinh.', rewardLoop: 'Nhìn nút thắt sinh kế, tổ chức người thật, hoàn thành công trình, tăng sản lượng rồi giải bài toán quyền lực mới.', progressionCurrencies: ['dân số tự nguyện', 'năng lực sản xuất', 'tính chính danh'], conflictSource: 'Địa hình, mùa vụ, phe lợi ích và người dân chỉ hợp tác khi lợi ích cùng rủi ro được chia rõ.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'HX-05', workingLabel: 'Luyện khí và kinh tế tài nguyên', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_crafting', experienceMode: 'Độc giả hưởng khoái cảm chế tạo, kiểm chứng và biến đồ bỏ thành công cụ thay đổi cán cân.', advantageFamily: 'rebirth', advantageBoundary: 'Nhớ nguyên lý và sai lầm cũ nhưng không nhớ công thức hoàn chỉnh; nguyên liệu hiện tại có sai số.', rewardLoop: 'Phân tích nhu cầu, thử vật liệu, chế tạo có hao hụt, bán hoặc sử dụng rồi tái đầu tư vào xưởng.', progressionCurrencies: ['tay nghề', 'dụng cụ xưởng', 'quan hệ cung ứng'], conflictSource: 'Độc quyền nguyên liệu, tiêu chuẩn sản phẩm, hỏng thử nghiệm và khách hàng có yêu cầu đối nghịch.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid', 'market_urban_professional'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'HX-06', workingLabel: 'Mạt thế khoa huyễn huyền huyễn', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_apocalypse', experienceMode: 'Sinh tồn chủ động, dựng nơi ở và khám phá bí mật thế giới với thành quả đời sống đều đặn.', advantageFamily: 'native', advantageBoundary: 'Năng lực đặc biệt chỉ xử lý một dạng năng lượng và luôn tiêu hao tài nguyên có thể đo.', rewardLoop: 'Trinh sát hiểm họa, thu hồi vật tư, cải tạo nơi ở, cứu năng lực cộng đồng rồi mở vùng an toàn mới.', progressionCurrencies: ['năng lượng dự trữ', 'hạ tầng trú ẩn', 'nhân lực tin cậy'], conflictSource: 'Môi trường biến đổi, chuỗi cung ứng đứt gãy và các cộng đồng có chiến lược sinh tồn khác nhau.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'TH-01', workingLabel: 'Gia tộc tu tiên nhiều thế hệ', audience: 'male', portfolioGroup: 'fantasy', genre: 'tien-hiep', genreLane: 'xianxia_clan', experienceMode: 'Tu tiên là bài toán gia tộc, sinh kế và lựa chọn truyền đời chứ không phải độc hành leo cảnh giới.', advantageFamily: 'rebirth', advantageBoundary: 'Nhớ xu thế đại biến nhưng sai lệch theo butterfly effect; không nhớ kho báu hoặc thời điểm chính xác.', rewardLoop: 'Chọn người và tài nguyên, đầu tư một thế hệ, thu kết quả có độ trễ, xử lý hệ quả rồi đổi vị thế gia tộc.', progressionCurrencies: ['nhân tài gia tộc', 'linh điền', 'minh ước'], conflictSource: 'Tuổi thọ khác nhau, phân chia tài nguyên, hôn minh và quyết định hôm nay ảnh hưởng con cháu.', worldMode: 'alternate_world', laneCardIds: ['market_xianxia_modern', 'market_family_healing'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'TH-02', workingLabel: 'Tông môn nghề nghiệp và sư đồ', audience: 'male', portfolioGroup: 'fantasy', genre: 'tien-hiep', genreLane: 'xianxia_sect_business', experienceMode: 'Dạy người, tuyển môn sinh và vận hành tông môn tạo phần thưởng ấm áp lẫn cạnh tranh.', advantageFamily: 'native', advantageBoundary: 'Giỏi nhìn người nhưng không nhìn được thiên mệnh; học trò có ý chí, tốc độ và mục tiêu riêng.', rewardLoop: 'Phát hiện tiềm năng, thiết kế cách dạy, học trò tự vượt nút thắt, tông môn tăng uy tín rồi phát sinh nghĩa vụ.', progressionCurrencies: ['năng lực môn sinh', 'công xưởng tông môn', 'danh dự sư môn'], conflictSource: 'Khác biệt phương pháp dạy, nghĩa vụ môn phái và học trò trưởng thành theo hướng thầy không kiểm soát.', worldMode: 'alternate_world', laneCardIds: ['market_xianxia_modern', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'TH-03', workingLabel: 'Tu tiên nghiên cứu và thí nghiệm', audience: 'male', portfolioGroup: 'fantasy', genre: 'tien-hiep', genreLane: 'xianxia_research', experienceMode: 'Khám phá công pháp, đan dược và pháp khí bằng giả thuyết có thể sai cùng thí nghiệm có hậu quả.', advantageFamily: 'transmigration', advantageBoundary: 'Tư duy khoa học giúp đặt câu hỏi chứ không áp định luật Trái Đất nguyên xi lên linh khí.', rewardLoop: 'Nêu giả thuyết, kiếm vật liệu, thử có kiểm soát, nhận kết quả bất ngờ rồi ứng dụng vào vấn đề thật.', progressionCurrencies: ['dữ liệu thí nghiệm', 'thiết bị đo', 'quyền tiếp cận học thuật'], conflictSource: 'Sai số linh khí, đạo đức thí nghiệm, quyền công bố và trường phái có lợi ích học thuật khác nhau.', worldMode: 'alternate_world', laneCardIds: ['market_xianxia_modern', 'market_xuanhuan_hybrid'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'TH-04', workingLabel: 'Mô phỏng vòng đời tiên môn', audience: 'male', portfolioGroup: 'fantasy', genre: 'tien-hiep', genreLane: 'xianxia_simulation', experienceMode: 'Mỗi vòng đời cho thêm hiểu biết nhưng làm thế giới và bản thân đổi khác, buộc lựa chọn chiến lược mới.', advantageFamily: 'simulation_loop', advantageBoundary: 'Mỗi lượt chỉ giữ được một mảnh thông tin hoặc kỹ năng; sự kiện phản ứng và không thể farm vô hạn.', rewardLoop: 'Chọn mục tiêu vòng đời, thử con đường, thất bại có dữ liệu, mang một kết quả về rồi đổi chiến lược hiện thực.', progressionCurrencies: ['ký ức giữ lại', 'quan hệ nhân quả', 'quyền trong tiên môn'], conflictSource: 'Giới hạn lượt, biến động lịch sử và việc dùng hiểu biết tương lai làm người khác thay đổi quyết định.', worldMode: 'alternate_world', laneCardIds: ['market_xianxia_modern', 'market_script_breaker'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'HX-07', workingLabel: 'Phản diện huyền huyễn phá mệnh', audience: 'male', portfolioGroup: 'fantasy', genre: 'huyen-huyen', genreLane: 'xuanhuan_villain_fate', experienceMode: 'Nam chính biết mình là quân cờ sẽ chết, chủ động rời phe cũ và dựng thế lực bằng giao dịch cùng lựa chọn có giá.', advantageFamily: 'script_awareness', advantageBoundary: 'Chỉ biết các điểm chết lớn của nguyên tác; ngay sau lựa chọn đầu, chi tiết và động cơ người khác đã lệch.', rewardLoop: 'Nhận ra điểm chết, cắt một ràng buộc, xây tài sản và đồng minh mới, chịu butterfly effect rồi giành thêm quyền tự quyết.', progressionCurrencies: ['quyền tự quyết', 'tài sản phe mới', 'liên minh có điều kiện'], conflictSource: 'Các thế lực bảo vệ lợi ích thật và nhân vật nguyên tác đổi chiến lược khi quân cờ không còn diễn đúng vai.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid', 'market_script_breaker'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'TH-05', workingLabel: 'Tiên hiệp y tu và cộng đồng', audience: 'male', portfolioGroup: 'fantasy', genre: 'tien-hiep', genreLane: 'xianxia_healing_community', experienceMode: 'Tu luyện đi cùng chữa trị, dựng dược điền và giúp một cộng đồng sống tốt lên mà không biến y thuật thành phép cứu miễn phí.', advantageFamily: 'native', advantageBoundary: 'Khả năng cảm nhận sinh cơ chỉ chẩn đoán phạm vi hẹp và tiêu hao sức lực; người bệnh vẫn có quyền từ chối.', rewardLoop: 'Chẩn đoán nhu cầu, tìm dược liệu, chữa trị có đổi chác, phục hồi sức lao động rồi cộng đồng mở nguồn lực mới.', progressionCurrencies: ['sinh cơ', 'dược điền', 'lòng tin cộng đồng'], conflictSource: 'Dược liệu hữu hạn, chuẩn mực y tu, dịch bệnh và bệnh nhân hoặc gia tộc có lợi ích không giống nhau.', worldMode: 'alternate_world', laneCardIds: ['market_xianxia_modern', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-01', workingLabel: 'Trọng sinh niên đại làng biển', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'era_coastal', experienceMode: 'Biết xu thế mùa cá, làm thật và nhìn gia đình khá lên từng nấc trong làng biển Việt hư cấu.', advantageFamily: 'rebirth', advantageBoundary: 'Ký ức giữ xu hướng và kỹ thuật, không cho giá, sản lượng, thời tiết hoặc tọa độ chính xác.', rewardLoop: 'Nhận ra hàng bị đánh giá thấp, đánh bắt hoặc chế biến, bán có nguồn, tái đầu tư rồi cải thiện bữa cơm.', progressionCurrencies: ['tiền mặt', 'ngư cụ', 'đầu ra ổn định'], conflictSource: 'Thời tiết, hao hụt, thiếu vốn, tranh đầu ra và giới hạn nguồn lợi biển.', worldMode: 'fictionalized', laneCardIds: ['market_era_livelihood'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-02', workingLabel: 'Trọng sinh miền núi và lâm sản', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'era_mountain', experienceMode: 'Kinh nghiệm tương lai biến kỹ năng rừng núi thành sinh kế gia đình nhưng phải giữ tài nguyên sống lâu.', advantageFamily: 'rebirth', advantageBoundary: 'Nhớ mùa và kỹ thuật chứ không biết vị trí con mồi, kho báu hay giá chắc thắng.', rewardLoop: 'Đọc dấu rừng, khai thác hợp lý, sơ chế, tìm đầu ra rồi tái đầu tư vào công cụ và bảo vệ nguồn lợi.', progressionCurrencies: ['dụng cụ rừng', 'nguồn hàng tái sinh', 'uy tín bản địa'], conflictSource: 'Mùa vụ, an toàn, quyền khai thác, thương lái và xung đột giữa lợi nhanh với sinh kế bền vững.', worldMode: 'fictionalized', laneCardIds: ['market_era_livelihood'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-03', workingLabel: 'Trọng sinh công nghiệp và phân phối', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'era_industrial', experienceMode: 'Dùng hiểu biết tương lai về sản phẩm và chuỗi cung ứng để dựng xưởng nhỏ, không ăn cắp phát minh hoàn chỉnh.', advantageFamily: 'rebirth', advantageBoundary: 'Chỉ nhớ nhu cầu và nguyên lý; thiếu bản vẽ, máy móc, tiêu chuẩn, vốn và đội ngũ hiện tại.', rewardLoop: 'Chọn nhu cầu thật, làm mẫu, sửa lỗi, bán lô nhỏ, dựng quy trình rồi mở mạng phân phối.', progressionCurrencies: ['máy móc', 'tay nghề đội ngũ', 'hợp đồng phân phối'], conflictSource: 'Sai số sản xuất, vốn lưu động, tiêu chuẩn chất lượng và đại lý bảo vệ lợi ích riêng.', worldMode: 'fictionalized', laneCardIds: ['market_era_livelihood', 'market_urban_professional'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'DT-04', workingLabel: 'Nông thôn hưu nhàn và ẩm thực', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'rural_leisure', experienceMode: 'Đời sống thư thái có tiến triển qua mùa vụ, món ăn, cửa hàng và quan hệ làng xóm.', advantageFamily: 'native', advantageBoundary: 'Tay nghề tốt nhưng bị giới hạn bởi mùa, nguyên liệu, sức lao động và khách thật.', rewardLoop: 'Thu hoạch đúng lúc, chế biến có tay nghề, phục vụ khách, cải thiện nhà cửa rồi mở một sinh hoạt cộng đồng mới.', progressionCurrencies: ['vườn mùa vụ', 'dụng cụ bếp', 'khách quen'], conflictSource: 'Thời tiết, chất lượng nguyên liệu, sức khỏe gia đình và nhu cầu khách thay đổi theo mùa.', worldMode: 'fictionalized', laneCardIds: ['market_era_livelihood', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-05', workingLabel: 'Giao dịch song xuyên', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'di-gioi', genreLane: 'dual_world_trade', experienceMode: 'Khai thác chênh lệch giá trị giữa hai thế giới bằng logistics hữu hạn và hậu quả thị trường ở cả hai bên.', advantageFamily: 'dual_world', advantageBoundary: 'Cổng có khối lượng, thời gian và rủi ro; không gian không chứa vô hạn và vật tư không tự sinh.', rewardLoop: 'Phát hiện nhu cầu lệch, gom hàng có nguồn, vận chuyển giới hạn, giao dịch rồi xử lý biến động giá và quyền lực.', progressionCurrencies: ['hạn mức vận chuyển', 'vốn hai thế giới', 'đối tác tin cậy'], conflictSource: 'Logistics, tỷ giá giá trị, luật hai bên và đối tác phản ứng khi nguồn cung mới xuất hiện.', worldMode: 'alternate_world', laneCardIds: ['market_dual_world', 'market_urban_professional'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'DT-06', workingLabel: 'Giải trí và người sáng tạo', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'entertainment_creator', experienceMode: 'Từng sản phẩm sáng tạo được làm, phát hành và nhận phản hồi có nguyên nhân thay vì sao chép kho tác phẩm.', advantageFamily: 'transmigration', advantageBoundary: 'Chỉ mang thẩm mỹ và phương pháp làm nghề, không nhớ nguyên văn tác phẩm, số liệu hoặc thuật toán nền tảng.', rewardLoop: 'Tạo sản phẩm, thử với công chúng, đọc phản hồi, sửa nghề, nhận cơ hội rồi làm dự án khó hơn.', progressionCurrencies: ['kỹ năng sáng tạo', 'khán giả trung thành', 'quyền sản xuất'], conflictSource: 'Deadline, ngân sách, thị hiếu phân hóa và cộng sự có tác quyền cùng mục tiêu riêng.', worldMode: 'fictionalized', laneCardIds: ['market_entertainment', 'market_urban_professional'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-07', workingLabel: 'Nãi ba và gia đình', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'family_parenting', experienceMode: 'Nuôi con, chữa lành mái nhà và dựng lại nghề nghiệp bằng hành động chăm sóc cụ thể.', advantageFamily: 'rebirth', advantageBoundary: 'Nhớ những tiếc nuối lớn nhưng không biết trước mọi bệnh, cảm xúc hoặc tương lai của con.', rewardLoop: 'Nhận ra nhu cầu của trẻ, hành động chăm sóc, xây lại lòng tin, giải một vấn đề nghề rồi gia đình ấm hơn.', progressionCurrencies: ['lòng tin của con', 'nếp nhà', 'năng lực nghề nghiệp'], conflictSource: 'Thời gian chăm sóc, tài chính, khác biệt nuôi dạy và người thân có ranh giới chính đáng.', worldMode: 'fictionalized', laneCardIds: ['market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-08', workingLabel: 'Đô thị nghề nghiệp và khởi nghiệp', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'urban_professional', experienceMode: 'Thắng bằng năng lực ngành nghề, khách hàng và tổ chức; mỗi kết quả tạo nghĩa vụ kinh tế mới.', advantageFamily: 'native', advantageBoundary: 'Kinh nghiệm chỉ giúp đặt câu hỏi và ưu tiên, không biết dữ liệu, ý định đối tác hoặc kết quả thị trường.', rewardLoop: 'Chẩn đoán nút thắt, thử thay đổi nhỏ, đo kết quả, nhận nghĩa vụ mới rồi biến thành năng lực đội ngũ.', progressionCurrencies: ['dòng tiền', 'quyền truy cập', 'năng lực đội ngũ'], conflictSource: 'Hợp đồng, khách hàng, dòng tiền và đồng đội có lợi ích không hoàn toàn tương thích.', worldMode: 'realistic', laneCardIds: ['market_urban_professional'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-09', workingLabel: 'Nam phản diện phá kịch bản', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'male_script_breaker', experienceMode: 'Biết điểm chết trong kịch bản rồi tự thoát vai bằng nghề nghiệp và lựa chọn khiến canon đổi thật.', advantageFamily: 'script_awareness', advantageBoundary: 'Chỉ nhớ tuyến sự kiện chính; sau mỗi can thiệp, thông tin cũ mất giá và người khác phản ứng độc lập.', rewardLoop: 'Nhận diện bẫy, đổi lựa chọn, chịu butterfly effect, xây nguồn lực mới rồi buộc kịch bản tái cấu trúc.', progressionCurrencies: ['độ tự do khỏi kịch bản', 'tài sản hợp pháp', 'quan hệ mới'], conflictSource: 'Các nhân vật bảo vệ mục tiêu của họ và sự kiện cũ biến dạng do lựa chọn của nhân vật chính.', worldMode: 'fictionalized', laneCardIds: ['market_script_breaker', 'market_urban_professional'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-10', workingLabel: 'Trò chơi và kinh tế cộng đồng', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'vong-du', genreLane: 'game_community_economy', experienceMode: 'Xây đội, thị trường và ảnh hưởng số bằng chiến lược cộng đồng thay vì chỉ tăng trang bị.', advantageFamily: 'bounded_system', advantageBoundary: 'Bảng dữ liệu chỉ phản ánh giao dịch đã xảy ra, không dự báo drop, giá hoặc hành động người chơi.', rewardLoop: 'Đọc nhu cầu cộng đồng, tổ chức đội, tạo dịch vụ, tích lũy niềm tin rồi mở quyền tác động thị trường.', progressionCurrencies: ['vốn trong game', 'độ tin cậy đội nhóm', 'quyền thị trường'], conflictSource: 'Người chơi, bang hội và nhà phát hành phản ứng theo lợi ích, luật chơi và kinh tế khan hiếm.', worldMode: 'fictionalized', laneCardIds: ['market_game_economy', 'market_urban_professional'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-11', workingLabel: 'Giám bảo và thị trường đồ cũ', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'urban_collectibles', experienceMode: 'Khoái cảm phát hiện giá trị ẩn đến từ kiến thức vật liệu, lịch sử món đồ và thương lượng có chứng cứ, không phải mắt thần toàn năng.', advantageFamily: 'bounded_system', advantageBoundary: 'Công cụ chỉ gợi ý một thuộc tính vật liệu sau khi chạm và luôn có sai số; nguồn gốc, giá và tính hợp pháp phải tự điều tra.', rewardLoop: 'Nhận món đồ bị đánh giá sai, kiểm chứng nguồn gốc, phục hồi hoặc kết nối đúng người mua, thu lợi rồi nâng năng lực thẩm định.', progressionCurrencies: ['hồ sơ nguồn gốc', 'vốn quay vòng', 'uy tín giới sưu tầm'], conflictSource: 'Hàng giả, lịch sử sở hữu thiếu đoạn, chi phí phục hồi và người mua bán có thông tin cùng mục tiêu khác nhau.', worldMode: 'fictionalized', laneCardIds: ['market_urban_professional'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'DT-12', workingLabel: 'Thể thao và sự nghiệp đường dài', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'sports_career', experienceMode: 'Tiến bộ thể thao được nhìn thấy qua luyện tập, chiến thuật, đồng đội và cơ hội nghề nghiệp thay vì chỉ lập kỷ lục liên tục.', advantageFamily: 'native', advantageBoundary: 'Nhân vật có khả năng đọc trận đấu nhưng thể lực, chấn thương và kỹ năng chỉ tăng qua luyện tập có thời gian.', rewardLoop: 'Phân tích một điểm yếu, luyện bài cụ thể, thi đấu ứng dụng, giúp đội nhận kết quả rồi mở vai trò khó hơn.', progressionCurrencies: ['thể lực bền vững', 'quyền chiến thuật', 'niềm tin đồng đội'], conflictSource: 'Chấn thương, lịch thi đấu, cạnh tranh vị trí và đồng đội hoặc huấn luyện viên có chiến lược hợp lý riêng.', worldMode: 'fictionalized', laneCardIds: ['market_urban_professional', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-13', workingLabel: 'Y nghiệp có giới hạn', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'medical_professional', experienceMode: 'Thắng lợi đến từ chẩn đoán, phối hợp và chăm sóc đúng quy trình; ca bệnh thay đổi đời sống chứ không chỉ làm nền tung hô thần y.', advantageFamily: 'native', advantageBoundary: 'Bác sĩ giỏi một chuyên khoa cụ thể, vẫn cần xét nghiệm, đồng nghiệp, consent và không thể cứu mọi trường hợp.', rewardLoop: 'Thu thập dấu hiệu, loại trừ giả thuyết, phối hợp điều trị, theo dõi kết quả rồi đổi lòng tin hoặc năng lực khoa.', progressionCurrencies: ['năng lực chẩn đoán', 'quyền phối hợp', 'lòng tin bệnh nhân'], conflictSource: 'Thông tin thiếu, thời gian, nguồn lực y tế, quyền bệnh nhân và đồng nghiệp có đánh giá chuyên môn khác.', worldMode: 'fictionalized', laneCardIds: ['market_urban_professional', 'market_family_healing'], promotionCohort: 'opening_tournament' }),
  preparedSlot({ slotId: 'DT-14', workingLabel: 'Kỹ nghệ và hạ tầng thế giới mới', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'khoa-huyen', genreLane: 'infrastructure_engineering', experienceMode: 'Dùng tư duy kỹ sư để sửa nước, điện, đường và sản xuất trong thế giới hư cấu, với công trình tạo payoff cộng đồng rõ.', advantageFamily: 'transmigration', advantageBoundary: 'Nhớ nguyên lý chứ không có bản vẽ, máy móc hoặc vật liệu chuẩn; mọi giải pháp phải thử bằng công nghệ tại chỗ.', rewardLoop: 'Đo nút thắt hạ tầng, thiết kế bản thử, huy động nguồn lực, vận hành công trình rồi giải hậu quả quy mô mới.', progressionCurrencies: ['dữ liệu địa hình', 'năng lực công xưởng', 'quyền điều phối công trình'], conflictSource: 'Sai số kỹ thuật, vật liệu địa phương, bảo trì và nhóm hưởng lợi hoặc chịu thiệt khác nhau từ công trình.', worldMode: 'alternate_world', laneCardIds: ['market_xuanhuan_hybrid', 'market_urban_professional'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-15', workingLabel: 'Logistics đường dài', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'transport_logistics', experienceMode: 'Một đội vận tải nhỏ đi lên bằng tuyến đường, thời gian, bảo quản và lòng tin khách hàng được ghi nhận.', advantageFamily: 'native', advantageBoundary: 'Nhân vật hiểu tuyến và vận hành nhưng không biết trước tai nạn, đơn hàng hoặc quyết định của tài xế và khách.', rewardLoop: 'Ghép nhu cầu với năng lực xe, lập tuyến, xử lý biến cố, giao có bằng chứng rồi tái đầu tư vào đội vận tải.', progressionCurrencies: ['năng lực đội xe', 'dữ liệu tuyến', 'hợp đồng dài hạn'], conflictSource: 'Nhiên liệu, thời tiết, lịch tài xế, hao hụt hàng và khách hàng có ưu tiên chi phí khác an toàn.', worldMode: 'realistic', laneCardIds: ['market_urban_professional', 'market_era_livelihood'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-16', workingLabel: 'Quán ăn hưu nhàn và cộng đồng', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'do-thi', genreLane: 'cozy_inn_food', experienceMode: 'Nam chính dựng quán nhỏ đáng sống, món ăn và khách quen tạo chữa lành nhưng mỗi mùa vẫn có tiến bộ nghề cùng tài sản.', advantageFamily: 'native', advantageBoundary: 'Tay nghề tốt nhưng bị giới hạn bởi nguyên liệu, sức lao động, mặt bằng và khẩu vị khách thật.', rewardLoop: 'Tìm nguyên liệu đúng mùa, làm món có tay nghề, phục vụ một nhu cầu cụ thể, giữ khách rồi cải thiện quán và mái nhà.', progressionCurrencies: ['tay nghề bếp', 'khách quen', 'không gian quán'], conflictSource: 'Mùa vụ, giá nguyên liệu, sức khỏe, mặt bằng và khách hàng có câu chuyện hoặc ranh giới riêng.', worldMode: 'fictionalized', laneCardIds: ['market_era_livelihood', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-17', workingLabel: 'Song xuyên cứu trợ cổ đại', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'di-gioi', genreLane: 'dual_world_relief', experienceMode: 'Cổng hai giới được dùng giải bài toán nước, lương thực và y tế có giới hạn; payoff là một vùng sống lại chứ không chỉ đổi báu vật.', advantageFamily: 'dual_world', advantageBoundary: 'Cổng khóa khối lượng và thời gian, hàng phải mua có nguồn; can thiệp làm giá, quyền lực và nhu cầu hai bên thay đổi.', rewardLoop: 'Xác định nhu cầu cấp bách, thiết kế gói hàng hữu hạn, vận chuyển, tổ chức phân phối rồi xử lý hệ quả xã hội.', progressionCurrencies: ['hạn mức vận chuyển', 'mạng lưới phân phối', 'tín nhiệm hai thế giới'], conflictSource: 'Logistics, dịch bệnh, quyền phân phối và các cộng đồng có ưu tiên sinh tồn cùng nghi ngại hợp lý.', worldMode: 'alternate_world', laneCardIds: ['market_dual_world', 'market_family_healing'], promotionCohort: 'reserve' }),
  preparedSlot({ slotId: 'DT-18', workingLabel: 'Khoái xuyên nhiệm vụ nghề nghiệp', audience: 'male', portfolioGroup: 'urban_era_dual_world', genre: 'khoai-xuyen', genreLane: 'quick_world_missions', experienceMode: 'Mỗi thế giới là một bài toán nghề và tổ chức khác; nhân vật giữ kỹ năng ra quyết định chứ không farm thưởng hệ thống.', advantageFamily: 'simulation_loop', advantageBoundary: 'Mỗi vòng chỉ giữ được một bài học hoặc kỹ năng; thất bại mất tài nguyên và thế giới không reset hoàn hảo.', rewardLoop: 'Nhận vai trò khó, hiểu cơ chế địa phương, tạo một thay đổi bền, trả giá rời thế giới rồi mang về bài học hữu hạn.', progressionCurrencies: ['kỹ năng giữ lại', 'mảnh ký ức', 'quyền chọn nhiệm vụ'], conflictSource: 'Luật nghề nghiệp, mục tiêu người bản địa và sự hao mòn bản sắc khi nhân vật phải thích nghi liên tục.', worldMode: 'alternate_world', laneCardIds: ['market_script_breaker', 'market_game_economy'], promotionCohort: 'reserve' }),
];

export const FLAGSHIP_FIRST_30_MANIFEST = PortfolioManifestV1Schema.parse({
  schemaVersion: 1,
  portfolioId: 'flagship-first-30',
  generatedAt: '2026-07-13T05:00:00.000Z',
  strategy: {
    funnel: '30_to_9_to_3',
    writerIsolation: true,
    productionDefault: 'paused_hidden_manual_only',
    existingPilots: 'lab_reference_not_counted',
  },
  slots,
});

const sources = [
  { id: 'source_cass_2025_report', title: '2025中国网络文学发展研究报告', publisher: '中国社会科学网', publishedAt: '2026-04-20', url: 'https://www.cssn.cn/skgz/bwyc/202604/t20260420_5981165.shtml', finding: 'Báo cáo ghi nhận đô thị huyền huyễn, mạt thế cao võ, hiện thực, huyền ảo và các dòng chữa lành cùng phát triển; độc giả chuyển từ sảng đơn nhất sang nội dung đa dạng, sâu và mới.', limitation: 'Báo cáo toàn ngành Trung Quốc, không trực tiếp đo thị hiếu độc giả Việt hoặc bảo đảm một trope cụ thể sẽ thành công.' },
  { id: 'source_cass_social_value', title: '中国网络文学的社会价值生成', publisher: '中国社会科学网', publishedAt: '2026-03-04', url: 'https://www.cssn.cn/skgz/bwyc/202603/t20260304_5974950.shtml', finding: 'Sảng, nhiệt huyết, ngọt và chữa lành tạo giải tỏa áp lực nhờ cơ chế nhập vai, cộng hưởng và bù đắp cảm xúc.', limitation: 'Phân tích chức năng xã hội, không phải bảng xếp hạng thương mại hay công thức viết chương.' },
  { id: 'source_wyb_intellectual_fantasy', title: '智性幻想小说的崛起', publisher: '文艺报', publishedAt: '2026-02-06', url: 'https://wyb.chinawriter.com.cn/content/202602/06/content82721.html', finding: 'Nam tần fantasy mới nổi kết hợp tư duy lý tính, nghề nghiệp, công nghiệp, khoa học viễn tưởng và hệ thống thế giới logic thay cho chỉ khoe thiên phú.', limitation: 'Tập trung một số tác giả và tác phẩm tiêu biểu, nên chỉ dùng làm tín hiệu cơ chế chứ không thành template chung.' },
  { id: 'source_wyb_type_hybrid', title: '诚于时代，诚于文学', publisher: '文艺报', publishedAt: '2026-01-21', url: 'https://wyb.chinawriter.com.cn/content/202601/21/content82487.html', finding: 'Type fiction đang phá ranh giới: tiên hiệp và tu chân kết hợp khoa huyễn, mạt thế, vòng lặp, dị vật và thẩm mỹ mạng mới.', limitation: 'Bình luận văn học rộng, không cung cấp dữ liệu retention theo chương hoặc theo nền tảng.' },
  { id: 'source_chinawriter_fantasy_reality', title: '从玄幻到现实——网络文学的回归与超越', publisher: '中国作家网', publishedAt: '2025-08-14', url: 'https://www.chinawriter.com.cn/n1/2025/0814/c404027-40542448.html', finding: 'Bài viết chỉ ra công thức xuất thân thấp, cơ duyên, nâng cấp và đánh quái đã thành lối mòn rõ, đồng thời nhấn mạnh giá trị của chất liệu hiện thực và văn hóa trong fantasy.', limitation: 'Góc nhìn phê bình lịch sử thể loại, không có mẫu thử độc giả Việt và không phủ hết các nhánh nữ tần.' },
  { id: 'source_wyb_story_character', title: '好故事、好设定、好人物依旧是“新网文”的核心', publisher: '文艺报', publishedAt: '2026-05-22', url: 'https://wyb.chinawriter.com.cn/Pad/content/202605/22/content83945.html', finding: 'Truyện mạng mới vẫn cần story, setting và character mạnh; xu hướng là dung hợp hiện thực, hài, huyền ảo và nghề nghiệp thay vì chỉ tối đa hóa sảng cảm.', limitation: 'Tọa đàm định tính, không thay thế blind test opening hoặc đánh giá nhân quả trên chương thật.' },
];

const commonSourceIds = ['source_cass_2025_report', 'source_cass_social_value', 'source_wyb_story_character'];
const card = (id: string, label: string, readerPromise: string, activeMechanisms: string[], saturationRisks: string[], sourceIds = commonSourceIds) => ({ id, label, usage: 'upstream_concept_lab_only' as const, mustNeverReachWriter: true as const, readerPromise, activeMechanisms, saturationRisks, sourceIds });

export const FLAGSHIP_MARKET_RESEARCH_V1 = MarketResearchRegistryV1Schema.parse({
  schemaVersion: 1,
  researchedAt: '2026-07-13T05:00:00.000Z',
  sources,
  cards: [
    card('market_xuanhuan_hybrid', 'Huyền huyễn lai ghép hiện đại', 'Sức mạnh vẫn sảng nhưng được kiếm qua quy tắc, nghề nghiệp, tổ chức và lựa chọn có giá.', ['Lai ghép khoa huyễn, mạt thế, nghề nghiệp hoặc quản trị vào một causal world riêng.', 'Cho ít nhất hai loại tiến bộ ngoài chiến lực để cảnh không chỉ là đấu thắng.', 'Dùng trí mưu và kiểm chứng làm nguồn bất ngờ thay cho cơ duyên liên tiếp.'], ['Đổi tên cảnh giới nhưng giữ nguyên vòng đánh quái và đo sức mạnh.', 'Học viện, bí cảnh, đấu giá và thiên kiêu xuất hiện như checklist.', 'Hệ thống phát thưởng khiến tài nguyên và năng lực mất nhân quả.'], ['source_cass_2025_report', 'source_wyb_intellectual_fantasy', 'source_wyb_type_hybrid', 'source_chinawriter_fantasy_reality']),
    card('market_xianxia_modern', 'Tiên hiệp phi cổ điển', 'Tu hành gắn với gia tộc, tông môn, nghiên cứu, sinh kế hoặc thể chế có ký ức dài.', ['Thay độc hành bằng quyết định nhiều thế hệ hoặc nhiều thành viên.', 'Biến đan khí trận pháp thành nghề có thử nghiệm, thị trường và chuẩn mực.', 'Cho đạo tâm thể hiện qua lựa chọn tài nguyên và trách nhiệm chứ không chỉ lời tuyên ngôn.'], ['Báo cảnh giới và thọ nguyên thay cho diễn biến.', 'Đấu giá, giết cướp và nhặt túi trữ vật thành vòng lặp chính.', 'Phi thăng reset toàn bộ quan hệ, tài sản và lời hứa.'], ['source_cass_2025_report', 'source_wyb_type_hybrid', 'source_chinawriter_fantasy_reality']),
    card('market_era_livelihood', 'Niên đại và sinh kế', 'Biết hoặc làm tốt sớm hơn, kiếm thành quả có nguồn và nhìn đời sống gia đình khá lên.', ['Dùng nghề thật, mùa vụ và chuỗi giá trị làm causal engine.', 'Chuyển tiền thành công cụ, nhà cửa, sức khỏe và quyền quyết định nhìn thấy được.', 'Buộc lợi thế tương lai giảm dần khi người khác học và thị trường đổi.'], ['Ký ức là bảng giá, tọa độ hoặc xổ số chính xác.', 'Vật tư, vốn và đầu ra xuất hiện đúng lúc không có nguồn.', 'Lặp thu mua rẻ rồi bán đắt với đám đông chỉ biết kinh ngạc.']),
    card('market_dual_world', 'Giao dịch hai thế giới', 'Chênh lệch giá trị giải bài toán hai bên nhưng logistics và giá cả phản ứng thật.', ['Khóa khối lượng, thời gian, bảo quản và bằng chứng nguồn hàng.', 'Theo dõi tác động cung mới lên giá và quyền lực của cả hai thị trường.', 'Tạo quan hệ dài hạn thay vì mỗi chương đổi một món hàng lạ.'], ['Mì gói đổi báu vật lặp vô hạn.', 'Cổng như kho vô hạn không tiêu hao hoặc rủi ro.', 'Không ai điều tra nguồn hàng hay phản ứng với biến động giá.']),
    card('market_entertainment', 'Giải trí nghề nghiệp', 'Được công nhận qua từng sản phẩm, kỹ năng và phản hồi công chúng có nguyên nhân.', ['Viết quy trình tạo sản phẩm và phối hợp đội ngũ thành cảnh.', 'Phân hóa công chúng thay vì toàn mạng đồng thanh.', 'Cho quyền sáng tạo và quan hệ nghề tăng cùng trách nhiệm.'], ['Sao chép kho tác phẩm Trái Đất nguyên văn.', 'Khán giả chỉ biết kinh ngạc và gọi thiên tài.', 'Đối thủ tự đạo văn hoặc tự hủy đúng lúc để bị vả mặt.']),
    card('market_family_healing', 'Gia đình và chữa lành', 'Bữa cơm, chăm sóc và lòng tin là payoff thật nhưng đời sống vẫn tiến về vật chất lẫn quan hệ.', ['Đứa trẻ và người thân có nhu cầu, ranh giới và phản ứng riêng.', 'Mỗi comfort payoff phải đến từ hành động và nguồn lực đã trả.', 'Đan xen nghề nghiệp vừa đủ để gia đình không sống bằng may mắn.'], ['Trẻ chỉ bán manh hoặc nói như người lớn để đẩy plot.', 'Thân phận giàu có xuất hiện giải quyết toàn bộ sinh kế.', 'Hưu nhàn thành nhật ký món ăn không có thay đổi trạng thái.']),
    card('market_urban_professional', 'Đô thị nghề nghiệp', 'Năng lực thật tháo nút thắt, tạo kết quả có bằng chứng và nghĩa vụ kinh tế mới.', ['Xác định ai giữ dữ liệu, quyền ký, hàng hóa và dòng tiền.', 'Cho thử nghiệm nhỏ có thể thất bại trước khi scale.', 'Để đối tác phản ứng khi lợi ích hoặc quyền bị thay đổi.'], ['Bịa quy trình pháp lý, ngân hàng hoặc nền tảng.', 'Doanh thu tăng mà không có khách, chi phí hay vốn lưu động.', 'Tập đoàn và xã hội đen nhảy vào chỉ để nâng cấp đối thủ.']),
    card('market_script_breaker', 'Phá kịch bản và phản diện', 'Biết một phần số phận, đổi lựa chọn sớm rồi sống với butterfly effect ngày càng lớn.', ['Giới hạn ký ức về mốc lớn thay vì chi tiết tuyệt đối.', 'Đo độ mất giá của thông tin sau mỗi can thiệp.', 'Xây nguồn lực mới thay cho chỉ né sự kiện cũ.'], ['Canon vẫn phục vụ nữ hoặc nam chính sau khi đã lệch.', 'Mọi người giữ nguyên tính cách để bị dẫn dắt.', 'Vả mặt dựa trên bí mật tác giả trao chứ không phải hành động.']),
    card('market_game_economy', 'Game và kinh tế cộng đồng', 'Đội nhóm, thị trường và ảnh hưởng số tạo sảng cảm xã hội ngoài chiến lực cá nhân.', ['Theo dõi nguồn tiền, vật phẩm và quyền thị trường.', 'Để bang hội và nhà phát hành phản ứng theo luật cùng lợi ích.', 'Dùng niềm tin đội nhóm như tài sản có thể mất.'], ['Drop hiếm liên tục cứu mọi kế hoạch.', 'Người chơi khác không học hoặc không phản ứng.', 'Chỉ báo level, trang bị và bảng xếp hạng thay cho câu chuyện.']),
  ],
});
