-- Phase 2026-05-16 root-cause fix: chapter event repetition.
--
-- Adds an explicit ledger of major resolved events to story_synopsis. This
-- complements the rolling free-text synopsis with a structured "what's been
-- definitively closed" list that arc plan generation + chapter Architect
-- read as a hard "do not re-stage" anchor.
--
-- Column is TEXT[] of pre-rendered event tags (e.g. "ch.4: Băng Tinh Yến
-- cured by Lâm Uyên via Đá Vôi method"). Generated by generateSynopsis()
-- whenever a plot_thread flips to status='resolved' in the rolling window.

ALTER TABLE story_synopsis
  ADD COLUMN IF NOT EXISTS major_events_resolved TEXT[] NOT NULL DEFAULT '{}';

COMMENT ON COLUMN story_synopsis.major_events_resolved IS
  'Phase 2026-05-16: structured ledger of major resolved events tagged by chapter. Used by generateArcPlan + Architect to prevent event re-staging in later arcs.';
