// Arc 1 detailed chapter briefs (ch.6-50, 45 briefs).
// Ch.1-5 already written/refined separately.
//
// Format per brief:
//   chapterNumber, brief (1-line goal), sceneDirection (tone + BAN list),
//   scenes (4-6 short scenes), mcBenefit (concrete payoff), sub_arc_number

import type { ChapterBrief } from './arc-skeleton';

const TONE_LAO_LUC = 'TONE: MC Cố Diệp lạnh đạm + tự tin + tính toán. Public face thiếu niên 16 tuổi may mắn. KHÔNG paranoid. KHÔNG tự khoe.';
const BAN_BASE = 'BAN: cliffhanger "có người theo dõi/rình mò"; pet evolve công khai; em gái biết Vạn Linh Phổ; MC chõ mồm bênh người lạ; lặp scene Tro Bụi evolve (đã xong ở ch.4-5).';

export const ARC1_BRIEFS_CH6_50: ChapterBrief[] = [
  // ─── Sub-arc 2 (ch.6-10): Cố Già Tâm mentor + đệ tử trẻ network ──────────
  {
    n: 6, beat: 'breathing',
    brief: 'Sáng yên — Cố Già Tâm dẫn MC vào kho di sản tạm thời (vài kệ ngoài, chưa mở phần niêm phong). MC nhận sách tiến hóa cổ + 50g Linh Mạch + 2 viên Hỏa Diễm Thạch. Trưa: MC dạy 5 đệ tử trẻ kiến thức cơ bản. Em gái nhìn anh ngưỡng mộ.',
    scenes: [
      'Sáng: Cố Già Tâm gõ cửa MC, dẫn ra kho di sản phía bắc Cố phủ (kệ ngoài chỉ vài chục cuốn sách + nguyên liệu)',
      'Già Tâm: "phần niêm phong sâu cần trưởng tộc hợp pháp mở, ta tạm cho cháu phần này" — trao sách + vật phẩm hữu hình',
      'MC scan Vạn Linh Phổ với Già Tâm (lén): Già Tâm có pet Lão Quy E peak — internal note',
      'Trưa: MC dạy 5 đệ tử trẻ (Cố Khang, Cố Tử Vũ, 3 khác) kiến thức phong/lôi/hỏa',
      'Đệ tử trẻ ngầm phục — chuyển hướng theo MC (network expand)',
      'Chiều: em gái Cố Tiểu Đào ngắm anh giảng, ngưỡng mộ. Hà Thúc thở phào "thiếu gia có thần thái thế này, gia tộc còn hy vọng"',
      'Tối: MC về phòng kín, Lửa Tro nằm cuộn — pet kìm chế tốt',
    ],
    mcBenefit: 'sách tiến hóa cổ + 50g Linh Mạch + 2 viên Hỏa Diễm Thạch (tài nguyên), 5 đệ tử trẻ ngầm phục (network), uy tín với Già Tâm + Hà Thúc (quan hệ)',
    threadsAdvance: ['phục hưng gia tộc', 'Vạn Linh Phổ tuyến tiến hóa expand'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC + Lửa Tro yên tĩnh, KHÔNG cliffhanger paranoia.'],
  },
  {
    n: 7, beat: 'setup',
    brief: 'MC chuẩn bị giải đấu nội tộc vòng 1 — Vân Kiếm thách đấu (5 ngày sau brief gốc, AI đã đổi thành 3 ngày trong ch.3, follow tiếp). Tập Lửa Tro kìm chế. Quan sát đối thủ Vân Kiếm + Bạch Ngân Lang qua Vạn Linh Phổ.',
    scenes: [
      'Sáng: MC ra võ trường Cố tộc xem đám đệ tử luyện tập — quan sát từ xa',
      'Vân Kiếm xuất hiện với Bạch Ngân Lang, khoe kỹ năng Phong hệ Tốc Độ Tăng + Vân Khí Phá',
      'MC scan Vạn Linh Phổ: Bạch Ngân Lang cấp D, kỹ năng Phong, weakness = Hoả + bị nhiệt cản tốc độ',
      'MC ngầm note chiến thuật: Lửa Tro phun tro vào mắt → giảm tốc → bóp lăn trúng chân',
      'Trưa: MC tập Lửa Tro trong phòng kín — kỹ năng kìm chế "show 25% sức = cấp F+"',
      'Chiều: Cố Vân Kiếm gặp MC ở sân, chế nhạo "huynh không có pet, đừng để mất mặt" — MC vỏ bình thản, không đáp',
      'Tối: MC về phòng, viết kế hoạch giải đấu vào sổ kiếp trước',
    ],
    mcBenefit: 'manh mối Bạch Ngân Lang weakness (thông tin), kỹ năng kìm chế Lửa Tro (skill), confirm chiến thuật giải đấu',
    threadsAdvance: ['phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC viết sổ trong phòng yên tĩnh.'],
  },
  {
    n: 8, beat: 'confront',
    brief: 'Sáng: chú Cố Trường Khải tổ chức cuộc họp trưởng lão sớm, tung Cố Khiếu cáo buộc MC tối qua ra ngoài lén lút. MC deflect bằng manh mối Cố Già Tâm — Già Tâm xác nhận MC ở kho di sản với mình. Cuộc họp Khiếu lại mất mặt. Trưởng lão khác bắt đầu nghi ngờ Khiếu vu cáo.',
    scenes: [
      'Sáng: Cuộc họp trưởng lão tại sảnh chính — Cố Trường Khải mở đầu, Khiếu cáo buộc MC ra ngoài đêm',
      'Khiếu: "tôi nghe tiếng người lén lút khu hậu sơn, có người báo cáo MC ở đó"',
      'MC bình tĩnh: "tôi đêm qua trong kho di sản với trưởng lão Cố Già Tâm — ngài có thể xác nhận"',
      'Già Tâm xác nhận: "thiếu gia ở kho di sản với ta đến canh ba" — Khiếu câm họng',
      'Trưởng lão Cố Trường Lệ (phe Khiếu) tái mặt, các trưởng lão khác bắt đầu thì thầm Khiếu vu cáo',
      'Cố Trường Khải bực: "thôi, vào việc khác" — chuyển chủ đề, mất uy thế',
      'Chiều: MC + Hà Thúc về phòng kín, Hà Thúc nghi vấn nhỏ "Già Tâm thực ra biết gì về tôi?" — MC: "ông ấy chưa biết Vạn Linh Phổ, chỉ thấy tôi có chí"',
    ],
    mcBenefit: 'deflect cáo buộc thành công (uy tín nội tộc tăng), Già Tâm tăng đứng phe MC (quan hệ), Khiếu mất uy tín hội đồng (face-slap nhỏ), Trường Khải mất thế (đột phá quyền lực)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC + Hà Thúc thảo luận, KHÔNG cliffhanger paranoia.'],
  },
  {
    n: 9, beat: 'big_wow',
    brief: 'BIG WOW (small scale — nội tộc): MC + Già Tâm cùng dạy 10 đệ tử trẻ trong vườn Cố tộc. MC giải đáp 1 vấn đề pet evolution mà Già Tâm cũng không biết — bystander shock thầm. Đám đệ tử trẻ chuyển hướng hoàn toàn theo MC. Vân Kiếm đi ngang, nghe được, mặt sa sầm.',
    scenes: [
      'Sáng: Già Tâm tổ chức buổi giảng cho 10 đệ tử trẻ ngoài vườn Cố tộc — mời MC cùng dạy',
      'Đệ tử Cố Khang hỏi: "tại sao Tro Bụi cấp F lại có sức tấn công cấp E?" — câu hỏi khó',
      'Già Tâm trầm ngâm "đây là vấn đề về mutation tuyến tiến hóa, ngay cả ta cũng không rõ"',
      'MC: "tôi đọc trong sách tổ phụ — pet F nếu feed đúng sequence thì có thể đột biến chỉ số. Ví dụ Tro Bụi feed Tro Lửa Linh sẽ tăng linh lực + thuộc tính hỏa"',
      'Già Tâm bystander shock thầm: "tổ phụ đã viết về thứ này? Ta chưa bao giờ thấy" — internal monologue dài',
      '10 đệ tử trẻ chấn động, một đệ tử quỳ xuống "thiếu gia, xin nhận chúng tôi làm đệ tử" — MC lịch sự "không cần quỳ, chúng ta cùng học hỏi"',
      'Vân Kiếm đi ngang, nghe được, mặt sa sầm. Bỏ đi không nói',
      'Chiều: 10 đệ tử trẻ + Cố Khang chính thức theo MC, group ngầm thành lập',
    ],
    mcBenefit: 'Già Tâm bystander shock thầm + tăng đứng phe MC (uy tín lớn), 10 đệ tử trẻ chính thức theo MC (network mạnh), face-slap Vân Kiếm thầm (đối thủ kinh ngạc), authority về tuyến tiến hóa (skill recognition)',
    threadsAdvance: ['phục hưng gia tộc', 'Vạn Linh Phổ tuyến tiến hóa expand'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene 10 đệ tử trẻ ngoài vườn cùng MC + Già Tâm.'],
  },
  {
    n: 10, beat: 'resolution',
    brief: 'BREATHING + RESOLUTION: MC tổ chức nhánh đệ tử trẻ riêng, đặt tên "Tro Linh Phái" (informal). Hà Thúc cảm động, kể cho MC chuyện tổ phụ ngày xưa cũng dạy đệ tử trẻ giống MC. Em gái Cố Tiểu Đào lần đầu xin MC dạy chính thức.',
    scenes: [
      'Sáng: MC + 10 đệ tử trẻ + Cố Khang tổ chức buổi tập nhỏ ở hậu sơn',
      'MC dạy basic feed sequence cho đệ tử có pet F-E (không tiết lộ Vạn Linh Phổ, chỉ "kiến thức tổ phụ")',
      'MC đặt tên nhóm "Tro Linh Phái" — informal label, đệ tử hào hứng',
      'Trưa: Hà Thúc bưng cơm cho MC, ngồi cạnh kể: "tổ phụ ngài ngày xưa cũng dạy đệ tử trẻ ở đây. Cảnh này giống lắm"',
      'MC cảm xúc nhẹ — tổ phụ link tăng. Hà Thúc đưa MC một vòng đeo cũ, "tổ phụ để lại, dặn trao cho người kế thừa thực sự"',
      'Vòng đeo: vật phẩm cấp B (Già Tâm cũng không biết), MC scan: "Vòng Linh Tinh — tăng 30% tốc độ thấu thị Vạn Linh Phổ"',
      'Chiều: em gái Cố Tiểu Đào xin chính thức học cùng MC. MC đồng ý — Tiểu Đào thành đệ tử công khai đầu tiên',
      'Tối: MC về phòng kín, đeo vòng, scan Lửa Tro — tốc độ HUD tăng rõ rệt',
    ],
    mcBenefit: 'Vòng Linh Tinh cấp B (vật phẩm + tăng skill 30%), Tro Linh Phái formed (network 11 đệ tử + em gái), tổ phụ link tăng từ Hà Thúc (manh mối + cảm xúc)',
    threadsAdvance: ['phục hưng gia tộc', 'Vạn Linh Phổ tuyến tiến hóa expand'],
    newThreads: ['Tro Linh Phái nhánh đệ tử riêng'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC trong phòng kín đeo vòng, scan pet — yên tĩnh tích cực.'],
  },
  // ─── Sub-arc 3 (ch.11-15): Giải đấu Vân Kiếm — first BIG WOW mass face-slap ─
  {
    n: 11, beat: 'setup',
    brief: 'Đêm trước giải đấu. MC tập luyện Lửa Tro lần cuối với 11 đệ tử (kín). Vân Kiếm khoa trương ở khu sinh hoạt — đám tùy tùng nịnh hót. Tiểu Đào lo lắng đến phòng MC, MC trấn an.',
    scenes: [
      'Sáng: MC + 11 đệ tử + em gái tập trong vườn hậu sơn — Lửa Tro vs pet Cố Khang (Tiểu Sói E), Lửa Tro thắng kìm chế',
      'Đệ tử trẻ thì thầm "Tro Bụi mạnh khủng khiếp", MC: "đây là kết quả feed đúng sequence, ai cũng làm được"',
      'Trưa: Vân Kiếm xuất hiện ở khu sinh hoạt với 5 tùy tùng, khoe Bạch Ngân Lang sắp giành giải vô địch — đám tùy tùng nịnh',
      'Chiều: Tiểu Đào đến phòng MC lo lắng "mai ca thua thì sao?" — MC trấn an "ca có pet bí mật" + xoa đầu',
      'Em gái: "ca ngoan" — chemistry ấm áp, thề nhau "ca bảo vệ em mãi"',
      'Tối: MC về phòng kín, Lửa Tro sẵn sàng. Hà Thúc canh ngoài',
    ],
    mcBenefit: 'pet Lửa Tro confirm chiến đấu được (skill validate), 11 đệ tử + em gái niềm tin (network + quan hệ), em gái relationship đỉnh',
    threadsAdvance: ['phục hưng gia tộc'],
    risks: [
      BAN_BASE,
      TONE_LAO_LUC,
      'END: MC + Lửa Tro trong phòng kín đêm yên tĩnh.',
      'CẤM nhắc "bản đồ", "chìa khóa", "vòng đeo" hoặc bất kỳ vật phẩm cấp B+ nào trong chương này — chương training thuần. Vật phẩm cấp cao reveal ở ch.10 (Vòng Linh Tinh đã có) hoặc ch.15+ (bản đồ Bắc Vực sau).',
      'KHÔNG giới thiệu resource/item mới ngoài: pet Lửa Tro, Tro Lửa Linh đã có, đệ tử Tro Linh Phái 11 người. CẤM kho di sản scene ở chương này.',
    ],
  },
  {
    n: 12, beat: 'breathing',
    brief: 'Sáng giải đấu vòng loại — vòng 1, MC bắt cặp với Cố Khang (đã theo MC). Cố Khang chủ động intentionally yếu để giúp MC ăn điểm sớm — MC ngầm cảm ơn nhưng vẫn show kỹ năng. Trưa: vòng 2, MC vs Cố Tử Vũ (đại bàng E peak) — Lửa Tro phun tia tro lửa, đại bàng giật mình rút.',
    scenes: [
      'Sáng: võ trường Cố tộc, 30 đệ tử + 8 trưởng lão dự khán. MC xuất hiện trong vỏ thiếu niên gầy yếu',
      'Vòng 1: MC vs Cố Khang. Cố Khang bí mật ra hiệu "tôi sẽ thua nhanh để huynh ăn điểm" — MC nhẹ gật',
      'Lửa Tro phun tro lửa nhỏ, Cố Khang rút trong 60 giây. Đám đệ tử trẻ vỗ tay',
      'Vòng 2: MC vs Cố Tử Vũ + đại bàng E peak. Đại bàng tấn công nhanh, Lửa Tro né + phun tro lửa',
      'Đại bàng giật mình rút, Cố Tử Vũ thừa nhận thua. Lửa Tro thắng cấp E peak — bystander bắt đầu shock thầm',
      'Trưa: nghỉ giải lao. Già Tâm đến chúc MC, "có cốt cách tổ phụ"',
      'Chiều: vòng 3 sắp tới — MC vs Cố Vân Kiếm + Bạch Ngân Lang D, trận cao trào',
    ],
    mcBenefit: 'thắng vòng 1+2 giải đấu (uy tín nội tộc), bystander đám đệ tử shock thầm (face-slap tier 1), Già Tâm khen công khai (quan hệ)',
    threadsAdvance: ['phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC chuẩn bị vòng 3 — yên tĩnh.'],
  },
  {
    n: 13, beat: 'big_wow',
    brief: 'BIG WOW MASS FACE-SLAP. Vòng 3: MC vs Cố Vân Kiếm + Bạch Ngân Lang D. Vân Kiếm tự tin khoa trương trước trận. Trận đấu: Lửa Tro kìm chế F+ (25% sức), tránh Vân Khí Phá, phun tro vào mắt Bạch Ngân Lang, bóp lăn trúng chân — Bạch Ngân Lang ngã trong 90 giây. Vân Kiếm câm họng tái mặt. 30 đệ tử + 8 trưởng lão SHOCK THẦM "slime cấp F không tên thắng cấp D?". Già Tâm khen công khai "Đại Sư Cố Lập Khải đã trở lại".',
    scenes: [
      'Sảnh đấu sửa, 30 đệ tử + 8 trưởng lão tập trung. Tiểu Đào đứng cạnh Hà Thúc lo lắng',
      'Vân Kiếm vào sảnh, Bạch Ngân Lang theo sau lông trắng bạc — đám tùy tùng vỗ tay',
      'Vân Kiếm khoa trương: "đại thiếu gia, slime của huynh có dám lên đài?" — MC bình thản gật, đặt Lửa Tro xuống đài',
      'Lửa Tro hình dạng slime tro xám đỏ, đám đệ tử cười khẽ "đây là pet?". MC ra lệnh "kìm chế 25% — show cấp F+"',
      'Bạch Ngân Lang lao ra Vân Khí Phá tốc độ + dao gió — Lửa Tro né nhanh, phun tia tro lửa nhỏ vào mắt Bạch Ngân Lang',
      'Bạch Ngân Lang giật mình mất hướng. Vân Kiếm hét "không!" — Lửa Tro bóp lại quả cầu, lăn nhẹ qua trúng chân Bạch Ngân Lang. Bạch Ngân Lang kêu thảm, ngã',
      'BIG WOW: 30 đệ tử + 8 trưởng lão SHOCK THẦM. Vân Kiếm câm họng tái mặt, đám tùy tùng cúi đầu.',
      'Già Tâm đứng dậy: "có cốt cách tổ phụ — Đại Sư Cố Lập Khải đã trở lại?" — công khai khen',
      'Cố Trường Lệ (phe biển thủ) tái mặt, internal "thằng nhóc này không thể coi thường". Cố Trường Khải mặt sa sầm',
      'MC vỏ "may mắn, slime hơi đặc biệt thôi" — public face thiếu niên may mắn',
    ],
    mcBenefit: 'thắng giải đấu vòng 3 (uy tín nội tộc lớn), face-slap Vân Kiếm + đám đệ tử mass (face-slap tier 2), Già Tâm khen công khai (quan hệ + tổ phụ link), Cố Trường Lệ tái mặt (đột phá quyền lực)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    threadsResolve: ['Vân Kiếm thách giải đấu'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene Già Tâm khen + đám đệ tử shock — KHÔNG cliffhanger paranoia.'],
  },
  {
    n: 14, beat: 'resolution',
    brief: 'Sau big wow. MC nhận tiền thưởng 30 đồng + 5 viên Hồi Khí Đan. Đám đệ tử trẻ + 5 đệ tử khác đến hỏi MC bí quyết. MC deflect "thiên phú slime". Cố Già Tâm dẫn MC vào kho di sản phần niêm phong (sub-arc payoff): được vào phần sâu hơn, nhận thêm 200g Linh Mạch + sách kỹ năng cấp D.',
    scenes: [
      'Sáng sau giải đấu, MC nhận tiền thưởng 30 đồng + 5 viên Hồi Khí Đan từ ban tổ chức Cố tộc',
      'Đám đệ tử trẻ + 5 đệ tử khác trước đây không quen đến hỏi MC bí quyết — MC deflect "thiên phú slime, sách tổ phụ"',
      '10 đệ tử mới chuyển hướng theo MC — Tro Linh Phái expand → 21 đệ tử',
      'Trưa: Cố Già Tâm gặp MC riêng, thấp giọng: "cháu thắng giải đấu cho thấy năng lực thực sự. Ta dẫn cháu vào phần niêm phong sâu hơn của kho di sản"',
      'Chiều: MC + Già Tâm vào kho di sản phần sâu hơn — kệ kín mít, Già Tâm mở 1 cửa nội bộ',
      'MC nhận: 200g Linh Mạch + sách kỹ năng cấp D "Linh Tinh Đoạt Thiên Đan Phương" + 1 viên Phượng Linh Đan (vật phẩm cấp C)',
      'Già Tâm: "phần này tổ phụ chỉ định trao cho người kế thừa. Ta giúp cháu chuẩn bị đoạt trưởng tộc"',
      'Tối: MC về phòng kín, scan Vạn Linh Phổ với Phượng Linh Đan — viên này có thể giúp Tro Bụi tăng tốc tiến hóa Phượng Linh C đáng kể',
    ],
    mcBenefit: 'tiền thưởng 30 đồng + 5 viên Hồi Khí Đan + 200g Linh Mạch + sách Linh Tinh Đoạt Thiên Đan Phương + 1 viên Phượng Linh Đan (tài nguyên + skill book + vật phẩm cấp C), 10 đệ tử mới (network → Tro Linh Phái 21 thành viên), Già Tâm dẫn vào phần niêm phong (đột phá quan hệ)',
    threadsAdvance: ['phục hưng gia tộc', 'Vạn Linh Phổ tuyến tiến hóa expand'],
    threadsResolve: ['kho di sản tạm thời mở'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC scan Phượng Linh Đan trong phòng kín — yên tĩnh tích cực.'],
  },
  {
    n: 15, beat: 'breathing',
    brief: 'BREATHING. MC tổ chức Tro Linh Phái buổi đầu chính thức — 21 đệ tử + em gái. Dạy basic feed sequence + sharing kiến thức tổ phụ. Cố Vân Kiếm đến vườn quan sát từ xa, nội tâm dao động (redemption seed). Hà Thúc kể chuyện đêm bố Cố Hành ra Bắc Vực — manh mối arc 4 plant.',
    scenes: [
      'Sáng: MC tổ chức Tro Linh Phái buổi đầu chính thức ở vườn hậu sơn',
      '21 đệ tử + Tiểu Đào tham gia — MC dạy basic feed sequence + 5 nguyên tắc nuôi pet (không dùng Vạn Linh Phổ trực tiếp, chỉ "kiến thức tổ phụ")',
      'Đệ tử Cố Khang xin làm trưởng nhánh — MC: "ta cần 3 trưởng nhánh, Khang là 1, sẽ chọn 2 khác sau"',
      'Trưa: Cố Vân Kiếm đến vườn quan sát từ xa, không vào. Nội tâm "huynh ấy thay đổi rồi... mình thua một cách hợp lý"',
      'Chiều: MC dạy em gái Tiểu Đào kiến thức nâng cao về thuộc tính lôi hệ + hỏa hệ',
      'Hà Thúc gặp MC sau buổi học, kể: "đêm trước khi bố ngài ra Bắc Vực, ông ấy có dặn dò tôi giữ một thứ — đây" — đưa MC một mảnh bản đồ Bắc Vực cũ',
      'MC scan bản đồ — thấy ký hiệu "di tích cổ" + "cánh cửa" (manh mối arc 4)',
      'Tối: MC ghi vào sổ "bản đồ bố để lại — Bắc Vực có di tích cổ + cánh cửa. Liên kết với Vạn Linh Phổ?"',
    ],
    mcBenefit: 'Tro Linh Phái chính thức (network institutional), Cố Khang trưởng nhánh (network leadership), Vân Kiếm redemption seed (đối thủ chuyển), bản đồ Bắc Vực bố để lại (manh mối arc 4)',
    threadsAdvance: ['phục hưng gia tộc', 'bố Cố Hành Bắc Vực mất tích'],
    newThreads: ['di tích cổ Bắc Vực', 'cánh cửa Vạn Linh Phổ'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC ghi sổ trong phòng — yên tĩnh tích cực, KHÔNG paranoia.'],
  },
  // ─── Sub-arc 4 (ch.16-20): Bằng chứng Cố Trường Lệ biển thủ ─────────────
  {
    n: 16, beat: 'setup',
    brief: 'MC + Hà Thúc bí mật investigate kho lưu trữ chính + sổ giao dịch — phát hiện Cố Trường Lệ đã bán 3 pet quý của tổ phụ cho thương nhân Vương thị. Hà Thúc có sổ đối chiếu cũ — chứng cứ. Bí mật chuẩn bị bẫy hội đồng.',
    scenes: [
      'Đêm: MC + Hà Thúc lén vào kho lưu trữ chính (Cố Khiếu hiện đang bị giảm uy thế nên không canh kỹ)',
      'Hà Thúc đem sổ ghi 5 năm qua — đối chiếu với inventory hiện tại',
      'Phát hiện: 3 pet quý cấp B của tổ phụ (Lưu Vân Hổ, Hồng Ngân Tước, Bạch Linh Mãng) thiếu — last seen có chữ ký Cố Trường Lệ',
      'Hà Thúc: "tôi giữ sổ đối chiếu cũ, có manh mối Trường Lệ bán cho Vương thị" — đưa MC sổ cũ',
      'MC scan: chứng cứ rõ — Trường Lệ đã bán 3 pet cấp B, kiếm 5000 linh thạch riêng. Đây là leverage cực lớn',
      'MC + Hà Thúc lên kế hoạch: tuần sau cuộc họp trưởng lão, sẽ đem chứng cứ ra công khai',
      'Sáng: MC trở về phòng kín, viết kế hoạch face-slap Trường Lệ vào sổ',
    ],
    mcBenefit: 'chứng cứ biển thủ Trường Lệ (3 pet B + 5000 linh thạch) (manh mối + leverage cực lớn), sổ đối chiếu Hà Thúc (vật phẩm chứng cứ), kế hoạch face-slap hội đồng (setup-payoff)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    newThreads: ['Cố Trường Lệ biển thủ 3 pet B'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC viết kế hoạch trong phòng kín đêm.'],
  },
  {
    n: 17, beat: 'breathing',
    brief: 'BREATHING. MC dạy Tro Linh Phái về kỹ năng phối hợp pet (group combat). Cố Khang trưởng nhánh — chọn thêm 2 trưởng nhánh khác. Tiểu Đào lần đầu thấy Vân Kiếm và bắt đầu nói chuyện với Vân Kiếm (chuẩn bị seed redemption arc 2).',
    scenes: [
      'Sáng: Tro Linh Phái buổi 2 — MC dạy phối hợp pet group (2-3 pet cùng combat)',
      'Cố Khang dẫn 7 đệ tử nhánh A, MC chọn thêm Cố Tử Vũ làm trưởng nhánh B (7 đệ tử), Cố Lan Nhi làm trưởng nhánh C (7 đệ tử)',
      '3 nhánh × 7 = 21 đệ tử + em gái + MC = 23 thành viên',
      'Trưa: Tiểu Đào ra sân chính, gặp Vân Kiếm. Tiểu Đào hồn nhiên: "huynh ấy không xấu đâu, em thấy huynh thua công bằng"',
      'Vân Kiếm im lặng vài giây, gật nhẹ "ta biết" — đi mất. Internal: redemption seed',
      'Chiều: MC trao đổi với Già Tâm về cuộc họp trưởng lão tuần sau — Già Tâm đồng ý sẽ ủng hộ MC khi cần',
      'Tối: MC về phòng kín, feed Lửa Tro thêm — Lửa Tro tiến độ Phượng Linh tăng 5% (path arc 2)',
    ],
    mcBenefit: '3 nhánh Tro Linh Phái formal (network institutional 23 thành viên), Vân Kiếm redemption seed advance, Già Tâm pre-commit ủng hộ cuộc họp tuần sau (quan hệ)',
    threadsAdvance: ['phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC + Lửa Tro tiến triển feed.'],
  },
  {
    n: 18, beat: 'confront',
    brief: 'Cuộc họp trưởng lão tuần này — Cố Khiếu vẫn dự dù mất uy tín. Cố Trường Khải mở đầu, đề xuất MC ký giấy "tạm hoãn thừa kế" 3 tháng. MC từ chối nhẹ nhàng. Cuộc họp căng thẳng, Cố Khiếu lại tung 1 cáo buộc nhỏ — Trường Khải bực vì timing kém, Khiếu bị Trường Khải nháy mắt im đi.',
    scenes: [
      'Sáng cuộc họp trưởng lão — Cố Trường Khải mở đầu',
      'Trường Khải: "thiếu gia, gia tộc đang khó khăn. Tạm hoãn thừa kế 3 tháng để tổ chức lại. Ngài ký?" — đưa giấy',
      'MC bình tĩnh: "tôi nghĩ tạm hoãn không cần thiết. Tôi đã 16 tuổi, đủ tuổi nhận thừa kế theo gia phả"',
      'Trường Khải: "nhưng tu vi ngài còn yếu" — MC: "tu vi và thừa kế là 2 việc. Theo gia pháp, thừa kế chỉ cần đủ tuổi và năng lực ngự thú cơ bản"',
      'Cố Khiếu nháy mắt với Trường Khải, định tung cáo buộc — Trường Khải nháy mắt im đi (timing kém)',
      'Già Tâm phát biểu: "thiếu gia thắng giải đấu vừa qua, năng lực ngự thú đã chứng minh. Tôi ủng hộ giữ thừa kế hợp pháp"',
      'Trường Khải im lặng vài giây, mất thế: "thôi, để cuộc họp sau bàn tiếp" — chuyển chủ đề',
      'Chiều: MC + Hà Thúc về phòng kín, Hà Thúc thì thầm "Trường Khải đang chuẩn bị đòn lớn hơn — Khiếu chỉ là quân cờ"',
    ],
    mcBenefit: 'từ chối tạm hoãn thừa kế thành công (uy tín lớn), Già Tâm công khai ủng hộ thừa kế (quan hệ), Trường Khải mất thế tiếp (đột phá quyền lực), manh mối Trường Khải đang chuẩn bị đòn lớn (thông tin)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Hà Thúc thảo luận thông tin — KHÔNG paranoia, MC tự tin.'],
  },
  {
    n: 19, beat: 'big_wow',
    brief: 'BIG WOW. Cuộc họp trưởng lão tiếp tuần sau, MC chủ động mở chứng cứ Trường Lệ biển thủ 3 pet B. Đem sổ đối chiếu Hà Thúc + bằng chứng giao dịch Vương thị. Trường Lệ tái mặt câm họng. Hội đồng SỐC. Già Tâm: "yêu cầu Trường Lệ rút khỏi hội đồng + bồi hoàn 5000 linh thạch + 3 pet". Trường Khải mất 1 ally cứng.',
    scenes: [
      'Sáng cuộc họp tiếp — MC chủ động xin phép phát biểu',
      'MC: "tôi muốn báo cáo việc kiểm kê kho gia tộc — phát hiện 3 pet quý của tổ phụ thiếu 5 năm qua"',
      'Trường Khải bực: "thiếu gia, không phận sự" — MC: "đây là tài sản gia tộc, tôi là trưởng tôn có quyền kiểm tra"',
      'MC đưa sổ đối chiếu Hà Thúc + bằng chứng giao dịch Vương thị, chỉ rõ chữ ký Trường Lệ',
      'Trường Lệ tái mặt câm họng "đó là... tu luyện..."',
      'MC: "3 pet B này last seen có chữ ký ngài. Sổ Vương thị ghi rõ ngài bán 5000 linh thạch"',
      'Hội đồng SỐC. Trường Khải mặt sa sầm "đây là chuyện riêng Trường Lệ, không liên quan tôi"',
      'Già Tâm: "đây là biển thủ tài sản gia tộc. Yêu cầu Trường Lệ rút hội đồng + bồi hoàn 5000 linh thạch + 3 pet thay thế cấp B"',
      'Các trưởng lão khác đồng ý. Trường Lệ đứng dậy run rẩy, "tôi... tôi sẽ bồi hoàn" — rút khỏi hội đồng. Trường Khải mất 1 ally cứng',
      'MC vỏ "tôi chỉ làm việc đúng với gia tộc thôi" — public face thiếu niên ngay thẳng',
    ],
    mcBenefit: 'Trường Lệ rút hội đồng + bồi hoàn 5000 linh thạch + 3 pet B (tài nguyên cực lớn), Trường Khải mất 1 ally cứng (đột phá quyền lực), uy tín hội đồng tăng (uy tín)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    threadsResolve: ['Cố Trường Lệ biển thủ 3 pet B'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene MC ngồi yên, hội đồng vẫn đang xôn xao về Trường Lệ.'],
  },
  {
    n: 20, beat: 'resolution',
    brief: 'RESOLUTION + BREATHING. Trường Lệ rút khỏi hội đồng. MC nhận 5000 linh thạch + 3 pet B (Lưu Vân Hổ, Hồng Ngân Tước, Bạch Linh Mãng) trở về Cố tộc. Tro Linh Phái vui mừng. MC scan 3 pet — pet thứ 4 sẽ acquired là Cơ Niệm (mech bug đường phố ch.21+ planned).',
    scenes: [
      'Sáng: Trường Lệ chính thức rút hội đồng + chuyển 5000 linh thạch + 3 pet B về Cố tộc',
      'Hà Thúc + Tro Linh Phái 23 thành viên đón nhận tài sản — vui mừng',
      'MC scan 3 pet B (Lưu Vân Hổ, Hồng Ngân Tước, Bạch Linh Mãng) — Vạn Linh Phổ show tuyến tiến hóa của từng pet',
      '3 pet này MC để cho 3 trưởng nhánh Tro Linh Phái sử dụng — Cố Khang nhận Lưu Vân Hổ, Cố Tử Vũ nhận Hồng Ngân Tước, Cố Lan Nhi nhận Bạch Linh Mãng',
      'Đệ tử trẻ chấn động "thiếu gia trao pet B cho nhánh trưởng?" — MC: "tài sản gia tộc, dùng đúng người"',
      'Trưa: MC nhận 5000 linh thạch — chia 1500 cho Tro Linh Phái + 3500 giữ làm vốn riêng',
      'Chiều: Hà Thúc kể MC kế hoạch của Trường Khải lớn hơn — sẽ tung Vương thị (tiểu tộc cùng cấp) vào tuần sau',
      'Tối: MC về phòng kín, đặt 3500 linh thạch vào hộc bí mật, scan Vạn Linh Phổ với Lửa Tro — Lửa Tro tiến triển ổn, Phượng Linh Đan đã chuẩn bị sẵn cho ch.40+',
    ],
    mcBenefit: '5000 linh thạch + 3 pet B (3500 giữ + 1500 chia cho nhánh) (tài nguyên cực lớn), Tro Linh Phái 3 trưởng nhánh có pet B (network upgrade), uy tín nhánh trưởng (quan hệ), manh mối Trường Khải sắp tung Vương thị (thông tin)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    newThreads: ['Vương thị tiểu tộc sắp tham chiến'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Lửa Tro phòng kín đêm yên tĩnh.'],
  },
  // ─── Sub-arc 5 (ch.21-25): Acquire Cơ Niệm + face-slap Cố Khiếu ──────────
  {
    n: 21, beat: 'setup',
    brief: 'MC ra chợ Linh Châu Thành tìm pet thứ 2 — Vạn Linh Phổ scan pet đường phố. Phát hiện Cơ Niệm (mech bug cấp E, "côn trùng cơ giới rẻ tiền") ở sạp lão thợ thủ công. Tuyến tiến hóa: Cơ Khí Vũ Sĩ D → Thần Thuật Cơ Sư B → Cơ Giới Thần Sứ S. MC mua giá 50 đồng (rẻ).',
    scenes: [
      'Sáng: MC khoác áo choàng cũ, ra chợ Linh Châu (cùng kiểu ch.2)',
      'Đi đến khu pet đường phố — sạp lão thợ thủ công bán "côn trùng cơ giới" giá rẻ',
      'MC scan Vạn Linh Phổ với 3 con bug khác nhau — chỉ Cơ Niệm có tuyến tiến hóa cao',
      'HUD: 【Cơ Niệm — Mech Bug Cấp E】Tuyến tiến hóa: Mech Bug E → Cơ Khí Vũ Sĩ D → Thần Thuật Cơ Sư B → Cơ Giới Thần Sứ S → Cơ Giới Thiên Đế. Feed: 100g Cơ Linh Tinh + 5 viên Linh Đan + 1 lõi Yêu Thú E',
      'MC hỏi giá lão thợ "50 đồng một con" — MC trả 50 đồng (mua rẻ), bao Cơ Niệm vào túi',
      'Trưa: về Cố tộc, MC giấu Cơ Niệm trong phòng kín cùng Lửa Tro',
      'Chiều: MC + Hà Thúc thảo luận chuẩn bị cho Vương thị tham chiến tuần sau',
    ],
    mcBenefit: 'Cơ Niệm pet thứ 2 (vật phẩm, pet portfolio expand), tuyến tiến hóa Cơ Niệm (manh mối + skill), kinh nghiệm thị trường pet (kinh nghiệm)',
    threadsAdvance: ['Vạn Linh Phổ tuyến tiến hóa expand', 'phục hưng gia tộc'],
    newThreads: ['Cơ Niệm pet thứ 2'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 2 pet (Lửa Tro + Cơ Niệm) trong phòng kín — yên tĩnh tích cực.'],
  },
  {
    n: 22, beat: 'breathing',
    brief: 'BREATHING. MC bí mật feed Cơ Niệm — bắt đầu sequence Cơ Khí Vũ Sĩ D (cần 100g Cơ Linh Tinh — MC chưa có, sẽ mua từ kho gia tộc tới 1 phần). Tro Linh Phái buổi 3 — MC dạy 23 đệ tử kỹ năng đặc biệt. Em gái Cố Tiểu Đào lần đầu thử khế ước với pet F của Cố Khang (Tiểu Sói).',
    scenes: [
      'Sáng: MC scan Cơ Niệm thêm — confirm cần 100g Cơ Linh Tinh + 5 viên Linh Đan',
      'MC vào kho gia tộc (hợp pháp, vì là trưởng tôn) — lấy 50g Cơ Linh Tinh từ tài nguyên Trường Lệ bồi hoàn + 5 viên Linh Đan từ tài nguyên gia tộc',
      'Trưa: Tro Linh Phái buổi 3 — MC dạy 23 đệ tử kỹ năng "feed counter" (cách phá feed sequence của đối thủ)',
      'Đệ tử Cố Khang ngạc nhiên: "thiếu gia có thể nhìn ra cách phá feed?" — MC: "đây là kỹ năng tổ phụ, tôi sẽ dạy"',
      'Chiều: Tiểu Đào lần đầu thử khế ước với pet F của Cố Khang (Tiểu Sói) — không thành công vì Tiểu Sói đã có chủ',
      'MC khuyến khích em "không sao, tuần sau ca tìm pet F miễn phí cho em" — em gái háo hức',
      'Tối: MC bắt đầu feed Cơ Niệm trong phòng kín. Cơ Niệm tiến độ Cơ Khí Vũ Sĩ D: 5%',
    ],
    mcBenefit: 'Cơ Niệm bắt đầu feed (pet stage advance), 50g Cơ Linh Tinh + 5 viên Linh Đan từ kho hợp pháp (tài nguyên), 23 đệ tử kỹ năng feed counter (skill teaching expand), em gái háo hức về pet đầu (quan hệ)',
    threadsAdvance: ['phục hưng gia tộc', 'Vạn Linh Phổ tuyến tiến hóa expand'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC feed Cơ Niệm yên tĩnh, em gái háo hức.'],
  },
  {
    n: 23, beat: 'confront',
    brief: 'Cố Khiếu vẫn dự hội đồng dù mất uy tín, tổ chức 1 đợt tấn công cuối — cáo buộc MC "đột nhập kho gia tộc" tối qua (thực ra MC vào hợp pháp). Già Tâm + Hà Thúc xác nhận MC vào hợp pháp với danh phận trưởng tôn. Khiếu mất mặt thêm. Hội đồng đề xuất Khiếu "nghỉ tạm thời".',
    scenes: [
      'Sáng cuộc họp trưởng lão — Cố Khiếu mở đầu cáo buộc MC đột nhập kho',
      'Khiếu: "thiếu gia tối qua vào kho lấy nguyên liệu — đây là vi phạm gia pháp"',
      'MC bình tĩnh: "tôi là trưởng tôn, có quyền dùng tài nguyên gia tộc cho việc tu luyện. Hơn nữa, tôi đã sign sổ với Hà Thúc"',
      'Hà Thúc đưa sổ ký nhận: "thiếu gia ký 50g Cơ Linh Tinh + 5 viên Linh Đan, hợp pháp"',
      'Già Tâm: "thiếu gia là trưởng tôn, có quyền dùng tài nguyên cho tu luyện. Khiếu cáo buộc sai lần thứ 2 trong tháng"',
      'Hội đồng đồng ý: Khiếu "nghỉ tạm thời 1 tháng" để tự kiểm điểm',
      'Trường Khải mặt sa sầm — mất 2 ally cứng (Trường Lệ + Khiếu) trong 3 tuần',
      'Chiều: Khiếu rời hội đồng, internal "thằng nhóc này không đơn giản. Phải báo Trường Khải đẩy mạnh kế hoạch Vương thị"',
      'Tối: Hà Thúc thì thầm với MC "Khiếu đi, Trường Khải sẽ tung Vương thị sớm hơn — chuẩn bị"',
    ],
    mcBenefit: 'Cố Khiếu nghỉ hội đồng 1 tháng (face-slap đối thủ + đột phá quyền lực), Trường Khải mất 2 ally cứng (Trường Lệ + Khiếu) (đột phá quyền lực lớn), manh mối Vương thị sắp tung sớm (thông tin)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Hà Thúc thảo luận chuẩn bị Vương thị — KHÔNG paranoia, MC tự tin.'],
  },
  {
    n: 24, beat: 'big_wow',
    brief: 'BIG WOW. Cơ Niệm evolve thành công Cơ Khí Vũ Sĩ D — pet thứ 2 cấp D. MC test trong phòng kín — Cơ Khí Vũ Sĩ có kỹ năng "Cơ Khí Phun" + "Hệ Thống Linh Lực Tự Động". MC giấu cấp thật, public sẽ show cấp E.',
    scenes: [
      'Sáng ngày 5 feed sequence: Cơ Niệm tiến độ 80%',
      'Trưa: MC bổ sung 50g Cơ Linh Tinh cuối cùng (mua thêm từ chợ chiều hôm trước với 30 đồng)',
      'Chiều: Cơ Niệm hấp thụ — vỏ ngoài kim loại bóng loáng dần',
      'Tối: ánh sáng vàng kim bùng lên trong phòng kín — Cơ Niệm evolve thành Cơ Khí Vũ Sĩ Cấp D',
      'MC scan: 【Cơ Khí Vũ Sĩ D】Sức mạnh: 25, Nhanh: 18, Thể: 30, Linh: 20. Kỹ năng: Cơ Khí Phun (tia kim loại + nhiệt) + Hệ Thống Linh Lực Tự Động (auto-recharge)',
      'MC test: Cơ Khí Vũ Sĩ phun tia kim loại, làm cháy tường gỗ. MC dạy "kìm chế cấp E khi public — chỉ phun tia mỏng"',
      'Hà Thúc đến báo: "Vương thị đại biểu sắp đến Cố tộc tuần sau" — MC gật, "Cơ Khí Vũ Sĩ vừa kịp"',
      'Internal MC: "2 pet cấp D + B (Lửa Tro Phượng Linh path) — đủ đối phó tiểu tộc"',
    ],
    mcBenefit: 'Cơ Niệm evolve Cơ Khí Vũ Sĩ D (đột phá pet level, pet thứ 2 cấp D), pet portfolio Lửa Tro E + Cơ Khí Vũ Sĩ D (skill expand), kế hoạch đối phó Vương thị (setup-payoff)',
    threadsAdvance: ['Vạn Linh Phổ tuyến tiến hóa expand', 'Vương thị tiểu tộc sắp tham chiến'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 2 pet evolve trong phòng kín — yên tĩnh tích cực.'],
  },
  {
    n: 25, beat: 'resolution',
    brief: 'BREATHING + RESOLUTION sub-arc 5. MC tổ chức Tro Linh Phái buổi 4 — dạy đệ tử về kỹ năng phối hợp 2 pet (Lửa Tro + Cơ Khí Vũ Sĩ trong phòng kín, demo nhỏ ở sân với 2 pet F của đệ tử). Em gái Tiểu Đào nhận 1 pet F từ MC — Tiểu Mèo.',
    scenes: [
      'Sáng: MC tặng em gái Tiểu Đào 1 pet F (Tiểu Mèo Linh) mua từ chợ — em gái háo hức nhận, khế ước thành công',
      'Tiểu Đào ôm Tiểu Mèo, vui mừng: "ca cảm ơn ca ơi!" — chemistry đỉnh',
      'Trưa: Tro Linh Phái buổi 4 — MC dạy 23 đệ tử kỹ năng phối hợp 2 pet (group combat)',
      'Demo nhỏ: 2 đệ tử Cố Khang + Cố Tử Vũ phối hợp Tiểu Sói + Hồng Ngân Tước (pet B mới)',
      'Đám đệ tử ngạc nhiên: "thiếu gia, sao biết nhiều thế?" — MC deflect "kiến thức tổ phụ + thiên phú"',
      'Chiều: Vân Kiếm đến vườn xa quan sát — internal "huynh ấy thực sự khác. Mình thua không oan"',
      'Vân Kiếm bước đến gần MC, cúi đầu: "huynh, tôi xin lỗi vì thái độ trước. Xin huynh chỉ giáo"',
      'MC bất ngờ nhẹ — Vân Kiếm redemption arc start formal. MC: "không cần xin lỗi. Cùng nhau phục hưng gia tộc"',
      'Tối: MC về phòng kín, scan Lửa Tro + Cơ Khí Vũ Sĩ — pet portfolio bí mật mạnh, sẵn sàng Vương thị',
    ],
    mcBenefit: 'em gái Tiểu Đào có pet đầu (quan hệ + bảo vệ family), Tro Linh Phái kỹ năng phối hợp (skill expand), Vân Kiếm redemption formal start (đối thủ chuyển đồng minh — đột phá quan hệ lớn), 2 pet portfolio mạnh sẵn sàng Vương thị',
    threadsAdvance: ['phục hưng gia tộc'],
    threadsResolve: ['Vân Kiếm rival chuyển đồng minh'],
    newThreads: ['em gái Tiểu Đào pet đầu Tiểu Mèo Linh'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 2 pet phòng kín đêm — sẵn sàng Vương thị.'],
  },
  // ─── Sub-arc 6 (ch.26-30): Activate Lục Vũ + Tro Bụi → Phượng Linh C path ─
  {
    n: 26, beat: 'setup',
    brief: 'Sáng: MC ra vườn nhà, lần đầu chính thức observe Lục Vũ (sparrow đã có từ ch.1). Vạn Linh Phổ show tuyến tiến hóa Phong: Sparrow F → Phong Yến E → Phong Linh C → ... → Cuồng Phong Tổ Thần SS. MC khế ước Lục Vũ — pet thứ 3.',
    scenes: [
      'Sáng: MC ra vườn cây bồ đề, ngồi yên — Lục Vũ (sparrow) đậu trên cành, đã hồi phục từ ch.1',
      'MC scan kỹ Lục Vũ — HUD: 【Lục Vũ Tước Cấp F】Sức: 3, Nhanh: 8, Thể: 2, Linh: 1. Tuyến: Sparrow F → Phong Yến E → Phong Linh C → Phong Linh Vương B → Bão Phong Đại Đế S → Cuồng Phong Tổ Thần SS',
      'Feed Tuyến E: 50g Linh Mạch + 2 viên Nhất Phẩm Hồi Khí Đan, 5 ngày, rủi ro 20%',
      'MC giơ tay, thì thầm "ngươi sẽ cùng ta phục hưng gia tộc" — Lục Vũ đậu trên tay MC, khế ước thành công',
      'MC: "ngươi sẽ là pet thứ 3" — Lục Vũ kêu nhẹ',
      'Trưa: MC tổ chức kho riêng + chuẩn bị feed Lục Vũ song song Tro Bụi đang feed Phượng Linh C',
      'Chiều: Hà Thúc báo Vương thị đại biểu sẽ đến trong 3 ngày — MC gật, lên kế hoạch chuẩn bị',
    ],
    mcBenefit: 'Lục Vũ pet thứ 3 acquired (vật phẩm + pet portfolio expand), tuyến Phong tier (manh mối + skill), kế hoạch chuẩn bị Vương thị (setup)',
    threadsAdvance: ['Vạn Linh Phổ tuyến tiến hóa expand', 'phục hưng gia tộc'],
    newThreads: ['Lục Vũ pet thứ 3 — tuyến Phong'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet trong phòng kín đêm.'],
  },
  {
    n: 27, beat: 'breathing',
    brief: 'BREATHING. MC + Vân Kiếm cùng dạy Tro Linh Phái — Vân Kiếm chính thức tham gia. Em gái Tiểu Đào tập feed Tiểu Mèo. Hà Thúc kể chuyện kiếp trước tổ phụ ở Bắc Vực — manh mối arc 4 plant thêm.',
    scenes: [
      'Sáng: Tro Linh Phái buổi 5 — Vân Kiếm chính thức tham gia, dạy đệ tử kỹ năng Phong hệ',
      'Vân Kiếm khiêm tốn: "tôi sai trước đây. Cùng nhau phục hưng gia tộc"',
      '23 đệ tử + Vân Kiếm + em gái = 25 thành viên Tro Linh Phái',
      'Trưa: Tiểu Đào tập feed Tiểu Mèo Linh, em gái có thiên phú nhẹ — pet response tốt',
      'Chiều: Hà Thúc kể MC chuyện kiếp trước tổ phụ ở Bắc Vực — "tổ phụ ngài 50 năm trước có một chuyến đi Bắc Vực 3 tháng, sau đó về với một số vật phẩm cổ"',
      'MC ghi nhớ — manh mối arc 4 thêm. "Vạn Linh Phổ có liên kết với Bắc Vực?"',
      'Tối: MC feed Lục Vũ tiến độ 20%, Tro Bụi Phượng Linh C tiến độ 40%',
    ],
    mcBenefit: 'Vân Kiếm chính thức tham gia Tro Linh Phái (quan hệ + network), em gái Tiểu Đào talent feed lộ (manh mối future), manh mối tổ phụ Bắc Vực 50 năm trước (thông tin)',
    threadsAdvance: ['phục hưng gia tộc', 'di tích cổ Bắc Vực', 'cánh cửa Vạn Linh Phổ'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín đêm — feed yên tĩnh.'],
  },
  {
    n: 28, beat: 'confront',
    brief: 'Vương thị đại biểu (3 người) đến Cố tộc — gặp Trường Khải + MC. Vương thị chủ tịch (cấp Sơ Cấp peak) khoa trương, đề xuất "hợp tác kinh tế" thực ra là ép Cố tộc bán tài nguyên rẻ. MC từ chối lịch sự, đề xuất "trao đổi công bằng theo giá thị trường". Vương thị bực, ra về nhưng không tuyên chiến công khai.',
    scenes: [
      'Sáng: Vương thị đại biểu 3 người đến Cố tộc — chủ tịch Vương Đại Hoàng (Sơ Cấp peak) + 2 trưởng lão',
      'Trường Khải đón tiếp ấm áp, mời MC ra chứng kiến (cố lừa MC ký hợp đồng bất lợi)',
      'Vương Đại Hoàng đề xuất: "Vương thị mua linh thạch + pet B từ Cố tộc với giá ưu đãi — 60% giá thị trường"',
      'MC bình tĩnh: "60% là quá thấp. Theo giá thị trường, tôi không thể đồng ý"',
      'Trường Khải nháy mắt MC: "thiếu gia, đây là cơ hội tốt..." — MC ngắt: "tôi là trưởng tôn, quyết định thuộc về tôi"',
      'MC đề xuất: "Vương thị mua giá thị trường 100% — tôi sẵn sàng. Hoặc trao đổi tài nguyên + pet công bằng"',
      'Vương Đại Hoàng bực, không tuyên chiến công khai: "thôi, để bàn lại" — ra về',
      'Trường Khải sa sầm: "thiếu gia, ngài làm hỏng cơ hội!" — MC: "đây không phải cơ hội, là bóc lột"',
      'Chiều: Già Tâm gặp MC, "cháu xử lý tốt. Vương thị sẽ tung đòn lớn hơn — chuẩn bị"',
    ],
    mcBenefit: 'từ chối hợp đồng Vương thị bất lợi (uy tín nội tộc + đột phá quyền lực), Trường Khải mất 1 cơ hội ép MC (đột phá quyền lực), Già Tâm khen + cảnh báo Vương thị tung đòn lớn (quan hệ + thông tin)',
    threadsAdvance: ['Vương thị tiểu tộc sắp tham chiến', 'phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Già Tâm thảo luận chuẩn bị — KHÔNG paranoia.'],
  },
  {
    n: 29, beat: 'big_wow',
    brief: 'BIG WOW. Vương thị tổ chức "giải đấu liên tộc Linh Châu" — mời 5 tiểu tộc + Cố tộc tham gia. MC + Tro Linh Phái + Vân Kiếm + 3 trưởng nhánh tham gia. Vòng đầu: Cố tộc đại biểu thắng 4/5 trận — Lửa Tro kìm chế F+, Cơ Khí Vũ Sĩ kìm chế E+, Lục Vũ feed dở vẫn chưa tham gia. Mass face-slap Vương thị.',
    scenes: [
      'Sáng: giải đấu liên tộc Linh Châu tại quảng trường thành — 6 tiểu tộc tham gia, mỗi tộc 5 đại biểu',
      'Cố tộc đại biểu: MC (Lửa Tro), Vân Kiếm (Bạch Ngân Lang), Cố Khang (Lưu Vân Hổ), Cố Tử Vũ (Hồng Ngân Tước), Cố Lan Nhi (Bạch Linh Mãng)',
      'Vòng 1: Cố Khang vs Vương thị đại biểu (pet D) — Lưu Vân Hổ thắng nhanh',
      'Vòng 2: Cố Tử Vũ vs Lý thị đại biểu — Hồng Ngân Tước thắng',
      'Vòng 3: Cố Lan Nhi vs Hoàng thị đại biểu — Bạch Linh Mãng thắng',
      'Vòng 4: Vân Kiếm vs Trầm thị đại biểu — Bạch Ngân Lang thắng',
      'Vòng 5: MC vs Vương Đại Hoàng (chủ tịch Vương thị, Sơ Cấp peak với pet C)',
      'BIG WOW: MC ra lệnh Lửa Tro kìm chế F+ (25% sức) — Lửa Tro phun tro vào pet C của Vương Đại Hoàng, pet C giật mình. Lửa Tro thừa cơ hội bóp lăn — pet C ngã. Vương Đại Hoàng câm họng, đám đệ tử Vương thị shock thầm "slime cấp F thắng pet C?"',
      'Cố tộc thắng 5/5 vòng — quảng trường rộn ràng. Trường Khải mặt sa sầm, Vương Đại Hoàng tái mặt',
      'Cố tộc nhận 5000 linh thạch + 3 pet B + 5 pet C + 1 sách kỹ năng cấp B "Phong Lôi Hợp Bích" (giải thưởng lớn nhất)',
    ],
    mcBenefit: 'thắng giải đấu liên tộc 5/5 (uy tín thành lớn), 5000 linh thạch + 3 pet B + 5 pet C + sách kỹ năng cấp B (tài nguyên cực lớn), face-slap Vương thị + 5 tiểu tộc mass (face-slap tier 3 — thành level), Vương Đại Hoàng tái mặt (đột phá quyền lực)',
    threadsAdvance: ['phục hưng gia tộc'],
    threadsResolve: ['Vương thị tiểu tộc sắp tham chiến'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: scene Cố tộc về phủ với tài sản — KHÔNG paranoia, MC vỏ bình thản.'],
  },
  {
    n: 30, beat: 'resolution',
    brief: 'RESOLUTION sub-arc 6. Cố tộc đem 5000 linh thạch + 3 pet B + 5 pet C về Cố tộc — Tro Linh Phái 25 thành viên đón nhận. MC chia tài sản: 2000 linh thạch giữ riêng, 3000 cho gia tộc + Tro Linh Phái. 3 pet B đưa cho 3 nhánh trưởng nâng cấp (Cố Khang đổi sang pet B mới mạnh hơn). Sách kỹ năng cấp B "Phong Lôi Hợp Bích" — Vân Kiếm + Cố Lan Nhi học (Phong + Lôi).',
    scenes: [
      'Sáng: Cố tộc tổ chức ăn mừng — toàn bộ 30+ đệ tử + trưởng lão đến mừng',
      'Già Tâm phát biểu: "Cố tộc đã thắng giải đấu liên tộc Linh Châu sau 50 năm. Đây là dấu hiệu phục hưng"',
      'MC vỏ "tôi chỉ làm việc đúng" — public face khiêm tốn',
      'Trưa: MC chia tài sản — 2000 linh thạch riêng vào hộc bí mật, 3000 cho gia tộc + Tro Linh Phái',
      '3 pet B đưa cho 3 nhánh trưởng (Cố Khang, Cố Tử Vũ, Cố Lan Nhi) — pet trước đó của họ down xuống cho đệ tử nhánh',
      'Sách kỹ năng cấp B "Phong Lôi Hợp Bích" — Vân Kiếm (Phong) + Cố Lan Nhi (Lôi) học',
      'Chiều: Trường Khải gặp MC riêng — "thiếu gia, ngài đang làm gia tộc tốt lên. Tôi xin rút lại đề xuất tạm hoãn thừa kế" (giả vờ thay đổi để dụ MC)',
      'MC bình tĩnh: "tôi cảm ơn chú. Nhưng việc thừa kế tôi đã xác định" — không sa bẫy',
      'Tối: MC về phòng kín, đặt 2000 linh thạch + 1 viên Phượng Linh Đan vào hộc bí mật, scan Tro Bụi tiến độ 50% Phượng Linh C',
    ],
    mcBenefit: '2000 linh thạch riêng + 1 viên Phượng Linh Đan giữ kín (tài nguyên), Cố tộc + Tro Linh Phái 3000 linh thạch + 3 pet B mới (tài nguyên gia tộc), Vân Kiếm + Cố Lan Nhi học sách cấp B (skill expand), Trường Khải giả vờ thay đổi (manh mối âm mưu)',
    threadsAdvance: ['phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín đêm — feed yên tĩnh tích cực.'],
  },
  // ─── Sub-arc 7 (ch.31-35): Cố Trường Khải tung Vương thị đợt 2 ──────────
  {
    n: 31, beat: 'setup',
    brief: 'Trường Khải bí mật gặp Vương thị + Lý thị tại nhà riêng — lập kế hoạch ám sát MC + bắt cóc em gái Tiểu Đào để ép MC ký từ bỏ thừa kế. Hà Thúc nghe lén qua một tay nội ứng. MC chuẩn bị bẫy ngược.',
    scenes: [
      'Sáng: Hà Thúc đến phòng MC tinh sương, tin: "có nội ứng tôi cài bên Trường Khải báo. Trường Khải tối qua gặp Vương Đại Hoàng + Lý thị chủ tịch tại nhà riêng"',
      'Hà Thúc: "họ lập kế hoạch — tuần sau, một trong 3 đêm, sẽ ám sát ngài + bắt cóc Tiểu Đào để ép ngài ký từ bỏ thừa kế"',
      'MC bình tĩnh: "ai sẽ ám sát?" — Hà Thúc: "đám sát thủ Lý thị thuê — 3 người cấp Sơ Cấp"',
      'MC: "Tiểu Đào ở phòng nào?" — Hà Thúc: "phòng phía đông, gần phòng ngài"',
      'MC suy nghĩ: "ta sẽ chuyển Tiểu Đào sang phòng tu luyện cũ tổ phụ dưới gốc bồ đề — nơi không ai biết. 2 pet (Lửa Tro + Cơ Khí Vũ Sĩ) canh"',
      'Trưa: MC + Vân Kiếm + Cố Khang + Hà Thúc lập bẫy ngược — 3 nhánh Tro Linh Phái sẽ phục kích trong khu vực sát thủ vào',
      'Chiều: MC nhẹ nhàng nói với em gái Tiểu Đào "tối nay em ngủ ở phòng cũ tổ phụ dưới gốc bồ đề, ca có việc bí mật"',
      'Em gái nghe lời, không hỏi',
    ],
    mcBenefit: 'manh mối ám sát + bắt cóc của Trường Khải (thông tin cực lớn), kế hoạch bẫy ngược (setup-payoff), nội ứng Hà Thúc (network + thông tin), em gái di chuyển an toàn (bảo vệ family)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    newThreads: ['Trường Khải ám sát + bắt cóc Tiểu Đào'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + em gái + 2 pet phòng kín tổ phụ — yên tĩnh, KHÔNG paranoia.'],
  },
  {
    n: 32, beat: 'breathing',
    brief: 'BREATHING. Em gái ngủ ở phòng tu luyện cũ tổ phụ với 2 pet canh. MC + Vân Kiếm + 3 trưởng nhánh + Hà Thúc lập tỏa cuối cùng. Tro Linh Phái 25 thành viên xếp đội phục kích kín ở 3 lối vào Cố phủ.',
    scenes: [
      'Sáng: MC kiểm tra phòng tu luyện cũ tổ phụ — 2 pet (Lửa Tro + Cơ Khí Vũ Sĩ) canh em gái + Tiểu Mèo Linh',
      'MC dạy em gái: "nếu có ai vào, Tiểu Mèo Linh sẽ kêu báo. Lửa Tro + Cơ Khí Vũ Sĩ sẽ phun tia bảo vệ"',
      'Em gái: "ca, em sợ" — MC ôm: "em an toàn. Ca sẽ xử lý đám sát thủ"',
      'Trưa: MC + Vân Kiếm + 3 nhánh trưởng + Hà Thúc lập kế hoạch chi tiết',
      '3 lối vào Cố phủ (cổng chính, cổng hông, cổng sau) — mỗi nhánh 7-8 đệ tử + 1 trưởng',
      'MC + Vân Kiếm + Hà Thúc giữ vị trí trung tâm gần phòng MC (giả vờ MC vẫn ở đó)',
      'Chiều: Tro Linh Phái 25 thành viên xếp đội — bí mật phục kích, không ai biết Trường Khải sắp tung sát thủ',
      'Tối: MC vào giường giả ngủ, đợi sát thủ',
    ],
    mcBenefit: 'em gái an toàn (bảo vệ family), Tro Linh Phái 25 thành viên xếp đội phục kích (network institutional), Vân Kiếm tin tưởng tham gia (quan hệ), kế hoạch chi tiết bẫy ngược (setup-payoff)',
    threadsAdvance: ['Trường Khải ám sát + bắt cóc Tiểu Đào'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC giường giả ngủ đêm khuya — chuẩn bị bẫy ngược.'],
  },
  {
    n: 33, beat: 'confront',
    brief: 'Đêm ám sát. 3 sát thủ Lý thị thuê (cấp Sơ Cấp, mỗi người pet C) lén vào Cố phủ. Cố Khang + nhánh A phát hiện ở cổng hông, MC + Vân Kiếm + Hà Thúc đối đầu. Trận đấu nhanh: Lửa Tro (cấp E thật, kìm chế D+) + Cơ Khí Vũ Sĩ (cấp D thật, public D+) phối hợp với pet B của 3 nhánh trưởng — 3 sát thủ thua trong 5 phút.',
    scenes: [
      'Đêm: 3 sát thủ Lý thị (Sơ Cấp peak, pet C) lén vào cổng hông Cố phủ',
      'Cố Khang + nhánh A phát hiện — báo MC qua tín hiệu',
      'MC + Vân Kiếm + Hà Thúc đến cổng hông, gặp 3 sát thủ',
      '3 sát thủ thấy MC: "thằng nhóc tự nguyện ra à? Tốt, ta giết ngươi luôn"',
      'MC bình tĩnh: "các ngươi không biết ai ngươi đang đối đầu"',
      'MC ra lệnh Lửa Tro: "đánh thật — không kìm chế trong nội bộ này"',
      'Trận đấu: Lửa Tro phun tro lửa cấp E thật + Cơ Khí Vũ Sĩ phun tia kim loại cấp D + 3 pet B của nhánh trưởng = 5 pet vs 3 pet C',
      '3 sát thủ thua nhanh — pet C của họ ngã trong 3 phút, sát thủ tự đầu hàng',
      'MC: "ai thuê các ngươi?" — 1 sát thủ hé "Lý thị chủ tịch... Trường Khải làm trung gian"',
      'MC ra lệnh Cố Khang giam sát thủ trong kho gia tộc, đợi cuộc họp trưởng lão sáng mai',
      'Vân Kiếm + Hà Thúc xác nhận em gái an toàn ở phòng tu luyện cũ',
    ],
    mcBenefit: 'thắng 3 sát thủ Sơ Cấp peak với 3 pet C (face-slap đối thủ), nhân chứng sát thủ confirm Lý thị + Trường Khải làm trung gian (chứng cứ cực lớn), bảo vệ em gái thành công (family safe), Tro Linh Phái 25 thành viên thử lửa thật (skill validate)',
    threadsAdvance: ['Trường Khải ám sát + bắt cóc Tiểu Đào'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + sát thủ bị giam — chuẩn bị cuộc họp sáng mai.'],
  },
  {
    n: 34, beat: 'big_wow',
    brief: 'BIG WOW NỘI TỘC ĐỈNH. Sáng cuộc họp trưởng lão khẩn cấp. MC đem 3 sát thủ ra hội đồng + nhân chứng confirm Trường Khải làm trung gian. Trường Khải mặt cắt không ra giọt máu, cố biện minh "tôi không biết" — sát thủ chỉ tay "ông là trung gian, đưa tôi 1000 linh thạch". Hội đồng SỐC. Già Tâm: "Trường Khải đã vi phạm gia pháp tối nghiêm trọng — bắt cóc trưởng tôn + trưởng tôn em gái. Yêu cầu Trường Khải bị giam + tước hết quyền lực".',
    scenes: [
      'Sáng cuộc họp trưởng lão khẩn cấp — MC mở đầu',
      'MC: "tối qua có 3 sát thủ Lý thị xâm nhập Cố phủ định ám sát tôi + bắt cóc Tiểu Đào. Tôi đã bắt được" — đưa 3 sát thủ ra',
      'Trường Khải mặt cắt không ra giọt máu',
      'Sát thủ trưởng (Lý thị peak) chỉ tay Trường Khải: "ông là trung gian. Ông đưa tôi 1000 linh thạch + plan ám sát + bản đồ Cố phủ"',
      'Hội đồng SỐC. Cố Lâm trưởng lão: "đây là vi phạm gia pháp tối nghiêm trọng"',
      'Trường Khải cố biện minh: "tôi... tôi không biết. Tôi chỉ trao đổi với Lý thị về kinh tế..."',
      'MC đưa thêm bằng chứng — Hà Thúc cài nội ứng có 1 đoạn ghi âm Trường Khải nói "ám sát thằng nhóc"',
      'Trường Khải câm họng tái mặt — không thể biện minh thêm',
      'Già Tâm đứng dậy: "Trường Khải đã vi phạm gia pháp tối nghiêm trọng. Yêu cầu bị giam + tước hết quyền lực. Quyền trưởng tộc lâm thời chuyển cho thiếu gia Cố Diệp"',
      'Hội đồng đồng ý 7/8 phiếu. Trường Khải bị giam vào phòng kín gia tộc, tước hết quyền lực',
      'MC chính thức tiếp quản quyền lực Cố tộc — vẫn còn 1 bước cuối là cuộc họp đại trưởng lão chính thức công nhận trưởng tộc',
    ],
    mcBenefit: 'Trường Khải bị giam + tước hết quyền lực (đột phá quyền lực CỰC LỚN), MC tiếp quản quyền lực Cố tộc lâm thời (uy tín tối thượng), 7/8 phiếu hội đồng ủng hộ MC (network institutional), gần đoạt trưởng tộc danh phận (path to climax)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    threadsResolve: ['Trường Khải ám sát + bắt cóc Tiểu Đào'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC tiếp quản quyền lực Cố tộc lâm thời — KHÔNG paranoia, MC tự tin.'],
  },
  {
    n: 35, beat: 'resolution',
    brief: 'RESOLUTION sub-arc 7. MC tổ chức Cố tộc — tài sản, đệ tử, gia phả tổng kê. Già Tâm trao MC chìa khóa kho di sản tổ phụ phần niêm phong sâu hơn (chỉ trưởng tộc lâm thời mở được). Tro Linh Phái 25 thành viên + MC tổ chức buổi mừng. Em gái Tiểu Đào về phòng riêng an toàn.',
    scenes: [
      'Sáng: MC tiếp quản quyền lực Cố tộc lâm thời — Già Tâm tổ chức ceremony nhỏ',
      'Già Tâm trao MC chìa khóa kho di sản tổ phụ phần niêm phong sâu hơn',
      'MC + Già Tâm + Hà Thúc vào kho di sản — phần này tổ phụ niêm phong, có nhiều di sản giá trị',
      'MC nhận: 5000 linh thạch + sách kỹ năng cấp A "Vạn Linh Hỏa Pháp" + 3 viên Phượng Linh Đan + 1 mảnh ngọc cấp B "Linh Tinh Ngọc"',
      'Mảnh ngọc Linh Tinh Ngọc: scan Vạn Linh Phổ — "tăng 50% tốc độ thấu thị Vạn Linh Phổ + giảm 20% rủi ro feed sequence"',
      'Trưa: Tro Linh Phái 25 thành viên + MC tổ chức buổi mừng — Vân Kiếm phát biểu cảm xúc',
      'Chiều: em gái Tiểu Đào về phòng riêng — an toàn, ôm Tiểu Mèo Linh',
      'Tối: MC về phòng kín, đeo Linh Tinh Ngọc — Vạn Linh Phổ HUD nhanh hơn rõ rệt',
      'MC scan Tro Bụi: tiến độ Phượng Linh C 60%. Còn 10 ngày nữa Phượng Linh C reveal — sẽ là big wow của arc 1 climax',
    ],
    mcBenefit: '5000 linh thạch + sách kỹ năng cấp A + 3 viên Phượng Linh Đan + Linh Tinh Ngọc cấp B (tài nguyên CỰC lớn), kho di sản tổ phụ phần niêm phong sâu (đột phá), Linh Tinh Ngọc tăng 50% tốc độ Vạn Linh Phổ (skill upgrade lớn), Tro Bụi Phượng Linh C tiến độ 60% (path to climax)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín đêm — yên tĩnh tích cực.'],
  },
  // ─── Sub-arc 8 (ch.36-40): Bằng chứng cuối cùng + cuộc họp đại trưởng lão ─
  {
    n: 36, beat: 'setup',
    brief: 'MC + Hà Thúc lên kế hoạch cuộc họp đại trưởng lão chính thức công nhận trưởng tộc. Hà Thúc thu thập thêm bằng chứng các trưởng lão biển thủ còn lại (Cố Lâm, Cố Hảo) qua nội ứng. Tro Bụi Phượng Linh C tiến độ 70%.',
    scenes: [
      'Sáng: MC + Hà Thúc bí mật investigate — 2 trưởng lão còn lại Cố Lâm + Cố Hảo cũng có manh mối biển thủ nhỏ hơn',
      'Cố Lâm: bán 200g Linh Mạch cho Vương thị giá 50% (kiếm 1000 linh thạch riêng)',
      'Cố Hảo: chuyển 1 pet C của gia tộc cho con riêng (kiếm 800 linh thạch ngầm)',
      'Hà Thúc đem sổ đối chiếu cuối cùng + bằng chứng nội ứng',
      'MC + Hà Thúc lên kế hoạch face-slap 2 trưởng lão này tại cuộc họp đại trưởng lão tuần sau',
      'Trưa: MC + Vân Kiếm + Già Tâm bàn cuộc họp đại trưởng lão — thủ tục chính thức công nhận trưởng tộc',
      'Chiều: MC về phòng kín, feed Tro Bụi 70% Phượng Linh C — chỉ còn 4 ngày',
    ],
    mcBenefit: 'manh mối biển thủ Cố Lâm + Cố Hảo (chứng cứ + leverage), kế hoạch face-slap đại trưởng lão (setup-payoff), Tro Bụi Phượng Linh C 70% (path to climax)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    newThreads: ['Cố Lâm + Cố Hảo biển thủ minor'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín — feed yên tĩnh.'],
  },
  {
    n: 37, beat: 'breathing',
    brief: 'BREATHING. MC + em gái + Vân Kiếm + 3 nhánh trưởng cùng training Tro Linh Phái — kỹ năng phối hợp 3-4 pet group combat. Em gái Tiểu Đào lần đầu tham gia training với Tiểu Mèo Linh — em gái talent feed lộ rõ hơn.',
    scenes: [
      'Sáng: Tro Linh Phái buổi 6 — toàn bộ 25 thành viên + em gái Tiểu Đào tham gia',
      'MC dạy kỹ năng phối hợp 3-4 pet group combat — chiến thuật cao cấp',
      'Demo: Vân Kiếm (Bạch Ngân Lang Phong) + Cố Khang (Lưu Vân Hổ Lưu) + Cố Tử Vũ (Hồng Ngân Tước Hỏa) + Cố Lan Nhi (Bạch Linh Mãng Băng) phối hợp 4 pet vs 1 pet C của Cố Lâm Tử',
      'Tro Linh Phái thắng nhanh — bystander đám đệ tử trẻ ngạc nhiên',
      'Trưa: em gái Tiểu Đào training feed Tiểu Mèo Linh F — em gái talent feed nhanh hơn đệ tử khác 30%',
      'MC scan em gái: "không thấy Vạn Linh Phổ cho người. Nhưng em có talent gì khác?" — internal thinking',
      'Chiều: MC bí mật về phòng kín, feed Tro Bụi tiến độ 80% Phượng Linh C',
      'Tối: Hà Thúc đến báo, "đại trưởng lão sẽ đến Cố tộc trong 5 ngày để chủ trì cuộc họp công nhận trưởng tộc"',
    ],
    mcBenefit: 'Tro Linh Phái 25 + em gái kỹ năng group combat (skill expand), em gái Tiểu Đào talent feed lộ (manh mối future), Tro Bụi 80% Phượng Linh C (path to climax), tin đại trưởng lão đến 5 ngày (thông tin)',
    threadsAdvance: ['phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín đêm — feed yên tĩnh.'],
  },
  {
    n: 38, beat: 'confront',
    brief: 'Cuộc họp trưởng lão thông thường — MC chủ động đem chứng cứ Cố Lâm + Cố Hảo biển thủ minor. 2 trưởng lão tái mặt, biện minh nhưng yếu. Hội đồng đồng ý: 2 trưởng lão này bồi hoàn + bị cảnh cáo (không tước quyền lực, vì tội nhẹ hơn Trường Lệ + Khiếu).',
    scenes: [
      'Sáng cuộc họp trưởng lão thông thường — MC mở đầu',
      'MC: "tôi muốn báo cáo tiếp vài việc kiểm kê — phát hiện 2 trưởng lão Cố Lâm + Cố Hảo có hoạt động kinh tế cá nhân với tài sản gia tộc"',
      'Cố Lâm tái mặt: "đó là... vay mượn..." — MC: "200g Linh Mạch bán cho Vương thị 50%. Đây không phải vay"',
      'Cố Hảo tái mặt: "pet đó... cho con tôi tu luyện..." — MC: "không qua hội đồng, không trao đổi tài sản hợp pháp"',
      'Hà Thúc đưa sổ đối chiếu — chứng cứ rõ',
      'Hội đồng đồng ý: 2 trưởng lão bồi hoàn 1800 linh thạch + 1 pet C, bị cảnh cáo. Tội nhẹ hơn nên không tước quyền',
      'Cố Trường Khải vẫn bị giam, không tham gia hội đồng',
      'MC tiếp tục tiếp quản quyền lực Cố tộc lâm thời — chưa chính thức trưởng tộc',
      'Chiều: MC + Già Tâm bàn cuộc họp đại trưởng lão sắp tới',
    ],
    mcBenefit: 'Cố Lâm + Cố Hảo bồi hoàn 1800 linh thạch + 1 pet C + bị cảnh cáo (tài nguyên + face-slap nhẹ), uy tín hội đồng tăng tiếp (uy tín)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    threadsResolve: ['Cố Lâm + Cố Hảo biển thủ minor'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Già Tâm thảo luận đại trưởng lão — KHÔNG paranoia.'],
  },
  {
    n: 39, beat: 'big_wow',
    brief: 'BIG WOW. Tro Bụi evolve thành công Phượng Linh Cấp C trong phòng kín — pet đầu tiên cấp C. MC scan: 【Phượng Linh C】Sức 80, Nhanh 60, Thể 70, Linh 90. Kỹ năng: Phượng Linh Hỏa (cấp C, damage diện rộng + AOE) + Phượng Linh Hồi Phục (heal). MC test, hài lòng. Public sẽ show cấp B+ (kìm chế).',
    scenes: [
      'Đêm ngày 4 sequence: Tro Bụi tiến độ 95% Phượng Linh C',
      'Sáng ngày 5: MC bổ sung viên Phượng Linh Đan thứ 2',
      'Trưa: Tro Bụi hấp thụ — vỏ ngoài chuyển từ đỏ tro sang đỏ vàng kim, hình dạng từ slime tròn → slime có cánh nhỏ',
      'Chiều: ánh sáng đỏ vàng kim bùng lên trong phòng kín — Tro Bụi evolve Phượng Linh Cấp C',
      'MC scan: 【Phượng Linh Cấp C】Sức 80, Nhanh 60, Thể 70, Linh 90. Kỹ năng: Phượng Linh Hỏa (cấp C, damage diện rộng + AOE) + Phượng Linh Hồi Phục (heal pet ally)',
      'MC test trong phòng kín: Phượng Linh Hỏa thiêu đốt 1 cục đá lớn, Phượng Linh Hồi Phục heal Cơ Khí Vũ Sĩ trong 2 giây',
      'Lửa Tro (Phượng Linh) — pet đầu tiên cấp C của MC. Tổng pet portfolio: Phượng Linh C + Cơ Khí Vũ Sĩ D + Lục Vũ E (đang feed)',
      'MC dạy Phượng Linh kìm chế cấp B+ public (60% sức) — chỉ show cấp B+, giấu cấp C thật',
      'Tối: MC ghi vào sổ kế hoạch — đại trưởng lão đến trong 4 ngày, MC sẽ show Phượng Linh cấp B+ tại cuộc họp công nhận trưởng tộc',
    ],
    mcBenefit: 'Tro Bụi Phượng Linh Cấp C (đột phá pet level + pet đầu tiên C), kỹ năng Phượng Linh Hỏa AOE + Phượng Linh Hồi Phục (skill cực lớn), pet portfolio C + D + E (skill expand), kế hoạch show B+ tại đại trưởng lão (setup-payoff)',
    threadsAdvance: ['Vạn Linh Phổ tuyến tiến hóa expand', 'phục hưng gia tộc'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Phượng Linh trong phòng kín đêm — yên tĩnh tích cực.'],
  },
  {
    n: 40, beat: 'resolution',
    brief: 'RESOLUTION sub-arc 8. Tro Bụi Phượng Linh C kìm chế ổn. Lục Vũ feed sequence Phong Yến E tiến độ 60%. Cơ Khí Vũ Sĩ D ổn. MC + em gái + Vân Kiếm + 3 nhánh trưởng + Hà Thúc tổ chức ăn mừng nội bộ — biết MC sắp đoạt trưởng tộc chính thức.',
    scenes: [
      'Sáng: MC scan 3 pet — Phượng Linh C ổn, Cơ Khí Vũ Sĩ D ổn, Lục Vũ Phong Yến E 60%',
      'Trưa: MC tổ chức ăn mừng nội bộ Tro Linh Phái 25 + em gái + Hà Thúc + Già Tâm = 28 người',
      'Già Tâm phát biểu: "đại trưởng lão sẽ đến trong 3 ngày để chủ trì công nhận trưởng tộc. Cố Diệp gần như chắc chắn được công nhận"',
      'Vân Kiếm cảm xúc: "huynh ấy thay đổi gia tộc. Ban đầu tôi sai, giờ tôi xin theo huynh trọn đời"',
      'MC vỏ "tôi chỉ làm việc đúng cho gia tộc thôi" — public face khiêm tốn',
      'Chiều: em gái Tiểu Đào lần đầu cảm xúc lộ rõ, "ca, em tự hào ca lắm" — MC ôm em',
      'Tối: MC + Hà Thúc bàn lễ phục cho cuộc họp đại trưởng lão — chuẩn bị chính thức',
      'MC về phòng kín, feed Lục Vũ thêm — đêm yên tĩnh',
    ],
    mcBenefit: 'pet portfolio Phượng Linh C + Cơ Khí Vũ Sĩ D + Lục Vũ E (60%) (skill expand stable), Tro Linh Phái 25 + em gái + Vân Kiếm trung thành (network institutional), Già Tâm + Hà Thúc tin tưởng tối đa (quan hệ), chuẩn bị đại trưởng lão (setup-payoff)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín đêm — yên tĩnh tích cực.'],
  },
  // ─── Sub-arc 9 (ch.41-45): Trường Khải bắt cóc Tiểu Đào — climax setup ───
  {
    n: 41, beat: 'setup',
    brief: 'Trường Khải bị giam đã 10 ngày — bí mật liên lạc với Lý thị qua mật mã trong thư cá nhân. Lý thị tổ chức 1 đợt cuối cùng — 5 cao thủ Sơ Cấp + 1 cao thủ Trung Cấp đến Cố tộc bắt cóc Tiểu Đào để ép MC ký giấy từ bỏ thừa kế trước khi đại trưởng lão đến.',
    scenes: [
      'Sáng: Hà Thúc nhận tin từ nội ứng — Trường Khải bị giam vẫn liên lạc qua mật mã',
      'Hà Thúc: "Lý thị sắp tổ chức đợt cuối — 6 cao thủ (5 Sơ Cấp + 1 Trung Cấp) sẽ đến Cố phủ trong 2 đêm tới"',
      'MC bình tĩnh: "Trung Cấp nguy hiểm. Phượng Linh C kìm chế B+ chỉ vừa đủ"',
      'MC + Vân Kiếm + 3 nhánh trưởng + Hà Thúc lên kế hoạch chi tiết bẫy ngược lần 2',
      'Trưa: MC chuyển em gái Tiểu Đào sang phòng tu luyện cũ tổ phụ với 3 pet (Phượng Linh + Cơ Khí Vũ Sĩ + Lục Vũ) canh',
      'Em gái: "ca, em đã quen với phòng tu luyện này rồi" — MC nhẹ nhàng',
      'Chiều: MC + Già Tâm bàn — Già Tâm: "ta sẽ tham gia phục kích — Trung Cấp tôi đối phó được"',
      'Tối: Tro Linh Phái 25 + Vân Kiếm + Già Tâm + Hà Thúc + MC = 29 thành viên + 4 pet B + 5 pet C + Phượng Linh + Cơ Khí Vũ Sĩ + Lục Vũ phục kích',
    ],
    mcBenefit: 'manh mối Lý thị đợt cuối + 6 cao thủ (thông tin cực lớn), kế hoạch bẫy ngược lần 2 (setup-payoff), em gái an toàn ở phòng tu luyện cũ (bảo vệ family), Già Tâm tham gia phục kích đối phó Trung Cấp (quan hệ + skill)',
    threadsAdvance: ['đoạt thừa kế'],
    newThreads: ['Lý thị đợt cuối cùng — 6 cao thủ'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + em gái + 3 pet phòng tu luyện cũ — yên tĩnh, KHÔNG paranoia.'],
  },
  {
    n: 42, beat: 'breathing',
    brief: 'BREATHING. MC + Vân Kiếm + Già Tâm cùng huấn luyện 3 nhánh trưởng kỹ năng đối phó Trung Cấp. Già Tâm dạy MC kỹ năng "Linh Tinh Khoá" — kỹ năng cấp B đặc biệt khoá pet cao cấp 5 giây.',
    scenes: [
      'Sáng: MC + Vân Kiếm + Già Tâm + 3 nhánh trưởng training kỹ năng đối phó Trung Cấp',
      'Già Tâm dạy MC kỹ năng "Linh Tinh Khoá" cấp B — khoá pet cao cấp 5 giây, dùng trong critical moment',
      'MC scan kỹ năng — confirm hợp với Phượng Linh Hỏa (kết hợp khoá + đốt)',
      'Trưa: 3 nhánh trưởng học kỹ năng group combat đối phó pet C peak — Cố Khang + Cố Tử Vũ + Cố Lan Nhi training rất nghiêm túc',
      'Chiều: Vân Kiếm + Bạch Ngân Lang luyện chiến thuật Phong + Lôi Hợp Bích — kỹ năng cấp B',
      'Tối: MC về phòng tu luyện cũ với em gái — em gái ngủ êm với Tiểu Mèo Linh + 3 pet canh ngoài',
      'MC ngồi yên cạnh em gái, scan Tro Bụi Phượng Linh + Cơ Khí Vũ Sĩ + Lục Vũ — 3 pet sẵn sàng',
    ],
    mcBenefit: 'kỹ năng "Linh Tinh Khoá" cấp B từ Già Tâm (skill upgrade lớn), 3 nhánh trưởng kỹ năng nâng cao (skill expand), Vân Kiếm Phong + Lôi Hợp Bích cấp B (skill upgrade), kế hoạch chi tiết phục kích đợt cuối',
    threadsAdvance: ['Lý thị đợt cuối cùng — 6 cao thủ'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + em gái + 3 pet phòng tu luyện cũ — yên tĩnh.'],
  },
  {
    n: 43, beat: 'confront',
    brief: 'Đêm phục kích. 5 cao thủ Sơ Cấp + 1 cao thủ Trung Cấp Lý thị lén vào Cố phủ. Cố Khang nhánh A phát hiện ở cổng chính — báo MC. MC + Già Tâm + Vân Kiếm + 3 nhánh trưởng đối đầu. Trận đấu căng thẳng — Già Tâm + Phượng Linh kìm chế B+ chiến cao thủ Trung Cấp, 3 nhánh trưởng + 5 pet B/C chiến 5 cao thủ Sơ Cấp.',
    scenes: [
      'Đêm: 6 cao thủ Lý thị (5 Sơ Cấp + 1 Trung Cấp) lén vào cổng chính Cố phủ',
      'Cố Khang phát hiện — báo MC qua tín hiệu',
      'MC + Già Tâm + Vân Kiếm + 3 nhánh trưởng + 25 đệ tử Tro Linh Phái đến cổng chính',
      'Cao thủ Trung Cấp Lý thị (Lý Đại Phong, Trung Cấp tầng 5, pet Phượng Linh Trung Cấp): "Già Tâm cũng ở đây? Thằng nhóc này có thế lực thật"',
      'Già Tâm: "Lý Đại Phong, ngươi xâm phạm Cố phủ vũ trang. Hôm nay ngươi không thoát"',
      'Trận đấu chính: Già Tâm + pet Lão Quy E peak vs Lý Đại Phong + Phượng Linh Trung Cấp — căng thẳng, Già Tâm hơi yếu thế',
      'MC quyết định tham gia: Phượng Linh kìm chế B+ + Linh Tinh Khoá khoá Lý Đại Phong 5 giây',
      'Già Tâm thừa cơ hội đánh trọng thương Lý Đại Phong — Lý Đại Phong rút lui',
      'Trận đấu phụ: 3 nhánh trưởng + 25 đệ tử + 5 pet B/C vs 5 cao thủ Sơ Cấp + 5 pet Sơ Cấp — Tro Linh Phái thắng nhanh, 5 Sơ Cấp đầu hàng',
      'Lý Đại Phong rút trước khi bị bắt — Già Tâm bị thương nhẹ, MC + Phượng Linh không bị thương',
      'MC ra lệnh giam 5 cao thủ Sơ Cấp + thu thập chứng cứ Lý thị',
      'Vân Kiếm + Hà Thúc xác nhận em gái an toàn',
    ],
    mcBenefit: 'thắng 5 cao thủ Sơ Cấp + đánh đuổi 1 cao thủ Trung Cấp với hỗ trợ Già Tâm (face-slap đối thủ + skill validate), 5 cao thủ Sơ Cấp Lý thị + 5 pet Sơ Cấp giam (chứng cứ + tài nguyên), Già Tâm + MC phối hợp thành công (quan hệ đỉnh), bảo vệ em gái lần 2 thành công (family safe)',
    threadsAdvance: ['Lý thị đợt cuối cùng — 6 cao thủ'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Già Tâm + 5 cao thủ giam — chuẩn bị cuộc họp đại trưởng lão.'],
  },
  {
    n: 44, beat: 'big_wow',
    brief: 'BIG WOW NỘI TỘC ĐỈNH. Sáng cuộc họp trưởng lão khẩn cấp lần 2. MC đem 5 cao thủ Sơ Cấp + bằng chứng + chứng cứ Trường Khải liên lạc với Lý thị qua mật mã trong thư. Trường Khải bị đem ra hội đồng — câm họng, không thể biện minh. Hội đồng đồng ý: Trường Khải bị tử hình theo gia pháp. MC chính thức được công nhận trưởng tộc lâm thời tuyệt đối + chuẩn bị đại trưởng lão.',
    scenes: [
      'Sáng cuộc họp trưởng lão khẩn cấp lần 2 — MC + Già Tâm chủ trì',
      'MC đem 5 cao thủ Sơ Cấp Lý thị + chứng cứ Trường Khải liên lạc qua mật mã trong thư cá nhân',
      'Trường Khải bị đem ra hội đồng — bị giam, mặt cắt không ra giọt máu',
      '5 cao thủ Sơ Cấp confirm: "Trường Khải qua thư mật mã sai bảo Lý thị tổ chức đợt cuối. Mục đích bắt cóc Tiểu Đào"',
      'Hội đồng SỐC tuyệt đối — Trường Khải đã vi phạm gia pháp tối nghiêm trọng lần 2 (sau lần 1 đã bị giam)',
      'Già Tâm: "Trường Khải đã vi phạm gia pháp tối nghiêm trọng lần 2 từ trong giam. Theo gia pháp, tử hình"',
      'Hội đồng đồng ý 7/7 phiếu (Khiếu vẫn nghỉ, Trường Lệ đã rút). Trường Khải bị tử hình theo gia pháp',
      'MC chính thức được công nhận trưởng tộc lâm thời tuyệt đối — chỉ cần đại trưởng lão chính thức công nhận trong cuộc họp tuần sau',
      'Chiều: tin lan ra Linh Châu Thành — Cố tộc đã thanh trừng nội bộ thành công, sắp có trưởng tộc trẻ',
      'Tối: MC + Già Tâm + Hà Thúc + Vân Kiếm + 3 nhánh trưởng tổ chức bữa tối nhỏ — tinh thần phục hưng gia tộc đỉnh',
    ],
    mcBenefit: 'Trường Khải bị tử hình theo gia pháp (đột phá quyền lực CỰC LỚN — kẻ thù chính arc 1 hết), MC chính thức trưởng tộc lâm thời tuyệt đối (uy tín tối thượng), 5 cao thủ Sơ Cấp Lý thị giam + chứng cứ (chứng cứ + leverage cho arc 2), tin lan Linh Châu Thành (uy tín thành)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    threadsResolve: ['Lý thị đợt cuối cùng — 6 cao thủ', 'Trường Khải antagonist arc 1'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 28 thành viên Tro Linh Phái + Già Tâm bữa tối tinh thần phục hưng — yên tĩnh tích cực.'],
  },
  {
    n: 45, beat: 'resolution',
    brief: 'RESOLUTION sub-arc 9. MC tiếp tục feed Lục Vũ — Lục Vũ Phong Yến E giai đoạn cuối. Tro Bụi Phượng Linh C ổn. Cơ Khí Vũ Sĩ D ổn. Tro Linh Phái 25 thành viên + Vân Kiếm + em gái = 27 thành viên + Già Tâm + Hà Thúc = 29 core team. Chuẩn bị cuộc họp đại trưởng lão chính thức.',
    scenes: [
      'Sáng: MC scan 3 pet — Phượng Linh C ổn, Cơ Khí Vũ Sĩ D ổn, Lục Vũ Phong Yến E 90%',
      'MC bổ sung 30g Linh Mạch + 1 viên Hồi Khí Đan cuối cùng cho Lục Vũ',
      'Trưa: Lục Vũ evolve thành Phong Yến Cấp E — pet thứ 3 cấp E. MC scan: 【Phong Yến E】Sức 15, Nhanh 25, Thể 10, Linh 8. Kỹ năng: Phong Trảm + Phong Hồi Phục',
      'Pet portfolio finally: Phượng Linh C (kìm chế B+) + Cơ Khí Vũ Sĩ D (kìm chế E+) + Phong Yến E (kìm chế F+)',
      'Chiều: MC + Già Tâm + Hà Thúc + Vân Kiếm + 3 nhánh trưởng họp riêng — bàn cuộc họp đại trưởng lão tuần sau',
      'Già Tâm: "đại trưởng lão Cố Trường Hành (em họ tổ phụ, Cao Cấp tầng 3) sẽ đến chủ trì. Ngài rất nghiêm khắc nhưng công bằng"',
      'MC chuẩn bị lễ phục + các bằng chứng đầy đủ',
      'Tối: MC + em gái phòng tu luyện cũ — em gái về phòng riêng từ mai (sau khi Trường Khải bị xử)',
      'MC scan toàn bộ pet portfolio + tài sản — sẵn sàng đại trưởng lão',
    ],
    mcBenefit: 'Lục Vũ Phong Yến Cấp E (đột phá pet level + pet thứ 3 cấp E), pet portfolio đủ 3 cấp (C + D + E), Già Tâm pre-commit hỗ trợ đại trưởng lão (quan hệ), tin về Cố Trường Hành đại trưởng lão (thông tin), em gái về phòng riêng (family safe)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + 3 pet phòng kín đêm — yên tĩnh tích cực.'],
  },
  // ─── Sub-arc 10 (ch.46-50): CLIMAX arc 1 — đoạt trưởng tộc + vào kho di sản ─
  {
    n: 46, beat: 'setup',
    brief: 'Đại trưởng lão Cố Trường Hành (Cao Cấp tầng 3, em họ tổ phụ) đến Cố tộc 2 ngày trước cuộc họp công nhận trưởng tộc. Ngài investigate gia tộc, khá nghiêm khắc với MC. MC vỏ thiếu niên khiêm tốn, không show pet portfolio. Già Tâm tổ chức bữa ăn welcome.',
    scenes: [
      'Sáng: đại trưởng lão Cố Trường Hành (Cao Cấp tầng 3) đến Cố phủ cùng 2 trưởng lão khác',
      'Cố Trường Hành tuổi 80, râu tóc bạc phơ, mắt sắc bén, mặc trường bào màu xám đậm',
      'Già Tâm + Hà Thúc + Tro Linh Phái 25 đón tiếp — formal',
      'Cố Trường Hành nhìn MC: "thiếu gia, ngài là hậu duệ Đại Sư Cố Lập Khải. Tôi kỳ vọng ngài chứng minh xứng đáng"',
      'MC vỏ khiêm tốn: "tôi sẽ cố gắng không phụ kỳ vọng tổ phụ + đại trưởng lão"',
      'Trưa: Cố Trường Hành investigate kho gia tộc + sổ tài chính + tài sản',
      'Chiều: Cố Trường Hành kiểm tra Tro Linh Phái 25 đệ tử — ngạc nhiên "thiếu gia tổ chức nhanh thế"',
      'Tối: bữa ăn welcome — Cố Trường Hành nói với Già Tâm: "thằng nhóc này có thần thái tổ phụ. Cuộc họp tuần sau sẽ thú vị"',
      'MC scan Cố Trường Hành — Cao Cấp tầng 3, pet Lưỡng Đầu Long cấp A peak. Internal: "đại trưởng lão thực lực, không thể lừa"',
    ],
    mcBenefit: 'đại trưởng lão Cố Trường Hành đến (path to climax), uy tín nội tộc tăng (đại trưởng lão dự cuộc họp), thông tin về Cố Trường Hành Cao Cấp tầng 3 + pet A (thông tin), Già Tâm pre-commit ủng hộ (quan hệ)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    newThreads: ['Cố Trường Hành đại trưởng lão chủ trì'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: bữa ăn welcome — yên tĩnh tích cực.'],
  },
  {
    n: 47, beat: 'breathing',
    brief: 'BREATHING + setup cho big wow. Cố Trường Hành đề xuất "thử thách công khai" — MC phải dùng pet đối đầu 1 đại biểu Cố tộc cấp Sơ Cấp peak để chứng minh năng lực. MC bí mật quyết định: show Phượng Linh C kìm chế cấp B (75% sức) — tỉ lệ hơp lý với 16 tuổi peak Sơ Cấp.',
    scenes: [
      'Sáng: Cố Trường Hành tổ chức cuộc họp nội bộ — đại trưởng lão + Già Tâm + 3 trưởng lão khác + MC',
      'Cố Trường Hành: "thiếu gia, để chính thức công nhận trưởng tộc, ngài cần thử thách công khai. Đối đầu 1 đại biểu Cố tộc cấp Sơ Cấp peak. Pass = trưởng tộc chính thức"',
      'MC: "tôi đồng ý" — bình tĩnh',
      'Đại biểu được chọn: Cố Lâm Tử (Sơ Cấp tầng 7, pet C peak — Lưu Kim Hổ)',
      'Trưa: MC + Già Tâm + Hà Thúc bàn chiến thuật. Già Tâm: "Phượng Linh C của ngài đủ thắng. Nhưng đừng show full"',
      'MC: "tôi sẽ show Phượng Linh kìm chế cấp B (75% sức) — đủ thắng cấp C peak nhưng không lộ tier thật"',
      'Chiều: MC dạy Phượng Linh kìm chế B specific cho cuộc thử thách',
      'Tối: MC về phòng kín feed Phượng Linh thêm — Phượng Linh tiến độ Hỏa Phụng Tế A path bắt đầu (arc 2)',
    ],
    mcBenefit: 'thử thách công khai chính thức (path to climax), Cố Lâm Tử đại biểu Sơ Cấp peak (thông tin đối thủ), kế hoạch show Phượng Linh kìm chế B (setup-payoff), Phượng Linh Hỏa Phụng Tế A path start (skill expand)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Phượng Linh phòng kín đêm — yên tĩnh.'],
  },
  {
    n: 48, beat: 'confront',
    brief: 'Sáng cuộc thử thách công khai. Toàn bộ Cố tộc + đại trưởng lão Cố Trường Hành + 5 trưởng lão khác từ các Cố tộc khác Linh Châu Thành dự khán. MC vs Cố Lâm Tử + Lưu Kim Hổ. Phượng Linh kìm chế cấp B đối đầu — Cố Lâm Tử mạnh hơn dự kiến nhưng không bằng Phượng Linh.',
    scenes: [
      'Sáng: võ trường Cố tộc — đại trưởng lão Cố Trường Hành + 5 trưởng lão Cố tộc khác từ Linh Châu Thành dự khán',
      'Toàn bộ Cố tộc + Tro Linh Phái 25 + Vân Kiếm + Già Tâm + Hà Thúc + em gái Tiểu Đào dự khán',
      'Cố Lâm Tử (Sơ Cấp tầng 7, pet Lưu Kim Hổ Cấp C peak) vào sảnh — formal salute',
      'MC: "thiếu gia Cố Diệp, Đồ Tể tầng 3 (vỏ — thực 5), pet Tro Bụi (vỏ — thực Phượng Linh C)" — public face khiêm tốn',
      'Trận đấu: Cố Lâm Tử ra lệnh Lưu Kim Hổ tấn công Liên Hoàn Phá — kỹ năng cấp B',
      'MC ra lệnh Phượng Linh kìm chế B: Phượng Linh Hỏa AOE — Lưu Kim Hổ né được phần lớn nhưng bị đốt 30% sức mạnh',
      'Cố Lâm Tử phản công Linh Khí Phá kỹ năng B+: Phượng Linh kìm chế B sử dụng Phượng Linh Hồi Phục heal đồng thời tránh',
      'Trận đấu kéo 3 phút — Phượng Linh kìm chế B thắng Lưu Kim Hổ C peak cách "vừa đủ"',
      'Lưu Kim Hổ rút lui, Cố Lâm Tử thừa nhận: "thiếu gia thực lực rõ"',
      'Đại trưởng lão Cố Trường Hành: "thử thách thành công. MC pass"',
    ],
    mcBenefit: 'thử thách công khai pass (path to climax đỉnh), Phượng Linh kìm chế B thắng pet C peak (face-slap đối thủ public), 5 trưởng lão Cố tộc Linh Châu khác chứng kiến (uy tín thành), pre-công nhận trưởng tộc (uy tín tối thượng)',
    threadsAdvance: ['phục hưng gia tộc', 'đoạt thừa kế'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + Phượng Linh trở về phòng kín — yên tĩnh tích cực.'],
  },
  {
    n: 49, beat: 'big_wow',
    brief: 'BIG WOW CLIMAX ARC 1. Cuộc họp đại trưởng lão chính thức công nhận trưởng tộc. Toàn bộ Cố tộc + 5 trưởng lão Cố tộc khác Linh Châu + đại trưởng lão Cố Trường Hành dự. Cố Diệp chính thức được công nhận trưởng tộc Cố tộc Linh Châu Thành sub-branch. Gia tộc Cố từ phế tộc thành tiểu tộc lại + có thể thành trung tộc trong arc 2.',
    scenes: [
      'Sáng: cuộc họp đại trưởng lão chính thức công nhận trưởng tộc tại sảnh chính Cố phủ',
      'Đại trưởng lão Cố Trường Hành chủ trì, 5 trưởng lão Cố tộc khác Linh Châu + Già Tâm + Cố Lâm + Cố Hảo + 1 trưởng lão thay thế Trường Lệ + Khiếu',
      'Cố Trường Hành phát biểu: "Cố Diệp đã chứng minh năng lực qua 3 việc — thắng giải đấu nội tộc, thanh trừng nội bộ Trường Khải + Lý thị, vượt thử thách công khai. Tôi chính thức công nhận Cố Diệp là trưởng tộc Cố tộc Linh Châu Thành sub-branch"',
      'BIG WOW: toàn bộ Cố tộc + Tro Linh Phái 25 + Vân Kiếm + 5 trưởng lão Cố tộc khác + đại trưởng lão SHOCK + APPLAUSE',
      'Em gái Tiểu Đào ôm chân MC khóc vì vui — chemistry đỉnh',
      'Hà Thúc khóc: "tổ phụ ngài hôm nay nếu thấy hẳn rất tự hào"',
      'Già Tâm trao MC ấn trưởng tộc + chìa khóa kho di sản tổ phụ phần niêm phong toàn bộ',
      'MC vỏ "tôi sẽ cố gắng không phụ kỳ vọng tổ phụ + đại trưởng lão" — public face khiêm tốn',
      'Cố Trường Hành thì thầm với Già Tâm: "thằng nhóc này tài năng. Tôi kỳ vọng nó sẽ đưa Cố tộc lên trung tộc Linh Châu trong 5 năm"',
      'Chiều: tin lan ra Linh Châu Thành — Cố tộc đã có trưởng tộc trẻ 16 tuổi. Vương thị + Lý thị bắt đầu lo lắng',
    ],
    mcBenefit: 'CỐ DIỆP CHÍNH THỨC TRƯỞNG TỘC CỐ TỘC LINH CHÂU THÀNH SUB-BRANCH (uy tín tối thượng), ấn trưởng tộc + chìa khóa kho di sản tổ phụ phần niêm phong toàn bộ (vật phẩm + đột phá), đại trưởng lão Cố Trường Hành đặc biệt khen (quan hệ), tin Cố tộc trưởng tộc trẻ lan Linh Châu Thành (uy tín thành)',
    threadsAdvance: ['phục hưng gia tộc'],
    threadsResolve: ['đoạt thừa kế', 'Cố Trường Hành đại trưởng lão chủ trì'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: MC + ấn trưởng tộc + chìa khóa — yên tĩnh tích cực, tinh thần phục hưng đỉnh.'],
  },
  {
    n: 50, beat: 'resolution',
    brief: 'RESOLUTION CLIMAX ARC 1. MC + Già Tâm + Hà Thúc vào kho di sản tổ phụ phần niêm phong toàn bộ. Phát hiện gia phả tổ phụ chi tiết + bản đồ Bắc Vực với ghi chú cá nhân + sách kỹ năng cấp A "Vạn Linh Pháp Quyết" + 1 viên Hỏa Phụng Đan cấp B + 5000 Linh Mạch. MC scan Vạn Linh Phổ với gia phả — phát hiện manh mối tổ phụ có liên kết với Trái Đất.',
    scenes: [
      'Sáng: MC + Già Tâm + Hà Thúc cùng vào kho di sản tổ phụ phần niêm phong',
      'Kho rộng, kệ chất đầy sách + vật phẩm cấp B-A. MC scan toàn bộ qua Vạn Linh Phổ',
      'Phát hiện: gia phả tổ phụ chi tiết, có 1 trang ghi chú cá nhân tổ phụ — "Vạn Linh Phổ là di sản từ kiếp khác. Cẩn thận với người Bắc Vực"',
      'MC scan kỹ trang ghi chú — Vạn Linh Phổ HUD show: "kết nối kiếp trước Trái Đất xác nhận. Tổ phụ Cố Lập Khải = xuyên hồn từ Trái Đất 1000 năm trước"',
      'MC chấn động — manh mối arc 6 origin reveal',
      'Sách kỹ năng cấp A "Vạn Linh Pháp Quyết" — MC scan: kỹ năng cấp A có thể tăng tốc feed sequence 50% + giảm rủi ro 30%',
      'Hỏa Phụng Đan cấp B + 5000 Linh Mạch + bản đồ Bắc Vực với ghi chú cá nhân tổ phụ',
      'Bản đồ Bắc Vực: ghi rõ "di tích cổ — cánh cửa Vạn Linh Phổ — bố Cố Hành đã đến đây" → manh mối arc 4 + 6 cùng',
      'Trưa: MC + Già Tâm + Hà Thúc + Vân Kiếm + 3 nhánh trưởng + em gái Tiểu Đào + đại trưởng lão Cố Trường Hành tổ chức tiệc trưởng tộc',
      'Cố Trường Hành phát biểu cảm xúc + chính thức rời Cố tộc',
      'Chiều: tin lan rộng Linh Châu Thành — Cố tộc trưởng tộc trẻ + tài sản phục hưng',
      'Tối: MC + 3 pet (Phượng Linh + Cơ Khí Vũ Sĩ + Phong Yến) phòng kín đêm. MC ghi vào sổ — arc 1 hoàn thành. Arc 2 sẽ là Vương thị + Lý thị tranh đoạt tiểu tộc Linh Châu',
    ],
    mcBenefit: 'kho di sản tổ phụ phần niêm phong toàn bộ (đột phá tài nguyên), gia phả tổ phụ + manh mối tổ phụ xuyên hồn Trái Đất 1000 năm (manh mối arc 6 + thông tin cực lớn), sách kỹ năng cấp A "Vạn Linh Pháp Quyết" + Hỏa Phụng Đan cấp B + 5000 Linh Mạch (tài nguyên + skill cực lớn), bản đồ Bắc Vực với ghi chú tổ phụ + bố Cố Hành (manh mối arc 4 + 6)',
    threadsAdvance: ['phục hưng gia tộc', 'di tích cổ Bắc Vực', 'cánh cửa Vạn Linh Phổ', 'bố Cố Hành Bắc Vực mất tích'],
    threadsResolve: ['Lý thị đợt cuối cùng — 6 cao thủ'],
    newThreads: ['tổ phụ Cố Lập Khải xuyên hồn Trái Đất 1000 năm', 'Vạn Linh Phổ origin Trái Đất'],
    risks: [BAN_BASE, TONE_LAO_LUC, 'END: arc 1 hoàn thành — MC + 3 pet phòng kín đêm — yên tĩnh tích cực.'],
  },
];
