// Arc 4 detailed chapter briefs (ch.301-500, 200 briefs).
//
// Theme: "Bắc Vực — đại tộc Bắc Châu kẻ gài bẫy bố mẹ"
// Core payoff: Cứu bố Cố Hành + mẹ Lưu Tiêm Nhi từ giam cầm Bắc Châu, diệt
// đại tộc Bắc Châu, Tro Bụi Hỏa Phụng Tế A peak, MC Cao Cấp.
//
// Cumulative state entering arc 4 (post ch.300):
//   MC: Trung Cấp tầng 5 → Cao Cấp tầng 1 cuối arc
//   Pets: Hỏa Phụng Tế A peak (Tro Bụi), Thần Thuật Cơ Sư B (Cơ Niệm),
//     Phong Linh C (Lục Vũ), Mộc Linh B (đang feed Mộc Thần A path)
//   Gia tộc: Cố tộc đại tộc Linh Châu top + 13 đồng minh đại tộc đại lục
//   Tro Linh Phái: 200 đệ tử + Học viện Cố tộc 200 đệ tử + 2 nhánh con
//   Open threads: bố mẹ Bắc Vực mất tích → reveal+rescue arc 4

import type { ChapterBrief } from './arc-skeleton';

const TONE = 'TONE: MC lạnh đạm + tự tin. KHÔNG paranoid. KHÔNG tự khoe.';
const BAN = 'BAN cliffhanger paranoia; pet evolve công khai; em gái biết Vạn Linh Phổ; cosmic-tier elements (defer arc 6+).';
const TIER = 'PET TIER PUBLIC: Hỏa Phụng Tế kìm chế A− public, Thần Thuật Cơ Sư B+, Phong Linh C+, Mộc Linh B−.';

interface ClusterMeta { n: number; theme: string; }

function buildBriefs(clusterMeta: ClusterMeta[], context: string, resolveThread?: string): ChapterBrief[] {
  const beats: Array<'setup' | 'breathing' | 'confront' | 'big_wow' | 'resolution'> = [
    'setup', 'breathing', 'confront', 'big_wow', 'resolution',
  ];
  return clusterMeta.map((meta, idx) => {
    const beat = beats[idx % 5];
    const isLast = idx === clusterMeta.length - 1 && resolveThread;
    return {
      n: meta.n,
      beat,
      brief: `${meta.theme}. (${context}.)`,
      scenes: [
        `Beat ${beat}: ${meta.theme.split(/[—.,]/)[0].slice(0, 100)}`,
        `Cast: MC, Cố Tiểu Đào, Vân Kiếm + Hồ Linh Nhi (vợ chưa cưới), Già Tâm, Hà Thúc, 3 nhánh trưởng, đoàn thám hiểm 100 cao thủ`,
        `Pet portfolio public: Hỏa Phụng Tế A−, Thần Thuật Cơ Sư B+, Phong Linh C+, Mộc Linh B−`,
        `MC tone lão lục — internal tính toán, public face khiêm tốn`,
        `Beat-specific: ${beat === 'big_wow' ? 'mass face-slap + bystander shock visible' : beat === 'breathing' ? 'family/đoàn warm scene + intel' : beat === 'setup' ? 'observe + plant seed' : beat === 'confront' ? 'antagonist Bắc Châu face-off direct' : 'consolidate gain'}`,
        `Engine state: chapter_summaries + character_states + plot_threads update`,
      ],
      mcBenefit: `${beat === 'big_wow' ? 'face-slap Bắc Châu + uy tín đại lục' : beat === 'resolution' ? 'tài nguyên + manh mối bố mẹ thêm' : 'thông tin + setup-payoff'}`,
      threadsAdvance: ['phục hưng gia tộc', 'bố Cố Hành Bắc Vực mất tích', 'đại tộc Bắc Châu kẻ gài bẫy bố mẹ (arc 4)'],
      threadsResolve: isLast ? [resolveThread] : undefined,
      risks: [BAN, TONE, TIER, `END phù hợp beat ${beat}, KHÔNG cliffhanger paranoia.`],
    };
  });
}

export const ARC4_BRIEFS_CH301_500: ChapterBrief[] = [
  // Sub-arc 1 (ch.301-320): Cố tộc xuất phát Bắc Vực ─────────────────────
  ...buildBriefs([
    { n: 301, theme: 'SETUP: MC tổ chức đoàn thám hiểm Bắc Vực — 100 cao thủ + 50 đệ tử Tro Linh Phái + 8 đại biểu đồng minh' },
    { n: 302, theme: 'BREATHING: MC + Hà Thúc + Già Tâm + Vân Kiếm + Hồ Linh Nhi cuối cùng họp trước khi đi — Già Tâm ở lại giữ Linh Châu' },
    { n: 303, theme: 'CONFRONT: Đoàn xuất phát Linh Châu, gặp 1 đại tộc Trung Châu thân Bắc Châu chặn đường — formal threat' },
    { n: 304, theme: 'BIG WOW: MC + Hỏa Phụng Tế kìm chế đại biểu đại tộc Trung Châu — đường đi mở' },
    { n: 305, theme: 'RESOLUTION: Đoàn vào Trung Châu phía bắc, tin lan đại lục về Cố tộc xuất phát' },
    { n: 306, theme: 'SETUP: Đoàn camp trong cấm khu Trung Châu phía bắc — MC scan pet hoang' },
    { n: 307, theme: 'BREATHING: Tiểu Đào talent thông giao tâm linh tương tác với pet hoang — đọc được vị trí pet hiếm' },
    { n: 308, theme: 'CONFRONT: 1 đoàn đại tộc Bắc Châu phụ chặn đường — 50 cao thủ + 20 pet B' },
    { n: 309, theme: 'BIG WOW: MC + đoàn 100 cao thủ đè bẹp Bắc Châu phụ — bắt 30 cao thủ làm nhân chứng' },
    { n: 310, theme: 'RESOLUTION: 30 nhân chứng Bắc Châu confirm bố mẹ MC bị giam ở "thành Bắc Vực sâu"' },
    { n: 311, theme: 'SETUP: Đoàn tiến gần Bắc Vực ngoại vi — gặp pet thứ 5 acquire (Thuỷ Quân, B+) trong hồ băng' },
    { n: 312, theme: 'BREATHING: MC + Tiểu Đào thuyết phục Thuỷ Quân tự nguyện theo — pet thứ 5 chính thức' },
    { n: 313, theme: 'CONFRONT: Bắc Châu chính thức gửi sứ giả "đề nghị MC quay lại" — không chịu' },
    { n: 314, theme: 'BIG WOW: MC giao Bắc Châu sứ giả 1 lá thư — formal tuyên chiến với Bắc Châu' },
    { n: 315, theme: 'RESOLUTION: Bắc Châu mobilize đại quân 1000 cao thủ — đoàn MC phải dò đường vòng' },
    { n: 316, theme: 'SETUP: MC + đoàn vào Bắc Vực core — terrain hostile, beast hoang dại' },
    { n: 317, theme: 'BREATHING: Đoàn camp đêm Bắc Vực — Vân Kiếm + Hồ Linh Nhi tổ chức training cao thủ trẻ' },
    { n: 318, theme: 'CONFRONT: Đoàn gặp 1 ổ thần thú Bắc Vực hoang dại — pet S peak' },
    { n: 319, theme: 'BIG WOW: MC + Hỏa Phụng Tế A peak + Thuỷ Quân B+ thuần thần thú Bắc Vực — pet thứ 6' },
    { n: 320, theme: 'RESOLUTION sub-arc 1: Đoàn vào Bắc Vực thành công + 2 pet hoang acquired (Thuỷ Quân B+ + Băng Thú S)' },
  ], 'sub-arc 1, đoàn xuất phát Bắc Vực + acquire pet 5+6', 'đoàn thám hiểm Bắc Vực formed'),
  // Sub-arc 2 (ch.321-340): Khám phá Bắc Vực ngoại vi ───────────────────
  ...buildBriefs([
    { n: 321, theme: 'SETUP: Đoàn dò manh mối "thành Bắc Vực sâu" — bản đồ tổ phụ chỉ dẫn' },
    { n: 322, theme: 'BREATHING: MC + Hà Thúc đọc bản đồ tổ phụ kỹ — phát hiện ký hiệu liên kết với di tích cổ' },
    { n: 323, theme: 'CONFRONT: 1 đại tộc Bắc Vực địa phương (Băng thị, neutral) chặn đoàn — yêu cầu giao "lệ phí" qua' },
    { n: 324, theme: 'BIG WOW: MC negotiate với Băng thị — trao 5000 linh thạch + 1 pet C đổi đường đi + bảo hộ' },
    { n: 325, theme: 'RESOLUTION: Băng thị thành đồng minh nhỏ trong Bắc Vực — manh mối Bắc Châu sâu hơn' },
    { n: 326, theme: 'SETUP: Đoàn vào di tích cổ ngoại vi — kiến trúc lạ, niên đại 5000 năm' },
    { n: 327, theme: 'BREATHING: MC scan di tích — Vạn Linh Phổ HUD show "kiến trúc thuộc về thượng cổ tổ tông Vạn Linh Phổ"' },
    { n: 328, theme: 'CONFRONT: 5 cao thủ Đại Sư Bắc Châu xâm nhập di tích — chặn đoàn' },
    { n: 329, theme: 'BIG WOW: MC + Hỏa Phụng Tế A + Mộc Linh B + Vân Kiếm + Hồ Linh Nhi đè bẹp 5 cao thủ Bắc Châu Đại Sư' },
    { n: 330, theme: 'RESOLUTION: 5 cao thủ Bắc Châu giam, manh mối "trại giam tổ phụ" trong di tích' },
    { n: 331, theme: 'SETUP: Đoàn explore di tích — phát hiện kho cổ với "công thức tiến hóa thượng cổ"' },
    { n: 332, theme: 'BREATHING: MC scan công thức — Vạn Linh Phổ confirm: tuyến tiến hóa từ pet S → SS path activation' },
    { n: 333, theme: 'CONFRONT: Bắc Châu phái đợt 2 — 10 cao thủ Đại Sư + 1 cao thủ Truyền Thuyết tầng 1' },
    { n: 334, theme: 'BIG WOW: MC + Già Tâm (đến gấp từ Linh Châu qua transport magic) + Hỏa Phụng Tế đè bẹp Truyền Thuyết Bắc Châu' },
    { n: 335, theme: 'RESOLUTION: Đoàn rút khỏi di tích an toàn + công thức cổ + manh mối "bố mẹ trong cấm địa Bắc Châu trung tâm"' },
    { n: 336, theme: 'SETUP: Đoàn tiến vào Bắc Châu trung tâm — quy mô đại tộc, security lớn' },
    { n: 337, theme: 'BREATHING: MC + Vân Kiếm + Hồ Linh Nhi disguise vào Bắc Châu thành — intel scout' },
    { n: 338, theme: 'CONFRONT: MC scout phát hiện vị trí giam bố mẹ — 1 hầm ngầm bí mật' },
    { n: 339, theme: 'BIG WOW: MC bí mật tiếp cận hầm — gặp bố Cố Hành lần đầu sau 4 năm (kiếp này)' },
    { n: 340, theme: 'RESOLUTION sub-arc 2: bố Cố Hành xác nhận còn sống + bị giam cùng mẹ + nhiều cao thủ Cố tộc cũ' },
  ], 'sub-arc 2, di tích cổ + Bắc Châu trung tâm + reunion bố', 'tìm thấy bố Cố Hành'),
  // Sub-arc 3 (ch.341-360): Đại tộc Bắc Châu xuất hiện — first contact ──
  ...buildBriefs([
    { n: 341, theme: 'SETUP: Bắc Châu chủ tịch (Truyền Thuyết tầng 3) phát hiện đoàn MC trong thành — order tổng tấn công' },
    { n: 342, theme: 'BREATHING: MC + bố Cố Hành (giam 4 năm, hồi phục được 30%) bàn kế hoạch giải cứu mẹ + cao thủ Cố tộc' },
    { n: 343, theme: 'CONFRONT: Bắc Châu 200 cao thủ kéo đến hầm ngầm — quy mô tấn công đại lục' },
    { n: 344, theme: 'BIG WOW: MC + bố + đoàn 100 cao thủ + 5 pet portfolio đè bẹp đợt 1 Bắc Châu (50 cao thủ Đại Sư)' },
    { n: 345, theme: 'RESOLUTION mid: Bắc Châu rút lui đợt 1, MC + đoàn ổn định trại giam' },
    { n: 346, theme: 'SETUP: MC + bố tổ chức giải cứu mẹ Lưu Tiêm Nhi + 50 cao thủ Cố tộc cũ giam' },
    { n: 347, theme: 'BREATHING: Mẹ Lưu Tiêm Nhi gặp MC + Tiểu Đào lần đầu — chemistry gia đình ấm áp đỉnh' },
    { n: 348, theme: 'CONFRONT: Bắc Châu chủ tịch ra trận personally — Truyền Thuyết tầng 3 + pet SS peak' },
    { n: 349, theme: 'BIG WOW: MC + Hỏa Phụng Tế A peak + Mộc Linh B (sắp Mộc Thần A) đè bẹp Bắc Châu chủ tịch' },
    { n: 350, theme: 'RESOLUTION: Bắc Châu chủ tịch rút — bố mẹ + 50 cao thủ Cố tộc cũ giải cứu thành công' },
    { n: 351, theme: 'SETUP: MC + đoàn rút khỏi Bắc Châu thành — 150 thành viên + bố mẹ + 50 cao thủ Cố cũ' },
    { n: 352, theme: 'BREATHING: Đoàn camp ngoài thành — bố Cố Hành chia sẻ thông tin về Bắc Châu + tổ phụ + Vạn Linh Phổ' },
    { n: 353, theme: 'CONFRONT: Bắc Châu mobilize toàn lực — 500 cao thủ + 100 pet S+ truy đuổi' },
    { n: 354, theme: 'BIG WOW: MC + bố mẹ + đoàn 200 cao thủ vs 500 cao thủ Bắc Châu — trận đại lục' },
    { n: 355, theme: 'RESOLUTION: Cố tộc + đồng minh giữ vững, Bắc Châu thiệt hại 40%' },
    { n: 356, theme: 'SETUP: Bắc Châu chủ tịch tổ chức trận quyết định — chính mình + 5 cao thủ Truyền Thuyết khác' },
    { n: 357, theme: 'BREATHING: MC bí mật check Mộc Linh — Mộc Thần A path complete (12 ngày sau ch.246)' },
    { n: 358, theme: 'CONFRONT: Mộc Linh evolve Mộc Thần A peak trong phòng kín đoàn — pet thứ 5 cấp A' },
    { n: 359, theme: 'BIG WOW: MC ra trận với Hỏa Phụng Tế A peak + Mộc Thần A — đè bẹp Bắc Châu chủ tịch lần 2' },
    { n: 360, theme: 'RESOLUTION sub-arc 3: Bắc Châu chủ tịch tử trận, đại tộc Bắc Châu mất lãnh đạo, kế nhiệm phái ôn hoà cầu hoà' },
  ], 'sub-arc 3, giải cứu bố mẹ + Bắc Châu chủ tịch tử', 'đại tộc Bắc Châu kẻ gài bẫy bố mẹ'),
  // Sub-arc 4 (ch.361-380): Reveal Bắc Châu giam bố mẹ + manh mối ───────
  ...buildBriefs([
    { n: 361, theme: 'SETUP: Bắc Châu phái ôn hoà (kế nhiệm) gửi sứ giả formal cầu hoà với Cố tộc' },
    { n: 362, theme: 'BREATHING: MC + bố mẹ + Già Tâm (đã hợp đoàn) thảo luận — bố Cố Hành reveal Bắc Châu chủ tịch tử là kẻ chủ mưu chính' },
    { n: 363, theme: 'CONFRONT: Bắc Châu kế nhiệm cầu hoà — bồi hoàn 1,000,000 linh thạch + lãnh thổ + 100 pet S' },
    { n: 364, theme: 'BIG WOW: MC accept cầu hoà — Bắc Châu chính thức suy yếu, Cố tộc kế thừa lãnh thổ + tài sản' },
    { n: 365, theme: 'RESOLUTION: Bắc Châu trở thành chư hầu Cố tộc, đại lục chia phe rõ' },
    { n: 366, theme: 'SETUP: Bố Cố Hành reveal đầy đủ — Bắc Châu chủ tịch cũ là gián điệp của 1 thế lực thượng cổ "Hắc Vực"' },
    { n: 367, theme: 'BREATHING: MC ghi nhớ "Hắc Vực" — manh mối arc 5+ về thế lực thực sự đứng sau' },
    { n: 368, theme: 'CONFRONT: Hắc Vực gửi sứ giả ngầm vào Bắc Vực — không tự xưng tộc nào' },
    { n: 369, theme: 'BIG WOW: Sứ giả Hắc Vực gặp MC personal — đề xuất "hợp tác" với MC chống lại đại tộc đại lục' },
    { n: 370, theme: 'RESOLUTION: MC từ chối Hắc Vực formal — Hắc Vực rút lui, foreshadow arc 5 antagonist' },
    { n: 371, theme: 'SETUP: MC + đoàn chuẩn bị về Linh Châu — 200+ thành viên' },
    { n: 372, theme: 'BREATHING: Bố Cố Hành huấn luyện MC kỹ năng Cao Cấp — knowledge từ Trung Cấp peak' },
    { n: 373, theme: 'CONFRONT: 1 đại tộc trung lập Trung Châu (Đỗ thị) chặn đoàn — đề xuất hôn ước với Cố Diệp' },
    { n: 374, theme: 'BIG WOW: MC từ chối Đỗ thị politcial — đoàn về Linh Châu' },
    { n: 375, theme: 'RESOLUTION: Đoàn về Linh Châu thành công, lễ chào đón đại lục' },
    { n: 376, theme: 'SETUP: MC tổ chức bữa ăn mừng đại tộc — 13 đồng minh đại lục + bố mẹ' },
    { n: 377, theme: 'BREATHING: Em gái Tiểu Đào talent thông giao đỉnh — kết nối với 5 pet portfolio MC' },
    { n: 378, theme: 'CONFRONT: 1 đại tộc Trung Châu phía nam (Mạnh thị) đề xuất "đại lục liên minh đối phó Hắc Vực"' },
    { n: 379, theme: 'BIG WOW: MC + 13 đồng minh + Mạnh thị tổ chức "Đại Lục Liên Minh Phòng Hắc Vực" — formal' },
    { n: 380, theme: 'RESOLUTION sub-arc 4: Cố tộc thành lãnh đạo đại lục liên minh phòng cosmic threat' },
  ], 'sub-arc 4, reveal Hắc Vực + đại lục liên minh', 'reveal Bắc Châu giam bố mẹ + manh mối Hắc Vực'),
  // Sub-arc 5 (ch.381-400): BIG WOW tấn công căn cứ Bắc Châu phụ ────────
  ...buildBriefs([
    { n: 381, theme: 'SETUP: Hắc Vực phái cao thủ ngầm vào đại lục — phát hiện ở 3 đại tộc' },
    { n: 382, theme: 'BREATHING: MC training pet portfolio — Hỏa Phụng Tế A → Vạn Lửa Thiên Phụng S path activate' },
    { n: 383, theme: 'CONFRONT: 1 đại tộc Linh Châu (Hồ thị peripheral) bị Hắc Vực infiltrate — Hồ thị chia rẽ' },
    { n: 384, theme: 'BIG WOW: MC + Vân Kiếm + Hồ Linh Nhi (Hồ thị thân) cleansing Hồ thị — 5 cao thủ Hắc Vực giam' },
    { n: 385, theme: 'RESOLUTION: Hồ thị unified, Hắc Vực mất 1 ally đại lục' },
    { n: 386, theme: 'SETUP: Hắc Vực tổ chức tấn công Cố tộc trực tiếp — 100 cao thủ Truyền Thuyết' },
    { n: 387, theme: 'BREATHING: MC bí mật check Tro Bụi — Vạn Lửa Thiên Phụng S path 50% complete' },
    { n: 388, theme: 'CONFRONT: 100 cao thủ Hắc Vực Truyền Thuyết tấn công Cố phủ — quy mô đại lục' },
    { n: 389, theme: 'BIG WOW: MC + Hỏa Phụng Tế A peak + Mộc Thần A + Cơ Khí Vũ Sĩ B + Phong Linh C đè bẹp 100 cao thủ Hắc Vực' },
    { n: 390, theme: 'RESOLUTION: Hắc Vực rút lui, mất 70 cao thủ Truyền Thuyết — đại lục choáng' },
    { n: 391, theme: 'SETUP: MC + đại lục liên minh tổ chức "phản công Hắc Vực" — đoàn 1000 cao thủ' },
    { n: 392, theme: 'BREATHING: MC + bố Cố Hành + Già Tâm + Vân Kiếm + Hồ Linh Nhi + Tiểu Đào (talent thông giao) bàn chiến lược' },
    { n: 393, theme: 'CONFRONT: Đoàn 1000 vào Hắc Vực ngoại vi — terrain hostile, magic dark' },
    { n: 394, theme: 'BIG WOW: Đoàn đè bẹp 3 căn cứ Hắc Vực phụ — Hắc Vực mất 30% lực' },
    { n: 395, theme: 'RESOLUTION: Đoàn ổn định trại trong Hắc Vực ngoại vi, prep tấn công sâu' },
    { n: 396, theme: 'SETUP: Hắc Vực chủ tịch chưa lộ diện — nhưng đã lên kế hoạch trap đoàn' },
    { n: 397, theme: 'BREATHING: Tro Bụi Vạn Lửa Thiên Phụng S path 75% — sắp evolve' },
    { n: 398, theme: 'CONFRONT: Đoàn rơi vào trap Hắc Vực — 200 cao thủ Truyền Thuyết bao vây' },
    { n: 399, theme: 'BIG WOW: Tro Bụi evolve Vạn Lửa Thiên Phụng S trong giữa trận — pet đầu tiên cấp S của MC' },
    { n: 400, theme: 'RESOLUTION sub-arc 5: MC + Vạn Lửa Thiên Phụng S + đoàn 1000 đè bẹp 200 Hắc Vực, đoàn rút an toàn' },
  ], 'sub-arc 5, phản công Hắc Vực + Tro Bụi Vạn Lửa Thiên Phụng S', 'phản công Hắc Vực căn cứ phụ'),
  // Sub-arc 6-10 — phản công Hắc Vực continues → CLIMAX MC Cao Cấp ────────
  ...buildBriefs([
    { n: 401, theme: 'SETUP: Hắc Vực fragmented — 5 phe nhỏ tự lập, không có chủ tịch unified' },
    { n: 402, theme: 'BREATHING: MC + đoàn về Linh Châu — 6 tháng nghỉ ngơi recover' },
    { n: 403, theme: 'CONFRONT: 1 phe Hắc Vực gửi sứ giả cầu hoà với Cố tộc' },
    { n: 404, theme: 'BIG WOW: MC accept hoà — phe Hắc Vực ôn hoà thành chư hầu, đại lục unified phòng Hắc Vực' },
    { n: 405, theme: 'RESOLUTION: Cố tộc danh vọng đỉnh đại lục, MC tiến Cao Cấp tầng 1' },
    { n: 406, theme: 'SETUP: 4 phe Hắc Vực còn lại liên minh chống Cố tộc' },
    { n: 407, theme: 'BREATHING: MC training Cao Cấp realm — bố Cố Hành + Già Tâm + cao thủ Cố tộc cũ giảng' },
    { n: 408, theme: 'CONFRONT: 4 phe Hắc Vực + 200 cao thủ Truyền Thuyết tấn công đại lục liên minh' },
    { n: 409, theme: 'BIG WOW: MC + Vạn Lửa Thiên Phụng S + Mộc Thần A + đoàn đại lục đè bẹp 4 phe Hắc Vực' },
    { n: 410, theme: 'RESOLUTION: 4 phe Hắc Vực thua, lãnh thổ Cố tộc reach Hắc Vực ngoại vi' },
    { n: 411, theme: 'SETUP: Hắc Vực core còn 1 phe cứng đầu — Truyền Thuyết tầng 5 lãnh đạo' },
    { n: 412, theme: 'BREATHING: MC + Tiểu Đào talent thông giao + bố Cố Hành tổ chức training cao thủ trẻ' },
    { n: 413, theme: 'CONFRONT: Hắc Vực core phái 5 cao thủ Truyền Thuyết tầng 5 + 1 pet SS peak' },
    { n: 414, theme: 'BIG WOW: MC + Vạn Lửa Thiên Phụng S + Mộc Thần A + bố Cố Hành (Cao Cấp peak) đè bẹp 5 cao thủ' },
    { n: 415, theme: 'RESOLUTION: Hắc Vực core thua, Cố tộc + đại lục unified hoàn toàn' },
    { n: 416, theme: 'SETUP: MC tiến Cao Cấp tầng 5 — peak target arc 4' },
    { n: 417, theme: 'BREATHING: Em gái Tiểu Đào talent đỉnh — "thông giao team" 20 thành viên' },
    { n: 418, theme: 'CONFRONT: 1 đại tộc đại lục xa (Trần thị từ Trung Châu) đe dọa nhỏ' },
    { n: 419, theme: 'BIG WOW: MC face-slap Trần thị nhỏ — đại lục công nhận Cố tộc bá tộc khu vực Bắc Vực' },
    { n: 420, theme: 'RESOLUTION sub-arc 6: Cố tộc bá tộc khu vực Bắc Vực + MC Cao Cấp peak' },
  ], 'sub-arc 6, Hắc Vực fragmented + Cố tộc bá Bắc Vực', 'Hắc Vực core thua'),
  ...buildBriefs([
    { n: 421, theme: 'SETUP: MC + bố Cố Hành dẫn quân tinh anh vào Bắc Châu lõi (Hắc Vực origin) — explore di tích cổ lớn' },
    { n: 422, theme: 'BREATHING: Tiểu Đào talent kết nối với 5 pet portfolio MC + bố Cố Hành 2 pet' },
    { n: 423, theme: 'CONFRONT: Đoàn explore di tích cổ — gặp guardian pet S+ thượng cổ (chưa quá cosmic)' },
    { n: 424, theme: 'BIG WOW: MC + Vạn Lửa Thiên Phụng S thuần guardian — pet thứ 7 acquired' },
    { n: 425, theme: 'RESOLUTION: Đoàn vào sâu di tích, phát hiện kho cổ với "tài liệu thượng cổ" về Vạn Linh Phổ origin' },
    { n: 426, theme: 'SETUP: MC scan tài liệu — manh mối "Vạn Linh Phổ truyền từ thượng cổ tổ tông". Foreshadow arc 6' },
    { n: 427, theme: 'BREATHING: MC + bố Cố Hành + Già Tâm tham quan kho — không tiết lộ Vạn Linh Phổ với Già Tâm' },
    { n: 428, theme: 'CONFRONT: 1 cao thủ Hắc Vực sót lại tự sát attack đoàn — kamikaze' },
    { n: 429, theme: 'BIG WOW: MC + đoàn dập kamikaze trong giây — Tiểu Đào talent đỉnh phát hiện sớm' },
    { n: 430, theme: 'RESOLUTION: Đoàn rút khỏi di tích an toàn + tài liệu thượng cổ + pet thứ 7' },
    { n: 431, theme: 'SETUP: MC tổng kê tài sản đoàn — thắng arc 4 hơn 10,000,000 linh thạch + 500 pet A-S' },
    { n: 432, theme: 'BREATHING: MC + bố mẹ + Tiểu Đào (gia đình đoàn tụ) bữa ăn ấm áp' },
    { n: 433, theme: 'CONFRONT: 1 đại tộc Trung Châu (Lý thị, ôn hoà) đề xuất hợp tác economic với Cố tộc' },
    { n: 434, theme: 'BIG WOW: MC accept hợp tác — Cố tộc network kinh tế reach Trung Châu' },
    { n: 435, theme: 'RESOLUTION: Cố tộc network 20 đại tộc đại lục đồng minh' },
    { n: 436, theme: 'SETUP: Đoàn về Linh Châu — lễ chào đón đại lục formal' },
    { n: 437, theme: 'BREATHING: MC + bố Cố Hành + Già Tâm + 20 đại biểu đồng minh tổ chức "Đại Lục Cố tộc Hội Nghị"' },
    { n: 438, theme: 'CONFRONT: Đại tộc Cố Trường Hành (đại trưởng lão) đến Linh Châu lần 5 — formal recognize' },
    { n: 439, theme: 'BIG WOW: Cố Trường Hành phát biểu "Cố Diệp đã đưa Cố tộc đến đỉnh đại lục"' },
    { n: 440, theme: 'RESOLUTION: Cố tộc bá tộc đại lục — danh vọng vượt Linh Châu thành toàn đại lục' },
  ], 'sub-arc 7, di tích cổ + đoàn về Linh Châu + đại lục bá tộc', 'di tích cổ Bắc Vực'),
  ...buildBriefs([
    { n: 441, theme: 'SETUP: MC tổ chức "đoàn thám hiểm biển Đông" — open new front for arc 5' },
    { n: 442, theme: 'BREATHING: MC + Vân Kiếm + Hồ Linh Nhi + 3 nhánh trưởng + 100 cao thủ chuẩn bị' },
    { n: 443, theme: 'CONFRONT: 1 đại tộc biển Đông (Hà thị) chặn đoàn — đại lục mới chưa unified' },
    { n: 444, theme: 'BIG WOW: MC + Vạn Lửa Thiên Phụng S đè bẹp Hà thị — biển Đông open' },
    { n: 445, theme: 'RESOLUTION: Hà thị thành chư hầu, biển Đông open cho Cố tộc' },
    { n: 446, theme: 'SETUP: Đoàn explore biển Đông — gặp pet biển hoang dại' },
    { n: 447, theme: 'BREATHING: MC scan biển — 3 đại tộc biển Đông + 5 quần đảo' },
    { n: 448, theme: 'CONFRONT: 1 quần đảo bị Hắc Vực sót lại chiếm — gửi sứ giả threat' },
    { n: 449, theme: 'BIG WOW: MC + đoàn cleansing quần đảo — Hắc Vực sót lại tan hết' },
    { n: 450, theme: 'RESOLUTION: Cố tộc unified biển Đông + 3 đại tộc + 5 quần đảo' },
    { n: 451, theme: 'SETUP: MC tổ chức trở về Linh Châu sau 6 tháng explore' },
    { n: 452, theme: 'BREATHING: Cố tộc home base — học viện Cố tộc 500 đệ tử + Tro Linh Phái 200 cao thủ' },
    { n: 453, theme: 'CONFRONT: Cố Trường Hành (đại trưởng lão) đề xuất "Cố tộc thành Đại Đại Tộc Đại Lục"' },
    { n: 454, theme: 'BIG WOW: MC accept formal — Cố tộc nâng rank lên "Đại Đại Tộc" (top 1 đại lục)' },
    { n: 455, theme: 'RESOLUTION: Cố tộc Đại Đại Tộc đại lục — danh vọng đỉnh' },
    { n: 456, theme: 'SETUP: 1 đại tộc đại lục xa (Cố Khất từ Tây Châu) gửi tin chào — relative xa của Cố Lập Khải' },
    { n: 457, theme: 'BREATHING: Cố Khất reveal "tổ phụ Cố Lập Khải có connection với gia tộc Tây Châu"' },
    { n: 458, theme: 'CONFRONT: 1 đại tộc khác (Tây Châu, Lý thị) tổ chức threat Cố tộc — đối thủ mới' },
    { n: 459, theme: 'BIG WOW: MC + đoàn đè bẹp Lý thị Tây Châu small wave — đại lục Tây Châu lo' },
    { n: 460, theme: 'RESOLUTION sub-arc 8: Cố tộc reach Tây Châu, đại lục unified gradually' },
  ], 'sub-arc 8, biển Đông + Đại Đại Tộc + Tây Châu first contact', 'biển Đông unified'),
  ...buildBriefs([
    { n: 461, theme: 'SETUP: MC bí mật investigate "Vạn Linh Phổ origin" qua tài liệu thượng cổ + bản đồ tổ phụ' },
    { n: 462, theme: 'BREATHING: MC + Hà Thúc đêm khuya nghiên cứu — manh mối "Vạn Linh Phổ truyền từ Trái Đất qua tổ phụ"' },
    { n: 463, theme: 'CONFRONT: 1 sứ giả lạ (không tự xưng) đến Cố tộc — đề xuất "trao đổi thông tin về Vạn Linh Phổ"' },
    { n: 464, theme: 'BIG WOW: MC scan sứ giả — kẻ này có dấu hiệu "thượng cổ tu hành", liên quan arc 6' },
    { n: 465, theme: 'RESOLUTION: Sứ giả rút (foreshadow arc 6 antagonist), MC ghi nhớ tên "Hắc Lão Tổ"' },
    { n: 466, theme: 'SETUP: MC training pet portfolio + Cao Cấp realm intensively' },
    { n: 467, theme: 'BREATHING: MC + Tiểu Đào team thông giao bonding với pet portfolio — synergy đỉnh' },
    { n: 468, theme: 'CONFRONT: 1 đại tộc Tây Châu (Cố Khất relative) gặp MC — chia sẻ thông tin gia tộc Tây Châu' },
    { n: 469, theme: 'BIG WOW: Cố Khất đề xuất hôn ước con gái Cố Khất với 1 nhánh trưởng Cố tộc — politcial' },
    { n: 470, theme: 'RESOLUTION: Hôn ước formal, Cố tộc + Cố Khất Tây Châu thành liên minh chính thức' },
    { n: 471, theme: 'SETUP: MC + đoàn explore Tây Châu — terrain khác Bắc Vực, magic culture khác' },
    { n: 472, theme: 'BREATHING: Cố Khất tour MC qua Tây Châu — 5 đại tộc thân thiện + 2 đối thủ' },
    { n: 473, theme: 'CONFRONT: 1 đại tộc Tây Châu (Quách thị, đối thủ Cố Khất) chặn MC — đe dọa quy mô' },
    { n: 474, theme: 'BIG WOW: MC + Vạn Lửa Thiên Phụng S đè bẹp Quách thị Tây Châu — face-slap đại lục' },
    { n: 475, theme: 'RESOLUTION: Quách thị thành chư hầu, Tây Châu open cho Cố tộc' },
    { n: 476, theme: 'SETUP: Cố tộc network reach Tây Châu — đại lục unified mostly' },
    { n: 477, theme: 'BREATHING: MC + bố mẹ + Tiểu Đào + Hồ Linh Nhi gia đình ấm áp' },
    { n: 478, theme: 'CONFRONT: Hắc Lão Tổ (sứ giả ch.464) reappear — gửi tin formal về Vạn Linh Phổ' },
    { n: 479, theme: 'BIG WOW: MC formal từ chối Hắc Lão Tổ — foreshadow arc 6 antagonist' },
    { n: 480, theme: 'RESOLUTION sub-arc 9: Cố tộc đại lục unified + Hắc Lão Tổ arc 6 setup' },
  ], 'sub-arc 9, Tây Châu + Hắc Lão Tổ foreshadow', 'Vạn Linh Phổ origin manh mối'),
  // Sub-arc 10 (ch.481-500): CLIMAX arc 4 ──────────────────────────────
  ...buildBriefs([
    { n: 481, theme: 'SETUP: MC tổ chức "Đại Lục Hội Nghị" — 30 đại tộc + Cố tộc + bố mẹ + Già Tâm + đại trưởng lão Cố Trường Hành tham dự' },
    { n: 482, theme: 'BREATHING: Hội nghị 7 ngày — bàn chiến lược đại lục đối phó Hắc Lão Tổ' },
    { n: 483, theme: 'CONFRONT: 1 phe nhỏ trong hội nghị (Hà thị từ Tây Châu) đề xuất hợp tác với Hắc Lão Tổ — politcial split' },
    { n: 484, theme: 'BIG WOW: MC face-slap Hà thị split — Hà thị bị 29 đại tộc khác trục xuất khỏi liên minh' },
    { n: 485, theme: 'RESOLUTION: Đại lục liên minh unified vững chắc, 30 đại tộc + Cố tộc đứng đầu' },
    { n: 486, theme: 'SETUP: MC chính thức Cao Cấp tầng 9 peak — chuẩn bị đột phá Đại Sư' },
    { n: 487, theme: 'BREATHING: Bố Cố Hành + Già Tâm + cao thủ Cố tộc cũ giảng MC kỹ năng Đại Sư realm' },
    { n: 488, theme: 'CONFRONT: Cố Trường Hành (đại trưởng lão) thử thách MC — yêu cầu MC chứng minh xứng đáng Đại Sư' },
    { n: 489, theme: 'BIG WOW: MC + Vạn Lửa Thiên Phụng S kìm chế A− public + Mộc Thần A vs Cố Trường Hành (Đại Sư peak) + pet S — MC thắng' },
    { n: 490, theme: 'RESOLUTION: Cố Trường Hành công nhận MC Đại Sư realm — formal' },
    { n: 491, theme: 'SETUP: MC chính thức Đại Sư tầng 1 — trước plan Cao Cấp peak nhưng vượt lên' },
    { n: 492, theme: 'BREATHING: Cố tộc tổ chức bữa ăn mừng MC Đại Sư realm — 30 đại tộc đồng minh tham gia' },
    { n: 493, theme: 'CONFRONT: Hắc Lão Tổ (qua sứ giả) gửi tin "MC, ngài đã đến mức tôi phải lo. Sắp đến thời điểm gặp."' },
    { n: 494, theme: 'BIG WOW: MC đáp formal "ngươi đến, ta đợi"' },
    { n: 495, theme: 'RESOLUTION: Đại lục lo lắng cosmic threat, Cố tộc tổ chức phòng thủ' },
    { n: 496, theme: 'SETUP: MC + bố Cố Hành + Già Tâm + Cố Trường Hành + bố mẹ MC + Tiểu Đào talent đỉnh + Vân Kiếm + Hồ Linh Nhi + 3 nhánh trưởng + đoàn 1000 cao thủ — formation full Cố tộc' },
    { n: 497, theme: 'BREATHING: MC + Tiểu Đào riêng — gia đình ấm áp, foreshadow arc 5' },
    { n: 498, theme: 'CONFRONT: Hắc Lão Tổ disciple ngầm vào Cố tộc — assassination attempt' },
    { n: 499, theme: 'BIG WOW: MC + Tiểu Đào talent thông giao phát hiện sớm — đè bẹp disciple' },
    { n: 500, theme: 'CLIMAX RESOLUTION arc 4: MC Đại Sư realm, Cố tộc Đại Đại Tộc đại lục, bố mẹ rescued, đại lục unified phòng Hắc Lão Tổ — sẵn sàng arc 5' },
  ], 'sub-arc 10, CLIMAX arc 4 — MC Đại Sư + đại lục unified', 'CLIMAX arc 4 — cứu bố mẹ + Bắc Châu thua'),
];
